### ISSUE TITLE
nastools开的时间久了之后，网页就打不开了

### ISSUE THREAD

**Issue by chhc007** [hsuyelin/nas-tools#100]
大概运行了两天，日志显示还在正常读取rss订阅，但是网页就打不开了，要重启容器才行。
不知道问题出在哪里。
Nastools 版本v3.2.10.7

**Comment by hsuyelin** [comment]
3.2.10.7解决了这个：https://github.com/hsuyelin/nas-tools/pull/70，你看你是不是后拉的版本，建议拉去最新版再试试
