### ISSUE TITLE
电影订阅中，配置无法保存的BUG

### ISSUE THREAD

**Issue by chhc007** [hsuyelin/nas-tools#101]
我发现我在内建索引器中打开了两个PF站点和一个EZTV站点之后，在电影订阅的默认设置和随便选一个订阅的设置中，如果搜索站点添加了两个PT站和EZTV，则保存后提示成功但实际上并没成功写入数据库。我把EZTV从搜索站点中去除后，保存成功。

**Comment by chhc007** [comment]
还有电影订阅中，编辑一个订阅，全不选订阅站点，也无法保存

**Comment by hsuyelin** [comment]
抽空看看，先关了
