### ISSUE TITLE
大佬有空维护nastool官方自带的BUG吗

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#102]
我测试了官方 3.11-3.2.3
都存在我们之前讨论过的电视剧漏站点搜索问题。大佬会修复这个官方BUG吗

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/05e1bea3-65ea-4f27-9073-2c8bde77e472)
去看下开发线路

**Comment by MyGiki** [comment]
@jackloves111 
MP的搜索解决了漏站的问题，能把MP的搜索规则搬过来？

**Comment by MyGiki** [comment]
@jackloves111 
@hsuyelin 
MP的搜索解决了漏站和匹配的问题，能把MP的搜索规则搬过来？

**Comment by hsuyelin** [comment]
> @jackloves111 @hsuyelin MP的搜索解决了漏站和匹配的问题，能把MP的搜索规则搬过来？

抽空看看源码怎么实现的，好弄就弄过来

**Comment by MyGiki** [comment]
@hsuyelin 最爱大佬了
