### ISSUE TITLE
同时希望大佬可以加入IMBD的识别

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#103]
同时希望大佬可以加入IMBD的识别，自己添加词条给TMBD当然不及IMBD有资源的好了。有了IMBD、TMBD、豆瓣，资源不是更全了嘛，豆瓣识别不了还有TMBD，TMBD识别不了还有IBMD啊

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/05e1bea3-65ea-4f27-9073-2c8bde77e472)
去看下开发线路
