### ISSUE TITLE
是否可以更新一下憨憨的站点文件

### ISSUE THREAD

**Issue by baozaodetudou** [hsuyelin/nas-tools#105]
我不清楚现在的站点文件是加密还是非加密的
```yaml
```

tg：https://t.me/doumaodalao

**Comment by jackloves111** [comment]
憨憨已经适配了啊，你这个直接发出来不太好吧

**Comment by hsuyelin** [comment]
憨憨应该适配了的啊，有啥问题么。现在

**Comment by baozaodetudou** [comment]
> 

适配是适配，但是不是最新的我这个是最新的文件，不会出现其他问题

**Comment by baozaodetudou** [comment]
> 憨憨应该适配了的啊，有啥问题么。现在


适配是适配，但是不是最新的我这个是最新的文件，不会出现其他问题

**Comment by hsuyelin** [comment]
> > 憨憨应该适配了的啊，有啥问题么。现在
> 
> 适配是适配，但是不是最新的我这个是最新的文件，不会出现其他问题

已更新，你看看
