### ISSUE TITLE
豆瓣同步

### ISSUE THREAD

**Issue by m774303886** [hsuyelin/nas-tools#107]
我的豆瓣明明已经填了cookie，可在同步时还是报错，报需要cookie才能继续搜索
<img width="725" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/143067620/46659741-e148-4092-a8da-a06b517d89ab">
<img width="748" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/143067620/a53b8bd6-ff84-4a91-8bbc-b8f09cd8bccf">

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/a012749a-e51e-4091-aef9-e0a08047ca49)

**Comment by m774303886** [comment]
> ![image](https://github.com/hsuyelin/nas-tools/assets/17918063/a012749a-e51e-4091-aef9-e0a08047ca49)
> 
> 
> 
> 这个是你想看的不
> 
> 
> 
> 部分是详情获取不了，应该不影响吧，是豆瓣的限制

您搜出来的我和我搜出来的一样，但比实际的少好几部呢

**Comment by m774303886** [comment]
是不是配置的cookie没有生效，或者是配置的cookie需要特殊的要求
