### ISSUE TITLE
3.2.10.8 ac01eab 更新移除失效站点，原支持的影没了

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#108]
ac01eab 
3.2.10.8 大佬新增了熊猫和影是支持了，更新ac01eab 后移除失效站点，原支持的影没了，肉丝刷流免费的也没生效

**Comment by iovejieba** [comment]
> [ac01eab](https://github.com/hsuyelin/nas-tools/commit/ac01eab660b047ba26c9950b873b47f125c9db1d) 3.2.10.8 大佬新增了熊猫和影是支持了，更新ac01eab 后移除失效站点，原支持的影没了，肉丝刷流免费的也没生效

我有功夫在盲加吧....隔壁的sites  批量生成 那个机构有问题...

**Comment by iovejieba** [comment]
或者先回滚用10.8的 sites

**Comment by MyGiki** [comment]
因为没站点，盲加存在问题是吗

**Comment by iovejieba** [comment]
> 因为没站点，盲加存在问题是吗

不是后批量加的所有站貌似都没有free判断的正规表达式

**Comment by hsuyelin** [comment]
> > [ac01eab](https://github.com/hsuyelin/nas-tools/commit/ac01eab660b047ba26c9950b873b47f125c9db1d) 3.2.10.8 大佬新增了熊猫和影是支持了，更新ac01eab 后移除失效站点，原支持的影没了，肉丝刷流免费的也没生效
> 
> 我有功夫在盲加吧....隔壁的sites 批量生成 那个机构有问题...

不要用隔壁的，用我给你发的那个，如果你没有python环境你啥都不用动，仅需要按照规则添加或者修改即可: https://github.com/hsuyelin/nas-tools-sites，有的话就直接生成即可

**Comment by iovejieba** [comment]
> > > [ac01eab](https://github.com/hsuyelin/nas-tools/commit/ac01eab660b047ba26c9950b873b47f125c9db1d) 3.2.10.8 大佬新增了熊猫和影是支持了，更新ac01eab 后移除失效站点，原支持的影没了，肉丝刷流免费的也没生效
> > 
> > 
> > 我有功夫在盲加吧....隔壁的sites 批量生成 那个机构有问题...
> 
> 不要用隔壁的，用我给你发的那个，如果你没有python环境你啥都不用动，仅需要按照规则添加或者修改即可: [https://github.com/hsuyelin/nas-tools-sites，有的话就直接生成即可](https://github.com/hsuyelin/nas-tools-sites%EF%BC%8C%E6%9C%89%E7%9A%84%E8%AF%9D%E5%B0%B1%E7%9B%B4%E6%8E%A5%E7%94%9F%E6%88%90%E5%8D%B3%E5%8F%AF)

咱自己这个py生成 貌似没有free 正规表达啊

**Comment by hsuyelin** [comment]
> > > > [ac01eab](https://github.com/hsuyelin/nas-tools/commit/ac01eab660b047ba26c9950b873b47f125c9db1d) 3.2.10.8 大佬新增了熊猫和影是支持了，更新ac01eab 后移除失效站点，原支持的影没了，肉丝刷流免费的也没生效
> > > 
> > > 
> > > 我有功夫在盲加吧....隔壁的sites 批量生成 那个机构有问题...
> > 
> > 
> > 不要用隔壁的，用我给你发的那个，如果你没有python环境你啥都不用动，仅需要按照规则添加或者修改即可: [https://github.com/hsuyelin/nas-tools-sites，有的话就直接生成即可](https://github.com/hsuyelin/nas-tools-sites%EF%BC%8C%E6%9C%89%E7%9A%84%E8%AF%9D%E5%B0%B1%E7%9B%B4%E6%8E%A5%E7%94%9F%E6%88%90%E5%8D%B3%E5%8F%AF)
> 
> 咱自己这个py生成 貌似没有free 正规表达啊

有的，你可以看sites.json文件

**Comment by hsuyelin** [comment]
> > > > [ac01eab](https://github.com/hsuyelin/nas-tools/commit/ac01eab660b047ba26c9950b873b47f125c9db1d) 3.2.10.8 大佬新增了熊猫和影是支持了，更新ac01eab 后移除失效站点，原支持的影没了，肉丝刷流免费的也没生效
> > > 
> > > 
> > > 我有功夫在盲加吧....隔壁的sites 批量生成 那个机构有问题...
> > 
> > 
> > 不要用隔壁的，用我给你发的那个，如果你没有python环境你啥都不用动，仅需要按照规则添加或者修改即可: [https://github.com/hsuyelin/nas-tools-sites，有的话就直接生成即可](https://github.com/hsuyelin/nas-tools-sites%EF%BC%8C%E6%9C%89%E7%9A%84%E8%AF%9D%E5%B0%B1%E7%9B%B4%E6%8E%A5%E7%94%9F%E6%88%90%E5%8D%B3%E5%8F%AF)
> 
> 咱自己这个py生成 貌似没有free 正规表达啊

如果你有那个规则的话，修改就好了，我来生成

**Comment by iovejieba** [comment]
> 

嗯 看其他小伙伴先测吧....我看上面小伙伴说的情况还以为是没表达式

**Comment by hsuyelin** [comment]
@MyGiki @iovejieba 影的域名是啥

**Comment by hsuyelin** [comment]
@MyGiki rousi免费的规则来源于网络，这个没有站点就只能盲加，或者你可以直接打开 https://rousi.zip/torrents.php 然后右键查看网页源代码发我，我就可以适配了

**Comment by iovejieba** [comment]
> @MyGiki @iovejieba 影的域名是啥

shadowflow_org

**Comment by hsuyelin** [comment]
> > @MyGiki @iovejieba 影的域名是啥
> 
> shadowflow_org

是姿势不对么，打开是宝贝回家

**Comment by iovejieba** [comment]
> shadowflow_org

可能抽风了？  我也没这站就之前小伙伴说 才找的

**Comment by iovejieba** [comment]
他们也没反馈说行不行

**Comment by iovejieba** [comment]
> > > @MyGiki @iovejieba 影的域名是啥
> > 
> > 
> > shadowflow_org
> 
> 是姿势不对么，打开是宝贝回家

大佬一般那个free的正规表达 要怎么找...我去把fms的找一下

**Comment by hsuyelin** [comment]
> > > > @MyGiki @iovejieba 影的域名是啥
> > > 
> > > 
> > > shadowflow_org
> > 
> > 
> > 是姿势不对么，打开是宝贝回家
> 
> 大佬一般那个free的正规表达 要怎么找...我去把fsm的找一下

加回来了，看看，free是需要找到站点，以憨憨举例

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/bb2fa782-81b6-4eb5-aff7-9b56547be311)

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/5a085fad-35ba-498c-be56-14308bde1f25)

但是不同站点不一样，具体还是通过 站点/torrents.php 然后查看源代码查看

**Comment by iovejieba** [comment]
> > > > > @MyGiki @iovejieba 影的域名是啥
> > > > 
> > > > 
> > > > shadowflow_org
> > > 
> > > 
> > > 是姿势不对么，打开是宝贝回家
> > 
> > 
> > 大佬一般那个free的正规表达 要怎么找...我去把fsm的找一下
> 
> 加回来了，看看，free是需要找到站点，以憨憨举例
> 
> ![image](https://user-images.githubusercontent.com/17918063/262906317-bb2fa782-81b6-4eb5-aff7-9b56547be311.png)
> 
> ![image](https://user-images.githubusercontent.com/17918063/262906460-5a085fad-35ba-498c-be56-14308bde1f25.png)
> 
> 但是不同站点不一样，具体还是通过 站点/torrents.php 然后查看源代码查看

ok 感谢大佬  那我去把飞天拉面的补上

**Comment by MyGiki** [comment]
影PT长期关门，我今晚回家给安全链接你登录我号

**Comment by MyGiki** [comment]
@hsuyelin 影PT长期关门，我今晚回家给安全链接你登录我号

**Comment by MyGiki** [comment]
@hsuyelin 
肉丝的网页源代码
view-source:https://rousi.zip/torrents.php

**Comment by MyGiki** [comment]
@hsuyelin 
影 的需要Cookie才可以打开，这个怎么给你呢
