### ISSUE TITLE
憨憨刷流问题

### ISSUE THREAD

**Issue by IWONTTELL** [hsuyelin/nas-tools#109]
貌似选种规则种的促销选择【免费】之后不会添加种子。只有选择【全部】的时候才会添加种子。是我设置的问题吗？

**Comment by hsuyelin** [comment]
憨憨的新UI还没稳定，憨憨刷流还没有适配，等等

**Comment by hsuyelin** [comment]
可以关注：
https://github.com/hsuyelin/nas-tools/discussions/91

**Comment by IWONTTELL** [comment]
> 憨憨的新UI还没稳定，憨憨刷流还没有适配，等等

感谢大佬回复！了解了，谢谢大佬的付出

**Comment by liclown2020** [comment]
感谢大佬付出，我也想问这个问题。
