### ISSUE TITLE
插件：“豆瓣同步”失败

### ISSUE THREAD

**Issue by luotao21** [hsuyelin/nas-tools#11]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:[v3.2.5 81b1c5d](https://github.com/hsuyelin/nas-tools)
> 环境: docker Synology
## 你遇到什么问题了？
> 使用豆瓣同步插件，同步方式选择“近期动态”时可以正常同步最近的10条 想看。如果改为“全量同步”则会提示：
豆瓣同步 - 第 1 页未获取到数据
豆瓣同步 - 用户 xxx 解析完成，共获取到 0 个媒体	
豆瓣同步 - 所有用户解析完成，共获取到 0 个媒体
豆瓣同步 - 豆瓣数据同步完成

**Comment by hsuyelin** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本:[v3.2.5 81b1c5d](https://github.com/hsuyelin/nas-tools)
> > 环境: docker Synology
> 
> ## 你遇到什么问题了？
> > 使用豆瓣同步插件，同步方式选择“近期动态”时可以正常同步最近的10条 想看。如果改为“全量同步”则会提示：
> > 豆瓣同步 - 第 1 页未获取到数据
> > 豆瓣同步 - 用户 xxx 解析完成，共获取到 0 个媒体
> > 豆瓣同步 - 所有用户解析完成，共获取到 0 个媒体
> > 豆瓣同步 - 豆瓣数据同步完成

找到问题了，已经修复了，等待新版本发布

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/0d3e52ef-654f-4d88-86a7-253a6b2d34a6)

**Comment by zackfly** [comment]
@hsuyelin 3.3.4 这个问题又出现了

**Comment by zackfly** [comment]
@hsuyelin  3.3.5 这个版本全量同步可以工作，但是只能同步10条数据
