### ISSUE TITLE
咖啡更新完不支持索引

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#110]
https://github.com/hsuyelin/nas-tools/commit/86d4187349a65dae6c7377a128232e01ae360a9f
这个版本的可以

**Comment by hsuyelin** [comment]
是不支持索引，还是不支持索引统计

**Comment by hh0610** [comment]
> 是不支持索引，还是不支持索引统计
索引跟刷流

**Comment by hsuyelin** [comment]
@hh0610 拉一下再试试，刷流这个只能随缘没有站点，盲加的

**Comment by hh0610** [comment]
> @hh0610 拉一下再试试，刷流这个只能随缘没有站点，盲加的
如果需要我这边可以给个邀请

**Comment by hh0610** [comment]
https://github.com/hsuyelin
如果需要我这边可以给个邀请

**Comment by hsuyelin** [comment]
> > @hh0610 拉一下再试试，刷流这个只能随缘没有站点，盲加的
> > 如果需要我这边可以给个邀请

谢谢你，站点太多，我也管理不过来，如果希望给予帮助，就是打开 https://ptcafe.club/torrents.php 然后右键查看页面源代码保存为咖啡.html，通过网盘或者啥的贴上来，我看到回复你就可以删除那一楼。我根据页面源代码就可以适配了

**Comment by hsuyelin** [comment]
> > @hh0610 拉一下再试试，刷流这个只能随缘没有站点，盲加的
> > 如果需要我这边可以给个邀请

你拉下看看是不是有了

**Comment by hsuyelin** [comment]
> > > > @hh0610 拉一下再试试，刷流这个只能随缘没有站点，盲加的
> > > > 如果需要我这边可以给个邀请
> > 
> > 
> > 你拉下看看是不是有了
> 
> 有了怎么给你呢

有TG就联系这个：https://t.me/hsuyelin ，没有TG就随便放到啥网盘都可以

**Comment by hh0610** [comment]
> > > > > @hh0610 拉一下再试试，刷流这个只能随缘没有站点，盲加的
> > > > > 如果需要我这边可以给个邀请
> > > 
> > > 
> > > 你拉下看看是不是有了
> > 
> > 
> > 有了怎么给你呢
> 
> 有TG就联系这个：https://t.me/hsuyelin ，没有TG就随便放到啥网盘都可以

链接: https://pan.baidu.com/s/1fSLloM7wXnhexePos5SmFw 提取码: jn19 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by hsuyelin** [comment]
@hh0610 收到了，我晚上看下，有这个就可以适配了，你先看下索引对不对了

**Comment by hsuyelin** [comment]
@hh0610 我帮你那个删除了哈，以免被别人看到

**Comment by hh0610** [comment]
> @hh0610 我帮你那个删除了哈，以免被别人看到

谢谢.

**Comment by hh0610** [comment]
> @hh0610 我帮你那个删除了哈，以免被别人看到

刷流下载不到种子，搜索种子没有副标题
