### ISSUE TITLE
为什么索引器不生效

### ISSUE THREAD

**Issue by fuemo** [hsuyelin/nas-tools#111]
![image](https://github.com/hsuyelin/nas-tools/assets/77526675/a0813992-ef34-4544-8717-ed1295bd7367)
![image](https://github.com/hsuyelin/nas-tools/assets/77526675/87775b49-210c-4858-a7f7-86e365b43958)
![image](https://github.com/hsuyelin/nas-tools/assets/77526675/59ef2768-8f39-44e9-93c9-c7be3b461499)

**Comment by iovejieba** [comment]
http://ip+端口 不要带后续

**Comment by hsuyelin** [comment]
> [http://ip+端口](http://ip+%E7%AB%AF%E5%8F%A3) 不要带后续，比如http://192.168.1.1:9117

没有关系的，我做了兼容，这个人肯定下的不是我的最新版

**Comment by iovejieba** [comment]
> > ![image](https://user-images.githubusercontent.com/77526675/263013495-a0813992-ef34-4544-8717-ed1295bd7367.png)
> > ![image](https://user-images.githubusercontent.com/77526675/263013647-87775b49-210c-4858-a7f7-86e365b43958.png)
> > ![image](https://user-images.githubusercontent.com/77526675/263013857-59ef2768-8f39-44e9-93c9-c7be3b461499.png)
> 
> 反馈要提供，镜像和版本，你这肯定不是我的最新版，因为这个问题在几个版本之前就解决了

猛一看我还以为它是直接拉的 jk api....

**Comment by fuemo** [comment]
> > ![图像](https://user-images.githubusercontent.com/77526675/263013495-a0813992-ef34-4544-8717-ed1295bd7367.png)
> > ![图像](https://user-images.githubusercontent.com/77526675/263013647-87775b49-210c-4858-a7f7-86e365b43958.png)
> > ![图像](https://user-images.githubusercontent.com/77526675/263013857-59ef2768-8f39-44e9-93c9-c7be3b461499.png)
> 
> 反馈要提供，镜像和版本，你这肯定不是我的最新版本，因为这个问题在几个版本之前就已经解决了

就是最新版
![image](https://github.com/hsuyelin/nas-tools/assets/77526675/7cc4433c-1b3d-4e96-9a66-fbacc9ab346c)

**Comment by tsvico** [comment]
你可以打开这里，打开后再进入索引器看看
![image](https://github.com/hsuyelin/nas-tools/assets/32492304/b4be6ed4-6099-404f-8a1a-b3f5cfefc354)
