### ISSUE TITLE
大佬，我想问下我现在用的是官方的那个版本，用这个能直接导入配置吗，会有冲突不

### ISSUE THREAD

**Issue by wiiiii66** [hsuyelin/nas-tools#112]

**Comment by iovejieba** [comment]
不建议  基本玄学抽风 建议重新部署  咱们这边分支改动不少了

**Comment by yingpan008** [comment]
我从正版3.2.3转过来，订阅出问题，订阅会出现有资源不会下载的情况，晚上老老实实重新部署试下

**Comment by hsuyelin** [comment]
> 我从正版3.2.3转过来，订阅出问题，订阅会出现有资源不会下载的情况，晚上老老实实重新部署试下

基于原版3.2.3重构了，抽空更新下
