### ISSUE TITLE
用slack搜索影视最多显示8条相关信息，在nastool中实际上有20条信息

### ISSUE THREAD

**Issue by Raabo** [hsuyelin/nas-tools#113]
![new ducument](https://github.com/hsuyelin/nas-tools/assets/53669418/ddd80efd-5a52-473d-881e-631413835424)
![Screenshot 2023-08-25 at 09-31-25 NAStool](https://github.com/hsuyelin/nas-tools/assets/53669418/39c6169a-13e0-453e-b51f-d5f72dd4cc25)

**Comment by jackloves111** [comment]
不明白，这两者对使用有什么影响。

**Comment by Raabo** [comment]
![Screenshot 2023-08-25 at 09-31-252 NAStool](https://github.com/hsuyelin/nas-tools/assets/53669418/5e712806-93f2-42f7-bf54-1203fb73e3c1)
我其实想要的是这个，但slack只显示8条，导致无法满足我的需求

**Comment by yellowstrong** [comment]
那你为什么不去slack项目下面提 找错地方了吧

**Comment by jackloves111** [comment]
![5f2b9b046e11dbfe588e8d69451b2e7](https://github.com/hsuyelin/nas-tools/assets/89971817/303629f1-f459-4f46-9563-915a5ef3b376)
你搜的关键词不对兄弟，叫基地的这么多，你用英文名去搜就行了啊

**Comment by Raabo** [comment]
> 你搜的关键词不对兄弟，叫基地的这么多，你用英文名去搜就行了啊。第一个就是 ![5f2b9b046e11dbfe588e8d69451b2e7](https://user-images.githubusercontent.com/89971817/263147486-303629f1-f459-4f46-9563-915a5ef3b376.jpg)

但搞这个不就为了方便使用吗，这样多一步就背离这一目的了。

**Comment by Raabo** [comment]
> 那你为什么不去slack项目下面提 找错地方了吧

所以这是slack的问题吗？还是配置的时候设置了最多传8条信息

**Comment by Raabo** [comment]
> ![Screenshot 2023-08-25 at 09-31-252 NAStool](https://user-images.githubusercontent.com/53669418/263142863-5e712806-93f2-42f7-bf54-1203fb73e3c1.png) 我其实想要的是这个，但slack只显示8条，导致无法满足我的需求

出现这个问题其实和tmdb也有关系，它给基地的地区名称为空且无法编辑。
![图片](https://github.com/hsuyelin/nas-tools/assets/53669418/fc422f70-ebb8-43fb-a893-be9ff62ccfc5)

**Comment by jackloves111** [comment]
看下这个老哥的回复，让你多一步的不是nastool，是TMDB，建议你去TMDB官方社区。投诉他不让你编辑中文
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/6fd60966-8389-4bcd-86c8-acb1f0194f6f)

**Comment by Raabo** [comment]
> 看下这个老哥的回复，让你多一步的不是nastool，是TMDB，建议你去TMDB官方社区。投诉他不让你编辑中文。TMDB几个管理，都是反中派 ![image](https://user-images.githubusercontent.com/89971817/263154978-6fd60966-8389-4bcd-86c8-acb1f0194f6f.png)

就是我回复的，但在tmdb上改也是权宜之计。不知道微信上最多显示几个
