### ISSUE TITLE
问下各位大佬，3.2.10.7馒头porn刷大包的问题

### ISSUE THREAD

**Issue by ATMrunaway** [hsuyelin/nas-tools#114]
添加馒头porn站点后是能支持自动刷流吗？rss怎么抓取置顶免费呢？现在只是在站点资源里面能看到，仍然需要手动点击一键下载。

**Comment by hsuyelin** [comment]
> 添加馒头porn站点后是能支持自动刷流吗？rss怎么抓取置顶免费呢？现在只是在站点资源里面能看到，仍然需要手动点击一键下载。

试试新建一个rss，仅包含porn内容的

**Comment by ATMrunaway** [comment]
感谢解答。馒头置顶的大包一般是发布时间较久的，rss50条抓取不到。一直就是卡在这，没办法自动刷流。

**Comment by hsuyelin** [comment]
> 的大包一般是发布时间较久的，rss50条抓取不到。一直就是卡

是这样的，所以你新建一个rss，这个和rss有关系了，rss拉取不到的话，你怎么能自动刷流呢，只能手动刷了。加一个这个还是有必要的，因为如果正常的馒头这些资源都是看不到的
