### ISSUE TITLE
大佬隔壁出了个插件商店拓展包，应该有些作用，可以考虑咱们集成下

### ISSUE THREAD

**Issue by iovejieba** [hsuyelin/nas-tools#12]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.7
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？
大佬隔壁出了个插件商店拓展包，应该有些作用，可以考虑咱们集成下
https://gitee.com/Mattoid/nas-tools-plugin

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by hsuyelin** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.2.7
> > 环境: docker or windows or synology
> 
> ## 你想要新增或者改进什么功能？
> 大佬隔壁出了个插件商店拓展包，应该有些作用，可以考虑咱们集成下 https://gitee.com/Mattoid/nas-tools-plugin
> 
> > 你想要新增或者改进什么功能？
> 
> ## 这个功能有什么可以参考的资料吗？
> > 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

可以，我来研究下，目前他出了三个扩展，有两个是对官方的版本进行修复，我已经修复过了，还有一个我看看怎么集成进去

**Comment by iovejieba** [comment]
嗯嗯，感谢大佬 为爱更新！ :)

**Comment by hsuyelin** [comment]
> 嗯嗯，感谢大佬 为爱更新！ :)

已经集成了没有的2个插件，如果后续该作者继续更新将会继续同步更新，版本等我 3.2.8 更新，集成链接：https://github.com/hsuyelin/nas-tools/commit/188cfb9c8e19d6f2c9196e1b4a90c8892a3f267b
