### ISSUE TITLE
媒体整理实际重命名和刮削信息不符

### ISSUE THREAD

**Issue by Chen3553887** [hsuyelin/nas-tools#122]
![image](https://github.com/hsuyelin/nas-tools/assets/74977868/133e65fb-8760-4de3-91b0-df5c74fee2b0)
![image](https://github.com/hsuyelin/nas-tools/assets/74977868/66aac3ff-45a1-421f-9e05-990859748a5b)
刮削的是S01E31，但是硬链接转移后是S03E31，清理完了TMDB缓存，重新拉了最新代码。
指定季度（S01）+集数（31）也依然是S03E31

**Comment by hsuyelin** [comment]
> ![image](https://user-images.githubusercontent.com/74977868/263440066-133e65fb-8760-4de3-91b0-df5c74fee2b0.png)
> ![image](https://user-images.githubusercontent.com/74977868/263440078-66aac3ff-45a1-421f-9e05-990859748a5b.png)
> 刮削的是S01E31，但是硬链接转移后是S03E31，清理完了TMDB缓存，重新拉了最新代码。
> 指定季度（S01）+集数（31）也依然是S03E31

这个是原版识别的问题，完整名称自定义识别词试一下，近期有打算增强识别的

**Comment by Chen3553887** [comment]
找到原因了，因为我的路径是 /AnimeBT/租借女友 **第三季**/[[Nekomoe kissaten][Kanojo, Okarishimasu][25][1080p][JPSC].mp4]
上级目录有一个**第三季**，所以直接刮到S03了，改掉 **第三季**然后清理TMDB后就可以正确刮了。

**Comment by Chen3553887** [comment]
请问作者是否在某个更新版本中增加了对媒体文件的父文件夹识别，还是同样的问题。文件路径是/Anime/Mushoku.Tensei.Isekai.Ittara.Honki.Dasu.**S02**.2023.2160p.B-Global.WEB-DL.x264.AAC-ADWeb/Mushoku.Tensei.Isekai.Ittara.Honki.Dasu.S02E00.2023.2160p.B-Global.WEB-DL.x264.AAC-ADWeb.mkv，手动置顶S00E02时，整理完后是 **S02 E02 已入库**。在早些版本没有出现这个问题
