### ISSUE TITLE
目录同步报错

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#123]
## 目录同步配置如图
![QQ截图20230826202159](https://github.com/hsuyelin/nas-tools/assets/5012570/c2c3fc57-26a6-40b4-9b70-257131c780e9)

同步时报错如下

文件转移时发生错误：[Errno 2] No such file or directory: '/media/0本地待整理/nastools/电影/华语电影/聊斋之欲焰三娘子 (1992)/聊斋之欲焰三娘子 (1992).avi' - Traceback (most recent call last): File "/nas-tools/app/filetransfer.py", line 698, in transfer_media media.size = os.path.getsize(file_item) File "/usr/local/lib/python3.10/genericpath.py", line 50, in getsize return os.stat(filename).st_size FileNotFoundError: [Errno 2] No such file or directory: '/media/0本地待整理/nastools/电影/华语电影/聊斋之欲焰三娘子 (1992)/聊斋之欲焰三

由于日志显示不全复制不完整

## 虽然报错了，但是移动是成功了，就是结果也是对的，但是就老是出现这种错误，并不是这一次，有很多次，但是结果也是成功的

**Comment by hsuyelin** [comment]
抽空看看，应该是原版的问题，我之前就遇到过了，但是因为每次都是成功的，没去管他
