### ISSUE TITLE
Cloudflare IP优选 有修复计划吗

### ISSUE THREAD

**Issue by felix-klk** [hsuyelin/nas-tools#126]
![image](https://github.com/hsuyelin/nas-tools/assets/52670643/f4db856f-550c-46e0-81cc-043618ae681e)
rt 无法获取到优选ip

**Comment by hsuyelin** [comment]
cloudflare优选插件原理是直接调用cloudflare优选项目命令的，建议本地看看是否能直接通过cloudflare优选命令优选到ip

**Comment by felix-klk** [comment]
> cloudflare优选插件原理是直接调用cloudflare优选项目命令的，建议本地看看是否能直接通过cloudflare优选命令优选到ip

使用原版 win客户端是可以获取到的 以前用3.2.3 也是正常的

**Comment by hsuyelin** [comment]
新版本已修复
