### ISSUE TITLE
有计划修复下天空无法辅种的问题吗？

### ISSUE THREAD

**Issue by beiming0000** [hsuyelin/nas-tools#128]
IYUU插件在拼接torrent_url时会强制加上https=1参数（如下代码，引用自IYUU插件），这会导致获取天空的种子时报404错误，作者有计划修复这个问题吗？

        # 强制使用Https
        if "?" in torrent_url:
            torrent_url += "&https=1"
        else:
            torrent_url += "?https=1"

**Comment by hsuyelin** [comment]
有计划的，抽空看看

**Comment by Travisss** [comment]
同求，有时间帮修复一下，谢谢
