### ISSUE TITLE
站点Cookie一直失效

### ISSUE THREAD

**Issue by FantasticSkyBaby** [hsuyelin/nas-tools#129]
添加MT的站点，网页访问正常，测试添加站点一直显示失效
![image](https://github.com/hsuyelin/nas-tools/assets/14800057/d5cd73af-b67b-4fb4-be4d-ed6e6b2bdb48)

**Comment by hh0610** [comment]
> 添加MT的站点，网页访问正常，测试添加站点一直显示失效 ![image](https://user-images.githubusercontent.com/14800057/263655922-d5cd73af-b67b-4fb4-be4d-ed6e6b2bdb48.png)

你是不是有开二级认证

**Comment by FantasticSkyBaby** [comment]
> > 添加MT的站点，网页访问正常，测试添加站点一直显示失效 ![image](https://user-images.githubusercontent.com/14800057/263655922-d5cd73af-b67b-4fb4-be4d-ed6e6b2bdb48.png)
> 
> 你是不是有开二级认证

之前也一直开的认证，没有啥问题

**Comment by hh0610** [comment]
> 开了两步验证

关了就可以通过测试了

**Comment by iovejieba** [comment]
关两步验证，或者是cf抽风

**Comment by FantasticSkyBaby** [comment]
请问开启两步验证有办法能解决cookie问题么
