### ISSUE TITLE
憨憨无法下载订阅的电视剧

### ISSUE THREAD

**Issue by rotent** [hsuyelin/nas-tools#130]
如图，《完美世界》缺失第125集，憨憨站点已发布，订阅后显示未下载到资源

**Comment by rotent** [comment]
![1e585492981a0c6fad65b6c14879be5](https://github.com/hsuyelin/nas-tools/assets/93746829/2c9487ea-ef17-48c1-bb27-72d0006a72be)
![e07c47bcb591202ab8716f994830f4c](https://github.com/hsuyelin/nas-tools/assets/93746829/250805db-7dde-4e3d-8504-4194e26a4343)
![30ed610c237a4a9d507849105b0e250](https://github.com/hsuyelin/nas-tools/assets/93746829/4da65c7a-64bd-429e-bec4-e2273b4a382a)
![405eeed7d7f2dfce94c3ccee04bae55](https://github.com/hsuyelin/nas-tools/assets/93746829/ea499972-0ebb-48f2-87c4-a129c931b962)

**Comment by rotent** [comment]
而用观众订阅的《斗破苍穹》可以下载

**Comment by felix-klk** [comment]
> 而用观众订阅的《斗破苍穹》可以下载

自己自定义识别词

**Comment by felix-klk** [comment]
> > 而用观众订阅的《斗破苍穹》可以下载
> 
> 自己自定义识别词

不过我也想问问大佬 搜索是不会搜索副标题的吗 @hsuyelin

**Comment by iovejieba** [comment]
> > > 而用观众订阅的《斗破苍穹》可以下载
> > 
> > 
> > 自己自定义识别词
> 
> 不过我也想问问大佬 搜索是不会搜索副标题的吗 @hsuyelin

大佬这几天忙，等几天再说吧，我后来尝试适配了下 没号没办法测，你们谁拉一下sites 测下看看吧

**Comment by hsuyelin** [comment]
> > > 而用观众订阅的《斗破苍穹》可以下载
> > 
> > 
> > 自己自定义识别词
> 
> 不过我也想问问大佬 搜索是不会搜索副标题的吗 @hsuyelin

副标题会搜索到其他内容，之前尝试搜副标题，但是结果不准确
