### ISSUE TITLE
朱雀无法刷流

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#132]
Rss里面有符合刷流规则的种子，可能跟朱雀Rss改版有关系以下是朱雀Rss改版通知
返回信息做出如下变更:
标题格式由原有的主标题改为
[分类][主标题][副标题][标签][用户 ID]
若非本人且发种是勾选匿名则用户 ID 显示为 匿名
例:
[剧集][The Ingenious One 2023 S01 2160p WEB-DL H265 AAC-ZWEX][云襄传 第 1 季 全 36 集 | 导演: 游达志 主演: 陈晓 毛晓彤 腾讯视频][官方 | 国语 | 中字][匿名]

**Comment by hsuyelin** [comment]
可以基于此pr: https://github.com/hsuyelin/nas-tools-sites/blob/master/sites/%E6%9C%B1%E9%9B%80.json 或者等待我后期修复
