### ISSUE TITLE
硬连接的问题

### ISSUE THREAD

**Issue by shiningth** [hsuyelin/nas-tools#134]
![1fd1f816f83a11205b9e07db6427d90](https://github.com/hsuyelin/nas-tools/assets/38234408/0d8bca05-3ab2-48bd-ad30-aac84dca9dcb)
![9e2070e89928b67039ea06309905ff9](https://github.com/hsuyelin/nas-tools/assets/38234408/3f3b5f46-f3b2-4c99-b590-eee18e5ac65e)
![cc82443eb64cc2389b221d9a81382aa](https://github.com/hsuyelin/nas-tools/assets/38234408/f7df3967-a058-46bf-8d30-64a9886afd53)
自动同步就报错,但是手动能成功
![63327df32f2e2fcb1509ac5445515a8](https://github.com/hsuyelin/nas-tools/assets/38234408/82423d0a-4396-4bce-84a9-1e638240b383)
是我目录设置的不对吗?

**Comment by Teddy-Zhu** [comment]
媒体库是指 emby之类的媒体系统的目录 , 和 下载目录需要区分开来 , 比如 /Z4/Download/TV是下载目录 , 那么媒体目录可以是
/Z4/Media/TV ,媒体目录不能包含下载目录
