### ISSUE TITLE
下载器建议

### ISSUE THREAD

**Issue by glenhuo** [hsuyelin/nas-tools#135]
不好意思，我的想法有失考虑，抱歉

**Comment by yellowstrong** [comment]
你这描述就有问题，你的意思是下载种子到阿里云盘？怎么可能，首先不说阿里云盘支不支持离线下载，为什么要把BT的种子放在公开的网盘里面？BT就是BT，不可能在网盘传播

**Comment by jackloves111** [comment]
你可以用qb下载后，用群晖同步上传，定时删种。直接下载到云盘应该是不支持的
