### ISSUE TITLE
新版本无更新按钮.左下角github连接为官方版本链接

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#136]
![1693373621915](https://github.com/hsuyelin/nas-tools/assets/142991330/9fe460e6-a387-4203-9235-70cfa54dc7bd)
![1693373669495(1)](https://github.com/hsuyelin/nas-tools/assets/142991330/c2cd52f4-2fdc-474b-a3de-767daf65250f)

**Comment by hsuyelin** [comment]
等下在处理中

**Comment by hsuyelin** [comment]
等打包完成把
