### ISSUE TITLE
能直接打开刷流功能吗？

### ISSUE THREAD

**Issue by lddsb** [hsuyelin/nas-tools#14]
刷流好像要触发什么条件才能显示，能不能直接显示？

**Comment by iovejieba** [comment]
> 刷流好像要触发什么条件才能显示，能不能直接显示？

添加站点后 重启就启用了

**Comment by hsuyelin** [comment]
> > 刷流好像要触发什么条件才能显示，能不能直接显示？
> 
> 添加站点后 重启就启用了

@lddsb
