### ISSUE TITLE
dockerhub上的最新版本跑不起来了

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#143]
dockerhub上的最新版本跑不起来了，是不是打包出现问题了 hsuyelin/nas-tools:latest标签的

**Comment by DDSDerek** [comment]
> dockerhub上的最新版本跑不起来了，是不是打包出现问题了 hsuyelin/nas-tools:latest标签的

稍等，马上解决

**Comment by hsuyelin** [comment]
@DDSDerek @yellowstrong 打包好了，测试可以

**Comment by DDSDerek** [comment]
我这边测试debian和alpine镜像都正常了

**Comment by jackloves111** [comment]
大改动啊，大佬们

**Comment by yellowstrong** [comment]
一切正常了

**Comment by hsuyelin** [comment]
> 大改动啊，大佬们

docker这方面，大佬是专家
