### ISSUE TITLE
库非适配一下

### ISSUE THREAD

**Issue by xx-super** [hsuyelin/nas-tools#145]
{"id": "kufei", "name": "\u5e93\u975e", "builtin": true, "domain": "https://kufei.org", "search": {"paths": [{"path": "torrents.php", "method": "get"}], "params": {"search": "{keyword}"}, "batch": {"delimiter": " ", "space_replace": "_"}}, "batch": {"delimiter": " ", "space_replace": "_"}, "parser": null, "render": null, "browse": {}, "torrents": {"list": {"selector": "table.torrents > tr:has(\"table.torrentname\")"}, "fields": {"id": {"selector": "a[href*=\"details.php?id=\"]", "attribute": "href", "filters": [{"name": "re_search", "args": ["\\d+", 0]}]}, "category": {"selector": "a[href*=\"?cat=\"]", "attribute": "href", "filters": [{"name": "querystring", "args": "cat"}]}, "title_default": {"selector": "a[href*=\"details.php?id=\"]"}, "title_optional": {"optional": true, "selector": "a[title][href*=\"details.php?id=\"]", "attribute": "title"}, "title": {"text": "{% if fields['title_optional'] %}{{ fields['title_optional'] }}{% else %}{{ fields['title_default'] }}{% endif %}"}, "details": {"selector": "a[href*=\"details.php?id=\"]", "attribute": "href"}, "poster": {"selector": "img[data-orig]", "attribute": "data-orig"}, "download": {"selector": "a[href*=\"download.php?id=\"]", "attribute": "href"}, "size": {"selector": "td.rowfollow:nth-child(5)"}, "grabs": {"selector": "td.rowfollow:nth-child(8)"}, "seeders": {"selector": "td.rowfollow:nth-child(6)"}, "leechers": {"selector": "td.rowfollow:nth-child(7)"}, "date_elapsed": {"selector": "td.rowfollow:nth-child(4) > span", "optional": true}, "date_added": {"selector": "td.rowfollow:nth-child(4) > span", "attribute": "title", "optional": true}, "date": {"text": "{% if fields['date_elapsed'] or fields['date_added'] %}{{ fields['date_elapsed'] if fields['date_elapsed'] else fields['date_added'] }}{% else %}now{% endif %}", "filters": [{"name": "dateparse", "args": "%Y-%m-%d %H:%M:%S"}]}, "downloadvolumefactor": {"case": {"img.pro_free": 0, "img.pro_free2up": 0, "img.pro_50pctdown": 0.5, "img.pro_50pctdown2up": 0.5, "img.pro_30pctdown": 0.3, "*": 1}}, "uploadvolumefactor": {"case": {"img.pro_50pctdown2up": 2, "img.pro_free2up": 2, "img.pro_2up": 2, "*": 1}}, "free_deadline": {"default_value": "{% if fields['downloadvolumefactor']==0 %}{{max_time}}{% endif%}", "default_value_format": "%Y-%m-%d %H:%M:%S.%f", "selector": "div > b > span[title]", "attribute": "title", "filters": [{"name": "dateparse", "args": "%Y-%m-%d %H:%M:%S"}]}, "tags": {"selector": "div > a.torrents-tag"}, "subject": {"selector": "td.embedded:nth-child(2) > div > div:nth-child(2) > span", "contents": -1}, "description": {"selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)", "remove": "span,a,img,font,b", "contents": -1}, "labels": {"selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span"}}}, "category": {"movie": [{"id": 401, "cat": "Movies", "desc": "Movies(\u7535\u5f71)", "default": true}], "tv": [{"id": 402, "cat": "TV", "desc": "TV Series(\u7535\u89c6\u5267)", "default": true}, {"id": 403, "cat": "TV", "desc": "TV Shows(\u7efc\u827a)", "default": true}, {"id": 404, "cat": "TV/Documentary", "desc": "Documentaries(\u7eaa\u5f55\u7247)", "default": true}, {"id": 405, "cat": "TV/Anime", "desc": "Animations(\u52a8\u753b)", "default": true}]}, "siteid": null, "cookie": null, "ua": null, "rule": null, "public": false, "proxy": false, "language": null, "pri": 0}

**Comment by hsuyelin** [comment]
以后可以去这个仓库直接pr： https://github.com/hsuyelin/nas-tools-sites

**Comment by hsuyelin** [comment]
done
