### ISSUE TITLE
nastool的 红豆饭 和 蝶粉站点搜索不显示副标题，更新3.3.0站点不支持PTLSP

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#146]
nastool的 红豆饭 和 蝶粉站点搜索不显示副标题
原3.2.10.8支持PTLSP，更新3.3.0不支持PTLSP，只能通过自定义添加

**Comment by hh0610** [comment]
咖啡搜索也不显示副标题

**Comment by hsuyelin** [comment]
1. 副标题是站点索引规则导致的，有能力的可以去 https://github.com/hsuyelin/nas-tools-sites pr
2. 不要使用自定义插件，这个功能会导致程序不稳定，如果有需要的站点提issue即可
3. PTLSP我抽空加下

**Comment by MyGiki** [comment]
@hsuyelin 
刚刚测试，熊猫和肉丝站点搜不到东西。

**Comment by hsuyelin** [comment]
> 熊猫和肉丝

站点搜不到东西和站点文件有关系，修改站点文件即可，或者你有可用的站点文件，可以贴出来

**Comment by hsuyelin** [comment]
最近比较忙，抽空我来更新下

**Comment by hsuyelin** [comment]
@MyGiki @hh0610 没有站，看其他的大佬的配置文件的，尝试红豆饭、蝶粉增加副标题，咖啡没找到，新增了PTLSP，如果还不行，你们只能自己探索配置了，然后提交到 https://github.com/hsuyelin/nas-tools-sites 即可，等我更新后拉取代码即可

**Comment by hsuyelin** [comment]
已更新，暂且关了
