### ISSUE TITLE
3.3.0版本不支持岛和空的特殊站点签到了

### ISSUE THREAD

**Issue by iamchq** [hsuyelin/nas-tools#147]
3.3.0岛签到提示模拟登录成功，空提示无法获取验证码

**Comment by hsuyelin** [comment]
日志等级切到debug，看下日志

**Comment by iamchq** [comment]
[run.txt](https://github.com/hsuyelin/nas-tools/files/12481510/run.txt)
![屏幕截图 2023-08-31 101611](https://github.com/hsuyelin/nas-tools/assets/142661747/02a35749-9b18-42f4-87c9-84b8518b5fc4)

**Comment by iamchq** [comment]
那个run日志里面应该不涉及什么隐私的吧，还有岛的域名用的是带pt的，是之前更新过的域名，不是原来的

**Comment by hsuyelin** [comment]
> [run.txt](https://github.com/hsuyelin/nas-tools/files/12481510/run.txt)
> ![屏幕截图 2023-08-31 101611](https://user-images.githubusercontent.com/142661747/264515811-02a35749-9b18-42f4-87c9-84b8518b5fc4.png)

好嘞，抽空看下，问题应该不大

**Comment by beiming0000** [comment]
不是不支持了，是nastool的wiki和ocr服务器关闭了，空的验证码没法获取了。换成百度OCR服务应该可解。

**Comment by hsuyelin** [comment]
> 不是不支持了，是nastool的wiki和ocr服务器关闭了，空的验证码没法获取了。 nt群里的说法是有能力的自建ocr服务，没能力的改用mp。 个人觉得换成调用百度OCR接口，自己填api token应该可行。

原来是这样，我研究下百度OCR接口

**Comment by beiming0000** [comment]
> > 不是不支持了，是nastool的wiki和ocr服务器关闭了，空的验证码没法获取了。 nt群里的说法是有能力的自建ocr服务，没能力的改用mp。 个人觉得换成调用百度OCR接口，自己填api token应该可行。
> 
> 原来是这样，我研究下百度OCR接口

可能把ocr_helper.py改成mp的ocr.py也行？（不太懂代码，纯猜）
https://github.com/jxxghp/MoviePilot/blob/main/app/helper/ocr.py

**Comment by iamchq** [comment]
> > [run.txt](https://github.com/hsuyelin/nas-tools/files/12481510/run.txt)
> > ![屏幕截图 2023-08-31 101611](https://user-images.githubusercontent.com/142661747/264515811-02a35749-9b18-42f4-87c9-84b8518b5fc4.png)
> 
> 好嘞，抽空看下，问题应该不大

岛的特殊签到可以弄两个域名，不带pt的那个挂代理也能进，带pt的国内访问，域名我就不发了，应该都知道

**Comment by iamchq** [comment]
> > [run.txt](https://github.com/hsuyelin/nas-tools/files/12481510/run.txt)
> > ![屏幕截图 2023-08-31 101611](https://user-images.githubusercontent.com/142661747/264515811-02a35749-9b18-42f4-87c9-84b8518b5fc4.png)
> 
> 好嘞，抽空看下，问题应该不大

试了下，岛不带PT的域名挂代理进入后也会跳转到带PT的域名，那还是把特殊签到的域名改成带PT的吧

**Comment by hsuyelin** [comment]
> > > 不是不支持了，是nastool的wiki和ocr服务器关闭了，空的验证码没法获取了。 nt群里的说法是有能力的自建ocr服务，没能力的改用mp。 个人觉得换成调用百度OCR接口，自己填api token应该可行。
> > 
> > 
> > 原来是这样，我研究下百度OCR接口
> 
> 可能把ocr_helper.py改成mp的ocr.py也行？（不太懂代码，纯猜） https://github.com/jxxghp/MoviePilot/blob/main/app/helper/ocr.py

不可以，MP和NT用的一套代码，只是MP把host提取出可变参数了

**Comment by hsuyelin** [comment]
试试拉取下版本，看是否可以签到 @iamchq

**Comment by iamchq** [comment]
> 试试拉取下版本，看是否可以签到 @iamchq

可以签到了，现在提示签到成功了，岛也没提示模拟登录了
<html>
<body>


12:44:32 | Plugin | 站点自动签到 - 签到服务启动，立即运行一次
-- | -- | --
12:44:32 | Plugin | 站点自动签到 - 定时签到服务启动，周期：15 */1 * * *
12:44:35 | Plugin | 站点自动签到 - 今日 2023-08-31 未签到，开始签到已选站点
12:44:35 | Plugin | 站点自动签到 - 开始执行签到任务
12:44:36 | Sites | CHDBits - 今日已签到
12:44:40 | Sites | HDSky - ocr识别空验证码成功 2P1B4P
12:44:42 | Sites | HDSky - 签到成功
12:44:42 | Plugin | 站点自动签到 - 站点签到任务完成！
12:44:42 | Message | 发送消息 IYUU：title=站点签到, text=【空】签到成功 【岛】今日已签到
12:44:42 | Message | 发送消息 IYUU：title=【自动签到任务完成】, text=本次签到数量: 2 命中重试数量: 0 强制签到数量: 2 下次签到数量: 2 下次签到时间: 2023-08-31 13:15:00 详见签到消息


</body>
</html>

**Comment by hsuyelin** [comment]
> 不是不支持了，是nastool的wiki和ocr服务器关闭了，空的验证码没法获取了。 nt群里的说法是有能力的自建ocr服务，没能力的改用mp。 个人觉得换成调用百度OCR接口，自己填api token应该可行。

支持百度精确OCR，理论上会更牛，个人一个月1000次完全够用了
