### ISSUE TITLE
媒体整理文件管理UIbug

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#152]
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/5957e6ff-0682-4764-86f1-8c31715a8446)
看了下那个哥们的提交，应该是有bug吧，这个页面，没有适配最大宽度，而且硬连接标识也没有显示出来

**Comment by yellowstrong** [comment]
@waylonwang 想法是挺好，但是要考虑得多平台适配问题，不然其他设备整理起来就很困难了

**Comment by hsuyelin** [comment]
> @waylonwang 想法是挺好，但是要考虑得多平台适配问题，不然其他设备整理起来就很困难了

拉下代码看看

**Comment by jackloves111** [comment]
但是当用户的屏幕足够大的时候，可能限定高度可能看起来很奇怪

**Comment by hsuyelin** [comment]
> 其实就是让右边显示的多一些，让左边文件树压缩一点

是的，这个是这位pr的大佬考虑哪个更应该关注的问题，他觉得右边才是重点，所以让右边显示全一点

**Comment by jackloves111** [comment]
> > 其实就是让右边显示的多一些，让左边文件树压缩一点
> 
> 是的，这个是这位pr的大佬考虑哪个更应该关注的问题，他觉得右边才是重点，所以让右边显示全一点

是不是不应该限定高度？auto高度即可

**Comment by yellowstrong** [comment]
那位pr老哥想法是没错的，主要就是样式问题，他的提交上面 文件选择树整个宽度是固定的，应该是宽度跟随父容器的宽度，高度auto，然后，我看到他的图上面还有一些其他元素，比如硬连接指示器之类的，不是到是不是bug我这边都没有显示

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/3265918b-5b71-4cca-a955-566dc6db129b)

这是不限定高度的

![Uploading image.png…]()

这是限定高度的情况

**Comment by jackloves111** [comment]
这种用户屏幕足够大的情况下，限定高度是不合适的

**Comment by hsuyelin** [comment]
> 那位pr老哥想法是没错的，主要就是样式问题，他的提交上面 文件选择树整个宽度是固定的，应该是宽度跟随父容器的宽度，高度auto，然后，我看到他的图上面还有一些其他元素，比如硬连接指示器之类的，不是到是不是bug我这边都没有显示

你是硬链接么

**Comment by yellowstrong** [comment]
> > 那位pr老哥想法是没错的，主要就是样式问题，他的提交上面 文件选择树整个宽度是固定的，应该是宽度跟随父容器的宽度，高度auto，然后，我看到他的图上面还有一些其他元素，比如硬连接指示器之类的，不是到是不是bug我这边都没有显示
> 
> 你是硬链接么

是的

**Comment by hsuyelin** [comment]
@yellowstrong 我回复了那个大哥，貌似确实没有他那个效果，我觉得是不是有些提交没提交上来

**Comment by jackloves111** [comment]
> @yellowstrong 我回复了那个大哥，貌似确实没有他那个效果，我觉得是不是有些提交没提交上来

是不是指示器需要新的链接才会显示？

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/bfbc696a-c959-4843-8683-5717f88872c4)
为啥我有这个效果？这个你有吗？ @yellowstrong

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/bfc2567a-8859-444f-b940-f65256c82372)
还挺好看的

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/4777c1ed-2365-4d8e-8fa5-095c119f1862)
还会标识做种文件的名称，这个绝对实用，这个大哥肯定是个前端大佬

**Comment by yellowstrong** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/264574165-bfbc696a-c959-4843-8683-5717f88872c4.png) 为啥我有这个效果？这个你有吗？ @yellowstrong

完全没有，你是什么环境

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/855ac220-4da8-4bbf-9df9-e660a1004d0f)
我认真去看了一下大佬写的更新内容，他这个通过你设置的目录同步来实现判断的，也就是先设置目录同步，然后就会有显示，不设置应该就没有

**Comment by yellowstrong** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/264577639-855ac220-4da8-4bbf-9df9-e660a1004d0f.png)
> 
> ![image](https://user-images.githubusercontent.com/89971817/264578036-c02bdbc3-1b28-4c43-bcc6-29e15ef2038c.png)
> 
> 我认真去看了一下大佬写的更新内容，他这个通过你设置的目录同步来实现判断的，也就是先设置目录同步，然后就会有显示，不设置应该就没有

好吧，那我压根就没有用目录同步，我都是直接下载器硬连接转移

**Comment by jackloves111** [comment]
所有这个不能算是BUG，只是需要目录同步设置

**Comment by jackloves111** [comment]
> @hsuyelin 建议写进更新日志里，这个改动比较好的

@hsuyelin

**Comment by hsuyelin** [comment]
> > @hsuyelin 建议写进更新日志里，这个改动比较好的
> 
> @hsuyelin

看到了，牛的，今天更新一个版本吧
