### ISSUE TITLE
微信交互不显示图片的问题

### ISSUE THREAD

**Issue by mzj001** [hsuyelin/nas-tools#153]
微信交互不显示图片的问题
![微信图片_20230831160512](https://github.com/hsuyelin/nas-tools/assets/53402347/78534862-5942-4701-882b-f8020e41337d)
大佬能否修复一下，谢谢！

**Comment by jackloves111** [comment]
![691817546fdbc875325c3f23be49303](https://github.com/hsuyelin/nas-tools/assets/89971817/cf3a1d5e-d1fa-46fe-b7ef-af46d60fc94b)
不显示图片是你的网络问题，和程序无关，连不上TMDB可以开代理

**Comment by szicely** [comment]
微信企业号现在私人好象开通不了啦对吗？

**Comment by mzj001** [comment]
> ![691817546fdbc875325c3f23be49303_看图王(1)](https://user-images.githubusercontent.com/89971817/264579724-757b4cc4-1123-4520-a3c3-7cc0d6468dc4.jpg)
> 
> 不显示图片是你的网络问题，和程序无关，连不上TMDB可以开代理

不是网络问题，我网络是通畅。
![捕获](https://github.com/hsuyelin/nas-tools/assets/53402347/79d58863-fd77-4b3f-9379-f28fa9abb04a)

**Comment by mzj001** [comment]
不是网络问题，我网络是通畅。
![捕获](https://github.com/hsuyelin/nas-tools/assets/53402347/8f5a27e8-802c-4773-8a28-572aac54b7f3)
把这个关闭了就显示正常，打开就不显示图片。前几天是正常的，就前两天这样的了。

**Comment by jackloves111** [comment]
> 不是网络问题，我网络是通畅。 ![捕获](https://user-images.githubusercontent.com/53402347/264932646-8f5a27e8-802c-4773-8a28-572aac54b7f3.PNG) 把这个关闭了就显示正常，打开就不显示图片。前几天是正常的，就前两天这样的了。

那这个确实是BUG了，豆瓣图片之前的失效了，这里的api没有改 @hsuyelin

**Comment by jackloves111** [comment]
> > 不是网络问题，我网络是通畅。 ![捕获](https://user-images.githubusercontent.com/53402347/264932646-8f5a27e8-802c-4773-8a28-572aac54b7f3.PNG) 把这个关闭了就显示正常，打开就不显示图片。前几天是正常的，就前两天这样的了。
> 
> 那这个确实是BUG了，豆瓣图片之前的失效了，这里的api没有改 @hsuyelin ，这个选项开启后，图片是走的豆瓣

今天在群里看到问题的原因了，不是程序问题，应该是微信把豆瓣的接口屏蔽了，打开是404
