### ISSUE TITLE
能否提供docker的全版本镜像，目前不支持armv7的32位设备

### ISSUE THREAD

**Issue by hjdhnx** [hsuyelin/nas-tools#154]
如题。希望增加armv7镜像，感谢大佬

**Comment by flash168** [comment]
我也是armv7，网上找不到相关版本。群友还有好多armv7。希望大佬能给适配下。

**Comment by jackloves111** [comment]
我一直用的X86，想学习下，ARM V7和ARM有什么不同吗？

**Comment by hsuyelin** [comment]
> 

这个年代还有 armv7 的设备么 😭

**Comment by flash168** [comment]
有啊，矿渣一大堆呢。不过因为不支持好多都放弃转64了。大佬能适配下吗？

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/5a6bf1c7-333c-456e-a45f-215cbdfa6886)
直接本地化运行

**Comment by wdzzz** [comment]
没必要了吧，徒增维护压力。nastool对设备要求不低的，老设备就别玩nastool了

**Comment by hsuyelin** [comment]
> 

附议，而且armv7我升级了有些依赖包估计也不支持
