### ISSUE TITLE
咖啡最新版本刷流没有免费选项，旧版本有的

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#155]

**Comment by hsuyelin** [comment]
新版本是哪个版本，旧版本是哪个版本

**Comment by hh0610** [comment]
> 新版本是哪个版本，旧版本是哪个版本

feat(indexer): 尝试红豆饭、蝶粉增加副标题, 新增PTLSP/梓喵/exoticaz站点支持，这个版本前有的

**Comment by hsuyelin** [comment]
> > 新版本是哪个版本，旧版本是哪个版本
> 
> feat(indexer): 尝试红豆饭、蝶粉增加副标题, 新增PTLSP/梓喵/exoticaz站点支持，这个版本前有的

OK，我看下

**Comment by hsuyelin** [comment]
> > 新版本是哪个版本，旧版本是哪个版本
> 
> feat(indexer): 尝试红豆饭、蝶粉增加副标题, 新增PTLSP/梓喵/exoticaz站点支持，这个版本前有的

还真是，尝试修改咖啡副标题的时候，不小心编辑错了，我来提交

**Comment by hsuyelin** [comment]
> > 新版本是哪个版本，旧版本是哪个版本
> 
> feat(indexer): 尝试红豆饭、蝶粉增加副标题, 新增PTLSP/梓喵/exoticaz站点支持，这个版本前有的

已修复
