### ISSUE TITLE
OCR的config参数错了，项目启动失败

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#157]
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/64f5e09a-77c1-46b8-87ca-2462b107b79c)

**Comment by yellowstrong** [comment]
两个重复了

**Comment by hsuyelin** [comment]
@yellowstrong  done

**Comment by hsuyelin** [comment]
> 两个重复了

手滑了，😭
