### ISSUE TITLE
关于OCR建议

### ISSUE THREAD

**Issue by DDSDerek** [hsuyelin/nas-tools#160]
1. 实现支持百度OCR我是非常赞成的
2. 我不建议默认把MoviePilot的OCR地址填入，因为作者关闭NAStool服务也是因为很多软件解除了站点验证，导致再提供服务有一定风险，所以我认为默认可以把地址留空，提供自建OCR的教程，或者使用百度OCR，而不是去默认切换成MoviePilot的OCR地址。
3. 关于自建OCR我这边可以提供教程和镜像。

希望 @hsuyelin 可以考虑一下，并一起交流解决这个问题。

**Comment by hsuyelin** [comment]
> 1. 实现支持百度OCR我是非常赞成的
> 2. 我不建议默认把MoviePilot的OCR地址填入，因为作者关闭NAStool服务也是因为很多软件解除了站点验证，导致再提供服务有一定风险，所以我认为默认可以把地址留空，提供自建OCR的教程，或者使用百度OCR，而不是去默认切换成MoviePilot的OCR地址。
> 3. 关于自建OCR我这边可以提供教程和镜像。
> 
> 希望 @hsuyelin 可以考虑一下，并一起交流解决这个问题。

我也考虑了这个所以开放了多个OCR的方式，主要是大部分用的人基本是无能力用户，我这边也没有可用的服务器资源，你的意见是什么呢

**Comment by iovejieba** [comment]
可以默认用百度的ocr并且预留自建接口，在外部一个wik提供一个自建对接教程 我感觉就可以了  这样既可以考虑动手能力低的用户也可以考虑到其他用户

**Comment by hsuyelin** [comment]
> 可以默认用百度的ocr并且预留自建接口，在外部一个wik提供一个自建对接教程 我感觉就可以了 这样既可以考虑动手能力低的用户也可以考虑到其他用户

百度OCR需要自己申请Api key 和 Secret key，大部分小白用户盲猜一手不会不学 @iovejieba

**Comment by DDSDerek** [comment]
我这边有空余的服务器，可以通过OCR服务，但是以NAStool现在用户量有可能服务器会撑不住

**Comment by hsuyelin** [comment]
> 我这边有空余的服务器，可以提供OCR服务，但是以NAStool现在用户量有可能服务器会撑不住

那就下掉把，饭喂到嘴边了，还不会就没办法惹

**Comment by jackloves111** [comment]
> > 我这边有空余的服务器，可以提供OCR服务，但是以NAStool现在用户量有可能服务器会撑不住
> 
> 那就下掉把，饭喂到嘴边了，还不会就没办法惹

这个知会影响到签到的插件吧，自己申请Api key 和 Secret key好了。这都不会的话就不要用了，大家都是为爱发电的，可以放上教程，教程我可以写

**Comment by DDSDerek** [comment]
其实可以我们可以自己公益开OCR的服务端，然后让用户自己选或者自己开。

**Comment by iovejieba** [comment]
tx al 轻量对付个两年倒无所谓 关键...怕撑不住 就目前这个访问量来看的话

**Comment by DDSDerek** [comment]
@hsuyelin https://ocr.ddsrem.com/ 我暂时提供一个，看看访问量，如果撑得住就一直开着

**Comment by hsuyelin** [comment]
> @hsuyelin https://ocr.ddsrem.com/ 我暂时提供一个，看看访问量，如果撑得住就一直开着
 
好嘞，多谢大佬 https://github.com/hsuyelin/nas-tools/commit/c05cb16bf07e1a0d356ca3a8d7cdea625247b1d6 已内置
