### ISSUE TITLE
经测试 v3.3.1 15bf751 熊猫、Rousi、碟粉。这3个站点问题没处理

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#161]
1.熊猫、Rousi 直接搜不到东西。所以搜索结果有没修复显示副标题就不得而知
2.碟粉搜索结果不显示副标题

**Comment by hsuyelin** [comment]
之前可以搜到么，这个版本我用了MP的肉丝索引

**Comment by MyGiki** [comment]
3.2.10.8 初始版 没小更新过的版本，这些站都可以搜索，但就是不显示标题。

**Comment by hsuyelin** [comment]
> 3.2.10.8 初始版 没小更新过的版本，这些站都可以搜索，但就是不显示标题。

那我改回去，先保证能搜索，有标题什么的只能说更好

**Comment by MyGiki** [comment]
等等

**Comment by MyGiki** [comment]
@hsuyelin 
 v3.2.10.8 111e7b4
这个版本的 熊猫、Rousi、PTLSP、都能搜索，也能显示副标题，正常使用。
只是 红豆饭 和 碟粉 没有显示搜索副标题而已。在这个版本修复一下 红豆饭 和 碟粉显示搜索副标题就好了

**Comment by hsuyelin** [comment]
@MyGiki 最新提交已经恢复到到v3.2.10.8的索引内容了，再搜索不到，只能说站点改了，需要有大佬站出来喂索引的饭了

**Comment by MyGiki** [comment]
晚点我更新试试，我退回3.2.10.8了

**Comment by MyGiki** [comment]
@hsuyelin 
v3.3.1 a7e5ea7  问题依旧没解决

**Comment by MyGiki** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/107430324/1502887a-0af5-45ea-9324-60dac806829b)
