### ISSUE TITLE
是否能添加软连接的自定义

### ISSUE THREAD

**Issue by dahuzi-gege** [hsuyelin/nas-tools#164]
环境：阿里云网盘++alist+clouddrive2后会自动挂载为根目录。用nastool刮削软连接到emby 提示无法支持流。SSH进入发现软连接地址目标为空。手动软连接就正常了

**Comment by hsuyelin** [comment]
不打算支持，建议使用硬链接

**Comment by dahuzi-gege** [comment]
使用硬链接网盘会报错呀大佬
