### ISSUE TITLE
无法搜索资源，无论是内建索引，还是通过插件扩展，右上角小人点击没反应

### ISSUE THREAD

**Issue by yuzhi-jiang** [hsuyelin/nas-tools#165]
如题

**Comment by iovejieba** [comment]
> 如题

具体哪个站无法搜索 请说清楚一下

**Comment by iovejieba** [comment]
> > 如题
> 
> 具体哪个站无法搜索 请说清楚一下，这边刚测试不管是外部索引还是内建都正常

**Comment by hh0610** [comment]
你是什么版本的，最新版用插件扩展会有兼容性问题

**Comment by jackloves111** [comment]
issues模板还是之前的好，现在直接提问没有版本情况了。麻烦截图你的版本，你的站点配置，不然只能给你算一卦

**Comment by iovejieba** [comment]
3.3.0的话 目前插件内建都正常 331 还没拉镜像不好说

**Comment by yuzhi-jiang** [comment]
操作如下：搜索或者某个探索中豆瓣电影随便选择一个影片，点击搜索资源，显示 未搜索到任何资源
版本：docker最新版，win10 3.3.0

**Comment by yuzhi-jiang** [comment]
哈哈，是的，提的时候还疑惑没设置 issue模板

**Comment by jackloves111** [comment]
你的站点配置呢？

**Comment by yuzhi-jiang** [comment]
没设置pt站点，是不支持bt吗

**Comment by jackloves111** [comment]
日志截图呢

**Comment by iovejieba** [comment]
> 没设置pt站点，是不支持bt吗

内置现在不支持公开站点了  要bt折腾外部索引器吧

**Comment by yuzhi-jiang** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/45190043/ac223d8d-143c-4e0c-be5d-e3a9330f864e)
![image](https://github.com/hsuyelin/nas-tools/assets/45190043/4e762403-7ba8-4a87-889b-8e45f6550b34)
![image](https://github.com/hsuyelin/nas-tools/assets/45190043/5eaaa3e8-2749-4d23-bbb2-0f5bc9e39461)
右上角小人无法点击，这个日志是docker版本3.3.1的docker日志

**Comment by yuzhi-jiang** [comment]
是的，所以我弄了Jackett，不过还是一样

**Comment by yuzhi-jiang** [comment]
索引器未来支持linyuan0213/nas-tools这种选择方式吗
![image](https://github.com/hsuyelin/nas-tools/assets/45190043/dce3f670-aec2-49ee-b262-7bb5610a03e3)

**Comment by iovejieba** [comment]
> 索引器未来支持linyuan0213/nas-tools这种选择方式吗 ![image](https://user-images.githubusercontent.com/45190043/265193699-dce3f670-aec2-49ee-b262-7bb5610a03e3.png)

应该不会了

**Comment by iovejieba** [comment]
330 prowlarr 刚测过 正常搜索正常返回数据
jk没装 理论应该没问题

**Comment by iovejieba** [comment]
> 索引器未来支持linyuan0213/nas-tools这种选择方式吗 ![image](https://user-images.githubusercontent.com/45190043/265193699-dce3f670-aec2-49ee-b262-7bb5610a03e3.png)

你喜欢这种模式你pm作者找老版本 回滚  我记得3.2.9好像未集成插件模式 就是框架集成外部索引

**Comment by yuzhi-jiang** [comment]
linyuan0213作者是3.2开始集成，也有插件模式，不过就是索引也还支持老版本，不过后面没更新

**Comment by yuzhi-jiang** [comment]
看文档，这个是支持通过jk来拓展内部索引的吧，这个拓展是不是支持公开站的

**Comment by iovejieba** [comment]
> linyuan0213作者是3.2开始集成，也有插件模式，不过就是索引也还支持老版本，不过后面没更新

咱们这边项目3.2.9之前的版本都是框架外部索引 好像是具体版本我忘了一般尝试回滚3.2.9版本看一下    3.2.10之后是插件的集成化

**Comment by iovejieba** [comment]
> linyuan0213作者是3.2开始集成，也有插件模式，不过就是索引也还支持老版本，不过后面没更新

现在的sites索引规则就是 老版本的兼容模式  上段对应 下段 confg

**Comment by yuzhi-jiang** [comment]
咱们的项目是3.3.0开始是吧，回滚指的是官方3.2.9？

**Comment by iovejieba** [comment]
> 咱们的项目是3.3.0开始是吧，回滚指的是官方3.2.9？

3.2.x开始 只是你来晚了  你来的时候可能只看见了 3.3

**Comment by jackloves111** [comment]
这个我跟这版的作者讨论过了，我觉得放到索引器位置更好，但是并没有采取我的意见。按照你的描述。不i是版本问题，是你的插件设置的不对，之前的版本作者已经删掉了。重构了

**Comment by yuzhi-jiang** [comment]
> > 咱们的项目是3.3.0开始是吧，回滚指的是官方3.2.9？
> 
> 3.2.x开始 只是你来晚了 你来的时候可能只看见了 3.3

哦哦，最近半年都比较少关注nastool，用着养老版本，在交流群看到所以看看新版本

**Comment by iovejieba** [comment]
> > > 咱们的项目是3.3.0开始是吧，回滚指的是官方3.2.9？
> > 
> > 
> > 3.2.x开始 只是你来晚了 你来的时候可能只看见了 3.3
> 
> 哦哦，最近半年都比较少关注nastool，用着养老版本，在交流群看到所以看看新版本

找个pt养老吧....公开站哪怕用插件也没几个...除了那两三个动漫之外... 也就9kg有几个索引公开站

**Comment by yuzhi-jiang** [comment]
> 这个我跟这版的作者讨论过了，我觉得放到索引器位置更好，但是并没有采取我的意见。按照你的描述。不i是版本问题，是你的插件设置的不对，之前的版本作者已经删掉了。重构了

插件设置不对指的是？

**Comment by yuzhi-jiang** [comment]
> > > > 咱们的项目是3.3.0开始是吧，回滚指的是官方3.2.9？
> > > 
> > > 
> > > 3.2.x开始 只是你来晚了 你来的时候可能只看见了 3.3
> > 
> > 
> > 哦哦，最近半年都比较少关注nastool，用着养老版本，在交流群看到所以看看新版本
> 
> 找个pt养老吧....公开站哪怕用插件也没几个...除了那两三个动漫之外... 也就9kg有几个索引公开站

哈哈，是想找养老pt的不过比较烂维护，所以拿药都难

**Comment by jackloves111** [comment]
> > 这个我跟这版的作者讨论过了，我觉得放到索引器位置更好，但是并没有采取我的意见。按照你的描述。不i是版本问题，是你的插件设置的不对，之前的版本作者已经删掉了。重构了
> 
> 插件设置不对指的是？

让你截图，你一直在这文字描述，只能给你算一卦

**Comment by yuzhi-jiang** [comment]
> > > 这个我跟这版的作者讨论过了，我觉得放到索引器位置更好，但是并没有采取我的意见。按照你的描述。不i是版本问题，是你的插件设置的不对，之前的版本作者已经删掉了。重构了
> > 
> > 
> > 插件设置不对指的是？
> 
> 让你截图，你一直在这文字描述，只能给你算一卦
![image](https://github.com/hsuyelin/nas-tools/assets/45190043/654a6bdf-bddd-4041-849d-524d6a74a93b)

插件设置不应该不对吧，总共就几个，测试过通的jk也是一直用着的

**Comment by jackloves111** [comment]
随便你吧，用不了的又不是我，大家都是为爱发电没有义务教你，告诉你了要怎么反馈，你也是啥也不懂，建议你用你之前的版本

**Comment by yuzhi-jiang** [comment]
理解，无所谓的，感谢回复

**Comment by iovejieba** [comment]
> 理解，无所谓的，感谢回复

jackett v0.21.724     nastools 330  外部索引 实测无问题，jk设置如果有密码 尝试把密码去掉  http://不要用127.0.0.1  用内网ip   
http://192.168.1.1:9117

**Comment by yuzhi-jiang** [comment]
好的，感谢，我重新跑了一个，使用jk扩展内建索引后（内建索引可以看到扩展的站点），搜索资源可以用了，之前应该是没拓展成（允许插件扩展的时候卡了直接关闭选项卡）应该是这个原因

**Comment by yuzhi-jiang** [comment]
不过右上角小人还是点击无反应，f12看控制台没报错
版本：docker 3.3.1

**Comment by yuzhi-jiang** [comment]
索引器插件运行或者选择站点确定按钮时，会整个页面无法点击
![image](https://github.com/hsuyelin/nas-tools/assets/45190043/3bcfe182-1a5c-406a-9e74-a5700a8530df)

![image](https://github.com/hsuyelin/nas-tools/assets/45190043/7b0f1e42-f316-49fb-bce2-24bfe57ed2a4)

**Comment by hsuyelin** [comment]
这个是我的版本么，你是不是修改了索引啊。建议重新安装后试试

**Comment by jackloves111** [comment]
> 这个是我的版本么，你是不是修改了索引啊。建议重新安装后试试

现在的版本应该已经没有站点显示了，他这个还有显示，神仙看了都摇头

**Comment by iovejieba** [comment]
> > 这个是我的版本么，你是不是修改了索引啊。建议重新安装后试试
> 
> 现在的版本应该已经没有站点显示了，他这个还有显示，神仙看了都摇头
330 的容器镜像还是显示的....

**Comment by yuzhi-jiang** [comment]
没有修改索引啊，难道是缓存？还有个疑问就是，两个容器，config挂载的是不同的路径的，端口也不一样（比如一个3000一个3003）一个登录后另外一个刷新就要重新登陆，浏览器是谷歌，那个右上角个人中心点击问题换edge浏览器没问题

**Comment by hsuyelin** [comment]
重建容器吧，容器环境被你玩坏了，感觉你有可能看到什么修复就用命令执行或者替换或者覆盖镜像这种操作
