### ISSUE TITLE
能否修复下朱雀刷流

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#168]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.2

### 问题类型

其他问题

### 问题描述

朱雀刷流选择免费无法下载刷流种子.rss里面有免费的种子

**Comment by hsuyelin** [comment]
发一个朱雀的种子列表网页源代码上来，最好是有Free，2xFree的，方便我尝试适配

在网页端输入：view-source:https://zhuque.in/torrent/search 可能是这个，具体以种子列表为准，只是将后面的网址改为真实网址，然后保存所有的文本文件

**Comment by hh0610** [comment]
> 发一个朱雀的种子列表网页源代码上来，最好是有Free，2xFree的，方便我尝试适配
> 
> 在网页端输入：view-source:https://zhuque.in/torrent/search 可能是这个，具体以种子列表为准，只是将后面的网址改为真实网址，然后保存所有的文本文件
Microsoft Edge浏览器只有另存为.没有保存所有文件选项

**Comment by hh0610** [comment]
> 发一个朱雀的种子列表网页源代码上来，最好是有Free，2xFree的，方便我尝试适配
> 
> 在网页端输入：view-source:https://zhuque.in/torrent/search 可能是这个，具体以种子列表为准，只是将后面的网址改为真实网址，然后保存所有的文本文件

然后要怎么给你

**Comment by hh0610** [comment]
> 发一个朱雀的种子列表网页源代码上来，最好是有Free，2xFree的，方便我尝试适配
> 
> 在网页端输入：view-source:https://zhuque.in/torrent/search 可能是这个，具体以种子列表为准，只是将后面的网址改为真实网址，然后保存所有的文本文件

给个邮箱我从邮箱发给你

**Comment by hsuyelin** [comment]
> > 发一个朱雀的种子列表网页源代码上来，最好是有Free，2xFree的，方便我尝试适配
> > 在网页端输入：view-source:https://zhuque.in/torrent/search 可能是这个，具体以种子列表为准，只是将后面的网址改为真实网址，然后保存所有的文本文件
> 
> 给个邮箱我从邮箱发给你

hsuyelin@163.com

**Comment by hh0610** [comment]
> hsuyelin@163.com

已发

**Comment by hsuyelin** [comment]
> > [hsuyelin@163.com](mailto:hsuyelin@163.com)
> 
> 已发

不是ctrl+s保存，是复制里面的内容

**Comment by hh0610** [comment]
> > > [hsuyelin@163.com](mailto:hsuyelin@163.com)
> > 
> > 
> > 已发
> 
> 不是ctrl+s保存，是复制里面的内容
能说下怎么操作吗

**Comment by hsuyelin** [comment]
> > > > [hsuyelin@163.com](mailto:hsuyelin@163.com)
> > > 
> > > 
> > > 已发
> > 
> > 
> > 不是ctrl+s保存，是复制里面的内容
> > 能说下怎么操作吗

直接复制啊，复制文字内容保存到文本文件

**Comment by hh0610** [comment]
> > > > > [hsuyelin@163.com](mailto:hsuyelin@163.com)
> > > > 
> > > > 
> > > > 已发
> > > 
> > > 
> > > 不是ctrl+s保存，是复制里面的内容
> > > 能说下怎么操作吗
> 
> 直接复制啊，复制文字内容保存到文本文件

从新发了你看下对吗

**Comment by hsuyelin** [comment]
<img width="625" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/5c830a83-ae9e-4574-a741-ae80313726b5">
<img width="1156" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/6f83af6a-d5c8-455c-beb7-fd2d7df091fc">
这是憨憨的例子，再不会，只能歇逼了

**Comment by hh0610** [comment]
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/17918063/265215299-5c830a83-ae9e-4574-a741-ae80313726b5.png"> <img alt="image" width="1156" src="https://user-images.githubusercontent.com/17918063/265215321-6f83af6a-d5c8-455c-beb7-fd2d7df091fc.png"> 这是憨憨的例子，再不会，只能歇逼了


https://github.com/hsuyelin/nas-tools/assets/142991330/c5b41c97-58c3-42b1-b9ea-7a8fdcc0cacf

**Comment by hh0610** [comment]
> > > > > > [hsuyelin@163.com](mailto:hsuyelin@163.com)
> > > > > 
> > > > > 
> > > > > 已发
> > > > 
> > > > 
> > > > 不是ctrl+s保存，是复制里面的内容
> > > > 能说下怎么操作吗
> > 
> > 
> > 直接复制啊，复制文字内容保存到文本文件
> 
> 从新发了你看下对吗

就是这样点的进去就是我发给你的那样

**Comment by hsuyelin** [comment]
歇逼了，这种查看源代码的方式被朱雀禁了，有其他的方式但是需要动手能力，等有朱雀站的同学PR吧

**Comment by iovejieba** [comment]
朱雀现在的结构貌似是java脚本的那种  没有html硬编码 巨ex
