### ISSUE TITLE
能否搞个9KG的二级分类，方便下载管理和硬链接媒体库

### ISSUE THREAD

**Issue by 892899273** [hsuyelin/nas-tools#17]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by hsuyelin** [comment]
展开说说，或者截图说明下，不明白啥意思

**Comment by iovejieba** [comment]
> 展开说说，或者截图说明下，不明白啥意思

我估计它意思是现有媒体目录增加多分类，现在不是电影/外语，国语之类的么   
意思是能增加9kg分类，9kg/步兵，骑兵   巴拉巴拉
我估计是

**Comment by iovejieba** [comment]
但我感觉那就得调用三方刮削了  靠tmdb 然并卵

**Comment by iovejieba** [comment]
如果可以增加并且工程量不大的话，可以考虑用一个选项来关闭或启用  避免不必要的麻烦

**Comment by iovejieba** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: vx.x.x
> > 环境: docker or windows or synology
> 
> ## 你想要新增或者改进什么功能？
> > 你想要新增或者改进什么功能？
> 
> ## 这个功能有什么可以参考的资料吗？
> > 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

其实..有笨方法...目录同步  qb设置各种目录，下载器添加各种qb目录，同步目录添加各个同步目录，就是稍微麻烦点 但体验度没啥问题

**Comment by hsuyelin** [comment]
> > 展开说说，或者截图说明下，不明白啥意思
> 
> 我估计它意思是现有媒体目录增加多分类，现在不是电影/外语，国语之类的么 意思是能增加9kg分类，9kg/步兵，骑兵 巴拉巴拉 我估计是

明白了，非常感谢答疑 @iovejieba   ，这种不通用的暂且不考虑新增 @892899273

**Comment by iovejieba** [comment]
> > > 展开说说，或者截图说明下，不明白啥意思
> > 
> > 
> > 我估计它意思是现有媒体目录增加多分类，现在不是电影/外语，国语之类的么 意思是能增加9kg分类，9kg/步兵，骑兵 巴拉巴拉 我估计是
> 
> 明白了，非常感谢答疑 @iovejieba ，这种不通用的暂且不考虑新增 @892899273

这个其实....如果有扩展插件的话 是个好选择毕竟....nas人均 9kg比例高的可怕...
