### ISSUE TITLE
下载器问题

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#171]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.2

### 问题类型

主程序运行问题

### 问题描述

nastool访问目录设置好了在点进去就会显示加载路径失败
![1693704919446(1)](https://github.com/hsuyelin/nas-tools/assets/142991330/f8421260-6b33-4c66-b679-bdc6d2b1c4cb)

**Comment by waylonwang** [comment]
这个有可能是升级jQueryFileTree版本导致的，应该是中文的兼容性问题，我看看代码，你原始的路径是什么？包含中文的路径我这里也没有重现

**Comment by hh0610** [comment]
> 应该是中文的兼容性问题，我看看代码，你原始的路径是什么？包含中文的路径我这
![1693705971793(1)](https://github.com/hsuyelin/nas-tools/assets/142991330/8a9d1005-aa34-4060-a8a4-8ecbf6cc49d1)

**Comment by waylonwang** [comment]
另外，昨天我在测试文件浏览器时发现原版nastool在下载中配置路径时，弹出的文件浏览器位置不正确，怀疑与目录设置区域可折叠有关，暂时没有时间去检查具体的原因

**Comment by hh0610** [comment]
> 另外，昨天我在测试文件浏览器时发现原版nastool在下载中配置路径时，弹出的文件浏览器位置不正确，怀疑与目录设置区域可折叠有关，暂时没有时间去检查具体的原因

我在群晖的原始路径都是中文

**Comment by waylonwang** [comment]
无语，jQueryFileTree在showTree中用decodeURIComponent解码，却在调用showTree时用escape编码，估计是unescape改decodeURIComponent后，escape忘改encodeURIComponent了，jQueryFileTree早就已经停更了，只能改安装包中的jQueryFileTree.min.js来修复
<img width="576" alt="截屏2023-09-03 上午10 27 59" src="https://github.com/hsuyelin/nas-tools/assets/7424276/79a192ec-0139-407c-8a3f-433ea1feab46">
<img width="519" alt="截屏2023-09-03 上午10 27 50" src="https://github.com/hsuyelin/nas-tools/assets/7424276/675a1f9b-b7d8-498e-872a-a9834bd6ce87">

**Comment by hsuyelin** [comment]
已解决
