### ISSUE TITLE
[错误报告]: 天雪和tccf添加后无法使用

### ISSUE THREAD

**Issue by LoSiTeE** [hsuyelin/nas-tools#174]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.2

### 问题类型

其他问题

### 问题描述

天雪和tccf添加后，站点资源，内建索引器都不显示这两个站，搜索资源时两个站也不在索引范围内。

**Comment by hsuyelin** [comment]
天雪和tccf域名是什么，因为看下索引

**Comment by LoSiTeE** [comment]
> 天雪和tccf域名是什么，因为看下索引

天雪
https://skyeysnow.com/
他吹吹风
https://et8.org

**Comment by hsuyelin** [comment]
@LoSiTeE 我看看哈

**Comment by hsuyelin** [comment]
@LoSiTeE 

https://www.skyey2.com/ 这个不是天雪么

**Comment by hsuyelin** [comment]
已修复：https://github.com/hsuyelin/nas-tools/commit/a3f95c7e531fac9ef82e79f745d4cd8a7e22e2ec

**Comment by LoSiTeE** [comment]
> 已修复：[a3f95c7](https://github.com/hsuyelin/nas-tools/commit/a3f95c7e531fac9ef82e79f745d4cd8a7e22e2ec)

天雪好像是有俩域名。

功能正常了，感谢
