### ISSUE TITLE
[错误报告]: docker部署之后因为缺少配置文件无法启动

### ISSUE THREAD

**Issue by yunzhongci** [hsuyelin/nas-tools#176]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.2

### 问题类型

Docker或运行环境问题

### 问题描述

docker部署之后，因为缺少初始版的config.yaml，导致循环报错。
看到报错之后，将以前的配置文件复制过去才能正常启动。
我建议部署成功之后，自带一份初始的配置文件，用户在之后视各自情况重新配置或者替换

**Comment by hsuyelin** [comment]
日志给我看下，还有就是你这个是不是不是通过docker镜像升级的方式，而是通过在线升级方式呢

**Comment by ji1360677347** [comment]
我也是这个错误，把之前的config清空首次装，pull的镜像

**Comment by ji1360677347** [comment]
> 日志给我看下，还有就是你这个是不是不是通过docker镜像升级的方式，而是通过在线升级方式呢

![image](https://github.com/hsuyelin/nas-tools/assets/52523955/8c16ba9e-77a8-470c-8644-0fff07df1b30)

**Comment by hsuyelin** [comment]
@yunzhongci config文件夹没有创建吧，我用的docker-compose全新安装没有你这个问题啊，不管是docker-compose还是GUI界面创建容器，都需要映射config文件夹，建议自己看看教程把

**Comment by ji1360677347** [comment]
有文件夹的，还给了everyone权限

**Comment by ji1360677347** [comment]
刚才又试了docker-compose的安装方式，也是一样的结果，我看也有很多人说升级后启动不了了

**Comment by yunzhongci** [comment]
> @yunzhongciconfig文件夹没有创建吧，我用的docker-compose全新安装没有你这个问题啊，不管是docker-compose还是GUI界面创建容器，都需要mapconfig文件夹，建议自己看教程把

创建了config文件夹，权限也没问题，并且已经拉取了两个文件：user.db、media.db。
报错如楼上的日志，config里面只有这两个文件，我从其他地方复制旧的配置文件过去，才能继续拉取并且完成
