### ISSUE TITLE
[功能改进]: 希望优化一下瓷器站搜索

### ISSUE THREAD

**Issue by fzlzl** [hsuyelin/nas-tools#178]
### 当前程序版本

3.3.2

### 功能改进

在搜索瓷器站点时有些资源搜索不到，但官方版本却可以搜索到，对比了一下发现请求链接有一些不一样，比如搜索：巨齿鲨2
官方版本的请求链接为：
https://hdchina.org/torrents.php?search_mode=0&page=0&notnewword=1&search=Meg+2+The+Trench&cat20=1&cat17=1&cat16=1&cat9=1&cat27=1&cat410=1
返回结果有6个
此版本的请求链接为：
https://hdchina.org/torrents.php?search_mode=0&page=0&notnewword=1&search=Meg+2+The+Trench&cat20=1&cat17=1&cat16=1&cat9=1&cat27=1
返回结果只有2个
搜索：消失的她
官方版本的请求链接返回的结果有2个
此版本的请求链接返回的结果为0个

**Comment by hsuyelin** [comment]
看下搜索完的结果截图下看看

**Comment by fzlzl** [comment]
原版

![image](https://github.com/hsuyelin/nas-tools/assets/70704288/fc40c592-6147-4f86-bbb8-1bfb2ea77dca)

此版

![image](https://github.com/hsuyelin/nas-tools/assets/70704288/5f32d5d8-ee62-42c6-add6-9aa0409d23cd)


加上cat410=1则搜索全部，不加则只在勾选的类型里搜索

![image](https://github.com/hsuyelin/nas-tools/assets/70704288/67614f28-1758-4731-9f3c-056f86dc173b)

**Comment by hsuyelin** [comment]
你会手动更新么。会的话更新下，我加了410的识别 @fzlzl

**Comment by fzlzl** [comment]
不会更新 (流下了菜鸡的眼泪 呜呜）

**Comment by hsuyelin** [comment]
> 不会更新 (流下了菜鸡的眼泪 呜呜）

等版本打好后拉取更新下

**Comment by hsuyelin** [comment]
@fzlzl 打包好了

**Comment by fzlzl** [comment]
网站搜索得到6个结果，控制台返回数据也是6，现在一样了
![image](https://github.com/hsuyelin/nas-tools/assets/70704288/aeaac0b4-d4f3-4667-8d8e-30775a89b080)

**Comment by hsuyelin** [comment]
> 网站搜索得到6个结果，控制台返回数据也是6，现在一样了 ![image](https://user-images.githubusercontent.com/70704288/265263527-aeaac0b4-d4f3-4667-8d8e-30775a89b080.png)

OK
