### ISSUE TITLE
[错误报告]: config文件没了

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#179]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.3

### 问题类型

主程序运行问题

**Comment by hsuyelin** [comment]
你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的

**Comment by youyifentian** [comment]
> 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的

不是呀，我拉的镜像，也报config.yaml文件丢失，我等下给你截个图

**Comment by youyifentian** [comment]
> 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的

![QQ截图20230903203024](https://github.com/hsuyelin/nas-tools/assets/5012570/53896ffd-1502-4a84-ba37-04146a73296c)

**Comment by hsuyelin** [comment]
> > 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的
> 
> 不是呀，我拉的镜像，也报config.yaml文件丢失，我等下给你截个图

@DDSDerek 哥，帮忙check下，看看是不是重构的时候没打进去，我这边确认下主程序上的问题

**Comment by hsuyelin** [comment]
> > 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的
> 
> ![QQ截图20230903203024](https://user-images.githubusercontent.com/5012570/265264282-53896ffd-1502-4a84-ba37-04146a73296c.jpg)
> 
> ## 这是第一次全新创建的时候的报错

收到，你可以自己手动恢复下配置文件到config目录来解决，解决需要等我们check下

**Comment by DDSDerek** [comment]
> > > 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的
> > 
> > 
> > 不是呀，我拉的镜像，也报config.yaml文件丢失，我等下给你截个图
> 
> @DDSDerek 哥，帮忙check下，看看是不是重构的时候没打进去，我这边确认下主程序上的问题

https://github.com/hsuyelin/nas-tools/commit/e232d78ba13b6c1b78dfede81fd9f474b004069e 这个提交的问题，没提交上来还是删了，不是我操作的，是 @waylonwang

**Comment by youyifentian** [comment]
> > > 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的
> > 
> > 
> > ![QQ截图20230903203024](https://user-images.githubusercontent.com/5012570/265264282-53896ffd-1502-4a84-ba37-04146a73296c.jpg)
> > ## 这是第一次全新创建的时候的报错
> 
> 收到
> 
> 1. 你可以自己手动恢复下配置文件到config目录来解决
> 2. 完全修复需要等我们check下，你也确认下你的config是不是手动修改了或者删除了导致文件丢失



> > > 你是直接拉取代码的吧，升级镜像重新创建容器，容器打包方式重构了，更新日志有说明的
> > 
> > 
> > ![QQ截图20230903203024](https://user-images.githubusercontent.com/5012570/265264282-53896ffd-1502-4a84-ba37-04146a73296c.jpg)
> > ## 这是第一次全新创建的时候的报错
> 
> 收到
> 
> 1. 你可以自己手动恢复下配置文件到config目录来解决
> 2. 完全修复需要等我们check下，你也确认下你的config是不是手动修改了或者删除了导致文件丢失

问题我会解决，我也确实是全新安装的，就是全全全新安装的那种

**Comment by hsuyelin** [comment]
done: https://github.com/hsuyelin/nas-tools/pull/183/files

**Comment by DDSDerek** [comment]
@hsuyelin config文件还是没有上传，你上传一下

**Comment by DDSDerek** [comment]
这个 https://github.com/hsuyelin/nas-tools/commit/e232d78ba13b6c1b78dfede81fd9f474b004069e commit删了

**Comment by hsuyelin** [comment]
> 

OK

**Comment by hsuyelin** [comment]
cf10e5059896a34deeba488f176ea4d6e3b7c8ae 已上传
