### ISSUE TITLE
windows版启动报错

### ISSUE THREAD

**Issue by leiurayer** [hsuyelin/nas-tools#18]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.9
>
> 环境: windows 10
>

## 你遇到什么问题了？

> 启动后报错，查了下是selenium的问题

## 你期望的结果

> 修复报错

## 给出程序界面截图、后台运行日志或配置文件

![image](https://github.com/hsuyelin/nas-tools/assets/19290097/2bd81bbc-b908-402e-9d78-1b4db66dd738)

**Comment by iovejieba** [comment]
WebDriver 版本号115.X  好像pis上没有....但我不知道具体哪个位置能控制版本号  估计只要降低版本号就行了

**Comment by hsuyelin** [comment]
> 理论上降到[114.0.5735.90](http://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/) 就行 googleapis那边没有115.X的驱动貌似

@leiurayer 试试这个降级的方法，方便的时候反馈下

**Comment by hsuyelin** [comment]
> WebDriver 版本号115.X 好像pis上没有....但我不知道具体哪个位置能控制版本号 估计只要降低版本号就行了

![u=1691837534,3573093759 fm=253 app=138 size=b931,250 q=75 n=0 f=GIF fmt=auto maxorilen2heic=2000000](https://github.com/hsuyelin/nas-tools/assets/17918063/bb011b68-86df-46d9-b93c-12c581af97c5)

多谢大佬

**Comment by hsuyelin** [comment]
> > 理论上降到[114.0.5735.90](http://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/) 就行 googleapis那边没有115.X的驱动貌似
> 
> @leiurayer 试试这个降级的方法，方便的时候反馈下 但我不知道具体哪个py 是控制版本号的.....

我知道，明天看下吧，默认拉的最新版，理论上不会没有这个版本的

**Comment by iovejieba** [comment]
> > > 理论上降到[114.0.5735.90](http://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/) 就行 googleapis那边没有115.X的驱动貌似
> > 
> > 
> > @leiurayer 试试这个降级的方法，方便的时候反馈下 但我不知道具体哪个py 是控制版本号的.....
> 
> 我知道，明天看下吧，默认拉的最新版，理论上不会没有这个版本的

[我感觉也诡异....官网没有115.X的驱动！

**Comment by hsuyelin** [comment]
> > > > 理论上降到[114.0.5735.90](http://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/) 就行 googleapis那边没有115.X的驱动貌似
> > > 
> > > 
> > > @leiurayer 试试这个降级的方法，方便的时候反馈下 但我不知道具体哪个py 是控制版本号的.....
> > 
> > 
> > 我知道，明天看下吧，默认拉的最新版，理论上不会没有这个版本的
> 
> [我感觉也诡异....官网没有115.X的驱动！

我看了，确实没有，不会打包的时候有，然后后来下架了叭，因为默认拉的最新版本，不行的话我就固定下版本，明天重新打个版本试试

**Comment by iovejieba** [comment]
> > > > > 理论上降到[114.0.5735.90](http://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/) 就行 googleapis那边没有115.X的驱动貌似
> > > > 
> > > > 
> > > > @leiurayer 试试这个降级的方法，方便的时候反馈下 但我不知道具体哪个py 是控制版本号的.....
> > > 
> > > 
> > > 我知道，明天看下吧，默认拉的最新版，理论上不会没有这个版本的
> > 
> > 
> > [我感觉也诡异....官网没有115.X的驱动！
> 
> 我看了，确实没有，不会打包的时候有，然后后来下架了叭，因为默认拉的最新版本，不行的话我就固定下版本，明天重新打个版本试试

嗯 可能玄学行抽风 或者可能cdn节点？...

**Comment by hsuyelin** [comment]
@leiurayer @iovejieba 3.2.9.1 可用

**Comment by iovejieba** [comment]
> @leiurayer @iovejieba 3.2.9.1 可用
ok，辛苦！

**Comment by leiurayer** [comment]
还是存在问题，如果Chrome版本是115，依然有报错；Chrome版本114则可以正常运行。
这个问题就是Chrome自动更新后出现的

**Comment by hsuyelin** [comment]
抽时间看看
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月02日 14:11 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
State ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] windows版启动报错 (Issue #18) |

还是存在问题，如果Chrome版本是115，依然有报错；Chrome版本114则可以正常运行。
这个问题就是Chrome自动更新后出现的

**Comment by hsuyelin** [comment]
> 还是存在问题，如果Chrome版本是115，依然有报错；Chrome版本114则可以正常运行。 这个问题就是Chrome自动更新后出现的

@leiurayer 试试3.2.9.4，如果下载不到chrome对应的版本，默认下载最新版本安装
