### ISSUE TITLE
[错误报告]: windows 版本启动报错

### ISSUE THREAD

**Issue by XINGYUZHMM** [hsuyelin/nas-tools#180]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.2 3.3.3

### 问题类型

主程序运行问题

### 问题描述

![img0-9a1fe7e6-2a59-4c01-9369-31b875f759a1](https://github.com/hsuyelin/nas-tools/assets/112518475/93124047-d0a5-49a0-ace1-6045fffd1a96)
3.3.2，3.3.3版本报错无法启动
3.3.1正常

**Comment by hsuyelin** [comment]
@DDSDerek 哥，帮忙看看是否和 这个提交 72923f928a93da289922f7a4a25da3ff3a660f43 有关系

**Comment by hsuyelin** [comment]
@XINGYUZHMM 我重新打个包，你在看下哈，等我通知

**Comment by DDSDerek** [comment]
我这边可以100％确认docker文件夹下任何修改都不会影响二进制文件的构建

**Comment by DDSDerek** [comment]
@hsuyelin 我怀疑是增加了guessit库的原因，这个库是不是要关联什么iso？要手动调试一下pyinstaller

**Comment by DDSDerek** [comment]
@hsuyelin  https://stackoverflow.com/questions/51017068/pyinstaller-failed-to-execute-script 看这篇文章，我觉得遇到问题没必要revert的，直接Google搜索解决最简单了，revert还会增加工作量

**Comment by hsuyelin** [comment]
@DDSDerek 就是确认下是否和环境配置有关系，如果没关系会revert回来，不过确实会增加工作量，感谢指点

**Comment by hsuyelin** [comment]
> > @XINGYUZHMM 我重新打个包，你在看下哈，等我通知
> 
> 刚打包的3.3.3.1试了，一样报错

稍等，在处理

**Comment by DDSDerek** [comment]
@hsuyelin 我这边尝试了一番还是没有解决，因为明天要上学先睡觉了，你再看看吧

**Comment by hsuyelin** [comment]
我这边也在尝试，正在尝试使用hiddenimports来直接显示导入模块解决，如果可以的和你说下

**Comment by DDSDerek** [comment]
@hsuyelin https://github.com/guessit-io/guessit/blob/develop/guessit.spec 或许这个有参考价值，这是guessit官方的打包文件

**Comment by hsuyelin** [comment]
> @hsuyelin https://github.com/guessit-io/guessit/blob/develop/guessit.spec 或许这个有参考价值，这是guessit官方的打包文件

我参照了，没有用，会报 ModuleNotFoundError: No module named 'babelfish.converters.alpha2' ，显示加入hiddenimports也不生效，我看了babelfish应该还需要把 babelfish 下的文件加到datas

**Comment by hsuyelin** [comment]
@DDSDerek 总体来说还是那个，只是我没把guessit添加进去，需要两个都加进去才可以
```python
1. datas添加
(babelfish.__path__[0] + '/data', 'babelfish/data'),
(guessit.__path__[0] + '/config', 'guessit/config'),
(guessit.__path__[0] + '/data', 'guessit/data')

2. hiddenimports添加
 'babelfish.converters.alpha2',
 'babelfish.converters.alpha3b',
 'babelfish.converters.alpha3t',
 'babelfish.converters.name',
 'babelfish.converters.opensubtitles',
 'babelfish.converters.countryname',
```
