### ISSUE TITLE
[错误报告]: V3.3.3 熊猫、Rousi 站点还是搜索不出东西。 碟粉、红豆饭 搜索结果还是没显示副标题

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#181]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V 3.3.3

### 问题类型

Docker或运行环境问题

### 问题描述

V3.3.3 熊猫、Rousi 站点还是搜索不出东西。
碟粉、红豆饭 搜索结果还是没显示副标题

**Comment by hsuyelin** [comment]
没站点没办法测试，都是尝试性修复，回头问问看谁有没有这些站点

**Comment by zjjxwhh** [comment]
我这里 HDFans 的副标题正常，但是 PTT 带免费标签的资源副标题不正常

![image](https://github.com/hsuyelin/nas-tools/assets/14367334/126efebf-da4e-4d81-8710-31a15efc958d)

![image](https://github.com/hsuyelin/nas-tools/assets/14367334/04871f2b-defb-444a-b4a6-8eb013710c00)

**Comment by ZhanPhty** [comment]
主要是类别id没对上，下面是我自用的，熊猫和肉丝的，大佬什么时候替换下就行。。啥时候能有读取本地站点文件的功能就好了。。
https://github.com/ZhanPhty/nastool-site

**Comment by qsxazcv** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/113089025/995227e6-6af2-4ea9-a032-f622a677e4bf)
![image](https://github.com/hsuyelin/nas-tools/assets/113089025/1426c520-9c5c-401e-89f9-b9657613531e)
我用的目前是[v3.3.5 9ce8007]版本，为什么有一些资源搜索不全？还有一些就是站点有，但是搜索不出来站点。是不是每个站的命名规则不一样？

**Comment by hsuyelin** [comment]
> 主要是类别id没对上，下面是我自用的，熊猫和肉丝的，大佬什么时候替换下就行。。啥时候能有读取本地站点文件的功能就好了。。 https://github.com/ZhanPhty/nastool-site

@jackloves111 肉丝我有的，我应该上个版本修复了，不过都统一用了他这个
@ZhanPhty 不开放使用本地文件的功能是因为不是所有人都会配置，一旦有人搞错，就会出一堆问题，会的直接pr到 https://github.com/hsuyelin/nas-tools-sites 即可，我基本的都能在一天内更新好
