### ISSUE TITLE
[错误报告]: 增强识别V2搜索问题

### ISSUE THREAD

**Issue by k851026** [hsuyelin/nas-tools#187]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.3.3.2 0f541bf

### 问题类型

其他问题

### 问题描述

启动增强识别V2搜索的时候能搜到蜘蛛侠：纵横宇宙，却不能搜到闪电侠。不启动能搜到闪电侠却搜不到蜘蛛侠：纵横宇宙。这2个电影在PT论坛都有收录。

**Comment by hsuyelin** [comment]
闪电侠是不是中英文混合的。盲猜命名是   闪电侠.The Flash.2022.XX.XXX.XXX.XX.mkv

**Comment by yellowstrong** [comment]
同测试，搜索结果少了一部分
原始搜索
![iShot_2023-09-04_09 38 02](https://github.com/hsuyelin/nas-tools/assets/34505611/ab67d6ca-ec55-4611-a351-855ae55bdfde)
增强搜索
![iShot_2023-09-04_09 39 56](https://github.com/hsuyelin/nas-tools/assets/34505611/722873b5-7b64-43c5-a4e9-3cf4c125a885)
增强搜索日志
![iShot_2023-09-04_09 39 31](https://github.com/hsuyelin/nas-tools/assets/34505611/0079f105-bf35-47a7-8e79-f3e26c7593f9)

**Comment by hsuyelin** [comment]
可以的 @k851026  @yellowstrong 方便的话帮忙把少的集数找出来，我看看命名方式是什么样的，我自己自测是中英文混合且TMDB不是中英文混合的名称会匹配不到，比如说异人之下或者I AM NOBODY单独都可以匹配，如果是异人之下.I AM NOBODY就会有可能匹配不到，我在修正

**Comment by hsuyelin** [comment]
@yellowstrong 而且你注意看原始搜索其实是有问题的，The OutCast是动漫一人之下把，增强搜索会过滤掉，只会匹配你输入的关键词及关键词相关的

**Comment by jackloves111** [comment]
> @yellowstrong 而且你注意看原始搜索其实是有问题的，The OutCast是动漫一人之下把，增强搜索会过滤掉，只会匹配你输入的关键词及关键词相关的，增强搜索是正确的，你仔细看看

The OutCast是动漫没错，但是也有很多站点用The OutCast作为剧版的名称。比如 某众

**Comment by hsuyelin** [comment]
> > @yellowstrong 而且你注意看原始搜索其实是有问题的，The OutCast是动漫一人之下把，增强搜索会过滤掉，只会匹配你输入的关键词及关键词相关的，增强搜索是正确的，你仔细看看
> 
> The OutCast是动漫没错，但是也有很多站点用The OutCast作为剧版的名称。比如 某众
> 
> 关联#186

这个不是特别想兼容，我认为是站点问题，要写无意义的兼容代码，真要兼容也可以，但是以后搜索结果又变得模糊起来，又有一批人反馈说命名搜索异人之下出现了一人之下的结果，诸如此类

**Comment by jackloves111** [comment]
> > > @yellowstrong 而且你注意看原始搜索其实是有问题的，The OutCast是动漫一人之下把，增强搜索会过滤掉，只会匹配你输入的关键词及关键词相关的，增强搜索是正确的，你仔细看看
> > 
> > 
> > The OutCast是动漫没错，但是也有很多站点用The OutCast作为剧版的名称。比如 某众
> > 关联#186
> 
> 这个不是特别想兼容，我认为是站点问题，要写无意义的兼容代码，真要兼容也可以，但是以后搜索结果又变得模糊起来，又有一批人反馈说明明搜索异人之下出现了一人之下的结果，诸如此类

明白，就目前测试的情况来说，增强后的结果要比原版的准确，再长期使用看看效果

**Comment by yellowstrong** [comment]
> @yellowstrong 而且你注意看原始搜索其实是有问题的，The OutCast是动漫一人之下把，增强搜索会过滤掉，只会匹配你输入的关键词及关键词相关的，增强搜索是正确的，你仔细看看

其实就英文命名而言，很多站点都不一样，目前我手头的站点这部剧，还是The OutCast居多

**Comment by k851026** [comment]
有没有可能就是 使用2个搜索，V2没有搜到就启动以前的。现在的情况就是 有些剧 以前的能搜到 V2不能。V2能以前的又不能

**Comment by hsuyelin** [comment]
> 有没有可能就是 使用2个搜索，V2没有搜到就启动以前的。现在的情况就是 有些剧 以前的能搜到 V2不能。V2能以前的又不能

那搜索耗时就上来了，我觉着这个本身是站点问题吧，站点的命名不说要规范吧，起码得正确吧，The OutCast是动漫一人之下被硬生生塞在剧版名称里也不对啊，@k851026 @yellowstrong

**Comment by jackloves111** [comment]
> 有没有可能就是 使用2个搜索，V2没有搜到就启动以前的。现在的情况就是 有些剧 以前的能搜到 V2不能。V2能以前的又不能

最好不要盯着一部片子进行讨论，能否提供多部片子的案例进行举例分析，这样比较容易对比判断原因在哪里。异人之下是既有剧集又有动漫，相对比较特殊的。有没有正常的剧集可以举例的

**Comment by yellowstrong** [comment]
还有一个问题，我用V2搜索可见性的比之前搜出来的资源少了很多
V2
![iShot_2023-09-04_12 40 36](https://github.com/hsuyelin/nas-tools/assets/34505611/e36f683f-abbf-4582-8d2c-9c5512286aac)
before
![iShot_2023-09-04_12 39 41](https://github.com/hsuyelin/nas-tools/assets/34505611/857d6ec8-095c-4b66-a9b1-10aebc7a3fa5)

**Comment by hsuyelin** [comment]
你看下里面的内容是不是都是速度与激情9.帮忙确认下

**Comment by k851026** [comment]
闪电的的标题
![image](https://github.com/hsuyelin/nas-tools/assets/33319756/f28a8fc2-ac0f-461f-aff7-6288f8d16f09)

**Comment by hsuyelin** [comment]
> 闪电的的标题 ![image](https://user-images.githubusercontent.com/33319756/265332959-f28a8fc2-ac0f-461f-aff7-6288f8d16f09.png)

OK

**Comment by hsuyelin** [comment]
> 还有一个问题，我用V2搜索可见性的比之前搜出来的资源少了很多 V2 ![iShot_2023-09-04_12 40 36](https://user-images.githubusercontent.com/34505611/265322182-e36f683f-abbf-4582-8d2c-9c5512286aac.png) before ![2023-09-04 12 44 01](https://user-images.githubusercontent.com/34505611/265322558-27e26e26-cc3a-4c6a-894a-84c408f5a2e8.png)

我知道怎么回事了，其他的标题用的是F9  The Fast Saga 会被匹配到速度与激情 9799，一开始是使用TMDB ID去匹配的是 速度与激情9 385128 ，这种标题我看看怎么优化

**Comment by yellowstrong** [comment]
> > 还有一个问题，我用V2搜索可见性的比之前搜出来的资源少了很多 V2 ![iShot_2023-09-04_12 40 36](https://user-images.githubusercontent.com/34505611/265322182-e36f683f-abbf-4582-8d2c-9c5512286aac.png) before ![2023-09-04 12 44 01](https://user-images.githubusercontent.com/34505611/265322558-27e26e26-cc3a-4c6a-894a-84c408f5a2e8.png)
> 
> 我知道怎么回事了，其他的标题用的是F9 The Fast Saga 会被匹配到速度与激情 9799，一开始是使用TMDB ID去匹配的是 速度与激情9 385128 ，这种标题我看看怎么优化

对的～

**Comment by hsuyelin** [comment]
@k851026 @yellowstrong 会拉代码的拉下试试，不会的等我更新后试试

**Comment by yellowstrong** [comment]
重新拉代码依旧有问题
![iShot_2023-09-05_15 19 52](https://github.com/hsuyelin/nas-tools/assets/34505611/05fcad15-c9d3-4b41-a7ca-489659684922)

**Comment by k851026** [comment]
@hsuyelin  不行还是搜不到，已经更新到最新的 [v3.3.3 29f50f3]
![image](https://github.com/hsuyelin/nas-tools/assets/33319756/812477c6-0545-4be4-aeb7-ec7c06ab046a)

**Comment by k851026** [comment]
@hsuyelin 不用V2
![image](https://github.com/hsuyelin/nas-tools/assets/33319756/cc8494cf-1b26-4d6c-b921-8c95ed4c8c11)

**Comment by jackloves111** [comment]
> @hsuyelin 不用V2 ![image](https://user-images.githubusercontent.com/33319756/265619936-cc8494cf-1b26-4d6c-b921-8c95ed4c8c11.png)

闪电侠这个确实，好多都没了，可能这种既有电视剧，又有电影的，比较难识别吧
