### ISSUE TITLE
[错误报告]: nastools把我的cup占满了

### ISSUE THREAD

**Issue by lwd333** [hsuyelin/nas-tools#188]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3  1431fa6

### 问题类型

插件问题

### 问题描述

nastools把我的cup占满了，查看后台是nastools中chrome占满了cpu，查看nastools日志，并没有任何程序运行。

**Comment by lwd333** [comment]
![4FDB4ECE-623E-4b5b-8388-EDB8F876918F](https://github.com/hsuyelin/nas-tools/assets/130337710/669a036d-cc1a-4b77-a0e4-83f1bc7e8601)

**Comment by hsuyelin** [comment]
这个是什么系统啊

**Comment by jackloves111** [comment]
目测是群晖套件？本版跟套件无关啊大兄弟

**Comment by hsuyelin** [comment]
@jackloves111 确认了是群辉套件，不是我的版本。我没提供过群辉套件版
