### ISSUE TITLE
[错误报告]: 下载器中删除刷流种子时，刷流任务不会同步删除对应种子

### ISSUE THREAD

**Issue by LoSiTeE** [hsuyelin/nas-tools#189]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3

### 问题类型

主程序运行问题

### 问题描述

如题，这样的话删除刷流种子之后，nastool的刷流任务不会跟着同步“刷流种子明细”。当刷流任务设置了保种体积时，刷流任务会一直显示保种体积已满，不再自动刷入新的种子。

仅观察到明教的刷流任务是这种情况，其他站点是否如此还没注意，不排除仅为明教的刷流是这种问题，我会持续观察一下，后面再来反馈。

补充：

观察到pthome的刷流任务也是如此。

另外发现日志中没有了同步刷流种子明细的相关内容，以前官方镜像运行时，日志中是有相关的同步信息的，是否是相关进程出现了问题

**Comment by LoSiTeE** [comment]
观察到pthome的刷流任务也是如此。
另外发现日志中没有了同步刷流种子明细的相关内容，以前官方的镜像是有对应信息的，是否是相关进程出现了问题

**Comment by yellowstrong** [comment]
本来就没有这个功能，你手动去qb删除了种子，除非你的刷流任务里设置了删种规则达到删种条件，不然就会一直占用，最好的做法就是在刷流的任务明细里增加一个删除刷流种子的操作，而不是去qb删除

**Comment by LoSiTeE** [comment]
> 本来就没有这个功能，你手动去qb删除了种子，除非你的刷流任务里设置了删种规则达到删种条件，不然就会一直占用，最好的做法就是在刷流的任务明细里增加一个删除刷流种子的操作，而不是去qb删除

我搭一个官方镜像对比一下

**Comment by LoSiTeE** [comment]
> 本来就没有这个功能，你手动去qb删除了种子，除非你的刷流任务里设置了删种规则达到删种条件，不然就会一直占用，最好的做法就是在刷流的任务明细里增加一个删除刷流种子的操作，而不是去qb删除

**以下是官方镜像3.2.3的截图**

![QQ图片20230904194301](https://github.com/hsuyelin/nas-tools/assets/125968595/260da9cb-e71d-41cd-b2bc-9dd7b45c7874)

**Comment by hsuyelin** [comment]
刷流目前未做任何更改，使用的官方3.2.3的全部功能
