### ISSUE TITLE
[错误报告]: 关于站点u2 刷流任务选种规则不生效/不下载的奇怪问题

### ISSUE THREAD

**Issue by madoka315** [hsuyelin/nas-tools#190]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3.2

### 问题类型

主程序运行问题

### 问题描述

前些天有幸进入u2遂想用nastool刷流。昨天使用3.3.3发现设置了选种规则为“做种人数小于10”时，自动下了很多已有几十人做种的种子。
推测为版本问题所以更新到主分支最新版本，左下角显示3.3.3.2。再次尝试设置“做种人数为全部”&“发种时间小于12小时”，启动刷流任务后没有任何任务被添加，此时查看站点资源列表和rss都发现显然有符合条件的种子。不知道是什么问题。
![image](https://github.com/hsuyelin/nas-tools/assets/72589546/f2d1a6d9-3c92-4a97-87b6-ef4cd0e12663)
![image](https://github.com/hsuyelin/nas-tools/assets/72589546/19f10a05-f67d-4b16-b6cc-245aae31ebed)
![image](https://github.com/hsuyelin/nas-tools/assets/72589546/5ffb86a9-9d9c-4fb9-a50d-7d43e67654dd)

**Comment by hsuyelin** [comment]
没站，尝试修改了配置，下个版本你再试试
