### ISSUE TITLE
[功能改进]: 刮削元数据的时候，电影可不可增加：[电影集]数据，方便创建合集

### ISSUE THREAD

**Issue by caneman** [hsuyelin/nas-tools#191]
### 当前程序版本

3.3.3

### 功能改进

RT，Plex 创建合集需要NFO数据里还有正确的电影集信息，但是现在的NT刮削设置里面只能配置

基础信息和演员信息|

不知道是已经刮削了而我的使用方式不对，还是确实没有刮削[电影集]信息

如果没有刮削的话，希望可以增加

![image](https://github.com/hsuyelin/nas-tools/assets/13256051/d228e8f2-6f53-4f3e-814c-eccd01bed805)

![image](https://github.com/hsuyelin/nas-tools/assets/13256051/e5d24afe-9af5-466e-a06d-ac01387a2fe4)

**Comment by hsuyelin** [comment]
基于现有的结构改动太大，不准备增加这个
