### ISSUE TITLE
[错误报告]: docker版更新完无法访问web

### ISSUE THREAD

**Issue by m774303886** [hsuyelin/nas-tools#192]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新

### 问题类型

主程序运行问题

### 问题描述

<img width="1003" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/143067620/65752a28-b9c2-465d-83be-e49716b538cd">
<img width="666" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/143067620/fc2c4e17-ef27-4c2b-8ec0-536bb61de91e">
docker版更新完无法访问了

### 发生问题时系统日志和配置文件

```bash
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service init-010-update: starting
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-010-update/run: Permission denied
s6-rc: warning: unable to start service init-010-update: command exited 126
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/010-update
cont-init: info: /etc/cont-init.d/010-update: 更新主程序...
cont-init: info: /etc/cont-init.d/010-update: fatal: unable to access 'https://github.com/hsuyelin/nas-tools.git/': Failure when receiving data from the peer
cont-init: info: /etc/cont-init.d/010-update: HEAD is now at 1431fa6 fix(package): 尝试修复  No module named babelfish.converters.alpha2
cont-init: info: /etc/cont-init.d/010-update: 主程序更新成功
cont-init: info: /etc/cont-init.d/010-update exited 0
cont-init: info: running /etc/cont-init.d/020-fixuser
cont-init: info: /etc/cont-init.d/020-fixuser: 以PUID=1026，PGID=100的身份启动程序...
cont-init: info: /etc/cont-init.d/020-fixuser: usermod: no changes
cont-init: info: /etc/cont-init.d/020-fixuser exited 0
s6-rc: info: service legacy-cont-init successfully started
```

**Comment by jackloves111** [comment]
大兄弟，你用的什么镜像？感觉有点太着急了吧，日志来看没有任何问题，只是等他start完成就可以了

**Comment by jackloves111** [comment]
或者重置重启，之类的

**Comment by m774303886** [comment]
> 或者重置重启，之类的

重启好几遍了

**Comment by m774303886** [comment]
> 大兄弟，你用的什么镜像？感觉有点太着急了吧，日志来看没有任何问题，只是等他start完成就可以了

重启自动拉取最新版本

**Comment by hsuyelin** [comment]
> > 大兄弟，你用的什么镜像？感觉有点太着急了吧，日志来看没有任何问题，只是等他start完成就可以了
> 
> 重启自动拉取最新版本

使用镜像方式拉取

**Comment by m774303886** [comment]
、

> 你的科学不太好，应该是依赖没拉下来
> 
> ![image](https://user-images.githubusercontent.com/17918063/265409955-365f24d2-5604-4dad-af49-eb3653810d09.png)

我换一个

**Comment by hsuyelin** [comment]
保存你的config目录就可以了
