### ISSUE TITLE
[错误报告]: 使用豆瓣搜索电影配合增强识别V2结果异常

### ISSUE THREAD

**Issue by zjjxwhh** [hsuyelin/nas-tools#194]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.2 932b6d5（还没更新到最新版本，但看 commit 似乎不影响该 issue）

### 问题类型

主程序运行问题

### 问题描述

使用 **豆瓣搜索电影** 配合 增强识别V2 结果异常（TMDB + 增强识别V2 搜索无此问题）

0. 基础设置中开启 增强识别V2（其他设置见下图1）
1. 点击界面最上方搜索框左侧图标切换到豆瓣搜索（绿色图标）
2. 搜索框输入“奥本海默”，回车搜索
3. **搜索结果无海报**，使用局域网 IP 直接访问或群晖自带的反向代理访问表现一致（这一步没有日志，见下图2）
4. 点击第一个标记为 2023 年的奥本海默，详情页面显示的是 **剧集 Oppenheimer (1980)**，关闭 增强识别V2 时详情页面显示正确（错误的详情页面见下图3，日志后附，做了一些注释节省排查时间）

以上 3/4 两个问题，望修复，需要其他帮助或者日志可再提供，感谢！

![image](https://github.com/hsuyelin/nas-tools/assets/14367334/8a2645c6-8265-42eb-a6b2-3108c8b3b067)

![image](https://github.com/hsuyelin/nas-tools/assets/14367334/22b8bdd5-ea20-4ef2-a7fa-d2dd71f1200d)

![image](https://github.com/hsuyelin/nas-tools/assets/14367334/76490cb3-f538-462c-aca6-5866cb338c63)

### 发生问题时系统日志和配置文件

```bash
# 开启 增强识别V2 时的日志（详情页面错误）
2023-09-04 17:19:50,046	INFO: 【Douban】正在通过API查询豆瓣详情：35593344    # 这个ID在豆瓣确实是电影奥本海默(2023)
2023-09-04 17:19:50,046	INFO: 【Douban】查询到数据：奥本海默
2023-09-04 17:19:50,061	INFO: 【Meta】正在查询TMDB电视剧：8771 ...    # 这个ID在TMDB是剧集奥本海默(1980)，也就是上面图2里显示的错误详情
2023-09-04 17:19:50,061	INFO: 【Meta】8771 查询结果：Oppenheimer

# 关闭 增强识别V2 时的日志（详情页面正确）
2023-09-04 17:30:37,226	INFO: 【Douban】正在通过API查询豆瓣详情：35593344
2023-09-04 17:30:37,226	INFO: 【Douban】查询到数据：奥本海默
2023-09-04 17:30:37,227	INFO: 【Meta】正在查询TMDB电影：872585 ...
2023-09-04 17:30:37,230	INFO: 【Meta】872585 查询结果：奥本海默
```

**Comment by hsuyelin** [comment]
已知问题，就是看反馈然后才能改进。然后提供开关可以切换，具体看自己用

**Comment by yingpan008** [comment]
3.3.3已更新至最新，经过多次测试，开启V2增强，看日志没有E集数的都默认第一集，会导致一个比较大的问题，全集全跑到最底下的第一集去了，跟第一集混在一起，在有全集的情况下，先显示40多集分集，在往下去找全集下不是很合理，原版的全集会显示在顶部，再显示分集，还有就是我的豆瓣搜索搜索结果没图片，点进去又会有图片，大家都这样吗？是为了搜索更快吗？还是豆瓣又作妖了？不知道怎么发图片，白准备了图片

**Comment by yingpan008** [comment]
用豆瓣搜索电视剧搜索完再点上面的搜索跟，在搜索框里详细选择搜索，搜索的结果不一样，前者会分全集，在分每一集，后者只会有分辨率区分，希望能改进后者搜索结果，在有全集时，能单独优先分类先显示，再分集显示，不然搜索多一个步骤得先搜片再搜索，有时还是喜欢在精细搜索框直接搜索站点。。。

**Comment by jackloves111** [comment]
> 3.3.3已更新至最新，经过多次测试，开启V2增强，看日志没有E集数的都默认第一集，会导致一个比较大的问题，全集全跑到最底下的第一集去了，跟第一集混在一起，在有全集的情况下，先显示40多集分集，在往下去找全集下不是很合理，原版的全集会显示在顶部，再显示分集，还有就是我的豆瓣搜索搜索结果没图片，点进去又会有图片，大家都这样吗？是为了搜索更快吗？还是豆瓣又作妖了？不知道怎么发图片，白准备了图片

  发图片直接粘贴就行了

**Comment by hsuyelin** [comment]
@zjjxwhh 应该修复，会拉代码就拉代码试试，不会就等我更新
