### ISSUE TITLE
[错误报告]: 猫站索引有问题，搜索报错，站点资源中不显示标题。

### ISSUE THREAD

**Issue by XINGYUZHMM** [hsuyelin/nas-tools#195]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

windows 3.3.3

### 问题类型

主程序运行问题

### 问题描述

猫站索引有问题，搜索报错，站点资源中不显示标题。
![image](https://github.com/hsuyelin/nas-tools/assets/112518475/4838aede-a878-44df-a756-9f52cb16f83f)
![image](https://github.com/hsuyelin/nas-tools/assets/112518475/dcac3eb8-044c-4247-b780-d9c7c27eff45)

**Comment by iovejieba** [comment]
额 没站 没办法帮上忙....额

**Comment by hsuyelin** [comment]
没站，从其他地方锵来的配置，下个版本你试试

**Comment by jackloves111** [comment]
> 没站，从其他地方锵来的配置，下个版本你试试

我觉得，大佬有空可以教学一下，怎么获取爬取代码，这样让用户自己去获取修改json测试。授人与渔。当然，只是突然想到
