### ISSUE TITLE
[错误报告]: 多目录硬链接至默认目录存在bug（只能留存单一目录硬链接至媒体目录，其他目录会自动硬链接至空白位置）

### ISSUE THREAD

**Issue by x1186176868** [hsuyelin/nas-tools#196]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3

### 问题类型

主程序运行问题

### 问题描述

多目录硬链接至默认目录存在bug（只能留存单一目录硬链接至媒体目录，其他目录会自动硬链接至空白位置）

**Comment by hsuyelin** [comment]
单一目录硬链接至媒体目录，其他目录会自动硬链接至空白位置这句话是否描述的更加清楚点，或者举个例子，这个是热心大佬PR的，我也不是很明白

**Comment by x1186176868** [comment]
<img width="263" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/30969849/676259a5-74e4-438e-a2a7-bde0d89a1c17">
<img width="1175" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/30969849/3be8fe27-eff5-4b8b-aa76-638e40281b5f">
按理说应该是都会同步到媒体库，但是现在就会出现链接目标不明一个目录

**Comment by jackloves111** [comment]
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/30969849/265655378-676259a5-74e4-438e-a2a7-bde0d89a1c17.png"> <img alt="image" width="1175" src="https://user-images.githubusercontent.com/30969849/265655471-3be8fe27-eff5-4b8b-aa76-638e40281b5f.png"> 按理说应该是都会同步到媒体库，但是现在就会出现链接目标不明一个目录

你目的地都没有设置，系统怎么知道你要同步到哪个文件夹，然后显示给你呢？你可以尝试把目的目录设置好，你再看下

**Comment by x1186176868** [comment]
但是他是不填写为自动指定媒体库

**Comment by jackloves111** [comment]
> 但是他是不填写为自动指定媒体库

程序不是这样工作的，他只是读取你设置的目的地，然后显示给你看。你没有设置，就不显示。你自动的话，他可能A目录也可能B目录，难道都要显示给你吗？

**Comment by jackloves111** [comment]
而且你不设置目的目录，我甚至认为这个同步并不会工作，当然，我没有试过，只是猜测。具体可以看下官方的wiki，在TG群

**Comment by jackloves111** [comment]
不过可以让大佬修改一下，如果空白，则显示自动 @waylonwang

**Comment by youyifentian** [comment]
这是你目录结构的问题，nt会自动比较路径的，不指定目的路径的话，会自动匹配到路径最接近的媒体库目录，虽然你可能设置了多个媒体库路径，但如果跟源文件的路径相似度都是一样的话，那它默认就是选第一个，比如
电影媒体库路径2个：
/media1/movie
/media2/movie
如果你的源文件是在/media1/aa/bb，那就会同步到/media1/movie
如果你的源文件是在/media2/cc/dd，那就会同步到/media2/movie

## 但是
如果你的媒体库路径2个：
/media/movie1
/media/movie2
源文件路径是无论是啥，它都会同步到/media/movie1里面

**Comment by yingpan008** [comment]
3.3.5回退了文件管理，想问能不能做个开关，我觉得没回退的新版的文件管理，在整理文件上真的挺方便的，好用

**Comment by caneman** [comment]
新版的文件管理很好用，为了这个功能我特意从3.3.5回退到了3.3.2。
希望保留新版文件管理，或者加个开关允许自行选择使用。

**Comment by caneman** [comment]
> > 3.3.5回退了文件管理，想问能不能做个开关，我觉得没回退的新版的文件管理，在整理文件上真的挺方便的，好用
> 
> #290 增加了开关，等合并到新版本发布后，升级前建议备份一下数据库

感谢老哥，这个功能真的很好用，帮我找到了多季电视剧中的有些因为集数/识别错误导致的硬链接错误的问题，没有这个功能，不观看剧的情况下几乎发现不了。

还找到一些忘记识别了的影视剧，和复制而不是硬链接的，真的很好用，为了这个功能一直停在3.3.2，终于可以升级啦

**Comment by hsuyelin** [comment]
已修复 @caneman 等更新
