### ISSUE TITLE
[错误报告]: 有两个远古bug希望能修复一下

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#198]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.3

### 问题类型

主程序运行问题

## 1、api调用出错
[这里的返回值](https://github.com/hsuyelin/nas-tools/blob/b926d6242a35b45918ffdcff41e13ed460b1afe4/web/apiv1.py#L1738)并不是json格式的，当调用到这个api的时候会返回错误，这个并不是说程序运行会有问题，而是第三方通过nt的api调用这个的时候会出错，可以改成：
`
return {
  "code": 0,
  "success": True,
  "data": {
      "tasks": list(BrushTask().get_brushtask_info())
  }
}`
![QQ截图20230905121152](https://github.com/hsuyelin/nas-tools/assets/5012570/91ea61d9-066f-44bf-8d99-6d3a2b31b172)

就是加一个list函数

## 2、带“：”并且带HD的时候大概率识别出错
比如：
## 夺宝奇兵5：命运转盘.HD.mp4

![2222](https://github.com/hsuyelin/nas-tools/assets/5012570/4a504b30-b787-4a83-908b-329b21303762)

![333](https://github.com/hsuyelin/nas-tools/assets/5012570/614b4483-32d9-4019-b3be-5e11c2a49ef7)

## 这都是很久以前就有的问题了，第一个很好改，第二个希望大佬能考虑完善一下

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/36b0a93c-bb36-4d74-b7d2-5d67602de62e)
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/99fbada0-bd68-4c8a-91be-242d54bcaf8a)

建议使用增强识别V2，这个我在完善中

**Comment by youyifentian** [comment]
> ![image](https://user-images.githubusercontent.com/17918063/265607864-36b0a93c-bb36-4d74-b7d2-5d67602de62e.png) ![image](https://user-images.githubusercontent.com/17918063/265607918-99fbada0-bd68-4c8a-91be-242d54bcaf8a.png)
> 
> 建议使用增强识别V2，这个我在完善中

好的，开了果然识别了，66666666666666

**Comment by hsuyelin** [comment]
> > ![image](https://user-images.githubusercontent.com/17918063/265607864-36b0a93c-bb36-4d74-b7d2-5d67602de62e.png) ![image](https://user-images.githubusercontent.com/17918063/265607918-99fbada0-bd68-4c8a-91be-242d54bcaf8a.png)
> > 建议使用增强识别V2，这个我在完善中
> 
> 好的，开了果然识别了，66666666666666

不过这个还有问题，在优化中，视情况开，如果你没问题就开，有问题就关

**Comment by hsuyelin** [comment]
@youyifentian 第一个我不知道在哪用的啊。这个看实现是字典，改成数组有问题吧

**Comment by youyifentian** [comment]
> @youyifentian 看了，没问题是一个字典，字典的key是taskId，字典的value是taskInfo，我觉得是第三方调用的问题，你可以给我看看报错信息

这个确实是有问题的，图我暂时没法截，我给你说复现过程，http://IP:3000/api/v1，打开nt的api网页版，然后再用户认证那里通过用户名和密码认证，得到token，吧token填入网页那个Authorize那里，然后调用/brushtask/list和/brushtask/torrents接口，哪个出错我也忘了，你试试，肯定有一个会报错的

**Comment by youyifentian** [comment]
因为我之前发现qb种子多了之后会反应慢，然后nt刷流的时候有小概率会出现qb里面实际上添加成功了，可能是反应慢，nt就没有收到成功添加的回复或者其他不知道的情况，总之就是qb添加上了刷流，但是nt刷流种子明细里面没有，所以我就弄了个浏览器脚本，在qb页面上面调用nt的api获取某个站点的刷流明细，然后跟qb里面该站点的刷流标签种子对比，来找出来哪个是不在nt记录里面的，因为不在nt里面的nt就没法自动管理，这中情况多了qb就会出现很多没被管理的刷流任务，得手动清理一下，这样用脚本可以很快标记出来，所以才用到得nt得api，就发现了这个问题

**Comment by hsuyelin** [comment]
> 因为我之前发现qb种子多了之后会反应慢，然后nt刷流的时候有小概率会出现qb里面实际上添加成功了，可能是反应慢，nt就没有收到成功添加的回复或者其他不知道的情况，总之就是qb添加上了刷流，但是nt刷流种子明细里面没有，所以我就弄了个浏览器脚本，在qb页面上面调用nt的api获取某个站点的刷流明细，然后跟qb里面该站点的刷流标签种子对比，来找出来哪个是不在nt记录里面的，因为不在nt里面的nt就没法自动管理，这中情况多了qb就会出现很多没被管理的刷流任务，得手动清理一下，这样用脚本可以很快标记出来，所以才用到得nt得api，就发现了这个问题

不是那样改的，确实是远古bug，能不能生效我不知道，我先保证逻辑是通的

**Comment by youyifentian** [comment]
@hsuyelin 这个我也描述不清楚，但是无论是哪个版本的nt，这个肯定是有问题的，具体复现过程上面我也写了，可能这玩意除了我也真的没别人用把，反正我按照上面api去获取某个站点的详细刷流明细的时候是100%出错的，把apiv1.py修改之后就不会报错了，另外说明一下就是这个是在外部调用api的时候出错，我用docker exec -it直接进入容器用Python执行它并不报错，因为我对py这玩意也不太懂，但是按照http://ip:3000/api/v1/ 里面的方法调用/brushtask/torrents 查询刷流任务种子明细是100%报错的，希望大佬有空的时候可以测试下
