### ISSUE TITLE
[错误报告]: 重启后，启动时间过长

### ISSUE THREAD

**Issue by jackloves111** [hsuyelin/nas-tools#199]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.3

### 问题类型

主程序运行问题

### 问题描述

通过拉取到最新版本，重启之后一直卡在这个提示，重启问题依然存在，不清楚大家是不是都有这种情况

### 发生问题时系统日志和配置文件

![image](https://github.com/hsuyelin/nas-tools/assets/89971817/ee2c1fc9-0ac9-43b6-b5a0-adfc23d3a4df)

**Comment by jackloves111** [comment]
@DDSDerek 是不是和更新了docker的打包有关？

**Comment by hsuyelin** [comment]
> @DDSDerek 是不是和更新了docker的打包有关？

没关系，是你网络不行，每次重启会自动拉取，你别开自动更新就可以

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/b663d5c4-eb33-4530-8562-7b1e87a91f6e)
网络没有问题的，科学延迟速率都不差，依赖什么都已经拉取更新好了的。关闭更新还是会卡在这个提示。

**Comment by jackloves111** [comment]
可能原因是要拉取镜像更新，不能拉取代码更新。
