### ISSUE TITLE
Jackett测试添加失败

### ISSUE THREAD

**Issue by kissgun258** [hsuyelin/nas-tools#2]
## 你遇到什么问题了？

>你好docker-compose 构建  Jackett测试添加失败，添加了Indexer 也没测试成功，但我换了[linyuan0213](https://github.com/linyuan0213)

[nas-tools](https://github.com/linyuan0213/nas-tools)的镜像 添加成功，不知道哪里出了问题。

![2023-05-19_074054](https://github.com/hsuyelin/nas-tools/assets/64009324/adaf138d-d676-4a14-b64b-c26e77519b4c)

**Comment by Edger** [comment]
+1

我也是，搞了很久，emby 也连不上

**Comment by hsuyelin** [comment]
> +1
> 
> 我也是，搞了很久，emby 也连不上

本地测试如下，正常使用：

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/09ca1159-d440-4886-8d38-7904f081ef42)

1. 确保Emby服务正常开启；
2. 确保Emby地址填写正确
3. 确保Emby Key正确，大部分是APIKey含有空格导致无法连接

**Comment by hsuyelin** [comment]
> ## 你遇到什么问题了？
> > 你好docker-compose 构建  Jackett测试添加失败，添加了Indexer 也没测试成功，但我换了[linyuan0213](https://github.com/linyuan0213)
> 
> [nas-tools](https://github.com/linyuan0213/nas-tools)的镜像 添加成功，不知道哪里出了问题。
> 
> ![2023-05-19_074054](https://user-images.githubusercontent.com/64009324/239405020-adaf138d-d676-4a14-b64b-c26e77519b4c.jpg)

我本地未配置Jackett，内建足够了，后面有时间看下，你也确保如下：

1. 确保Jackett服务正常开启；
2. 确保Jackett地址填写正确, 可以尝试去掉http
3. 确保Jackett Key正确，大部分是APIKey含有空格导致无法连接

**Comment by Edger** [comment]
> > ## 你遇到什么问题了？
> > > 你好 docker-compose 构建  Jackett 测试添加失败，添加了 Indexer 也没测试成功，但我换了 [linyuan0213](https://github.com/linyuan0213)
> > 
> > 
> > [nas-tools](https://github.com/linyuan0213/nas-tools) 的镜像 添加成功，不知道哪里出了问题。
> > ![2023-05-19_074054](https://user-images.githubusercontent.com/64009324/239405020-adaf138d-d676-4a14-b64b-c26e77519b4c.jpg)
> 
> 我本地未配置 Jackett，内建足够了，后面有时间看下，你也确保如下：
> 
> 1. 确保 Jackett 服务正常开启；
> 2. 确保 Jackett 地址填写正确，可以尝试去掉 http
> 3. 确保 Jackett Key 正确，大部分是 APIKey 含有空格导致无法连接

我也换了这个镜像 [linyuan0213](https://github.com/linyuan0213) 就可以连上 Jackett 了，不是 Jackett 的问题，应该是 NASTool 镜像的问题

**Comment by Edger** [comment]
> > +1
> > 我也是，搞了很久，emby 也连不上
> 
> 本地测试如下，正常使用：
> 
> ![image](https://user-images.githubusercontent.com/17918063/239786716-09ca1159-d440-4886-8d38-7904f081ef42.png)
> 
> 1. 确保 Emby 服务正常开启；
> 2. 确保 Emby 地址填写正确
> 3. 确保 Emby Key 正确，大部分是 APIKey 含有空格导致无法连接

真的是在最前面多了一个空格，太坑了，感谢大佬🙏

**Comment by Edger** [comment]
@hsuyelin 只是 emyb 可以了，Jackett 还是不行的

**Comment by Edger** [comment]
今天有空又试了一下，可以添加成功了

有点奇怪，没搞懂什么原因

**Comment by Edger** [comment]
> 今天有空又试了一下，可以添加成功了
> 
> 有点奇怪，没搞懂什么原因

看了一下版本，v3.2.4-beta

应该是升级了版本就好了
