### ISSUE TITLE
v3.2.9 自定义

### ISSUE THREAD

**Issue by Fantuan-cell** [hsuyelin/nas-tools#20]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.9
>
> 环境: docker 
>

## 你遇到什么问题了？

> 自定义索引器插件设置站点后,索引器里面没有选项

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已经查看过issue,没发现有相同的问题

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
这里配置的dmhy是公开站点dmhy.org,其中生成的json中的public设置为True,但是没有生效,
ptchdbits是岛的新域名添加后,也是没有生效。这两个站点都在站点维护里面添加了。索引器那里没有选择它们的选项
![image](https://github.com/hsuyelin/nas-tools/assets/53990888/7331d6d7-55bc-408e-9938-91f997733934)
![image](https://github.com/hsuyelin/nas-tools/assets/53990888/f9e615a8-a1de-4d9c-929b-04898e94b280)
![image](https://github.com/hsuyelin/nas-tools/assets/53990888/3644b4e8-6186-4021-ada7-ce9b12392e7b)
![image](https://github.com/hsuyelin/nas-tools/assets/53990888/83eb2ae6-4253-474c-b009-107dfb492aff)
![image](https://github.com/hsuyelin/nas-tools/assets/53990888/489222ef-015f-4886-a1df-738488703583)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Juway111** [comment]
重启生效

**Comment by hsuyelin** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.2.9
> > 环境: docker
> 
> ## 你遇到什么问题了？
> > 自定义索引器插件设置站点后,索引器里面没有选项
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 已经查看过issue,没发现有相同的问题
> 
> > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> 
> ## 你期望的结果
> > 描述以下你期望的结果
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> 这里配置的dmhy是公开站点dmhy.org,其中生成的json中的public设置为True,但是没有生效, ptchdbits是岛的新域名添加后,也是没有生效。这两个站点都在站点维护里面添加了。索引器那里没有选择它们的选项 ![image](https://user-images.githubusercontent.com/53990888/257687238-7331d6d7-55bc-408e-9938-91f997733934.png) ![image](https://user-images.githubusercontent.com/53990888/257687459-f9e615a8-a1de-4d9c-929b-04898e94b280.png) ![image](https://user-images.githubusercontent.com/53990888/257687479-3644b4e8-6186-4021-ada7-ce9b12392e7b.png) ![image](https://user-images.githubusercontent.com/53990888/257687495-83eb2ae6-4253-474c-b009-107dfb492aff.png) ![image](https://user-images.githubusercontent.com/53990888/257687536-489222ef-015f-4886-a1df-738488703583.png)
> 
> > 如UI BUG请提供截图及配置文件截图
> > 其它问题提供后台日志，如为Docker请提供docker的日志

1. 重启生效
2. 找到public: 将false改为true
