### ISSUE TITLE
[错误报告]: 搜索结果显示问题

### ISSUE THREAD

**Issue by Wangsc1** [hsuyelin/nas-tools#200]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.3 1431fa6

### 问题类型

其他问题

### 问题描述

1、搜索结果涉及瓷器官种的会单独汇总到一个CTV的条目，这应该是个问题吧![微信图片_20230905170121](https://github.com/hsuyelin/nas-tools/assets/26079238/1a8d7ee0-1937-4d8a-a91b-5e7917898732)

2、完结剧集搜索结果会在后面显示E01，都是完结打包的没有单集，正常应该直接显示S01吧![EO1](https://github.com/hsuyelin/nas-tools/assets/26079238/7b121fa9-d20b-4c34-afce-af6472531da3)

麻烦大佬看下，谢谢

**Comment by hsuyelin** [comment]
@Wangsc1 已知问题，已修复

**Comment by Wangsc1** [comment]
刚更新到最新的c1ab9a6，第二条修复了，第一条还是有问题，直接就还是显示ctv，然后web-dl显示未知媒体![IMG_20230905_182344.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/61a4ea48-f670-4174-90e5-04883b110190)
