### ISSUE TITLE
刷流界面无法打开

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#201]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3

### 问题类型

主程序运行问题

### 问题描述

fix(api): 通过api获取所有刷流任务报错。更新完这个版本刷流界面无法打开

**Comment by hsuyelin** [comment]
@hh0610 哪个界面，刷流任务么

**Comment by hsuyelin** [comment]
出问题，贴一下日志啊

**Comment by hsuyelin** [comment]
不用日志了。我知道了

**Comment by hh0610** [comment]
> @hh0610 你咋更新的比我写代码还勤快，已修复

上班太无聊了，就一直关注，看有没有更新新版本。
