### ISSUE TITLE
憨憨  无法自动获取免费种子刷流，站点资源里面能获取到

### ISSUE THREAD

**Issue by yangdong123** [hsuyelin/nas-tools#202]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.3

### 问题类型

其他问题

### 问题描述

憨憨  无法自动获取免费种子刷流

### 发生问题时系统日志和配置文件

```bash
17:29:28		
憨憨 RSS获取数据：49
17:29:31		
任务 憨憨 本次添加了 0 个下载
```

**Comment by hsuyelin** [comment]
不是我不支持，是憨憨的rss没用

**Comment by yangdong123** [comment]
好的，谢谢大佬
