### ISSUE TITLE
[新增功能反馈]: 开启增强识别V2后搜索的资源变少了

### ISSUE THREAD

**Issue by KhyHolyDragon** [hsuyelin/nas-tools#204]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3 1431fa6

### 问题类型

其他问题

### 问题描述

![Screenshot_20230905_192029_nastool](https://github.com/hsuyelin/nas-tools/assets/140623652/2268c279-9303-419e-a7a9-869fbe58205c)
![Screenshot_20230905_191421_nastool](https://github.com/hsuyelin/nas-tools/assets/140623652/e5d89a4c-252d-4bb3-8f6c-ea4b48a20ef7)
开启增强识别V2后搜索的资源变少了

**Comment by hsuyelin** [comment]
已知问题，已修复，等新版本
