### ISSUE TITLE
[功能改进]: 目录同步数量多时操作会变卡

### ISSUE THREAD

**Issue by chris6868** [hsuyelin/nas-tools#205]
### 当前程序版本

3.3.3

### 功能改进

当目录同步数量超过20条时，增删改目录都会卡很久，并且刷新页面和重启容器都无效

**Comment by hsuyelin** [comment]
我具体说说，或者有更详细的复现场景么

**Comment by chris6868** [comment]
> 我具体说说，或者有更详细的复现场景么

在同步目录中添加不同目录的同步策略，如下图，当数量达到一定量（不超过20条）也会卡，比如添加一条数据有时候需要几分钟，有时候需要10多分钟，添加的同步策略越多耗时越久
![image](https://github.com/hsuyelin/nas-tools/assets/22971922/86b84013-5868-43cd-bc4c-e9733a063011)

**Comment by hsuyelin** [comment]
下次操作的时候方便贴下日志

**Comment by chris6868** [comment]
> 下次操作的时候方便贴下日志

![image](https://github.com/hsuyelin/nas-tools/assets/22971922/7ff60c08-1053-42ff-8230-037bf609e871)

添加的目录是/CloudNAS/WebDAV/阿里分享/电影4K（62T），目的目录：/mnt/nas/media/link/video，转移方式：软链接，实际上日志显示已经成功了，但是这个时候监控服务还没启动完成，所以界面上进度条也还在继续中，并且这个时候如果刷新页面或者做其他操作打断，那么这条记录就会消失，重启容器、刷新界面都不会出现，只有重新添加一条新数据等进度条走完才能把刚刚那条消失的数据显示出来

**Comment by wang-peak** [comment]
群晖docker，还是以ROOT运行的
不知道是目录层级太多，还是文件太多。目录同步会卡死。手动开启目录同步后，如果重启了，wed就打不开了！
cpu1900，不知道是不是性能太弱了！
![1](https://github.com/hsuyelin/nas-tools/assets/47379399/49c0d5cc-dbf2-4b50-b924-508445dd0659)
![2](https://github.com/hsuyelin/nas-tools/assets/47379399/3de7cdcd-6c57-4043-a634-0b1b5e3e4d24)
![3](https://github.com/hsuyelin/nas-tools/assets/47379399/6bf1d317-0028-4824-a761-7d8f20999baf)
![4](https://github.com/hsuyelin/nas-tools/assets/47379399/eadb445c-4369-430c-8099-3503371e28ab)
![5](https://github.com/hsuyelin/nas-tools/assets/47379399/f6e38610-3cd2-4c45-897e-3adb6a24e6cd)
![7](https://github.com/hsuyelin/nas-tools/assets/47379399/8fefcedc-4927-4741-961d-a9f8dafec52a)
![6](https://github.com/hsuyelin/nas-tools/assets/47379399/6eb2017c-1144-424e-a195-6cbe76f01831)

**Comment by jackloves111** [comment]
内存多大？实测2g太小。j1900应该是13年的cpu了

**Comment by hsuyelin** [comment]
已修复
