### ISSUE TITLE
憨憨刷流不行

### ISSUE THREAD

**Issue by WB-peter** [hsuyelin/nas-tools#206]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3

### 问题类型

其他问题

### 问题描述

憨憨刷流是不是不支持啊？还是怎么设置一下

**Comment by iovejieba** [comment]
hh的 rss 有问题
