### ISSUE TITLE
[错误报告]: 增强识别V2，识别TV港剧会把翡翠台Jade带上识别

### ISSUE THREAD

**Issue by 8aby-dudu** [hsuyelin/nas-tools#208]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.4

### 问题类型

主程序运行问题

### 问题描述

识别TV港剧会把翡翠台Jade带上识别，导致无法识别出对应剧集，原版本的是正常识别。

### 发生问题时系统日志和配置文件

```bash
如剧集“破毒强人”，其它也一样：
Jade Narcotics Heroes E03-08 HDTV 1080i H264 识别为 Jade Narcotics Heroes 未匹配到媒体信息
```

**Comment by hsuyelin** [comment]
多给几个识别不了的例子，我方便测试

**Comment by 8aby-dudu** [comment]
> 多给几个识别不了的例子，方便我测试
Jade Narcotics Heroes E03-08 HDTV 1080i H264 识别为 Jade Narcotics Heroes  正确为Narcotics Heroes
Jade.Final.Destiny.Complete.HDTV.1080i.H264 识别为 Jade Final Destiny  正确为Final Destiny
Jade.Hong.Kong.Love.Stories.Complete.HDTV.1080i.H264 识别为 Jade Hong Kong Love Stories  正确为Hong Kong Love Stories

实际就是TVB的HDTV剧集名字首都带Jade标识，V2会把它带进识别词。

**Comment by hsuyelin** [comment]
Ok

**Comment by 8aby-dudu** [comment]
> Ok

同理，还有ViuTV等电视台。

ViuTV Shooting Stars COMPLETE 1080i HDTV H.264-NGB 识别为ViuTV Shooting Stars 正确为Shooting Stars。

麻烦大佬了。

**Comment by hsuyelin** [comment]
> > Ok
> 
> 同理，还有ViuTV等电视台。
> 
> ViuTV Shooting Stars COMPLETE 1080i HDTV H.264-NGB 识别为ViuTV Shooting Stars 正确为Shooting Stars。
> 
> 麻烦大佬了。

暂且已兼容。如果后续有电影名存在Jade报bug就把这个去掉， 建议你这种使用自定义识别词来解决。将Jade替换为就好了呀
