### ISSUE TITLE
[错误报告]: 开启增强识别V2 识别能力减弱反馈

### ISSUE THREAD

**Issue by tyzzz** [hsuyelin/nas-tools#210]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.4 0488149

### 问题类型

主程序运行问题

### 问题描述

开启增强识别V2 识别能力减弱很多
例如图中所示 这种命名规则的基本都识别不了 关闭V2后可以准确识别
![Snipaste_2023-09-06_12-09-37](https://github.com/hsuyelin/nas-tools/assets/10782608/0c33ade1-bb6f-492d-b022-e39367096fbf)

**Comment by hsuyelin** [comment]
已知问题，对标签中同时具有中英文混合的剧名识别不好或者说BT识别不好，暂且没想到好的，跑了大量的PT命名，一般都是主标题是原始名称，副标题是中文或者别名，你这个不像是PT啊

**Comment by tyzzz** [comment]
> 已知问题，对标签中同时具有中英文混合的剧名识别不好或者说BT识别不好，暂且没想到好的，跑了大量的PT命名，一般都是主标题是原始名称，副标题是中文或者别名，你这个不像是PT啊

是PT  OurBits我堡的官组资源  港片有不少习惯这种命名

**Comment by hsuyelin** [comment]
> > 已知问题，对标签中同时具有中英文混合的剧名识别不好或者说BT识别不好，暂且没想到好的，跑了大量的PT命名，一般都是主标题是原始名称，副标题是中文或者别名，你这个不像是PT啊
> 
> 是PT OurBits我堡的官组资源 港片有不少习惯这种命名

这个是已知问题，中英文混合的剧名

**Comment by hsuyelin** [comment]
已修复
