### ISSUE TITLE
[功能改进]: 在站点资源里面下载的种子 ， 不受刷流任务的规则限制

### ISSUE THREAD

**Issue by yangdong123** [hsuyelin/nas-tools#212]
### 当前程序版本

v3.3.3

### 功能改进

在站点资源里面下载的种子 ， 不受刷流任务的规则限制
1,列如我在刷流规则里面设置了2两个小时的下载超时，实际过了两个小时还在下载，这样可能会导致超过了FREE的时间
2,能再站点资源的一键下载上添加选择框吗？（下载器选择 ， 下载标签 ，分类）

感谢大佬辛苦维护

**Comment by jackloves111** [comment]
你这个逻辑就不对，站点资源里面下载是你自己手动选择的，跟刷流毫无关系。刷流设置只对自动添加的刷流任务生效。

**Comment by yangdong123** [comment]
> 你这个逻辑就不对，站点资源里面下载是你自己手动选择的，跟刷流毫无关系。刷流设置只对自动添加的刷流任务生效。

因为考虑到一些站点可能无法自动R到种子刷流，那就手动去刷，手动刷的话 可能需要一些规则来限制 ，所以就提出这个问题

**Comment by hsuyelin** [comment]
手动选择和刷流是两个功能，不打算添加

**Comment by iovejieba** [comment]
qb加分类标签 限制不就好了.....
