### ISSUE TITLE
[错误报告]: https://hdmayi.com/小蚂蚁pt，站点资源菜单无法搜索到资源，是否与网址里是http，无s,有关？

### ISSUE THREAD

**Issue by chengli0946** [hsuyelin/nas-tools#213]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版本

### 问题类型

Docker或运行环境问题

### 问题描述

https://hdmayi.com/小蚂蚁pt，站点资源菜单无法搜索到资源，统计数据无法同步，是否与网址里是http，无s,有关？

### 发生问题时系统日志和配置文件

```bash
16:40:18		
开始请求：http://hdmayi.com/torrents.php
```

**Comment by hsuyelin** [comment]
修复了。拉下代码看看
