### ISSUE TITLE
[错误报告]: Cloudflare IP优选 安装不上？

### ISSUE THREAD

**Issue by qsxazcv** [hsuyelin/nas-tools#214]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.4 87ffe2a

### 问题类型

插件问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/113089025/9697337d-4bd8-421f-acb2-a09d587ec04f)
这个已经开启了，但是这个插件一直显示没有安装成功
![image](https://github.com/hsuyelin/nas-tools/assets/113089025/2664ae44-0a9e-4148-83e1-c2ed04e7c590)
我运行了就一直是这样
![image](https://github.com/hsuyelin/nas-tools/assets/113089025/1046f0dd-ee91-4324-9fa6-6e862734cc06)
没有任何命令了 就一直一条这个。。。
希望大佬帮我看看这个是哪里的问题
我也尝试取消代理，也是不行。

**Comment by hsuyelin** [comment]
这里没关系，主要看日志啊

**Comment by qsxazcv** [comment]
好的 明白了，我以为不需要先写周期就可以开启。。。
