### ISSUE TITLE
新安装没有办法正常启动

### ISSUE THREAD

**Issue by edu-hui** [hsuyelin/nas-tools#215]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.4

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/54179964/3fb08ba2-0356-435a-9897-f498438dec03)
我是这样安装的
docker run -d \
    --name nas-tool \
    --hostname nas-tools \
    -p 3000:3008 \
    -v /volume1/docker/nastool/config:/config \
    -v /volume2/downloads/Download:/Download \
    -e PUID=0 \
    -e PGID=0 \
    -e UMASK=000 \
    -e NASTOOL_AUTO_UPDATE=false \
    -e NASTOOL_CN_UPDATE=false \
    hsuyelin/nas-tools

**Comment by Llllwood** [comment]
你这个..虽然我不知道你别的问题所在，但是你端口3000:3008，你自己修改过Dockerfile吗

**Comment by hsuyelin** [comment]
-p 3008:3000

docker问题建议自己摸索

**Comment by edu-hui** [comment]
> -p 3008:3000
> 
> docker问题建议自己摸索，这样你需要访问3008端口才行

![image](https://github.com/hsuyelin/nas-tools/assets/54179964/0a46a94f-5ae4-47cd-909d-c6beddf3bba7)
还是有错误

**Comment by edu-hui** [comment]
> -p 3008:3000
> 
> docker问题建议自己摸索，这样你需要访问3008端口才行

麻烦了再看看

**Comment by iovejieba** [comment]
建议 用新配置文件 重新拉容器 在看看 网络环境不理想 尽量都别拉github更新

**Comment by iovejieba** [comment]
否则会遇到各种诡异情况

**Comment by edu-hui** [comment]
直接拉的docker也会有影响么网络,我试看重来
