### ISSUE TITLE
[功能改进]: 

### ISSUE THREAD

**Issue by chris6868** [hsuyelin/nas-tools#217]
### 当前程序版本

3.3.4

### 功能改进

在刮削设置里把图片勾上后，如果tmdb没有返回集的图片就会生成入下图的图片，该电视剧《龙城》，日志里面有显示微信公众号“Tacit0924”，应该代码里能搜出来
![image](https://github.com/hsuyelin/nas-tools/assets/22971922/2d5c10e8-43c9-4e07-a1a8-7811c070aeb5)

**Comment by hsuyelin** [comment]
这个是你下载的影片里的，盲猜你开了ffmpeg-thumb
