### ISSUE TITLE
[错误报告]: V3.3.4 北洋园搜索不出东西。

### ISSUE THREAD

**Issue by HuLuXi** [hsuyelin/nas-tools#218]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

334

### 问题类型

其他问题

### 问题描述

站点资源是有要搜的东西的，然后在该页面也是能搜到的，但是资源搜索就不行，就是没搜到该资源

**Comment by hsuyelin** [comment]
@HuLuXi 咋回事，又给自己关了

**Comment by HuLuXi** [comment]
> @HuLuXi 咋回事，又给自己关了

因为我刚发完，就在日志里看到 是我之前设置了免费种过滤，现在北洋已经不看流量了
