### ISSUE TITLE
[功能改进]: 希望某些地方能够加入快速输入的功能

### ISSUE THREAD

**Issue by bcseputetto** [hsuyelin/nas-tools#219]
### 当前程序版本

3.3.4

### 功能改进

在【设置-媒体库】里【电影】，【电视剧】【动漫】填入一个或多个目录后。
能在 【媒体整理-手动识别-自定义识别】之类的地方，根据选择的类型，能在输出路径那里提示【设置-媒体库】里已经设置好的目录，然后快速选择输入。

**Comment by hsuyelin** [comment]
你设置媒体库后，置空不就可以了么，没明白你的意思

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/ad00154d-51bb-4e67-b5b5-2468ebc75da7)

**Comment by bcseputetto** [comment]
因为我有多个路径，有的时候需要选择第二个或者第三个路径

**Comment by hsuyelin** [comment]
比如说你电影设置了
A/B/电影
C/D/电影
E/F/电影

程序能帮你怎么设置，也只能优先选择第一个路径啊

**Comment by bcseputetto** [comment]
我就是要手动选择，但每次都写路径太麻烦，所以说能不能快速选择输入

**Comment by hsuyelin** [comment]
> 

是选择输入的啊，你指针放到里面不就是自动出来文件夹么

**Comment by hsuyelin** [comment]
https://github.com/hsuyelin/nas-tools/assets/17918063/71453c77-77d4-40c6-8849-4c3d37a790aa

@bcseputetto

**Comment by bcseputetto** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/29139573/e6107b1d-c902-46a4-8288-887c5a748d59)
比如说我设置了这些目录。
![image](https://github.com/hsuyelin/nas-tools/assets/29139573/19955754-10b6-4cdf-b998-0e7a24b45503)
我希望能在这里能快速选择上面设置的目录。
你说的自动出来文件夹，也是一个一个点，那我还不如提前复制好整个路径，输入的时候粘贴进去？
我就是说能直接出现完整的路径候选

**Comment by hsuyelin** [comment]
@bcseputetto 不通用啊，这个是你的诉求，别人的下载路径和媒体路径并不一定在同一个父目录下，像我是直接映射的整个磁盘，因此也不存在跨盘问题，我上面输入的下载路径和我的媒体路径不对应还不是要一级级返回去设置么

**Comment by bcseputetto** [comment]
媒体库设置的路径，不就是最终要转移到的路径吗？
那在输出路径那里能直接快速选择，这个哪里不通用了？

**Comment by bcseputetto** [comment]
不需要能快速填写 输入路径。
只需要能快速填写 输出路径。

**Comment by hsuyelin** [comment]
> 媒体库设置的路径，不就是最终要转移到的路径吗？ 那在输出路径那里能直接快速选择，这个哪里不通用了？

你不能保证其他人跟你的映射是一样的，你的媒体库都在统一个media文件夹下面，别人的可以映射多个media

**Comment by hsuyelin** [comment]
我是映射了多块磁盘，就有多个media文件夹

**Comment by bcseputetto** [comment]
那不是一样在媒体库里设置好，然后在这里快速选择吗？有什么不一样吗？

**Comment by bcseputetto** [comment]
你在输出路径这里可以快速选择的候选
就是你自己在设置 媒体库里面设置好的路径，当然大家都不一样，但这个有什么问题？

**Comment by hsuyelin** [comment]
抽空看看吧

**Comment by bcseputetto** [comment]
宿主机 /NAS1/media 映射到 容器 内 /media1
宿主机 /NAS2/media 映射到 容器内 /media2
那么你在nastool 设置 媒体库里面设置不也是一样 写 /media1，/media2
然后在输出路径那里，能快速选择你已经写好的路径，就是这样，不一样也没有问题。
说白了，就是输出路径那里我想要有一个能快速选择已经写好过的路径而已。而不是每次都要复制粘贴路径，或者要点好几下才能点到输出路径

**Comment by bcseputetto** [comment]
比如我的路径深度，/NAS/media/Movie/电影BDMV/UHD/。如果用点击选择去操作，就需要点五次。
那么如果需要多次手动识别，多次填写这个输出路径，那我肯定是选择直接复制好一份这个路径，每次使用的时候直接粘贴上去更快。
那么能不能在填写输出路径的时候，直接提供我在设置 媒体库 里面已经写好的路径，这样我连复制粘贴都省了

**Comment by yellowstrong** [comment]
感觉这种需求没什么意义，个人色彩比较明显，毕竟极少数人是这样整理影片的

**Comment by jackloves111** [comment]
大兄弟，复制粘贴会不？又没规定要你一定要选择输入，你直接复制粘贴效果一样的

**Comment by bcseputetto** [comment]
> 大兄弟，复制粘贴会不？又没规定要你一定要选择输入，你直接复制粘贴效果一样的
> 
> 快捷键，Ctrl+C Ctrl+V。

我相信你有看我的回复，现在就是复制粘贴

**Comment by bcseputetto** [comment]
之前nastools还是原项目维护的时候的某个版本，媒体整理-手动识别，识别过一次后，只要不要离开手动识别的页面，再次点开自定义识别，还能保留之前输入过的输出路径信息，之后某个版本更新后这个就没了。现在每次都要重新填写一次 输出路径。
比如我一次性下了十部BDMV电影。输入路径我从NAS那边复制过来，然后粘贴进输入路径，然后再复制另外一个路径粘贴进输出路径，反复复制粘贴操作，这个需求就是为了只需要复制粘贴输入路径，输出路径可以快速选择已经设置好的路径

**Comment by bcseputetto** [comment]
而且，nastool的媒体库设置，完全可以拿来作为转移目的路径(输出路径)的候选。大家最终肯定是要转移到这里的。
本来就是很通用的东西，怎么会太个人？而且跟大家怎么映射的又无关，最后在媒体库里面设置什么路径大家肯定都不一样

**Comment by youyifentian** [comment]
## 插楼反馈一下小问题，请大佬看下这种情况是不是有问题，能不能改进下
## 情况演示见视频：

https://github.com/hsuyelin/nas-tools/assets/5012570/8953538a-13f9-4994-b0f5-26004a83b106

## 具体的操作过程：
就是在目录同步里面我选择目录的时候，如果点击次数多的话，文本框里面的路径直接被清空了
就是我虽然选择了路径，并且选的也是有效路径，但是如果我在文本框里面多点几次的话，就会被清空，
因为之前的逻辑是，点击之后会自动展开目录，有时候因为显示的慢，可能会多点几次，但是现在一旦多点了，内容就清空了，就非常容易误操作，得从来，请大佬看下，是不是能改进下
@hsuyelin

**Comment by bcseputetto** [comment]
这个路径清空的问题的确有，我也有遇到，旧版是没有问题的，已经有填写路径地址的输入框再点击就有可能出现清空

**Comment by jackloves111** [comment]
> ## 插楼反馈一下小问题，请大佬看下这种情况是不是有问题，能不能改进下
> ## 情况演示见视频：
>  _2023_09_07_18_36_57_669.mp4 
> ## 具体的操作过程：
> 就是在目录同步里面我选择目录的时候，如果点击次数多的话，文本框里面的路径直接被清空了 就是我虽然选择了路径，并且选的也是有效路径，但是如果我在文本框里面多点几次的话，就会被清空， 因为之前的逻辑是，点击之后会自动展开目录，有时候因为显示的慢，可能会多点几次，但是现在一旦多点了，内容就清空了，就非常容易误操作，得从来，请大佬看下，是不是能改进下 @hsuyelin

可能需要排查一下是否和这个有关？
![9da02e09-9365-4f19-af8e-51e6af32411a](https://github.com/hsuyelin/nas-tools/assets/89971817/993ff632-3ecd-4fc2-a789-68cb8ff2011e)

**Comment by hsuyelin** [comment]
> > ## 插楼反馈一下小问题，请大佬看下这种情况是不是有问题，能不能改进下
> > ## 情况演示见视频：
> > _2023_09_07_18_36_57_669.mp4
> > ## 具体的操作过程：
> > 就是在目录同步里面我选择目录的时候，如果点击次数多的话，文本框里面的路径直接被清空了 就是我虽然选择了路径，并且选的也是有效路径，但是如果我在文本框里面多点几次的话，就会被清空， 因为之前的逻辑是，点击之后会自动展开目录，有时候因为显示的慢，可能会多点几次，但是现在一旦多点了，内容就清空了，就非常容易误操作，得从来，请大佬看下，是不是能改进下 @hsuyelin
> 
> # 可能需要排查一下是否和这个有关？
> ![9da02e09-9365-4f19-af8e-51e6af32411a](https://user-images.githubusercontent.com/89971817/266323390-993ff632-3ecd-4fc2-a789-68cb8ff2011e.png)

已经撤回这个提交了，这个每次都查询硬链接。对于硬链接重度用户会造成过多占用资源卡顿

**Comment by youyifentian** [comment]
> > > ## 插楼反馈一下小问题，请大佬看下这种情况是不是有问题，能不能改进下
> > > ## 情况演示见视频：
> > > _2023_09_07_18_36_57_669.mp4
> > > ## 具体的操作过程：
> > > 就是在目录同步里面我选择目录的时候，如果点击次数多的话，文本框里面的路径直接被清空了 就是我虽然选择了路径，并且选的也是有效路径，但是如果我在文本框里面多点几次的话，就会被清空， 因为之前的逻辑是，点击之后会自动展开目录，有时候因为显示的慢，可能会多点几次，但是现在一旦多点了，内容就清空了，就非常容易误操作，得从来，请大佬看下，是不是能改进下 @hsuyelin
> > 
> > 
> > # 可能需要排查一下是否和这个有关？
> > ![9da02e09-9365-4f19-af8e-51e6af32411a](https://user-images.githubusercontent.com/89971817/266323390-993ff632-3ecd-4fc2-a789-68cb8ff2011e.png)
> 
> 已经撤回这个提交了，这个每次都查询硬链接。对于硬链接重度用户会造成过多占用资源卡顿

目前这个非常nice，速度比上个版本感觉快了10倍，切换菜单都是秒开，之前要响应好久

**Comment by bcseputetto** [comment]
> @bcseputetto #300 已合入mastr， 已在路径选择时实现特殊目录的快捷操作，待打入新版本后即可更新，如使用有问题请反馈 ![4101695038186_ pic](https://user-images.githubusercontent.com/7424276/268813230-ef5f5fb7-8dd8-43cd-a8fa-2571ad9061cc.jpg) ![4111695038187_ pic](https://user-images.githubusercontent.com/7424276/268813240-d0b97c12-06cd-4be1-9595-9f61f11c4483.jpg)

我更新了，试了一下非常不错，现在只需要点两次(一次媒体，一次目录) 就可以快速输入了
