### ISSUE TITLE
[错误报告]: 基础设置中开启“默认搜索豆瓣资源”选项，使用微信交互下载资源时，微信中的资源图片不显示。

### ISSUE THREAD

**Issue by LoSiTeE** [hsuyelin/nas-tools#220]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.4

### 问题类型

主程序运行问题

### 问题描述

隐约好像看到有人提过，但是翻了issue没翻到，所以提一下。
![Screenshot_20230907_141612_com tencent mm](https://github.com/hsuyelin/nas-tools/assets/125968595/39724903-6823-4088-8c2b-d6bb93ae5e1f)

**Comment by hsuyelin** [comment]
图片来自己TMDB，你TMDB联不通
