### ISSUE TITLE
[错误报告]: 群晖中docker配置启动秒报错

### ISSUE THREAD

**Issue by edu-hui** [hsuyelin/nas-tools#221]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V3.3.4

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/54179964/cd895446-31d5-43e9-a93d-193f8dc4febb)
尝试了很多次重新拉镜像和重新映射新文件夹都不行。（媒体文件夹是挂载到服务器上的）

**Comment by hsuyelin** [comment]
配置文件怎么写的

**Comment by edu-hui** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/54179964/6939039b-6d11-45b9-a3d7-cad7f38177ea)
改了这个地方之外其他都没有动过，全新启动

**Comment by hsuyelin** [comment]
你直接用的群晖自带的docker不是通过compose创建的是吧
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/6eae939d-5de6-4c77-a0f1-122121a6a2e9)
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/7a23f781-7d61-4258-98fa-ba3bfa55063d)
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/951e7b21-85b1-4c06-83c0-0393f9d7ec43)
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/ecf7cdac-2ad5-4cb8-8a12-56e3ef77777a)

这几个配置给我看看，存储空间那个地方不要打🐴

**Comment by edu-hui** [comment]
![1694071883(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/6684a71b-dc85-4942-a4cb-30cffb55f1f4)
![1694071873(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/46f741e1-fc21-4141-ab89-a79de9a3f2f6)
![1694071860(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/94c22021-c87d-456f-a912-45f23eb8cf49)

**Comment by hsuyelin** [comment]
你这个
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/020285e7-9ad2-4567-bc05-0220c5931c86)
是不是文件特别多

**Comment by edu-hui** [comment]
文件比较多
[hsuyelin-nas-tools1.csv](https://github.com/hsuyelin/nas-tools/files/12546177/hsuyelin-nas-tools1.csv)

**Comment by hsuyelin** [comment]
> 文件比较多 [hsuyelin-nas-tools1.csv](https://github.com/hsuyelin/nas-tools/files/12546177/hsuyelin-nas-tools1.csv)

能否帮忙使用含有较少文件的文件夹来映射，来看看是否可以正常启动，谢谢 ~

**Comment by edu-hui** [comment]
好的

**Comment by edu-hui** [comment]
![1694073319(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/2cbf0e2a-e944-4b7b-9d5a-dc6878bdf7a2)
![1694073337(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/9a2da3b2-4b3c-4832-bfdd-d90c2a5b79ad)
![1694073356(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/06344074-ce4d-434f-8efe-e8769a979483)
![1694073372(1)](https://github.com/hsuyelin/nas-tools/assets/54179964/447b5ea9-55f4-4b2e-abb5-bccf725c8830)

**Comment by edu-hui** [comment]
还是不可以，看完我删除一下图片，麻烦说明一下，看好了

**Comment by hsuyelin** [comment]
> 

好了，我大概知道了

**Comment by edu-hui** [comment]
大概是啥问题，很是困扰

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/005cc882-f816-45db-9734-1188741cfc3a)

1. 先输入 cd /

2. 在输入   echo 1000000 > /proc/sys/fs/inotify/max_user_watches ，如果提示权限问题就输入 sudo echo 1000000 > /proc/sys/fs/inotify/max_user_watches 然后输入密码

3. 停止容器，重新启动

**Comment by hsuyelin** [comment]
你这个要监控的文件太多了，导致超过文件系统限制了，这个命令是修改限制

**Comment by edu-hui** [comment]
好的谢谢

**Comment by edu-hui** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/54179964/beb7129c-93ac-4ec2-ab51-430ce28c8297)
都显示是只读文件

**Comment by edu-hui** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/54179964/5af9a519-ac4e-4922-b707-fbb271a607f4)

**Comment by hsuyelin** [comment]
-w @edu-hui

**Comment by edu-hui** [comment]
sudo sysctl -w fs.inotify.max_user_watches=100000  这个有什么问题么

**Comment by hsuyelin** [comment]
> sudo sysctl -w fs.inotify.max_user_watches=100000 这个有什么问题么，我直接复制的。你这个UID GID UMASK和我设置一样么

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/b20666c7-f43f-4b8c-8f65-3d63d0c288c9)

**Comment by edu-hui** [comment]
是一样的

**Comment by jackloves111** [comment]
镜像重新拉一下，配置文件和媒体库都空白文件夹，重新装试下。你先排查镜像依赖问题和配置文件的问题

**Comment by edu-hui** [comment]
要是重新拉就好了，不是这个权限什么的问题，应该是[hsuyelin](https://github.com/hsuyelin)说的数量的问题

**Comment by edu-hui** [comment]
解决办法：宿主机执行：
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf

**Comment by edu-hui** [comment]
echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf

**Comment by edu-hui** [comment]
sudo sysctl -p
执行完三条之后重启解决问题，本问题关闭，麻烦大佬排查了

**Comment by DDSDerek** [comment]
```bash
docker run -d \
  --sysctl fs.inotify.max_user_watches=524288 \
  --sysctl fs.inotify.max_user_instances=524288
```
```yaml
version: '3'
services:
  myservice:
    image: myimage
    sysctls:
      - fs.inotify.max_user_watches=524288
      - fs.inotify.max_user_instances=524288
```
理论上启动容器添加这个参数也可以解决（大概？）
我了解的是容器内是没有权限设置的，但是可以容器启动前设置好
@hsuyelin
