### ISSUE TITLE
[功能改进]: 是否有计划加入自动删种的插件

### ISSUE THREAD

**Issue by sebastian0619** [hsuyelin/nas-tools#222]
### 当前程序版本

3.3.4

### 功能改进

是否有计划加入自动删种的插件？

之前是nastool还是在原作者的新项目那有看到这个插件，还挺好用。

在此之前一直都是通过autoremove-torrent来弄，但这个作者也不更新了。

最好是能够支持根据下载器选择不同的策略~ 这样又便于区分BT还是PT下载>.<

**Comment by hsuyelin** [comment]
抽空来看看
