### ISSUE TITLE
[错误报告]: 每次直接关闭网页，控制台就会报错导致下次再打开之前的日志无法显示

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#223]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.4

### 问题类型

主程序运行问题

### 问题描述

![iShot_2023-09-07_16 32 03](https://github.com/hsuyelin/nas-tools/assets/34505611/e36ae9ac-b113-4032-9c29-bff09bddac7a)

![iShot_2023-09-07_16 39 38](https://github.com/hsuyelin/nas-tools/assets/34505611/f80e3cb8-0b4e-4a95-a5b6-8669c6fdda42)

**Comment by hsuyelin** [comment]
这个是历史bug，最近也在看，但是不敢乱改，最近在测试，你试试

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/6b3933a0-bad3-4672-9667-de107cf33734)

FLASK_APP=XXXXXXX/main.py 加到环境变量

**Comment by yellowstrong** [comment]
牛啊，我还以为没人注意到这个点呢，我观察了好久才发现这个问题

**Comment by hsuyelin** [comment]
不是特别影响啦，我本地测试测试，你刚好也帮忙测试下

**Comment by yellowstrong** [comment]
本地测试确实没问题了，是不是有办法搞到docker里面去，加一个可选项，线上测一下看看
![iShot_2023-09-07_17 03 18](https://github.com/hsuyelin/nas-tools/assets/34505611/545f70b8-48de-4b96-bbf3-0edfa50c0a81)

**Comment by yellowstrong** [comment]
> 你这是docker日志还是软件里的日志

第一张图是unraid日志，第二张图是本地代码运行日志

**Comment by hsuyelin** [comment]
> 本地测试确实没问题了，是不是有办法搞到docker里面去，加一个可选项，线上测一下看看 ![iShot_2023-09-07_17 03 18](https://user-images.githubusercontent.com/34505611/266265418-545f70b8-48de-4b96-bbf3-0edfa50c0a81.png)

搞到docker我要测试其实很简单加一个环境变量就可以了，这个内部开关没用，我之前就注意到了，因为没啥太大影响，一直没集成，这些人更新太快了，刚发布就更新，万一出问题还要修，就一直没动

**Comment by jackloves111** [comment]
> > 本地测试确实没问题了，是不是有办法搞到docker里面去，加一个可选项，线上测一下看看 ![iShot_2023-09-07_17 03 18](https://user-images.githubusercontent.com/34505611/266265418-545f70b8-48de-4b96-bbf3-0edfa50c0a81.png)
> 
> 搞到docker我要测试其实很简单加一个环境变量就可以了，这个内部开关没用，我之前就注意到了，因为没啥太大影响，一直没集成，这些人更新太快了，刚发布就更新，万一出问题还要修，就一直没动

上班是真的无聊
