### ISSUE TITLE
[错误报告]: 历史记录中返回上一级目录卡死

### ISSUE THREAD

**Issue by colorblank** [hsuyelin/nas-tools#225]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.4

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/16894837/bc5c9431-227c-4779-b66c-b07ef6f0463c)
从历史目录中返回上一级目录中会卡死。
类似问题： 从文件管理中展开多个目录也会卡死。
另外，从后台看cpu资源被find命令占满了，怀疑是读取文件的方式有问题。

**Comment by hsuyelin** [comment]
收到

**Comment by hsuyelin** [comment]
下个版本修复
