### ISSUE TITLE
[错误报告]: 电视剧的季识别错误

### ISSUE THREAD

**Issue by colorblank** [hsuyelin/nas-tools#226]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.4

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/16894837/69ae1088-2687-44a0-a45d-8e2875f49c44)
好几个电视剧的季识别错误。
上级目录样例：血族S01-S04.The.Strain.2014-2017.1080p.Blu-ray.x265.AC3￡cXcY@FRDS/血族S03.The.Strain.2016.1080p.Blu-ray.x265.AC3￡cXcY@FRDS

**Comment by hsuyelin** [comment]
你文件夹就是S03啊

**Comment by colorblank** [comment]
> 你文件夹就是S03啊

文件夹是S03，但识别结果是S04（见图片）。准确地说，不管是S01,S02,S03的文件夹下的文件，季都被识别成最后一季，S04。
其他类似的目录也是，比如大群有三季，文件夹下所有的视频文件都被识别为第3季了。

**Comment by hsuyelin** [comment]
@colorblank 昨晚兼容了，下个版本你再试试
