### ISSUE TITLE
[错误报告]: 请问BDMV原盘是无法硬链接吗？

### ISSUE THREAD

**Issue by bg1258** [hsuyelin/nas-tools#228]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.4

### 问题类型

其他问题

### 问题描述

下载蓝光原盘电影的时候，源目录会存在BDMV和CERTIFICATE文件夹，两个文件夹下面又包含多个文件和文件夹，这个时候目录同步硬链接的文件不完整，显示入库失败，并导致电影无法播放，请问有什么办法支持这种多文件夹的原盘电影硬链接吗？单个电影文件如ios、mkv等是可以同步成功并播放的。
![image](https://github.com/hsuyelin/nas-tools/assets/61741719/13e6ef7a-5372-4793-8034-9028c457ef8e)

### 发生问题时系统日志和配置文件

```bash
无
```

**Comment by hsuyelin** [comment]
不支持BD圆盘

**Comment by yellowstrong** [comment]
> 下载蓝光原盘电影的时候，源目录会存在BDMV和CERTIFICATE文件夹，两个文件夹下面又包含多个文件和文件夹，这个时候目录同步硬链接的文件不完整，显示入库失败，并导致电影无法播放，请问有什么办法支持这种多文件夹的原盘电影硬链接吗？单个电影文件如ios、mkv等是可以同步成功并播放的。

我也是基本都下载remux，有的remux也是BDMV形式的，比如天空的老种有很多这样的，但是按道理nt本来就是支持的，我用nt转过很多BD原盘都没问题。

**Comment by bg1258** [comment]
不太清楚，我是下的岛的BD，不管自动或者手动都显示入库失败，虽然能把BD文件夹转过去，但是第二个CER文件夹就转不了了
