### ISSUE TITLE
[功能改进]: 可否给nt里面的cookiecloud插件添加黑名单或者白名单

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#229]
### 当前程序版本

v3.3.4

### 参考资料

最主要的是现在nt里面新版的cookiecloud插件会自动创建站点了，如果我一组cookiecloud里面有不需要给nt的站点的话就没法不让他创建，就比如我现在有10个站，装了nt和mp，我想nt里面5个，mp里面5个，如果同步的时候如果可以对cookiecloud插件设置白名单，那nt和mp就可以共用一组cookiecloud的key和pwd了，这就不需要额外的设置了，因为毕竟一个浏览器插件只能同时设置一组key和pwd

**Comment by hsuyelin** [comment]
等有空加

**Comment by youyifentian** [comment]
> @youyifentian 你这个可以了[e8081f5](https://github.com/hsuyelin/nas-tools/pull/263/commits/e8081f518e5f46e9a8aaca709ea0f4c083bd5776)

感谢大佬!
