### ISSUE TITLE
[功能改进]: 增强识别v2

### ISSUE THREAD

**Issue by chris6868** [hsuyelin/nas-tools#230]
### 当前程序版本

3.3.4

### 功能改进

可以在增强识别v2里加入“第011话”、“第011集”这种格式的识别吗，还有就是文件整理里面的“转移”“自定义识别”在选择路径后在点一下输入框会清空选择的路径

**Comment by chris6868** [comment]
文件管理选择目录转移成功后会恢复到下载目录，而不是刚刚选择的目录

**Comment by hsuyelin** [comment]
第一个3.3.5已经支持了，第二个不懂你说的什么意思

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/49bf9ffd-6db2-4ce6-a8f5-6798ad0ed6ca)
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/740f3c2d-e632-49a5-b000-fdbe7bdd5449)

**Comment by Wangsc1** [comment]
开启v2识别，标题里面没有具体Exx第几集的，但是副标题里面有第几集的不能识别![IMG_20230908_140312.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/351628f5-48e1-4c65-98c0-e216bbb687cb)

关闭v2识别是可以识别的![IMG_20230908_140224.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/964e5564-4b98-48d6-9204-76da14c236c0)

**Comment by hsuyelin** [comment]
> 开启v2识别，标题里面没有具体Exx第几集的，但是副标题里面有第几集的不能识别![IMG_20230908_140312.jpg](https://user-images.githubusercontent.com/26079238/266516720-351628f5-48e1-4c65-98c0-e216bbb687cb.jpg)
> 
> 关闭v2识别是可以识别的![IMG_20230908_140224.jpg](https://user-images.githubusercontent.com/26079238/266516770-964e5564-4b98-48d6-9204-76da14c236c0.jpg)
> 
> 最新3.5.5 [81190bc](https://github.com/hsuyelin/nas-tools/commit/81190bca26913c085c2deea8bc1f8ca34947ede1)

抽空优化下

**Comment by hsuyelin** [comment]
@Wangsc1 原版识别会漏很多搜索结果

**Comment by Wangsc1** [comment]
还有开启v2后瓷器的官种(HDCTV)还是会归类到一个CTV类别![IMG_20230908_140939.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/62b87bf7-f024-448b-8a6f-e060340cf5db)

**Comment by chris6868** [comment]
> 第一个3.3.5已经支持了，第二个不懂你说的什么意思

文件整理里面的“转移”“自定义识别”在选择路径后在点一下输入框会清空选择的路径，这个的操作方式是：媒体整理-手动识别-自定义识别，然后在输入路径那选择一个路径，选择好后输入框下面选择路径的弹窗关闭后再次点击一下输入路径的输入框就会清空该输入框



文件管理选择目录转移成功后会恢复到下载目录，而不是刚刚选择的目录，这个的操作方式是：媒体整理-文件管理，进入该界面目录默认是下载目录，这个时候选择下载目录以外的目录，在右边出现的视频列表中点击转移，转移成功后目录恢复成下载目录，而不是刚刚选择的目录

**Comment by hsuyelin** [comment]
@chris6868 和有个人提的一样，抽空增加可以从媒体库选择

**Comment by hsuyelin** [comment]
> 还有开启v2后瓷器的官种(HDCTV)还是会归类到一个CTV类别![IMG_20230908_140939.jpg](https://user-images.githubusercontent.com/26079238/266517749-62b87bf7-f024-448b-8a6f-e060340cf5db.jpg)

去 [这里](https://github.com/hsuyelin/nas-tools/discussions/186 ) 反馈，HDCTV可能是把HD当做高清的识别了，我可以在下个版本中解决，你可以使用自定义识别词解决
