### ISSUE TITLE
[错误报告]:HANHAN刷流无法推送种子

### ISSUE THREAD

**Issue by zybzhong** [hsuyelin/nas-tools#234]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.5

### 问题类型

其他问题

### 问题描述

如下图所示，启动刷流可以获取数据，满足要求也不会推送下载。HANHAN的UI未更新前是正常的。
![image](https://github.com/hsuyelin/nas-tools/assets/48077186/e4859137-e883-43a1-8bc7-4fcb9bb0b111)

### 发生问题时系统日志和配置文件

```bash
20:03:11		
共搜索到 1 个有效资源
20:05:00		
开始站点 hanhan 的刷流任务：憨憨...
20:05:02		
hanhan RSS获取数据：8
20:05:02		
任务 憨憨 本次添加了 0 个下载
20:06:56		
1 个刷流服务正常启动
```

**Comment by hsuyelin** [comment]
憨憨rss不支持刷流，是憨憨不支持

**Comment by chuxinshuo** [comment]
> 憨憨rss不支持刷流，是憨憨不支持

请问 vertex 为什么可以支持呢？就是vertex配置太麻烦了...

**Comment by zybzhong** [comment]
MoviePilot)也支持，有点奇怪。
![image](https://github.com/hsuyelin/nas-tools/assets/48077186/b5745ad1-fcd7-4634-95ec-307ba7af8d29)

**Comment by iovejieba** [comment]
> vertex

想主力刷流 就跑个vertex吧.... 把nt 当整理 就没这么多纠结问题了

**Comment by Llllwood** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/144126126/8f2ae812-5efe-44e8-b44e-fcc7a482be72)
我觉得吧，不应该什么都算进BUG里面，是不是你自己选种设置问题

**Comment by chuxinshuo** [comment]
> ![image](https://user-images.githubusercontent.com/144126126/266791598-8f2ae812-5efe-44e8-b44e-fcc7a482be72.png)
> 我觉得吧，不应该什么都算进BUG里面，是不是你自己选种设置问题

这是ns刷的吗

**Comment by chuxinshuo** [comment]
> > vertex
> 
> 想主力刷流 就跑个vertex吧.... 把nt 当整理 就没这么多纠结问题了

vt不会js..不会设置每个站点的保种容量，同时刷几个站的时候有点难受

**Comment by Llllwood** [comment]
> > ![图像](https://user-images.githubusercontent.com/144126126/266791598-8f2ae812-5efe-44e8-b44e-fcc7a482be72.png)我觉得吧，不应该什么都算进BUG里面，是不是你自己选种设置问题
> 
> 这是ns刷的吗

nastools [v3.3.4 d5bb989]
