### ISSUE TITLE
[错误报告]: PIKPAK 離線下載不成功

### ISSUE THREAD

**Issue by skfunghk** [hsuyelin/nas-tools#237]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.3.5 9ce8007

### 问题类型

插件问题

### 问题描述

無法用PIKPAK 下載

### 发生问题时系统日志和配置文件

```bash
14:04:16 | Downloader | 下载器 Pikpak 添加任务：[GJ.Y] 伊甸星原 第二季 / Edens Zero 2nd Season - 47 (CR 1920x1080 AVC AAC MKV)，目录：/Anime，Url：https://mikanani.me/Download/20230903/bd4f8783d8a2012b117e0346b97f4e64e373ac66.torrent
-- | -- | --
14:04:17 | System | PikPak 添加离线下载任务失败: Object of type bytes is not JSON serializable
14:04:17 | RssChecker | 添加下载任务 伊甸星原 (2021) 失败：下载器 Pikpak 添加下载任务失败，请检查下载任务是否已存在
```

**Comment by hsuyelin** [comment]
不支持种子下载，仅支持磁力下载，你这个是种子换个其他的资源重试
