### ISSUE TITLE
[错误报告]: 用豆瓣搜索资源，图片无法显示。以及官方默认IMDB的地址下，IMDB图片不显示问题。

### ISSUE THREAD

**Issue by windn0** [hsuyelin/nas-tools#238]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.5 9ce8007

### 问题类型

主程序运行问题

### 【1】 用豆瓣搜索资源的时候，无法显示图片。
![image](https://github.com/hsuyelin/nas-tools/assets/52818798/3d0a6466-84f0-46f4-8ded-ee8adfcca57d)
如图，正常搜索一个资源出来的结果是如右手边那张（无法显示资源），将图片资源的地址从qrmob3 修改为img1 后就能显示了。
注：首页的豆瓣的图片是可以正常显示的，只有搜索资源后的图片无法显示，f12后发现，首页的图片资源的地址是：img1.doubanio.com ，而豆瓣搜索资源的图片地址是：qnmob3.doubanio.com
应该是个bug，麻烦修复下。
### 【2】IDMB 的图片无法正常显示，IDMB的地址是通的（在nas配置了clash的http代理下），但是无法正常显示图片，需要更换成 https://static-mdb.v.geilijiasu.com/ 才能显示。
![image](https://github.com/hsuyelin/nas-tools/assets/52818798/f2f8efde-72c9-4cd9-b64d-f0a0ad51dfee)
但是无法联通：
![image](https://github.com/hsuyelin/nas-tools/assets/52818798/dc6c5c55-0d88-4859-ae0d-3c1a98442c45)
注：关掉代理后，我发现我本地的网络是无法访问官方的图片代理的，不清楚是否是这个原因。

**Comment by hsuyelin** [comment]
抽空看下

**Comment by hsuyelin** [comment]
豆瓣已修复，IMDB确认是你科学的问题
