### ISSUE TITLE
[错误报告]: 站点标签为空时会自动创建None标签，能不能优化一下

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#239]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.5

### 问题类型

主程序运行问题

### 问题描述

![QQ截图20230909153221](https://github.com/hsuyelin/nas-tools/assets/5012570/acf9d8eb-7e1a-4443-9669-f6bf76e22c56)

**Comment by youyifentian** [comment]
而且对于从jackett或者Prowlarr导入的站点来说，也没法添加站点标签啊，这样也会多个None标签，就很突兀

**Comment by jackloves111** [comment]
也可以找下这个大佬改一下https://github.com/hsuyelin/nas-tools/pull/232

**Comment by youyifentian** [comment]
> 也可以找下这个大佬改一下#232

这个怎么@他啊，这没有别的意思，增加功能是好事情，可以有更多个性化设置，但还是希望兼容性更好一下，可以优化一下

**Comment by 9606** [comment]
我来了我来了
抱歉，自测的时候没有覆盖到jackett或者Prowlarr，https://github.com/hsuyelin/nas-tools/pull/231，这个pr预计会修复这个bug

**Comment by 9606** [comment]
@youyifentian 看下你github绑定的gmail邮箱，我再和你确认下问题，看看上面说那个pr有没有解决问题
