### ISSUE TITLE
内置软件无法连接

### ISSUE THREAD

**Issue by lwd333** [hsuyelin/nas-tools#240]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.3.5 9ce8007

### 问题类型

Docker或运行环境问题

### 问题描述

使用docker新安装的nastool，emby 、cookie cloud、qBittorrent等内置软件无法链接，之前使用正常，配置准确。

### 发生问题时系统日志和配置文件

```bash
16:20:11		
Library/SelectableMediaFolders 未获取到返回数据
16:20:32		
Users 未获取到返回数据
16:20:52		
System/Info 未获取到返回数据
16:21:12		
Items/Counts 未获取到返回数据
16:21:32		
Users/Query 未获取到返回数据
16:21:52		
System/ActivityLog/Entries 未获取到返回数据
16:22:12		
User/Views 未获取到返回数据
16:22:32		
Users/Items/Resume 未获取到返回数据
16:22:52		
Users/Items/Latest 未获取到返回数据
16:26:15		
连接出错：Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='192.168.2.2', port=8085): Max retries exceeded with url: /api/v2/auth/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5a6ac95b70>, 'Connection to 192.168.2.2 timed out. (connect timeout=15)'))"))
16:26:15		
下载器连接测试失败
16:27:34		
CookieCloud同步 - CookieCloud请求失败，请检查服务器地址、用户KEY及加密密码是否正确
```

**Comment by lwd333** [comment]
![16E27EA3-A2AD-42f6-B704-223532E4FBE1](https://github.com/hsuyelin/nas-tools/assets/130337710/47c37e8e-7708-40f7-91c1-648aaa4e7798)

**Comment by iovejieba** [comment]
本地网络环境问题 有可能桥接抽风  有可能host抽风

**Comment by lwd333** [comment]
> 

有解决办法么

**Comment by hsuyelin** [comment]
本地网络问题，检查自己的网络
