### ISSUE TITLE
站点仿真开启的时候，站点访问失败

### ISSUE THREAD

**Issue by 9606** [hsuyelin/nas-tools#244]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版本

### 问题类型

主程序运行问题

### 问题描述

开启仿真之后，测试站点的时候报错：
Message: unknown error: cannot connect to chrome at 127.0.0.1:35467 from chrome not reachable
也无法签到
我想知道是不是个例

**Comment by hsuyelin** [comment]
详细日志看下

**Comment by 9606** [comment]
这是签到的时候的日志：

nas-tools  | 2023-09-10 21:59:47,676    INFO: 【Plugin】站点自动签到 - 签到服务启动，立即运行一次
nas-tools  | 2023-09-10 21:59:47,684    INFO: 【Plugin】站点自动签到 - 定时签到服务启动，周期：0 8,20 * * *
nas-tools  | 2023-09-10 21:59:47,685    DEBUG: 生效插件配置：AutoSignIn
nas-tools  | 2023-09-10 21:59:50,680    INFO: 【Plugin】站点自动签到 - 今日 2023-09-10 已签到，开始重签重试站点、特殊站点、未签站点
nas-tools  | 2023-09-10 21:59:50,680    INFO: 【Plugin】站点自动签到 - 开始执行签到任务
nas-tools  | 2023-09-10 21:59:50,682    INFO: 【Plugin】站点自动签到 - 开始站点仿真签到：我堡
nas-tools  | 2023-09-10 22:00:21,222    WARNING: 【Plugin】站点自动签到 - 我堡 无法打开网站


测试站点的时候的日志就上面那句有效信息，我定位了半天也没头绪，我是威联通

**Comment by 9606** [comment]
@hsuyelin 你用仿真是没问题的对吧

**Comment by 9606** [comment]
我堡那个cf确实等的比较久，我打算重新适配一下签到，但是目前就是用仿真连通性都有问题，就很难受

**Comment by hsuyelin** [comment]
> @hsuyelin 你用仿真是没问题的对吧

没问题啊。我签到都好用的，大部分人这个倒也没问题，感觉和科学有关系？

**Comment by TonyLiooo** [comment]
> 这是签到的时候的日志：
> 
> nas-tools | 2023-09-10 21:59:47,676 INFO: 【Plugin】站点自动签到 - 签到服务启动，立即运行一次 nas-tools | 2023-09-10 21:59:47,684 INFO: 【Plugin】站点自动签到 - 定时签到服务启动，周期：0 8,20 * * * nas-tools | 2023-09-10 21:59:47,685 DEBUG: 生效插件配置：AutoSignIn nas-tools | 2023-09-10 21:59:50,680 INFO: 【Plugin】站点自动签到 - 今日 2023-09-10 已签到，开始重签重试站点、特殊站点、未签站点 nas-tools | 2023-09-10 21:59:50,680 INFO: 【Plugin】站点自动签到 - 开始执行签到任务 nas-tools | 2023-09-10 21:59:50,682 INFO: 【Plugin】站点自动签到 - 开始站点仿真签到：我堡 nas-tools | 2023-09-10 22:00:21,222 WARNING: 【Plugin】站点自动签到 - 我堡 无法打开网站
> 
> 测试站点的时候的日志就上面那句有效信息，我定位了半天也没头绪，我是威联通

威联通可以试试浏览器能不能访问，我这边重启nastool之后有时也要重启科学才能正常·访问
