### ISSUE TITLE
[错误报告]: 憨憨搜索位置错误

### ISSUE THREAD

**Issue by 8aby-dudu** [hsuyelin/nas-tools#245]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.5

### 问题类型

主程序运行问题

### 问题描述

搜索时，从日志发送请求的链接进去，发现憨憨站点是在“简介”里面搜索，应从“标题”处搜索，导致搜索内容不全。

程序搜简介（2个结果）：

![QQ图片20230910153239](https://github.com/hsuyelin/nas-tools/assets/125348082/51b55695-5037-4d9a-9a7e-82875c0d420a)

手动搜标题时（4个结果）：

![QQ图片20230910153457](https://github.com/hsuyelin/nas-tools/assets/125348082/e0c7c401-13d3-4f1c-900d-6b4f5b622209)

**Comment by caneman** [comment]
改一下站点索引里面的 search - params - search_area的值就可以了，忘记改成0还是4了

**Comment by hsuyelin** [comment]
改成0了

**Comment by Minecraft-Cube** [comment]
> 改一下站点索引里面的 search - params - search_area的值就可以了，忘记改成0还是4了

请问一下，站点索引这个在哪找啊？我没有在菜单栏里找到
