### ISSUE TITLE
[错误报告]: 搜索电影会匹配成电视剧导致搜索无结果

### ISSUE THREAD

**Issue by bg1258** [hsuyelin/nas-tools#247]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.4

### 问题类型

其他问题

### 问题描述

我在搜索变形金刚1的时候反馈无数据，然后看了一下日志，发现好像把他认成是电视剧了，但是我去TMDB上搜索变形金刚，分类还是电影，这是什么情况呢？
<img width="1280" alt="42834fad9c05d4b29811d6e8f18f552" src="https://github.com/hsuyelin/nas-tools/assets/61741719/23ccb7bf-9761-4899-9f38-f171ae106fb7">
<img width="861" alt="1b8f13c53718587b8235d70086f41c8" src="https://github.com/hsuyelin/nas-tools/assets/61741719/8f0d84af-8595-46a3-9cf6-5db4e7741d8c">
<img width="1280" alt="a341e142f0f0f841f0d3bf5e4fbd61c" src="https://github.com/hsuyelin/nas-tools/assets/61741719/5cea1def-1439-4fa3-94e7-fc39e8037e76">

**Comment by hsuyelin** [comment]
更新到3.3.5再试试

**Comment by bg1258** [comment]
更新后还是不行，都被过滤掉了，搜索站点有馒头、岛、观众
<img width="1280" alt="9911a274a4fb6ae247185e3f7b75d6e" src="https://github.com/hsuyelin/nas-tools/assets/61741719/8bddddbc-2d77-4c21-a101-10904c3cd86c">
<img width="1280" alt="3b17e3930c260cd491a22959770931f" src="https://github.com/hsuyelin/nas-tools/assets/61741719/1797695f-c07e-4bd8-8e78-575f87239dfc">

**Comment by bg1258** [comment]
开启V2搜索可以了
