### ISSUE TITLE
[错误报告]: 搜索结果显示

### ISSUE THREAD

**Issue by Wangsc1** [hsuyelin/nas-tools#248]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.6 fe1b508

### 问题类型

其他问题

### 问题描述

目前可以识别到副标题中的集数了，但是完结季的后面又显示Exx集了![IMG_20230911_095137.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/3afd7aa7-46c4-4e24-8da7-946e529147b4)

**Comment by hsuyelin** [comment]
多测测，有问题我一次性修复

**Comment by Wangsc1** [comment]
> 多测测，有问题我一次性修复

没更之前是正常的，应该是最新的识别副标题第几集功能引入的bug吧，像这个第8集和全8集或8集全就全部归类到S01E08了，区分一下“第”和“全”就好了吧![IMG_20230911_110924.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/92340ac9-b875-4543-8c18-afeb9f4f805d)

**Comment by Wangsc1** [comment]
> 多测测，有问题我一次性修复

还有副标题中如果是第xx集-第xx集的话也不能识别
这是不开启v2的![IMG_20230911_121634.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/08ec0ac2-4641-48c3-9175-79cd53f3b7ec)

这是开启v2的![IMG_20230911_121507.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/23fa2611-95c4-4261-911a-89bc7dba933a)

**Comment by hsuyelin** [comment]
第20-21集这种格式，我记得兼容了啊，你版本是最新的么

**Comment by hsuyelin** [comment]
<img width="902" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/e2ce96c7-3c62-4b08-8249-c88eb1abe192">

你在确认下版本对不对把

**Comment by hsuyelin** [comment]
我知道了，瓷器这个主标题连季信息（S01）都没有，因此不去解析副标题的集信息

**Comment by hsuyelin** [comment]
瓷器方便的话，来个💊

**Comment by jackloves111** [comment]
> 瓷器方便的话，来个💊

差8万魔力，得有人赞助一下魔力才行

**Comment by Wangsc1** [comment]
> 瓷器方便的话，来个💊

纯盒子玩家发不了邀😂

**Comment by jackloves111** [comment]
> > 瓷器方便的话，来个💊
> 
> 纯盒子玩家发不了邀😂

@Wangsc1 8万魔有没有，给个魔，我能发一个

**Comment by Wangsc1** [comment]
> > > 瓷器方便的话，来个💊
> > 
> > 纯盒子玩家发不了邀😂
> 
> @Wangsc1 10万魔有没有，给个魔，我能发一个，有手续费，所以要高一点，后面有了可以还你

不够😂

**Comment by hsuyelin** [comment]
没事，主要为了适配站点，每个站点的命名风格、rss都不太一样

**Comment by hsuyelin** [comment]
已修复

**Comment by Wangsc1** [comment]
> 已修复

现在全集显示S01 Exx-Exx，这样也没啥问题![IMG_20230912_085520.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/67b1cded-3c32-42aa-ae2c-00cc1303f066)

但是这样的显示会导致这个全集的归类会在最底下，不会像S01这样的在最上面![IMG_20230912_085620.jpg](https://github.com/hsuyelin/nas-tools/assets/26079238/2e23821a-0200-4bbc-a7e6-2c22a9c9142c)
