### ISSUE TITLE
关于自定义网站功能建议

### ISSUE THREAD

**Issue by EdisonCh4n** [hsuyelin/nas-tools#25]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.9.3
>
> 环境: docker of synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？  

大佬之前那个自定义模板的插件可以将jackett的网站直接加入到内置索引器中，集成后需要类似的网站的json才能搜索，我有尝试过修改json，但是一些网站还是不能显示，如果能直接将jackett内置到内置索引器中就可以直接显示jackett添加的网站，所以可不可以将jackett的插件直接添加到内置索引器中，感觉这样更方便。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
这个是我使用官方3.0版本的nastool加上之前修改脚本的 效果。
![QQ图片20230803190507](https://github.com/hsuyelin/nas-tools/assets/126320405/d90bc3f3-d704-45c4-a549-d3ee25df01b7)

**Comment by iovejieba** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: 3.2.9.3
> > 环境: docker of synology
> 
> ## 你想要新增或者改进什么功能？
> > 你想要新增或者改进什么功能？
> 
> 大佬之前那个自定义模板的插件可以将jackett的网站直接加入到内置索引器中，集成后需要类似的网站的json才能搜索，我有尝试过修改json，但是一些网站还是不能显示，如果能直接将jackett内置到内置索引器中就可以直接显示jackett添加的网站，所以可不可以将jackett的插件直接添加到内置索引器中，感觉这样更方便。
> 
> ## 这个功能有什么可以参考的资料吗？
> > 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
> > 这个是我使用官方3.0版本的nastool加上之前修改脚本的 效果。
> > ![QQ图片20230803190507](https://user-images.githubusercontent.com/126320405/258092875-d90bc3f3-d704-45c4-a549-d3ee25df01b7.png)

工程量不大的话估计可以考虑，但实际应用感觉不是特别刚需...毕竟主要还是关键字搜素，从添加站去直接访问索引页局限还是大...不够开放

**Comment by EdisonCh4n** [comment]
> 

如果把jackett合在一起的话有些公开的站点可以和pt站一起搜索，不然每次还需要分开设置才能搜索，如果是在用手机搜索远程下载的话还是很有用处的，自定义站点添加的json不是符合每个网站。大佬可以考虑修改下，看看效果

**Comment by Juway111** [comment]
其实用pt的玩家，已经抛弃了Bt了，同时需要两种的用户还是少数。资源不好不说，搜刮也识别很难。可以增加支持的PT站点，但是增加bt站点，没有必要，我认为

**Comment by iovejieba** [comment]
> > 
> 
> 如果把jackett合在一起的话有些公开的站点可以和pt站一起搜索，不然每次还需要分开设置才能搜索，如果是在用手机搜索远程下载的话还是很有用处的，自定义站点添加的json不是符合每个网站。大佬可以考虑修改下，看看效果

额  关键现在也没什么公开站点了关键....基本半公开可注册的 jackett基本都涵盖了  ....

**Comment by Juway111** [comment]
修改自建索引器的站点文件是可以实现，但是里面的数据识别比较难，我目前还看不出有什么头绪

**Comment by hsuyelin** [comment]
> 

要针对特殊的站点解析网站元素，可以搞但意义不大 @EdisonCh4n @iovejieba @Juway111 ，暂不准备支持，~回头看看（大概）~
