### ISSUE TITLE
[错误报告]: 每次启动都会在C:\Users\用户名\AppData\Local\Temp生成一个_MEI开头的文件夹

### ISSUE THREAD

**Issue by gaizhili112** [hsuyelin/nas-tools#253]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.6

### 问题类型

主程序运行问题

### 问题描述

每次启动都会在C:\Users\用户名\AppData\Local\Temp生成一个_MEI开头的文件夹
![图片](https://github.com/hsuyelin/nas-tools/assets/25604337/4d082afe-e5b9-40d7-bc04-5255aea701a9)

**Comment by jackloves111** [comment]
![993c66e5-561c-4d05-974e-a1a84ce82aa6](https://github.com/hsuyelin/nas-tools/assets/89971817/e87beba6-f5f2-4d37-95b0-92884c857259)
生成临时文件不是很正常吗？哪个软件没有临时缓存文件

**Comment by gaizhili112** [comment]
> ![993c66e5-561c-4d05-974e-a1a84ce82aa6](https://user-images.githubusercontent.com/89971817/267022874-e87beba6-f5f2-4d37-95b0-92884c857259.png) 生成临时文件不是很正常吗？哪个软件没有临时缓存文件

感谢答复，但您可能没完全理解我的意思。我是说每次启动都生成一个_MEI开头的文件夹，每个大小大概在80mb左右，启动十次就生成十个0.8G。
此外，我理解temp的含义。
再次，十分感谢！

**Comment by gaizhili112** [comment]
> > ![993c66e5-561c-4d05-974e-a1a84ce82aa6](https://user-images.githubusercontent.com/89971817/267022874-e87beba6-f5f2-4d37-95b0-92884c857259.png) 生成临时文件不是很正常吗？哪个软件没有临时缓存文件
> 
> 感谢答复，但您可能没完全理解我的意思。我是说每次启动都生成一个_MEI开头的文件夹，每个大小大概在80mb左右，启动十次就生成十个0.8G。 此外，我理解temp的含义。 再次，十分感谢！

我想咨询的是是否有方案对生成的临时文件夹名称固定，或者自动清除上次启动的临时文件夹。

**Comment by hsuyelin** [comment]
temp文件夹没关系的，系统会定期清理，你也可以手动清理
