### ISSUE TITLE
刷流促销设置中选择免费排除HR点保存，下次再点开设置是未选择促销的状态

### ISSUE THREAD

**Issue by 374246819** [hsuyelin/nas-tools#254]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.6 fe1b508

### 问题类型

主程序运行问题

### 问题描述

刷流促销设置中选择免费排除HR点保存，下次再点开设置是未选择促销的状态，试过馒头，憨憨，彩虹岛均出现此问题

### 发生问题时系统日志和配置文件

```bash
刷流设置没有日志
```

**Comment by hsuyelin** [comment]
已修复

**Comment by jackloves111** [comment]
> 已修复

[47c934b](https://github.com/hsuyelin/nas-tools/commit/47c934b1d617b92a80c632ad558690515b6b9334)  是这个的问题吗？
