### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by strawberry1018** [hsuyelin/nas-tools#255]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.6 Latest

### 问题类型

主程序运行问题

### 问题描述

2023/9/11 21:44:18  RuntimeError: cannot schedule new futures after shutdown
2023/9/11 21:44:18      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/11 21:44:18    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/11 21:44:18      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/11 21:44:18    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/11 21:44:18      self._do_submit_job(job, run_times)
2023/9/11 21:44:18    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/11 21:44:18      executor.submit_job(job, run_times)
2023/9/11 21:44:18    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/11 21:44:18  Traceback (most recent call last):
2023/9/11 21:44:18  Error submitting job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-09-11 21:44:18 CST)" to executor "default"
2023/9/11 21:43:50  RuntimeError: cannot schedule new futures after shutdown
2023/9/11 21:43:50      raise RuntimeError('cannot schedule new futures after shutdown')
2023/9/11 21:43:50    File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
2023/9/11 21:43:50      f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
2023/9/11 21:43:50    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
2023/9/11 21:43:50      self._do_submit_job(job, run_times)
2023/9/11 21:43:50    File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
2023/9/11 21:43:50      executor.submit_job(job, run_times)
2023/9/11 21:43:50    File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
2023/9/11 21:43:50  Traceback (most recent call last):
2023/9/11 21:43:50  Error submitting job "SiteUserInfo.refresh_site_data_now (trigger: interval[3:00:00], next run at: 2023-09-11 21:43:50 CST)" to executor "default"
2023/9/11 21:43:18  OSError: [Errno 28] inotify watch limit reached
2023/9/11 21:43:18      raise OSError(errno.ENOSPC, "inotify watch limit reached")
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 428, in _raise_error
2023/9/11 21:43:18      Inotify._raise_error()
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 416, in _add_watch
2023/9/11 21:43:18      self._add_watch(path, mask)
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 395, in _add_dir_watch
2023/9/11 21:43:18      self._add_dir_watch(path, recursive, event_mask)
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 179, in __init__
2023/9/11 21:43:18      self._inotify = Inotify(path, recursive)
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
2023/9/11 21:43:18      self._inotify = InotifyBuffer(path, self.watch.is_recursive)
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start
2023/9/11 21:43:18      self.on_thread_start()
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
2023/9/11 21:43:18      emitter.start()
2023/9/11 21:43:18    File "/usr/local/lib/python3.10/site-packages/watchdog/observers/api.py", line 261, in start
2023/9/11 21:43:18      _observer.start()
2023/9/11 21:43:18    File "/nas-tools/initializer.py", line 420, in start_config_monitor
2023/9/11 21:43:18      start_config_monitor()
2023/9/11 21:43:18    File "/nas-tools/run.py", line 107, in start_service
2023/9/11 21:43:18      start_service()
2023/9/11 21:43:18    File "/nas-tools/run.py", line 114, in <module>
2023/9/11 21:43:18  Traceback (most recent call last):
2023/9/11 21:43:18      AutoBackup.__backup (trigger: cron[month='*', day='*', day_of_week='*', hour='2', minute='0'], pending)
2023/9/11 21:43:18  Pending jobs:
2023/9/11 21:43:18      TorrentTransfer.check_recheck (trigger: interval[0:03:00], pending)
2023/9/11 21:43:18      TorrentTransfer.transfer (trigger: cron[month='*', day='*', day_of_week='*', hour='*/2', minute='0'], pending)
2023/9/11 21:43:18  Pending jobs:
2023/9/11 21:43:18      CloudflareSpeedTest.__cloudflareSpeedTest (trigger: cron[month='*', day='*', day_of_week='*', hour='*/6', minute='0'], pending)
2023/9/11 21:43:18  Pending jobs:
2023/9/11 21:43:18      SpeedLimiter.__check_playing_sessions (trigger: interval[0:05:00], pending)
2023/9/11 21:43:18  Pending jobs:
2023/9/11 21:43:18      AutoSignIn.sign_in (trigger: cron[month='*', day='*', day_of_week='*', hour='9', minute='0'], pending)
2023/9/11 21:43:18  Pending jobs:
2023/9/11 21:43:18      BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
2023/9/11 21:43:18      BrushTask.check_task_rss (trigger: interval[0:10:00], pending)
2023/9/11 21:43:18  Pending jobs:
2023/9/11 21:43:18      get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-09-11 21:43:18 CST)
2023/9/11 21:43:18      MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
2023/9/11 21:43:18      Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
2023/9/11 21:43:18      Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
2023/9/11 21:43:18      Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
2023/9/11 21:43:18      MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
2023/9/11 21:43:18      MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
2023/9/11 21:43:18      Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
2023/9/11 21:43:18      Rss.rssdownload (trigger: interval[0:53:20], pending)
2023/9/11 21:43:18      SiteUserInfo.refresh_site_data_now (trigger: interval[3:00:00], next run at: 2023-09-11 21:43:50 CST)
2023/9/11 21:43:18  Pending jobs:

**Comment by strawberry1018** [comment]
nas没有权限 执行命令

**Comment by hsuyelin** [comment]
1. 确认3000端口有没有被占用
2. 宿主机上（不是docker容器里），执行以下命令：
```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

**Comment by strawberry1018** [comment]
> 1. 确认3000端口有没有被占用
> 2. 宿主机上（不是docker容器里），执行以下命令：
> 
> ```shell
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
> echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
> sudo sysctl -p
> ```

主要是nas没有执行命令的权限
 sudo sysctl -p
'sudo' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by strawberry1018** [comment]
> 1. 确认3000端口有没有被占用
> 2. 宿主机上（不是docker容器里），执行以下命令：
> 
> ```shell
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
> echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
> sudo sysctl -p
> ```

搞了几个小时了 还不行 回退版本也不行  nas无法执行命令

**Comment by hsuyelin** [comment]
无法执行命令先去搜索nas如何开启root账号，

**Comment by strawberry1018** [comment]
> 无法执行命令先去搜索nas如何开启root账号，

大哥有没有其他办法解决，现在启动不了，nas也没办法开启root权限

**Comment by liangliang-wh** [comment]
> 无法执行命令先去搜索nas如何开启root账号，

我用的是极空间NAS Z2S-4G，好像无法开启root账号，用3.3.14版本，现在也报RuntimeError: cannot schedule new futures after shutdown错误，无法正常启动，通过Web无法访问，Web页面显示 “已拒绝连接”。
