### ISSUE TITLE
个别PT论坛签到不成功。

### ISSUE THREAD

**Issue by k851026** [hsuyelin/nas-tools#256]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.6 fe1b508

### 问题类型

插件问题

### 问题描述

签到时候，个别PT论坛签到没有成功，影 这个PT论坛就没有成功
![image](https://github.com/hsuyelin/nas-tools/assets/33319756/d8d367f9-8b6c-43b4-8adc-d25303fe5855)
![image](https://github.com/hsuyelin/nas-tools/assets/33319756/d30535b0-b9e7-433c-877f-3c1e4b05072c)

**Comment by zjjxwhh** [comment]
站点维护中站点地址填签到地址 `https://xxxxx/attendance.php`，开启浏览器仿真选`否`，再次签到试试

**Comment by k851026** [comment]
@zjjxwhh 谢谢 可行。。。
