### ISSUE TITLE
[错误报告]: 增强识别报错

### ISSUE THREAD

**Issue by cend1s** [hsuyelin/nas-tools#257]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.6

### 问题类型

主程序运行问题

### 问题描述

增强识别报错。
![image](https://github.com/hsuyelin/nas-tools/assets/125641670/9d9f652a-ab57-4b42-9898-44770a5b364c)

**Comment by cend1s** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/125641670/03b8c269-18d7-4554-ae74-d41b73206ed9)
还有一个错误，不知道是什么，报错之后页面无法打开，需要重启后才能访问页面。

**Comment by hsuyelin** [comment]
已修复
