### ISSUE TITLE
更换3.2.9.4后，windows版依旧无法打开

### ISSUE THREAD

**Issue by FireGodson** [hsuyelin/nas-tools#26]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.9.4
>
>
> 环境: windows
>

## 你遇到什么问题了？
更换3.2.9.4后，windows版依旧无法打开
> 描述一下你遇到的问题
之前的版本降级chrome后可以打开，更新新版本后把chrome升级到115后又无法打开了
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是

## 你期望的结果
修复问题
> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![20230804_124646](https://github.com/hsuyelin/nas-tools/assets/32048420/08d36e9e-32aa-4ea0-b1ac-276593ed3363)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
抱歉，调用方法手误了。重新打包了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月04日 12:52 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [hsuyelin/nas-tools] 更换3.2.9.4后，windows版依旧无法打开 (Issue #26) |

你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: 3.2.9.4

环境: windows

你遇到什么问题了？

更换3.2.9.4后，windows版依旧无法打开

描述一下你遇到的问题
之前的版本降级chrome后可以打开，更新新版本后把chrome升级到115后又无法打开了

是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是

你期望的结果

修复问题

描述以下你期望的结果

给出程序界面截图、后台运行日志或配置文件

如UI BUG请提供截图及配置文件截图
其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
等我重新构建一个包
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月04日 12:52 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [hsuyelin/nas-tools] 更换3.2.9.4后，windows版依旧无法打开 (Issue #26) |

你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: 3.2.9.4

环境: windows

你遇到什么问题了？

更换3.2.9.4后，windows版依旧无法打开

描述一下你遇到的问题
之前的版本降级chrome后可以打开，更新新版本后把chrome升级到115后又无法打开了

是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是

你期望的结果

修复问题

描述以下你期望的结果

给出程序界面截图、后台运行日志或配置文件

如UI BUG请提供截图及配置文件截图
其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by FireGodson** [comment]
谢谢啦，麻烦大佬啦

**Comment by FireGodson** [comment]
> 抱歉，调用方法手误了。重新打包了 ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年08月04日 12:52 | | 收件人 | hsuyelin/nas-tools ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [hsuyelin/nas-tools] 更换3.2.9.4后，windows版依旧无法打开 (Issue #26) | 你使用的 NAStool 是什么版本，什么环境？ NAStool 版本: 3.2.9.4 环境: windows 你遇到什么问题了？ 更换3.2.9.4后，windows版依旧无法打开 描述一下你遇到的问题 之前的版本降级chrome后可以打开，更新新版本后把chrome升级到115后又无法打开了 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？ 是 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问 是 你期望的结果 修复问题 描述以下你期望的结果 给出程序界面截图、后台运行日志或配置文件 如UI BUG请提供截图及配置文件截图 其它问题提供后台日志，如为Docker请提供docker的日志 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

谢谢啦，麻烦大佬啦

**Comment by hsuyelin** [comment]
> > 抱歉，调用方法手误了。重新打包了 ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 发送日期 | 2023年08月04日 12:52 | | 收件人 | hsuyelin/nas-tools _**@**_.**_> | | 抄送人 | Subscribed _**@**_._**> | | 主题 | [hsuyelin/nas-tools] 更换3.2.9.4后，windows版依旧无法打开 (Issue #26) | 你使用的 NAStool 是什么版本，什么环境？ NAStool 版本: 3.2.9.4 环境: windows 你遇到什么问题了？ 更换3.2.9.4后，windows版依旧无法打开 描述一下你遇到的问题 之前的版本降级chrome后可以打开，更新新版本后把chrome升级到115后又无法打开了 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？ 是 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问 是 你期望的结果 修复问题 描述以下你期望的结果 给出程序界面截图、后台运行日志或配置文件 如UI BUG请提供截图及配置文件截图 其它问题提供后台日志，如为Docker请提供docker的日志 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 谢谢啦，麻烦大佬啦

再试试，麻烦你了，主要我本地测试不了，使用115版本的也是可以的

**Comment by hsuyelin** [comment]
@FireGodson 下载最新版本的即可，我替换了，能不能帮忙测试后反馈下呀

**Comment by leiurayer** [comment]
最新版可以在Windows上正常使用了

**Comment by hsuyelin** [comment]
> 最新版可以在Windows上正常使用了

OK，我复现了就容易修复了
