### ISSUE TITLE
[功能改进]: 能否增加个单独硬链接的插件

### ISSUE THREAD

**Issue by 1chenman** [hsuyelin/nas-tools#260]
### 当前程序版本

3.3.4

### 功能改进

现在目录想手动硬链接 必须要识别到影视信息才能否则会直接报失败  希望能单独出个硬链接插件   可以手动只进行硬链接 不进行刮削   因为有些少儿资源TMDB资料不全或者就没有  想手动硬链接过去后 自己添加NFO资料以及海报图

**Comment by strawberry1018** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/32291016/7a269713-d07e-47c1-ac96-770fcf936fbc)

**Comment by jackloves111** [comment]
去了解一下HILK，已经做的很好了。go语言写的

**Comment by youyifentian** [comment]
https://github.com/NAStool/nas-tools-wiki/blob/main/%E7%9B%AE%E5%BD%95%E5%90%8C%E6%AD%A5.md
