### ISSUE TITLE
[错误报告]: 刷流任务编辑页面显示促销状态错误

### ISSUE THREAD

**Issue by zjjxwhh** [hsuyelin/nas-tools#262]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.6 fe1b508

### 问题类型

主程序运行问题

### 问题描述

刷流任务编辑页面显示促销状态错误

1. 新建刷流任务，**选种规则** 中促销选项选择 `免费`
2. 点击刚新建的刷流任务右上角的 **编辑任务** 按钮，发现促销选项显示为 `全部`

编辑任务界面显示的促销选项应与刷流任务界面下一致，望修复，感谢！

![image](https://github.com/hsuyelin/nas-tools/assets/14367334/b88a1ec7-6f5f-4f6b-a8ee-cc9867e75a5d)

### 发生问题时系统日志和配置文件

```bash
无日志
```

**Comment by hsuyelin** [comment]
修复过了，等下个版本
