### ISSUE TITLE
[功能改进]: 希望加上“订阅后点击编辑订阅就触发暂停执行订阅搜索”的功能

### ISSUE THREAD

**Issue by cng10001** [hsuyelin/nas-tools#265]
### 当前程序版本

3.3.6

### 功能改进

nt当点击添加订阅按钮后，后台是会立即根据默认过滤规则执行订阅搜索的，这导致都来不及对订阅的影视编辑更具体的过滤规则。
希望可以增加在用户点击添加订阅后如果再点击“编辑订阅”就触发暂停执行订阅搜索的功能，以便有足够的时间编辑更具体的过滤规则！
![编辑订阅](https://github.com/hsuyelin/nas-tools/assets/115156545/212b7456-98d3-414b-b54b-e87710cc69b3)

**Comment by hsuyelin** [comment]
立即订阅不影响，编辑后规则要照样生效，如果点击编辑订阅停止，会要写很多逻辑去判断是否是当前要订阅的，收益不高

**Comment by cng10001** [comment]
啊-，就是举个例子。或者其他解决方案都很难实现嘛- -
