### ISSUE TITLE
[错误报告]: 开启增强识别V2，出现了电影名称在副标题简介出现也会当为有效资源

### ISSUE THREAD

**Issue by jinhua523** [hsuyelin/nas-tools#269]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.4

### 问题类型

主程序运行问题

### 问题描述

搜索电影名比如：孤注一掷，电影名称没搜到，但是在电影的简介中有孤注一掷这个词语，会被当成有效资源
![image](https://github.com/hsuyelin/nas-tools/assets/35497576/d6e7faab-1168-473e-afd9-db7c988cd217)

### 发生问题时系统日志和配置文件

```bash
正在查询TMDB电影：1121612 ...
11:19:00		
1121612 查询结果：孤注一掷
11:19:00		
They Shoot Horses, Don't They? 1969 1080p Blu-ray AVC DTS-HD MA 2 0-COASTER 孤注一掷/夺命舞/射马记 [原盘英字] 识别为 孤注一掷 (2023) 匹配成功
11:19:00		
彩虹岛 1 条数据中，过滤 0，不匹配 0，错误 0，有效 1，耗时 1 秒
11:19:00		
杜比 未搜索到数据
11:19:00		
馒头 返回数据：1
11:19:00		
正在查询TMDB电影：1121612 ...
11:19:00		
1121612 查询结果：孤注一掷
11:19:00		
The Music Room 1958 BluRay Criterion Collection 720p BluRay x264-WiKi 音乐室「没落贵族的尊严和虚荣 孤注一掷的勇气和放弃」 识别为 孤注一掷 (2023) 匹配成功
11:19:00		
馒头 1 条数据中，过滤 0，不匹配 0，错误 0，有效 1，耗时 1 秒
```

**Comment by hsuyelin** [comment]
新版本已经修复了

**Comment by DJ2509560551** [comment]
最新版v3.3.6已经修复了，还是下一个版本，大佬大佬

**Comment by hsuyelin** [comment]
> 最新版v3.3.6已经修复了，还是下一个版本，大佬大佬
下个版本

**Comment by jinhua523** [comment]
期待大佬的更新，感谢你的### 无私奉献
