### ISSUE TITLE
关于刷流任务

### ISSUE THREAD

**Issue by KeySoundsLa** [hsuyelin/nas-tools#27]
请问大佬维护的NT，刷流任务也取消了吗🥺

**Comment by hsuyelin** [comment]
![screenshot-20230804-141647.png](https://pic3.58cdn.com.cn/nowater/webim/big/n_v224103bdc3fad4c89a726e99f17c76950.png)
![screenshot-20230804-141632.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v284766da662b44192b09a152cd4bef9fc.png)

添加后建议重启下nas-tools。理论上不重启也可以

**Comment by iovejieba** [comment]
添加完内置站 ，重启好像会即可生效...不重启  玄学性出现  重启肯定会有

**Comment by KeySoundsLa** [comment]
好的感谢大佬已经有了。另外我刚刚添加了彩虹岛的站点，添加刷流任务时，没有免费选项。添加其他站点，例如馒头等反而有免费种子选项- -！！请问是出问题了吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsuyelin/nas-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)





 
添加完内置站 ，重启好像会即可生效...不重启  玄学性出现  重启肯定会有

**Comment by hsuyelin** [comment]
> 添加完内置站 ，重启好像会即可生效...不重启 玄学性出现 重启肯定会有
大致知道不重启也能生效的方法，抽空修复后验证一下

**Comment by KeySoundsLa** [comment]
感谢大佬抽空测试，我刚下班看了你之前的回复，并尝试按你的要求操作，结果全部都不行了- -！！！！！
后面我更换了谷歌浏览器再次尝试，并且重新部署NT。
一、在配置站点后，刷流任务没出现！！
按大佬的提示操作，重启NT或者容器均无效，只能从网址更改后缀跳转进入刷流任务。。如【IP:3000/web#brushtask】



二、进入刷流界面配置彩虹岛任务，尝试在站点维护内，重新配置新老网址，均未出现免费，重启系统或容器也未果。。。T_T。。。。





救救老弟。。。。






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "hsuyelin/nas-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)





  
添加完内置站 ，重启好像会即可生效...不重启 玄学性出现 重启肯定会有
 大致知道不重启也能生效的方法，抽空修复后验证一下

**Comment by hsuyelin** [comment]
我没有彩虹岛账号只能我修复你协助测试了，进度比较慢
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月04日 17:39 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
State ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27) |

感谢大佬抽空测试，我刚下班看了你之前的回复，并尝试按你的要求操作，结果全部都不行了- -！！！！！
后面我更换了谷歌浏览器再次尝试，并且重新部署NT。
一、在配置站点后，刷流任务没出现！！
按大佬的提示操作，重启NT或者容器均无效，只能从网址更改后缀跳转进入刷流任务。。如【IP:3000/web#brushtask】



二、进入刷流界面配置彩虹岛任务，尝试在站点维护内，重新配置新老网址，均未出现免费，重启系统或容器也未果。。。T_T。。。。





救救老弟。。。。






------------------ 原始邮件 ------------------
发件人: "hsuyelin/nas-tools" ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)






添加完内置站 ，重启好像会即可生效...不重启 玄学性出现 重启肯定会有
大致知道不重启也能生效的方法，抽空修复后验证一下

**Comment by hsuyelin** [comment]
> 我没有彩虹岛账号只能我修复你协助测试了，进度比较慢 ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年08月04日 17:39 | | 收件人 | hsuyelin/nas-tools ***@***.***> | | 抄送人 | hsuyelin ***@***.***>, State ***@***.***> | | 主题 | Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27) | 感谢大佬抽空测试，我刚下班看了你之前的回复，并尝试按你的要求操作，结果全部都不行了- -！！！！！ 后面我更换了谷歌浏览器再次尝试，并且重新部署NT。 一、在配置站点后，刷流任务没出现！！ 按大佬的提示操作，重启NT或者容器均无效，只能从网址更改后缀跳转进入刷流任务。。如【IP:3000/web#brushtask】 二、进入刷流界面配置彩虹岛任务，尝试在站点维护内，重新配置新老网址，均未出现免费，重启系统或容器也未果。。。T_T。。。。 救救老弟。。。。
> […](#)

你怎么加的，截图看看，重要地方打码就好了

**Comment by iovejieba** [comment]
没岛...   只有mt  一会我去试试mt的应急域名 看看是否有类似情况

**Comment by KeySoundsLa** [comment]
不好意思，刚刚出门忙事情刚回来，我录了个视频，大佬你参考下。
刷流任务没显示，我通过http:IP/web#brushtask进入的
刷流任务与免费未显示的问题，我也都有重启容器试过，还是没有出现- -！！
我需要怎么协助大佬你修复，听你指令
有QQ或者微信相对比较方便联系的方式吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsuyelin/nas-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)





  
我没有彩虹岛账号只能我修复你协助测试了，进度比较慢 ---- 回复的原邮件 ---- | 发件人 | @.&gt; | | 发送日期 | 2023年08月04日 17:39 | | 收件人 | hsuyelin/nas-tools @.&gt; | | 抄送人 | hsuyelin @.&gt;, State @.&gt; | | 主题 | Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27) | 感谢大佬抽空测试，我刚下班看了你之前的回复，并尝试按你的要求操作，结果全部都不行了- -！！！！！ 后面我更换了谷歌浏览器再次尝试，并且重新部署NT。 一、在配置站点后，刷流任务没出现！！ 按大佬的提示操作，重启NT或者容器均无效，只能从网址更改后缀跳转进入刷流任务。。如【IP:3000/web#brushtask】 二、进入刷流界面配置彩虹岛任务，尝试在站点维护内，重新配置新老网址，均未出现免费，重启系统或容器也未果。。。T_T。。。。 救救老弟。。。。
 …
  
你怎么加的，截图看看，重要地方打码就好了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

bandicam 2023-08-04 20-23-13-686.mp4 (51.10M, 2023年09月03日 20:30 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6e373637c504abc47da06d37426557174f4306530704000a1a0e06515248060b56001b5656060315565155005653075c520404546441655a5659525e070408180507040449555d15070316055448570b1a06051a525d53165a47023759&code=7767dee8

**Comment by Juway111** [comment]
你的岛注册满一个月没有？

**Comment by KeySoundsLa** [comment]
还没，昨天刚进的。
一个月的问题我有考虑过
但是我馒头和织梦也都还没一个月。。可以显示免费。。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Juway111 ***@***.***&gt;
发送时间: 2023年8月4日 20:38
收件人: hsuyelin/nas-tools ***@***.***&gt;
抄送: KeySoundsLa ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)





 
你的岛注册满一个月没有？

**Comment by Juway111** [comment]
首先，你没有刷流选项了，就是因为你没有注册满一个月的原因。你说的没有免费的情况，我这边测出来都正常的

**Comment by KeySoundsLa** [comment]
我找到原因了- -！！RSS的地址改成旧网址，后面密匙不变，可以出现免费【chdbits】
RSS新网址【ptchdbits】就没办法显示。。我丢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月4日(星期五) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)





 
首先，你没有刷流选项了，就是因为你没有注册满一个月的原因。你说的没有免费的情况，我这边测出来都正常的

**Comment by Juway111** [comment]
我晚点看下，修改一下bat文件能不能解决

**Comment by Juway111** [comment]
我确实没有留意到rss对这个选项的影响

**Comment by KeySoundsLa** [comment]
感谢大佬们今天帮我答疑解惑指点问题！目前可以RSS到数据，就看能不能正常下载到FREE种
PS：反馈一个问题，电脑和手机登录NT查看日志，一直显示刷新中反应慢，无法查看历史- -！








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月4日(星期五) 晚上9:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hsuyelin/nas-tools] 关于刷流任务 (Issue #27)





 
我确实没有留意到rss对这个选项的影响
