### ISSUE TITLE
[功能改进]:qBittorrent下载设置能不能添加“Torrent 内容布局”

### ISSUE THREAD

**Issue by 8aby-dudu** [hsuyelin/nas-tools#271]
### 当前程序版本

3.3.7

### 功能改进

![image](https://github.com/hsuyelin/nas-tools/assets/125348082/33c676c0-6045-4447-87c9-d13ff925277f)

各站剧集上传文件目录没有同一标准，有的以“剧集名+单集集数”作为文件夹名，很不友好。

**Comment by hsuyelin** [comment]
找错地方了吧，这个你应该给QB提把，QBAPI没有设置这个的
