### ISSUE TITLE
[错误报告]: 订阅动漫等种子数量较多的资源时，因为搜索结果返回数量限制而无法正常订阅

### ISSUE THREAD

**Issue by KoBoAlter** [hsuyelin/nas-tools#274]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.6

### 问题类型

其他问题

### 问题描述

在对种子数量多的剧集作订阅时，内置的索引器只会返回每个站点搜索结果的第一页内容，站点配置文件中browse的设定似乎没有生效

尝试在mikan，动漫花园，m-team三个站点的搜索，只会返回100,80,100条结果

**Comment by hsuyelin** [comment]
这个暂且不改动这块逻辑，增加条数只会增加检索时间和复杂度，100条已经够了

**Comment by KoBoAlter** [comment]
这样下载字幕组很多动漫时会搜不到前几集，有什么好的解决方法吗

**Comment by jackloves111** [comment]
设置开关，交给用户去选择条数？
