### ISSUE TITLE
插件下载后无法删除，也无法安装其他新的插件

### ISSUE THREAD

**Issue by git-tracker** [hsuyelin/nas-tools#276]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.3

### 问题类型

插件问题

### 问题描述

插件下载后无法删除，也无法安装其他新的插件

**Comment by hsuyelin** [comment]
点击插件卸载
