### ISSUE TITLE
豆瓣榜单订阅读取不到数据

### ISSUE THREAD

**Issue by dwwl886** [hsuyelin/nas-tools#277]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

插件问题

### 问题描述

豆瓣榜单订阅 - RSS地址：https://rsshub.app/douban/movie/playing，未查询到数据

所有豆瓣榜单订阅 都是提示未查询到数据

### 发生问题时系统日志和配置文件

```bash
18:09:03		
豆瓣榜单订阅 - 获取RSS：https://rsshub.app/douban/movie/playing...
18:09:44		
豆瓣榜单订阅 - RSS地址：https://rsshub.app/douban/movie/playing，未查询到数据
```

**Comment by dwwl886** [comment]
是我设置的问题 还是  插件有问题

**Comment by dwwl886** [comment]
那位大神知道 指点以下

**Comment by hsuyelin** [comment]
触发流控下个版本再试试看

**Comment by hsuyelin** [comment]
@dwwl886 是你的问题。rss乱写

用这个就可以了：https://rsshub.app/douban/movie/playing/7.5

**Comment by dwwl886** [comment]
我发现是要开代理 网址才能访问 基础设置  里面有代理 但是对 豆瓣榜单不起作用

**Comment by dwwl886** [comment]
可以了
