### ISSUE TITLE
BANGUMI没有封面图

### ISSUE THREAD

**Issue by xiaobaiwaf** [hsuyelin/nas-tools#279]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

主程序运行问题

### 问题描述

主页面BANGUMI模块没有封面图

**Comment by xiaobaiwaf** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/97422881/e3e23d1d-1942-431d-8a69-d0105b0805db)

**Comment by hh0610** [comment]
> ![image](https://user-images.githubusercontent.com/97422881/268002886-e3e23d1d-1942-431d-8a69-d0105b0805db.png)

挂代理

**Comment by xiaobaiwaf** [comment]
我的直接是nc的服务器也要挂代理吗，之前用的原版是正常的

**Comment by hh0610** [comment]
![1694706672313](https://github.com/hsuyelin/nas-tools/assets/142991330/b5b0ea16-b485-4d10-8769-534118d2b5fe)
我这边挂代理是可以显示出来的

**Comment by hsuyelin** [comment]
要用魔法打败魔法

**Comment by mzj001** [comment]
将nginx-proxy-manager中nastool反代设置里的“阻止常见漏洞”选项关闭就正常了。
