### ISSUE TITLE
关于某站刷流任务，未显示免费

### ISSUE THREAD

**Issue by KeySoundsLa** [hsuyelin/nas-tools#28]
好的感谢大佬已经有了。另外我刚刚添加了彩虹岛的站点，添加刷流任务时，没有免费选项。添加其他站点，例如馒头等反而有免费种子选项- -！！请问是出问题了吗![image](https://github.com/hsuyelin/nas-tools/assets/140850069/bdd9a61f-a616-4791-8b22-f4ad7d6c590a)

**Comment by Juway111** [comment]
岛本来是有的吗？跟其他站点比较没有意义。因为站点每个爬取的代码都有出入的！

**Comment by KeySoundsLa** [comment]
PT交流群内的人说有，同时也在刷了- -！，我也是经介绍到大佬维护的NT这里来使用。。。PS：我不知道用QQ邮箱直接回复大佬是否能收到，另外GitHub会再次向你发一次。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月4日(星期五) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hsuyelin/nas-tools] 关于某站刷流任务，未显示免费 (Issue #28)





 
岛本来是有的吗？跟其他站点比较没有意义。因为站点每个爬取的代码都有出入的！

**Comment by hsuyelin** [comment]
> PT交流群内的人说有，同时也在刷了- -！，我也是经介绍到大佬维护的NT这里来使用。。。PS：我不知道用QQ邮箱直接回复大佬是否能收到，另外GitHub会再次向你发一次。。。
> […](#)

我没有彩虹岛的PT账号，没有日志的话，我只有帮你算一卦

**Comment by Juway111** [comment]
群里说有的话，是本项目代码，还是官方的镜像，因为官方镜像没有修改过域名，只能用原域名添加才会显示索引器

**Comment by hsuyelin** [comment]
> 好的感谢大佬已经有了。另外我刚刚添加了彩虹岛的站点，添加刷流任务时，没有免费选项。添加其他站点，例如馒头等反而有免费种子选项- -！！请问是出问题了吗![image](https://user-images.githubusercontent.com/140850069/258319615-bdd9a61f-a616-4791-8b22-f4ad7d6c590a.png)

有个插件彩虹岛的域名从chd改成ptchd我记得的，用那个插件映射一下就可以了 @KeySoundsLa

**Comment by Juway111** [comment]
本项目已经改过域名了，添加岛的新域名直接会出现在索引器

**Comment by Juway111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/fc5784b0-da25-4e04-afb6-42b6565b7696)
测试了，用老的域名确实可以显示免费选项，应该是bat数据文件里面还需要修改某个参数，等我测试好再更新

**Comment by Juway111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/c3f0b6da-9c21-470f-bf44-687f68e9b348)
这是我的测试结果，新的域名也会显示免费，建议你重启容器试下

**Comment by iovejieba** [comment]
没岛....没办法上测试了，mt的应急域名 我一会去测下看看是否有类似问题

**Comment by iovejieba** [comment]
93的版本 貌似确实会...也可能是我没重启  新添加的自定义站 促销选择 只有全部

**Comment by iovejieba** [comment]
94版本..自定义域名的版本貌似都会这样 不显示free  只有全部

**Comment by KeySoundsLa** [comment]
反馈一下昨天的问题- -！！
我创建了两个站点，一个新域名，一个老域名
1、新域名网址配置新域名的RSS，未显示免费。
2、老域名网址配置老域名的RSS，显示免费。
使用老域名刷流，可以RSS到数据
有符合的资源，但是一晚上到现在均没有任务添加- -！
![image](https://github.com/hsuyelin/nas-tools/assets/140850069/940e5c82-2843-4e06-a8df-484b7252b3f9)
![image](https://github.com/hsuyelin/nas-tools/assets/140850069/3ec100c6-7a52-4b8a-b9e0-6e93640cf199)
![image](https://github.com/hsuyelin/nas-tools/assets/140850069/954e44da-20a4-4cfc-b07b-7e9828e2f368)
![image](https://github.com/hsuyelin/nas-tools/assets/140850069/d722319a-cb4d-4377-aa7d-8426f6dab980)

**Comment by iovejieba** [comment]
> 反馈一下昨天的问题- -！！ 我创建了两个站点，一个新域名，一个老域名 1、新域名网址配置新域名的RSS，未显示免费，重启容器也一样。 2、老域名网址配置老域名的RSS，显示免费。 使用老域名刷流，可以RSS到数据 有符合的资源，但是一晚上到现在均没有任务添加- -！ ![image](https://user-images.githubusercontent.com/140850069/258564921-940e5c82-2843-4e06-a8df-484b7252b3f9.png) ![image](https://user-images.githubusercontent.com/140850069/258565008-3ec100c6-7a52-4b8a-b9e0-6e93640cf199.png) ![image](https://user-images.githubusercontent.com/140850069/258565046-954e44da-20a4-4cfc-b07b-7e9828e2f368.png) ![image](https://user-images.githubusercontent.com/140850069/258565137-d722319a-cb4d-4377-aa7d-8426f6dab980.png)

刷流...很玄学...只能说是能用 但是判断规则  就很玄学....

**Comment by Juway111** [comment]
已经修复了，等仓库同步以后就可以了，找到原因了

**Comment by Juway111** [comment]
#29

**Comment by KeySoundsLa** [comment]
好的，辛苦了大佬了！

**Comment by KeySoundsLa** [comment]
NT的刷流我感觉是没弄好- -！！
因为我有Movie robot，用他家刷某岛的流，FREE种反而一直有。。。
![K09D AL)CG({%`HCXI4H~P8](https://github.com/hsuyelin/nas-tools/assets/140850069/b2ec0ae4-7d76-447f-8de9-dae2ec941994)
但是我更想用的是NT- -！！

**Comment by Juway111** [comment]
仓库已经同步了，等更新版本了就有了

**Comment by KeySoundsLa** [comment]
卧槽 反馈这么快，大佬牛逼！！
我等更新后在试试看

**Comment by KeySoundsLa** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/140850069/f7e6640b-1c01-4557-802f-79610609819c)
感谢大佬！已经可以正常刷流了
