### ISSUE TITLE
副标题为“全25话”时会识别为第25集

### ISSUE THREAD

**Issue by xiaobaiwaf** [hsuyelin/nas-tools#281]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.7

### 问题类型

主程序运行问题

### 问题描述

副标题有全25话时会识别为第25集
![image](https://github.com/hsuyelin/nas-tools/assets/97422881/77875db6-23c5-4713-b649-1c4bc343a800)

**Comment by hsuyelin** [comment]
已修复等下个版本

<img width="1085" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/47aa030a-487f-4676-92ef-9a50f1d4df79">
