### ISSUE TITLE
[错误报告]: 剧集名称识别问题

### ISSUE THREAD

**Issue by huangmengsheng** [hsuyelin/nas-tools#283]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

其他问题

### 问题描述

金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E04.WEB-DL.2160p.HEVC.AAC.mp4
原因：无法识别媒体信息

自定义识别词屏蔽，金牌客服董董恩  可以识别
https://www.themoviedb.org/tv/234859

**Comment by huangmengsheng** [comment]
<html>
<body>


21:42:22 | Rmt | 开始处理：/volume1/nas/smb/pt刷流/金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01.WEB-DL.2160p.HEVC.AAC-ZmWeb，转移方式：软链接
-- | -- | --
21:42:22 | Meta | 未能获取到视频元信息
21:42:25 | Meta | 金牌客服董董恩 以年份 2023 在TMDB中未找到电视剧信息!
21:42:25 | Meta | 金牌客服董董恩 以年份 在TMDB中未找到电视剧信息!
21:42:31 | Meta | 未能获取到视频元信息
21:42:31 | Meta | 未能获取到视频元信息
21:42:31 | Meta | 未能获取到视频元信息
21:42:31 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E03.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:32 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E03.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:32 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E02.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:33 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E02.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:33 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E01.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:35 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E01.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:35 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E04.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:36 | Rmt | 金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01E04.WEB-DL.2160p.HEVC.AAC-ZmWeb.mp4 无法识别媒体信息！
21:42:36 | Rmt | /volume1/nas/smb/pt刷流/金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01.WEB-DL.2160p.HEVC.AAC-ZmWeb 处理完成，总数：4，失败：4
21:42:36 | Message | 发送消息 微信：title=【4 个文件入库失败】, text=源路径：/volume1/nas/smb/pt刷流/金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01.WEB-DL.2160p.HEVC.AAC-ZmWeb 原因：无法识别媒体信息
21:42:36 | System | 处理事件：transfer.fail - [<function Webhook.send at 0x7f02083de950>]
21:42:36 | Sync | /volume1/nas/smb/pt刷流/金牌客服董董恩.Hello.Im.At.Your.Service.2023.S01.WEB-DL.2160p.HEVC.AAC-ZmWeb转移失败：无法识别媒体信息
21:42:36 | Sync | 开始转移监控目录文件...


</body>
</html>

**Comment by hsuyelin** [comment]
![2023-09-16_211609](https://github.com/hsuyelin/nas-tools/assets/17918063/1604f14d-cf2c-4eff-9b72-1db5319093d9)

我们之中肯定有个人有问题，不是我
