### ISSUE TITLE
[功能改进]: 有可能增加一个刷流定时限速吗

### ISSUE THREAD

**Issue by IWONTTELL** [hsuyelin/nas-tools#285]
### 当前程序版本

3.3.7

### 功能改进

大佬你好，感谢你继续维护着nastool，你添加的很多功能都非常棒。以下是我个人使用的时候会遇到的问题：
刷流我个人一直有在用。白天带宽使用的人少，上传下载跑满也没事。但是晚上全家都看电视刷手机的经常需要手动去暂停刷流，如果添加一个定时限速或者定时暂停刷流的功能那就非常的方便了。请问这种有实现的可能吗？

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/31fcf18f-64a1-4d0b-ac7f-49f1142320a5)
不明白QB自带的功能，为什么还要nastool去增加呢？

**Comment by IWONTTELL** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/268423946-31fcf18f-64a1-4d0b-ac7f-49f1142320a5.png) 不明白QB自带的功能，为什么还要nastool去增加呢？

抱歉，请问刷流任务可以定时暂停添加新种吗？我的锅，我其实需要的是这个功能，刚起床稀里糊涂的没表述清楚。

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/1748029d-9ddc-460b-9e3d-ef1bd321a6a0)
可以通过学习正则表达式来设置周期！

**Comment by IWONTTELL** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/268424172-1748029d-9ddc-460b-9e3d-ef1bd321a6a0.png) 你说的功能也是有的，可以通过学习CRON表达式来设置周期！

哦哦哦！突然明白了，感谢大佬！之前我这个只是单纯设置的是间隔分钟数，我去研究一下

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/4e940a6d-92a3-4213-9a15-150baa052547)
```
*/10 2-17 * * *
```
可以在这个基础上做调整！

**Comment by IWONTTELL** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/268424419-4e940a6d-92a3-4213-9a15-150baa052547.png)
> 
> ```
> */10 2-17 * * *
> ```
> 
> 可以在这个基础上做调整！

大佬！太感谢你了！
