### ISSUE TITLE
[错误报告]: 动漫标题识别错误

### ISSUE THREAD

**Issue by ssmengyan** [hsuyelin/nas-tools#286]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

主程序运行问题

### 问题描述

![nastool](https://github.com/hsuyelin/nas-tools/assets/79904047/f9d30b8e-181e-44e2-aa6f-435945c52650)
![nas](https://github.com/hsuyelin/nas-tools/assets/79904047/de41266a-96c5-49f0-a5f3-5c2b682080d6)
nastool上面没法自动识别，但是点进去识别名称后，却能正确在IMDB上面搜索到，而且只要这一个正确选项，不知道为什么最后还是未被识别。

**Comment by ssmengyan** [comment]
### 文件名
[[FYSub][Pocket_Monsters_Horizontes][021][1080P][GB].mp4]

**Comment by hsuyelin** [comment]
<img width="801" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/b442a092-8201-4201-a87c-056759b682e7">

咱也不懂

**Comment by hsuyelin** [comment]
检查下TMDB连通性把

**Comment by ssmengyan** [comment]
> 检查下TMDB连通性把

![Uploading Snipaste_2023-09-17_12-48-19.png…]()

**Comment by ssmengyan** [comment]
> 检查下TMDB连通性把

![Snipaste_2023-09-17_12-48-19](https://github.com/hsuyelin/nas-tools/assets/79904047/cd245f16-7a90-4a2d-b96c-5065dbfde056)

**Comment by ssmengyan** [comment]
> 检查下TMDB连通性把

请问您那个实验室的选项是怎么设置的呀？都开了哪个增强识别呢？

**Comment by hsuyelin** [comment]
<img width="1345" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/8cd98bcb-a1fa-4b7e-8dde-b3de1be7d5c8">

**Comment by ssmengyan** [comment]
> <img alt="image" width="1345" src="https://user-images.githubusercontent.com/17918063/268486753-8cd98bcb-a1fa-4b7e-8dde-b3de1be7d5c8.png">
> chatgpt没有的话可以不开，增强识别v2可以解决一些命名不规范的

感谢，已经成功识别到了！
