### ISSUE TITLE
[错误报告]: 微信通知中不选择“数据统计”选项，仍会推送“站点数据统计”消息到微信

### ISSUE THREAD

**Issue by LoSiTeE** [hsuyelin/nas-tools#287]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

主程序运行问题

### 问题描述

如题，另外，“设置-服务-站点数据刷新时间”中设置的运行时间好像是无效的，nt不会按照设置进行统计。

**Comment by hsuyelin** [comment]
我没有勾选数据统计，也不会给我推送，建议自查或者是贴上完整的日志

<img width="692" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/2ee5dee1-a512-45f2-8750-3848447bfbd4">

**Comment by LoSiTeE** [comment]
> 我没有勾选数据统计，也不会给我推送，建议自查或者是贴上完整的日志
> 
> <img alt="image" width="692" src="https://user-images.githubusercontent.com/17918063/268505714-2ee5dee1-a512-45f2-8750-3848447bfbd4.png">

我刚把微信通知的代理VPS实例删除，并重新安装了nginx。然后重新启动了nastool容器。
我再观察两天，有问题再来反馈。
