### ISSUE TITLE
[功能改进]: 请求索引器添加支持"片源网"

### ISSUE THREAD

**Issue by sebastian0619** [hsuyelin/nas-tools#288]
### 当前程序版本

3.3.7

### 功能改进

请求添加索引器支持：片源网(https://pianyuan.org/)

是一个挺不错的半公开资源站。资源上线及时，且支持的比较全

**Comment by jackloves111** [comment]
这种会员式的一般不会添加的，目前BT以jackett为主，自带的索引BT应该不会再加了

**Comment by hsuyelin** [comment]
如楼上所说
