### ISSUE TITLE
添加订阅不会提示

### ISSUE THREAD

**Issue by xiaobaiwaf** [hsuyelin/nas-tools#289]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.7

### 问题类型

主程序运行问题

### 问题描述

添加电影，电视剧订阅不会通知，不知道是不是bug，之前官方版也是这样，是哪里设置有问题吗

**Comment by hsuyelin** [comment]
没有勾选消息通知吧

**Comment by xiaobaiwaf** [comment]
勾选了，很奇怪，我用jellyseere第三方订阅有通知，直接在nt上就不行，之前用原版也是，换了这个版本也是不会通知...

**Comment by hsuyelin** [comment]
应该是你设置的问题，参照wiki吧，我用的高德很，后面我嫌太吵了我都关了
