### ISSUE TITLE
[错误报告]: v2识别和自定义字幕组插件不兼容

### ISSUE THREAD

**Issue by MangMax** [hsuyelin/nas-tools#291]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

插件问题

### 问题描述

开启v2增强识别后，发现动漫的字幕组被识别到名称里面去了，随后我在自定义字幕组插件中加入字幕组名称发现字幕组仍然被识别到名称内，关闭v2增强识别恢复正常，未开启其他的辅助识别选项

**Comment by hsuyelin** [comment]
识别不正常的名称看看

**Comment by MangMax** [comment]
[Sakurato] Spy x Family [14][AVC-8bit 1080p AAC][CHS].mp4
![image](https://github.com/hsuyelin/nas-tools/assets/68525017/f1e911ea-5254-4979-9fc3-c6674bd4c6af)
[DMG&LoliHouse] Spy x Family - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
![image](https://github.com/hsuyelin/nas-tools/assets/68525017/74735c27-8525-43b6-b191-4998157814fa)
两个结构差不多的文件，同样开启v2的情况下第一个无法正确识别

**Comment by hsuyelin** [comment]
<img width="857" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/996d72b8-4a92-48c5-9632-61995d9e9102">
<img width="759" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/cd6758e4-313b-4219-a923-abb3c875b2e7">

善用自定义识别词

<img width="1344" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/1bfeead7-f07f-4183-a48f-a7b9029416db">
