### ISSUE TITLE
探索TMDB图片不显示

### ISSUE THREAD

**Issue by hh0610** [hsuyelin/nas-tools#292]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.38

### 问题类型

主程序运行问题

### 问题描述

![1694951435104](https://github.com/hsuyelin/nas-tools/assets/142991330/a03ce10f-de4a-403c-9b6b-ef1037cceeb4)
已经挂了代理

**Comment by hsuyelin** [comment]
代理不够给力，能显示则说明，部分请求成功了
