### ISSUE TITLE
[错误报告]: 没有明确季度时识别错误

### ISSUE THREAD

**Issue by MangMax** [hsuyelin/nas-tools#293]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.7

### 问题类型

主程序运行问题

### 问题描述

以鬼灭之刃为例，他一共四季，但是名称以篇名命名
![image](https://github.com/hsuyelin/nas-tools/assets/68525017/0f55666a-1709-4dea-b576-13c4c08e7567)
使用mikan作为索引器搜索是搜不到的，因为文件名没有写季度而是篇名，同样手动下载好之后识别也无法识别篇名，全都识别成第一季了，目前只能是手动添加规则来解决了，这种特殊的是否有办法自动识别
![image](https://github.com/hsuyelin/nas-tools/assets/68525017/1ec6223b-492c-472e-b43f-9f50a96017ed)

**Comment by hsuyelin** [comment]
不说其他的，不给你看TMDB，且你没看过鬼灭之刃，你知道游郭篇是第几季么 😂

**Comment by MangMax** [comment]
> 不说其他的，不给你看TMDB，且你没看过鬼灭之刃，你知道游郭篇是第几季么 😂，人都做不到，你指望代码做得到么，代码不是万能的

有没有可能识别的时候根据tmdb上的信息匹配文件名、季度、年份和级数之类的辅助识别，其实不止这种情况，有时候一个剧其实只有一季，但是是分时段出的，字幕组在文件名上就会人为写上季度，而级数又是接着的不是从第一级开始，识别的时候就会出现好几季，然后里面的级数就是断开的了，并且这些全都不能被正确刮削，最主要的是当分错季度时就无法刮削了

**Comment by hsuyelin** [comment]
> > 不说其他的，不给你看TMDB，且你没看过鬼灭之刃，你知道游郭篇是第几季么 😂，人都做不到，你指望代码做得到么，代码不是万能的
> 
> 有没有可能识别的时候根据tmdb上的信息匹配文件名、季度、年份和级数之类的辅助识别，其实不止这种情况，有时候一个剧其实只有一季，但是是分时段出的，字幕组在文件名上就会人为写上季度，而级数又是接着的不是从第一级开始，识别的时候就会出现好几季，然后里面的级数就是断开的了，并且这些全都不能被正确刮削，最主要的是当分错季度时就无法刮削了

这种情况毕竟少，改的话可能影响其他的，建议手动识别词稳妥一点
