### ISSUE TITLE
v2 无法识别

### ISSUE THREAD

**Issue by FireGodson** [hsuyelin/nas-tools#294]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.9

### 问题类型

其他问题

### 问题描述

v2增强识别无法识别类似第一张图片中的标题，关闭后正常识别转移
![20230918_121604](https://github.com/hsuyelin/nas-tools/assets/32048420/52c49374-6602-477c-ab23-e18ba7f5b21c)
![image](https://github.com/hsuyelin/nas-tools/assets/32048420/7d945c3c-d937-4417-af2e-da0475a36cb8)

**Comment by hsuyelin** [comment]
自定义识别词，\[Skymoon-Raws\] –> Skymoon-Raws ，后面我在优化下

**Comment by FireGodson** [comment]
好的，谢谢大佬啦

**Comment by FireGodson** [comment]
你好，加上了自定义识别词后依旧没法识别集数，关闭后可以正常识别出集数，第一张是打开的只能识别出季无法识别集数，关闭后能正常识别
![20230918_101607](https://github.com/hsuyelin/nas-tools/assets/32048420/25f2e5dd-dff2-4fb0-bbac-236e9cd6c07f)
![20230918_101638](https://github.com/hsuyelin/nas-tools/assets/32048420/3a5a92f0-c956-47e0-89f1-1691e6ab8785)
