### ISSUE TITLE
朱雀站点cookie一直失效，且站点开启浏览器仿真后连通性测试一直在进行。

### ISSUE THREAD

**Issue by xiaobaiwaf** [hsuyelin/nas-tools#295]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

朱雀战点连通性cookie一直失效，即使是刚刚更换，所有站点开启仿真后，连通性测试都没有结果，一直在转圈
![image](https://github.com/hsuyelin/nas-tools/assets/97422881/c184fb5f-5e7e-4a08-9209-483bafd82073)

**Comment by hsuyelin** [comment]
日志看下

**Comment by xiaobaiwaf** [comment]
额，测试连通性，看不到日志，开启仿真又可以了，前几天开启仿真一直转圈，我再观察观察，看看会不会复现
