### ISSUE TITLE
爬取豆瓣封面失效

### ISSUE THREAD

**Issue by 1229574757** [hsuyelin/nas-tools#3]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.4 9ab1e5e
>
> 环境: docker
>

## 你遇到什么问题了？

> 探索板块中，豆瓣电影、豆瓣电视墙获取封面失效（可能跟最近豆瓣接口升级有关）

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 浏览无发现解决方案，可能由于是最近豆瓣接口升级有关

## 你期望的结果

> 希望可能更新爬取豆瓣部分代码，让封面能正常显示

## 给出程序界面截图、后台运行日志或配置文件
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/4f3741b9-c50d-4be5-8972-25cd7a661302)

**Comment by hsuyelin** [comment]
已经提交，请等待3.2.5版本发布

**Comment by hsuyelin** [comment]
> 已经提交，请等待3.2.5版本发布

已发布
