### ISSUE TITLE
[功能改进]: 关于出现了同年,英文同名搜索的问题

### ISSUE THREAD

**Issue by Teddy-Zhu** [hsuyelin/nas-tools#301]
### 当前程序版本

3.3.9

### 功能改进

今天下载剧集时出现的问题

那些回不去的年少时光 , Stand By Me, 2023

tmdb 中 抉择 ,Stand By Me ,2023 两者同名 ,代码中直接匹配名称和 首播年份相同就返回了 ,实际上origin_name 不同 

简单看了下 可以继续判断月份, 或者传入副标题, 匹配origin_name ,但是这样改动较大,因为对nastools代码不熟悉,不知道会不会产生其他副作用,想问问还有什么其他好的方式解决这个问题

**Comment by hsuyelin** [comment]
抽空看看，是个好问题

**Comment by hsuyelin** [comment]
但其实可以用自定义识别词解决，这种情况并不常见

**Comment by Teddy-Zhu** [comment]
> 但其实可以用自定义识别词解决，这种情况并不常见

是的, 理论上可以直接替换为中文名,不过就是不怎么优雅, 不过是不常见
