### ISSUE TITLE
[功能改进]: 希望提供一个开关,刮削时候简介内容不使用CDATA标签

### ISSUE THREAD

**Issue by HankunYu** [hsuyelin/nas-tools#302]
### 当前程序版本

v3.3.9 d95848c

### 功能改进

infuse无法识别CDATA字段导致简介空白...希望可以有一个开关去选择不使用createCDATASection...
我知道这个是infuse的问题,而且贼蠢...但还是希望有一个可以方便一点

### 参考资料

<img width="1229" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/11606969/8098ca84-6ce2-49e3-85de-f8a08d22f249">
<img width="1229" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/11606969/f4a78fe5-e49c-40c3-b1fa-fd1c1e9a9f66">
分别是在nfo文件里存在与删除了cdata标签...

**Comment by HankunYu** [comment]
如果有人遇到跟我一样的问题...
```
import os

def replace_cdata_tags(file_path):
    with open(file_path, 'r') as file:
        content = file.read()

    # 替换 CDATA 标签
    content = content.replace('<![CDATA[', '').replace(']]>', '')

    with open(file_path, 'w') as file:
        file.write(content)

def process_nfo_files():
    # 获取当前目录下的所有 .nfo 文件
    files = [file for file in os.listdir() if file.endswith('.nfo')]

    for file in files:
        replace_cdata_tags(file)
        print(f'{file} 处理完成')

process_nfo_files()
```

可以用这个先将就一下

**Comment by HankunYu** [comment]
如果有人遇到跟我一样的问题 可以用这个先将就下
```
import os

def replace_cdata_tags(file_path):
    with open(file_path, 'r') as file:
        content = file.read()

    # 替换 CDATA 标签
    content = content.replace('<![CDATA[', '').replace(']]>', '')

    with open(file_path, 'w') as file:
        file.write(content)

def process_nfo_files():
    # 获取当前目录下的所有 .nfo 文件
    files = [file for file in os.listdir() if file.endswith('.nfo')]

    for file in files:
        replace_cdata_tags(file)
        print(f'{file} 处理完成')

process_nfo_files()
```

**Comment by hsuyelin** [comment]
这个不通用啊，两者只能取其一，建议还是本地跑脚本？因为大部分人都是emby或者jellyfin作为媒体服务器的

**Comment by jackloves111** [comment]
兄弟，你是媒体库直接用的SMB吗？

如果是的，我建议你用jellyfin建库，然后再添加jellyfin，应该就不会有这种问题了吧！

**Comment by HankunYu** [comment]
> 兄弟，你是媒体库直接用的SMB吗？
> 
> 如果是的，我建议你用jellyfin建库，然后再添加jellyfin，应该就不会有这种问题了吧！

我用的plex加infuse,jellyfin字幕显示有问题,emby太丑....
不加cdata plex能识别,jellyfin跟emby不清楚.
看起来就只能自己跑脚本了..
