### ISSUE TITLE
[疑问]: 不能用原版的配置直接运行新版本吗。

### ISSUE THREAD

**Issue by SouLXH** [hsuyelin/nas-tools#303]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

从原版3.2.2升级到v3.3.9
升级后无法启动

config文件不兼容吗。似乎只能重新配置了，pt也要重新添加了。

### 发生问题时系统日志和配置文件

```bash
正在加载配置：/config/config.yaml
正在加载flask环境变量: /nas-tools/.flaskenv
NAStool 当前版本号：v3.3.9
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新失败：(sqlite3.OperationalError) duplicate column name: LOCATING
[SQL: ALTER TABLE "CONFIG_SYNC_PATHS" ADD COLUMN "LOCATING" INTEGER]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
开始初始化数据...
数据初始化完成
开始启动服务...
```

**Comment by hsuyelin** [comment]
和config配置没关系，和数据库有关系，没针对原版直接做数据库迁移，或者你先升级到3.3.8，然后在升级到3.3.9

**Comment by SouLXH** [comment]
> 和config配置没关系，和数据库有关系，没针对原版直接做数据库迁移，或者你先升级到3.3.8，然后在升级到3.3.9

感谢回复，那我尝试一下，先升级3.3.8.

**Comment by SouLXH** [comment]
成功，v3.3.8 用原版/config，正常启动
