### ISSUE TITLE
搜索有问题，比如搜索「汉武大帝」[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by lovek8s** [hsuyelin/nas-tools#305]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9 36ea822

### 问题类型

主程序运行问题

### 问题描述

基本很多站都有这个资源，但是资源搜索不到，汉武大帝

### 发生问题时系统日志和配置文件

```bash
11
```

**Comment by lovek8s** [comment]
11

**Comment by hsuyelin** [comment]
请补充日志

**Comment by hsuyelin** [comment]
自定义识别词：

[hH][aA][nN]\s*[wW][uU]\s*[dD][aA]\s*[dD][iI] -> 汉武大帝

有问题先自己通过日志分析下，在issue
