### ISSUE TITLE
[错误报告]: 站点资源部份站点（咖啡、冰淇淋、猪猪、exoticaz）解析不到副标题、是否免费、发布时间等信息

### ISSUE THREAD

**Issue by jiezaizone** [hsuyelin/nas-tools#308]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/28976666/68f1eea1-207e-49ac-a119-2f679f307bc9)
![image](https://github.com/hsuyelin/nas-tools/assets/28976666/786abad8-ee92-461c-9f94-68c3e356c602)
![image](https://github.com/hsuyelin/nas-tools/assets/28976666/09fea2d6-7935-4174-be8f-1ee6d790d624)
![image](https://github.com/hsuyelin/nas-tools/assets/28976666/9fab13af-5f04-4218-a348-ad4565d5fcb2)
如截图所示，部分站点（猪猪、冰淇淋、咖啡）在站点资源页面访问，解析缺少副标题、是否免费、发布时间等信息。
exoticaz在站点资源访问不到资源，cookie、ssr更新过的，记得之前有个版本是可以访问到的（好像有个jackett添加后也可以在站点资源这里显示并访问），后面更新就没有了

**Comment by hsuyelin** [comment]
站点的种子页面，打包发上来，可以帮忙适配

**Comment by jiezaizone** [comment]
> 站点的种子页面，打包发上来，可以帮忙适配

种子页面是RSS地址吗？

**Comment by jiezaizone** [comment]
> 站点的种子页面，打包发上来，可以帮忙适配

还是torrents地址？
https://ptcafe.club/attendance.php
https://www.icc2022.com/torrents.php
https://piggo.me/torrents.php
https://exoticaz.to/torrents

**Comment by hh0610** [comment]
> > 站点的种子页面，打包发上来，可以帮忙适配
> 
> 还是torrents地址？ 咖啡： https://ptcafe.club/torrents.php 冰淇淋： https://www.icc2022.com/torrents.php 猪猪： https://piggo.me/torrents.php exoticaz： https://exoticaz.to/torrents

在种子页面查看源代码，然后把源代码复制到txt文本里面

**Comment by jiezaizone** [comment]
> > > 站点的种子页面，打包发上来，可以帮忙适配
> > 
> > 
> > 还是torrents地址？ 咖啡： https://ptcafe.club/torrents.php 冰淇淋： https://www.icc2022.com/torrents.php 猪猪： https://piggo.me/torrents.php exoticaz： https://exoticaz.to/torrents
> 
> 在种子页面查看源代码，然后把源代码复制到txt文本里面

[归档.zip](https://github.com/hsuyelin/nas-tools/files/12672468/default.zip)
请查收

**Comment by iovejieba** [comment]
ex...我在sites那边项目发过  貌似大佬一直没工夫看

**Comment by hsuyelin** [comment]
> > > > 站点的种子页面，打包发上来，可以帮忙适配
> > > 
> > > 
> > > 还是torrents地址？ 咖啡： https://ptcafe.club/torrents.php 冰淇淋： https://www.icc2022.com/torrents.php 猪猪： https://piggo.me/torrents.php exoticaz： https://exoticaz.to/torrents
> > 
> > 
> > 在种子页面查看源代码，然后把源代码复制到txt文本里面
> 
> [归档.zip](https://github.com/hsuyelin/nas-tools/files/12672468/default.zip) 请查收

抽空适配下，最近有点忙碌

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/e72798a1-7cdc-44d6-8429-3d270b84ff8b)

@jiezaizone 大概好了，其他的没有站点，我测试不了

**Comment by jiezaizone** [comment]
> ![image](https://user-images.githubusercontent.com/17918063/269891261-e72798a1-7cdc-44d6-8429-3d270b84ff8b.png)
> 
> @jiezaizone 大概好了，其他的没有站点，我测试不了

好的感谢大佬，等更新后我再试试
