### ISSUE TITLE
已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点

### ISSUE THREAD

**Issue by Juway111** [hsuyelin/nas-tools#31]
已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点，新提交的代码，已经增加了馒头新域名，江苏的朋友也可以使用nastool了

**Comment by iovejieba** [comment]
> 已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点，新提交的代码，已经增加了馒头新域名，江苏的朋友也可以使用nastool了

那么问题来了....额  爬取字典是类json？

**Comment by hsuyelin** [comment]
> 已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点，新提交的代码，已经增加了馒头新域名，江苏的朋友也可以使用nastool了

Cool，感谢

**Comment by Juway111** [comment]
你好，我想问下，用base64加密的话，是不是可以解码后用文本格式编辑，再编译即可？如果是的，感觉这样确实方便多了，我之前还用python解码。实在是繁琐 @hsuyelin

**Comment by hsuyelin** [comment]
@Juway111 不要轻易暴露细节，有些人看不懂，你猜想的是对的，我没有很多PT站，我改成那种方式方便你，你要有资源你维护就好了

**Comment by hsuyelin** [comment]
@Juway111 你那个评论我删除了

**Comment by hsuyelin** [comment]
@iovejieba @Juway111 大佬们有药的话，可以给我一个，方便我测试

**Comment by Juway111** [comment]
惊呆了，你维护这个项目竟然连PT站点都没有的吗？留个邮箱吧，找个好点的给你

**Comment by hsuyelin** [comment]
> 竟然连PT站点都没有的吗？

我只有馒头

**Comment by Juway111** [comment]
好的，我在外面，回去看看哪个能发的

**Comment by hsuyelin** [comment]
> 好的，我在外面，回去看看哪个能发的

感谢

**Comment by iovejieba** [comment]
> > 好的，我在外面，回去看看哪个能发的
> 
> 感谢

我也是只混了mt 大兄弟要mt的话喊我就行

**Comment by TonyLiooo** [comment]
BTSCHOOL资源也挺好的

**Comment by jackloves111** [comment]
@hsuyelin 已经发你邮箱，预注册ID是hsuyelin，邮箱是你的163，收到了说一声，祝你玩得开心

**Comment by hsuyelin** [comment]
感谢感谢，刚才查看邮箱收到了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月09日 12:01 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点 (Issue #31) |

@hsuyelin 已经发你邮箱，预注册ID是hsuyelin，邮箱是你的163，收到了说一声，祝你玩得开心

**Comment by hsuyelin** [comment]
> > 已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点，新提交的代码，已经增加了馒头新域名，江苏的朋友也可以使用nastool了
> 
> 大佬,按json添加的话 json校验没问题 但加入后发现 没free... 上加json参数 config 加free hr判断 这个逻辑应该没错吧.... 照着原列子 加了肉丝... 发现貌似刷流还是没有free判断... 有点诡异不知问题出在哪

加的不对，一个indexer是索引器，一个是正则取出free，我知道怎么加，可我没有肉丝，话说肉丝是什么站？瑟瑟就达咩

**Comment by iovejieba** [comment]
> > > 已经找到增加站点，修改站点的方法，理论上只要知道站点的爬取字典，就可以增加任何站点，新提交的代码，已经增加了馒头新域名，江苏的朋友也可以使用nastool了
> > 
> > 
> > 大佬,按json添加的话 json校验没问题 但加入后发现 没free... 上加json参数 config 加free hr判断 这个逻辑应该没错吧.... 照着原列子 加了肉丝... 发现貌似刷流还是没有free判断... 有点诡异不知问题出在哪
> 
> 加的不对，一个indexer是索引器，一个是正则取出free，我知道怎么加，可我没有肉丝，话说肉丝是什么站？瑟瑟就达咩

额  倒不是一定rousi....就是隔壁jspn  我按照对比法...加完 我发现貌似并没有生效  json校验倒是没问题 等会我在加下看看  正好不是有提issues加朱雀的么....
