### ISSUE TITLE
[功能改进]: 下载/转移类型能否扩展个音乐支持？

### ISSUE THREAD

**Issue by jiezaizone** [hsuyelin/nas-tools#310]
### 当前程序版本

v3.3.9

### 功能改进

![image](https://github.com/hsuyelin/nas-tools/assets/28976666/1a644552-d0b5-4338-84ca-d11cecda0981)
下载类型这里，只有电影、电视剧、动漫这三大选项，但有时候下载的是音乐，想单独给音乐归类目录存储，能否帮忙给支持扩展个音乐类型。要是能够支持音乐的刮削分类转移就再好不过了

**Comment by hsuyelin** [comment]
没有计划支持支持音乐类型，因为会与音轨文件冲突，且没有免费公开的音乐刮削器api支持
