### ISSUE TITLE
[功能改进]: 希望可以给一个大家api.themoviedb.org中转的方案

### ISSUE THREAD

**Issue by edu-hui** [hsuyelin/nas-tools#314]
### 当前程序版本

V3.3.9

### 功能改进

连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/multi?api_key=71dd70f36886******6b89c&include_adult=false&query=creation&language=en (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1a40b0a5f0>, 'Connection to api.themoviedb.org timed out. (connect timeout=10)'))
最近经常出现这个问题，所以希望有这样一个方案我可以通过hk服务器搭建一个中转

**Comment by jackloves111** [comment]
你都有能力搭建中转服务了，为什么不能用代理去连接呢？

**Comment by edu-hui** [comment]
> 你都有能力搭建中转服务了，为什么不能用代理去连接呢？

用代理需要过强，小猫咪啥的用多了不好

**Comment by ssmengyan** [comment]
> > 你都有能力搭建中转服务了，为什么不能用代理去连接呢？
> 
> 用代理需要过强，小猫咪啥的用多了不好

有啥不好的，怕被查水表吗

**Comment by iovejieba** [comment]
为爱发电可以，但让作者为爱捐服务器做中转，亲 自己挂吧 少看xwlb 没那么多事 莫怕 只要你不是轮子

**Comment by edu-hui** [comment]
> 为爱发电可以，但让作者为爱捐服务器做中转，多少差事了...亲 自己挂吧 .没那么多事 莫怕 只要你不是轮子，再不济自己度娘找个host执行脚本 24小时检dnscheck一次域名有变化就自动写host

主要是现在没有位置换，图片的刮削我们可以自己换，但是那个api不行呀，我已经搭建好了目前mp正常使用，但是这边我没有找到可以换的地方。

**Comment by hsuyelin** [comment]
可以，我可以给一个入口手动填写

**Comment by edu-hui** [comment]
> 可以，我可以给一个入口手动填写

谢谢大佬

**Comment by hsuyelin** [comment]
已添加
