### ISSUE TITLE
[功能改进]: 优先使用英文名搜索

### ISSUE THREAD

**Issue by code170202** [hsuyelin/nas-tools#315]
### 当前程序版本

3.3.9

### 功能改进

过去的版本，如3.2.3的时候，是存在一个优先使用英文名搜索的功能。
疑似有这个功能时，搜，封神第一部这部剧能正常搜到。
而3.3.9必须增加自定义识别词才能搜到。

**Comment by code170202** [comment]
补充：当时没开v2识别，开了以后也能搜到

**Comment by GavinIves** [comment]
是的 确实需要优先英文搜索 我也发现了这个问题 搜索到的资源变少了 很多站都是英文命名的 就搜不到了

**Comment by code170202** [comment]
> 是的 确实需要优先英文搜索 我也发现了这个问题 搜索到的资源变少了 很多站都是英文命名的 就搜不到了

希望能恢复

**Comment by hsuyelin** [comment]
> 补充：当时没开v2识别，开了以后也能搜到

我开了V2可以搜得到啊，你的意思是没开V2就搜不到是吧

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/d8da1a1e-56c8-4b41-aad3-4952598d0820)

**Comment by code170202** [comment]
> > 补充：当时没开v2识别，开了以后也能搜到
> 
> 我开了V2可以搜得到啊，你的意思是没开V2就搜不到是吧

是的，这个应该是tmdb的名字被改好了。
开了v2确实好很多，但是优先使用英文名，是不是与这个只有互补

**Comment by GavinIves** [comment]
是的 用英文搜索成功率肯定会比中文高 或者考虑搜索的时候查两遍 一遍中文一遍英文

**Comment by hsuyelin** [comment]
> > > 补充：当时没开v2识别，开了以后也能搜到
> > 
> > 
> > 我开了V2可以搜得到啊，你的意思是没开V2就搜不到是吧
> 
> 是的，这个应该是tmdb的名字被改好了。 开了v2确实好很多，但是优先使用英文名，是不是与这个只有互补

没关系的，会自动检测关键词，如果输入的关键词以英文为准就会优先搜索英文

**Comment by code170202** [comment]
> > > > 补充：当时没开v2识别，开了以后也能搜到
> 
> > > 
> 
> > > 
> 
> > > 我开了V2可以搜得到啊，你的意思是没开V2就搜不到是吧
> 
> > 
> 
> > 是的，这个应该是tmdb的名字被改好了。 开了v2确实好很多，但是优先使用英文名，是不是与这个只有互补
> 
> 
> 
> 没关系的，会自动检测关键词，如果输入的关键词以英文为准就会优先搜索英文

问题主要在3个地方，订阅，主动查询，下载完成后的识别，感觉优先使用英文名搜索还是有必要的，以前3.2.3的时候，大家默认都是开的这个，识别率会有较大提升

**Comment by hsuyelin** [comment]
> > > > > 补充：当时没开v2识别，开了以后也能搜到
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我开了V2可以搜得到啊，你的意思是没开V2就搜不到是吧
> > 
> > 
> > > 
> > 
> > 
> > > 是的，这个应该是tmdb的名字被改好了。 开了v2确实好很多，但是优先使用英文名，是不是与这个只有互补
> > 
> > 
> > 没关系的，会自动检测关键词，如果输入的关键词以英文为准就会优先搜索英文
> 
> 问题主要在3个地方，订阅，主动查询，下载完成后的识别，感觉优先使用英文名搜索还是有必要的，以前3.2.3的时候，大家默认都是开的这个，识别率会有较大提升

可以把，下个版本恢复

**Comment by code170202** [comment]
> > > > > > 补充：当时没开v2识别，开了以后也能搜到
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 我开了V2可以搜得到啊，你的意思是没开V2就搜不到是吧
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 是的，这个应该是tmdb的名字被改好了。 开了v2确实好很多，但是优先使用英文名，是不是与这个只有互补
> > > 
> > > 
> > > 没关系的，会自动检测关键词，如果输入的关键词以英文为准就会优先搜索英文
> > 
> > 
> > 问题主要在3个地方，订阅，主动查询，下载完成后的识别，感觉优先使用英文名搜索还是有必要的，以前3.2.3的时候，大家默认都是开的这个，识别率会有较大提升
> 
> 可以把，下个版本恢复

多谢多谢，辛苦。

**Comment by hsuyelin** [comment]
已添加下个版本
