### ISSUE TITLE
[错误报告]: 标题中如果有罗马数字，不一定能识别

### ISSUE THREAD

**Issue by cng10001** [hsuyelin/nas-tools#317]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.8

### 问题类型

其他问题

### 问题描述

看似标题中都是同样的罗马数字，但是实际识别或者订阅的时候会有差异、大家帮忙看看，以下图中框选的2个标题为例子
![360截图20230921200558466](https://github.com/hsuyelin/nas-tools/assets/115156545/08c37878-3924-44ff-a746-bad67ee00400)
**ourtv版不能被识别，chdweb版可以被识别** 但个人感觉标题中片名是一样的。

> ourtv

![Snipaste_2023-09-21_19-12-27](https://github.com/hsuyelin/nas-tools/assets/115156545/4d2354fe-26fe-4cc1-af71-f53780b47a6c)

> chdweb

![Snipaste_2023-09-21_19-09-27](https://github.com/hsuyelin/nas-tools/assets/115156545/465bcffc-51d8-443e-b87f-1e5dbe09292e)
**是实际识别过程中，看似相同的罗马数字在似乎被识别成了不同字符↓**
![Snipaste_2023-09-21_20-04-02](https://github.com/hsuyelin/nas-tools/assets/115156545/135fef8c-4435-4cde-bbfd-de0ae462b6bc)
![Snipaste_2023-09-21_20-07-05 拷贝](https://github.com/hsuyelin/nas-tools/assets/115156545/46da30fe-d0b0-4390-b759-955828537728)
_把ourtv版在moviepilot中识别也有这个情况_ 但似乎在手动搜索是能显示ourtv版结果的
![Snipaste_2023-09-21_20-05-03](https://github.com/hsuyelin/nas-tools/assets/115156545/d9e62494-c8b7-408a-b130-8ec1294c2de2)

**Comment by hsuyelin** [comment]
笑死我了，一个是英文字母I，一个是罗马数字I，这都是哪个憨批编辑的标题

<img width="1171" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/c8e082c5-f0a1-4b77-9927-e802e0c98731">

**Comment by cng10001** [comment]
额， 复制到文档确实有点不同，但感觉也不是I，显示有点怪，可能是平台不同？
![Snipaste_2023-09-22_13-43-23](https://github.com/hsuyelin/nas-tools/assets/115156545/5abb08ba-9540-4012-bb80-5669135c2bff)
