### ISSUE TITLE
Invite all the big shots to join our project!

### ISSUE THREAD

**Issue by mantou568** [hsuyelin/nas-tools#32]
由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。

贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。
@hsuyelin @Juway111 @chengnan049 @DDSDerek 
我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！
我的邮箱：
xqxplm@gmail.com

为了保密，该Issues稍后将关闭！

**Comment by iovejieba** [comment]
> 由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。
> 
> 贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。 @hsuyelin @Juway111 @chengnan049 @DDSDerek 我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！ 我的邮箱： [xqxplm@gmail.com](mailto:xqxplm@gmail.com)
> 
> 为了保密，该Issues稍后将关闭！

亲....该说不说现在不是19年了  BT没啥公开站了，冲击力度及其有限  连rarbg 都走了...，过于私密化只是把路走窄了，个人言论仅供参考！

**Comment by hsuyelin** [comment]
> 由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。
> 
> 贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。 @hsuyelin @Juway111 @chengnan049 @DDSDerek 我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！ 我的邮箱： [xqxplm@gmail.com](mailto:xqxplm@gmail.com)
> 
> 为了保密，该Issues稍后将关闭！

有着某派派的先例，所以本项目维护一直处于低调状态，我本人从未在各个地方宣传本项目也未建立交流群，就是避免不必要的麻烦，为保证项目可持续发展确实需要做出一些努力，但是本人其实是爱好者，算是为爱发电，为了尽量让更多的普通人尽可能简单使用，我本人一直也在考虑如何平衡这一问题

**Comment by iovejieba** [comment]
> > 由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。
> > 贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。 @hsuyelin @Juway111 @chengnan049 @DDSDerek 我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！ 我的邮箱： [xqxplm@gmail.com](mailto:xqxplm@gmail.com)
> > 为了保密，该Issues稍后将关闭！
> 
> 有着某派派的先例，所以本项目维护一直处于低调状态，我本人从未在各个地方宣传本项目也未建立交流群，就是避免不必要的麻烦，为保证项目可持续发展确实需要做出一些努力，但是本人其实是爱好者，算是为爱发电，为了尽量让更多的普通人尽可能简单使用，我本人一直也在考虑如何平衡这一问题

感谢大佬为爱发电,现在的项目不过是让其他还在坚持nt的小伙伴有的玩而已，大家凑在一起测试 维护 完善 不过也都是让一个曾经开源的项目还能继续走下去而已，单纯  纯粹...

**Comment by Juway111** [comment]
纯个人意见：开源项目私有化，用得好是保护项目，用的不好，变成特权项目。工具没有错，错的只是使用他的人。再次感谢所有为项目付出的人，尤其感谢作者的无私奉献！

**Comment by mantou568** [comment]
> > 由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。
> > 贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。 @hsuyelin @Juway111 @chengnan049 @DDSDerek 我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！ 我的邮箱： [xqxplm@gmail.com](mailto:xqxplm@gmail.com)
> > 为了保密，该Issues稍后将关闭！
> 
> 有着某派派的先例，所以本项目维护一直处于低调状态，我本人从未在各个地方宣传本项目也未建立交流群，就是避免不必要的麻烦，为保证项目可持续发展确实需要做出一些努力，但是本人其实是爱好者，算是为爱发电，为了尽量让更多的普通人尽可能简单使用，我本人一直也在考虑如何平衡这一问题

嗯嗯，我们这边项目也是一群用爱发电的pter，只不过咱们更加隐秘战线罢了，采用私下邀请制，不公开，不宣传。我之所以注意到该项目，也是因为该项目已经在pter中传开了。

之所以我们采用隐秘战线，也是因为pt本身属于灰色产业，而pt圈内人员参差不齐。

再次感谢诸位大佬们还在维护该项目！不过也随时欢迎加入咱们的隐秘战线哈！毕竟你们现在是公开战线的维护者！

**Comment by mantou568** [comment]
> 纯个人意见：开源项目私有化，用得好是保护项目，用的不好，变成特权项目。工具没有错，错的只是使用他的人。再次感谢所有为项目付出的人，尤其感谢作者的无私奉献！如果要保护，可以给项目更名，替换README



> > 由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。
> > 贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。 @hsuyelin @Juway111 @chengnan049 @DDSDerek 我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！ 我的邮箱： [xqxplm@gmail.com](mailto:xqxplm@gmail.com)
> > 为了保密，该Issues稍后将关闭！
> 
> 亲....该说不说现在不是19年了 BT没啥公开站了，冲击力度及其有限 连rarbg 都走了...，过于私密化只是把路走窄了，个人言论仅供参考！

多元发展罢了，私密化有私密话的好处，公开由公开的好处。

**Comment by mantou568** [comment]
> 纯个人意见：开源项目私有化，用得好是保护项目，用的不好，变成特权项目。工具没有错，错的只是使用他的人。再次感谢所有为项目付出的人，尤其感谢作者的无私奉献！如果要保护，可以给项目更名，替换README

是的，所以才邀请各路愿意维护nt的开发们加入进来，虽然走向了隐秘战线，但是使用者和开发者都是开放态度的。

**Comment by hsuyelin** [comment]
@mantou568​ 多谢善意提醒和诚邀加入，BT基本已死的，使用这个项目的手上至少一个PT，如果有发现利用本项目包括但不限于违法、盈利等，我也会立刻删除该项目，我是既不想这个圈子乌烟瘴气，也想给普通的pter方便的，之后本人也会一直本着该目的不在互联网能到达的地方宣传本项目的初心，持续维护该项目，有什么需要帮助的地方也可以尽管提
---- Replied Message ----
| From | ***@***.***> |
| Date | 08/06/2023 13:37 |
| To | hsuyelin/nas-tools ***@***.***> |
| Cc | hsuyelin ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [hsuyelin/nas-tools] Invite all the big shots to join our project! (Issue #32) |

纯个人意见：开源项目私有化，用得好是保护项目，用的不好，变成特权项目。工具没有错，错的只是使用他的人。再次感谢所有为项目付出的人，尤其感谢作者的无私奉献！如果要保护，可以给项目更名，替换README

是的，所以才邀请各路愿意维护nt的开发们加入进来，虽然走向了隐秘战线，但是使用者和开发者都是开放态度的。

**Comment by DDSDerek** [comment]
> 由于【某派派】，擅自公布破解版的开源项目 NasTool3.x，导致 NasTool 作者停止维护了项目。 为了自己还能继续使用该工具，一群 pter 团结起来，自行继续维护该项目。基于 NT 继续出发，扬帆远航！ 目前已经经过是数十个迭代，项目发展良好。
> 
> 贵项目现在依旧是公开而开源，项目危险性高!为了改nt项目的长远发展，真诚邀请诸位大佬，加入我们的保密项目，让这个工具一直可持续下去。 @hsuyelin @Juway111 @chengnan049 @DDSDerek 我们的项目名称就不公布了，低调行事，目前只在PT圈，如有意向，请联系我们！ 我的邮箱： [xqxplm@gmail.com](mailto:xqxplm@gmail.com)
> 
> 为了保密，该Issues稍后将关闭！

这边向您发邮箱了，期待回复
