### ISSUE TITLE
[错误报告]: 请问一下为啥目录转移时提示这个报错

### ISSUE THREAD

**Issue by snow61520** [hsuyelin/nas-tools#323]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

Docker或运行环境问题

### 问题描述

有些媒体是正常的，有一些会报这个错，没找到原因
发生错误：'str' object has no attribute 'items' - Traceback (most recent call last): File "/nas-tools/app/media/media.py", line 994, in get_media_info_on_files meta_info.set_tmdb_info(file_media_info) File "/nas-tools/app/media/meta/_base.py", line 569, in set_tmdb_info self.category = self.category_handler.get_movie_category(info) File "/nas-tools/app/media/category.py", line 115, in get_movie_category return self.get_category(self._movie_categorys, tmdb_info) File "/nas-tools/app/media/category.py", line 149, in get_category for attr, value in item.items():

**Comment by hsuyelin** [comment]
偶发现象，已经做了容错
