### ISSUE TITLE
aria2下载服务连接失败

### ISSUE THREAD

**Issue by szicely** [hsuyelin/nas-tools#33]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v3.2.9.3
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

>Aria2 连接测试失败 试过下载出现提示连接aria服务器失败，http://192.168.123.1:6800/rpc
但我的aria2服务器应该是http://192.168.123.1:6800/jsonrpc

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>是

## 你期望的结果

> 希望修正

## 给出程序界面截图、后台运行日志或配置文件
![NAStool](https://github.com/hsuyelin/nas-tools/assets/140148567/8bcff630-315f-445c-ac39-6422c648fd82)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
@szicely 你这和aria2 地址是啥，我测试的项目是rpc的

**Comment by szicely** [comment]
rpc 是旧版本aria2的，新版本服务端是的jsonrpc, 在app/downloader/client/_pyaria2.py 第七行。

**Comment by szicely** [comment]
或者可以在设置aria2下载参数那里加一个可以自己选择的，旧版本的用rpc,新版本的用jsonrpc,不改一下我这连不上aria2服务器。

**Comment by hsuyelin** [comment]
> 或者可以在设置aria2下载参数那里加一个可以自己选择的，旧版本的用rpc,新版本的用jsonrpc,不改一下我这连不上aria2服务器。

![Xnip2023-08-06_14-57-50.png](https://pic8.58cdn.com.cn/nowater/webim/big/n_v20aa987d8b72b46a58f1a422ae3023c30.png)

已修复，稍等版本更新，用开关控制了，开启就是/jsonrpc

**Comment by szicely** [comment]
是的。这个问题其实最早的2.9版本就存在了，后来有个不知哪个的版改正过。但有其它问题和少更新我就没用，换了你的版本。

**Comment by hsuyelin** [comment]
> 是的。这个问题其实最早的2.9版本就存在了，后来有个不知哪个的版改正过。但有其它问题和少更新我就没用，换了你的版本。

你更新后试下

**Comment by szicely** [comment]
还是不行，提示500错误。<ProtocolError for 192.168.123.1:6800/jsonrpc: 500 Internal Server Error>

**Comment by szicely** [comment]
我服务器在chrome的aria2的插件上是可以连通的。

**Comment by szicely** [comment]
这是我chrome上的aria2插件上的连接rpc的设置。chrome上的插件是可以连接我的aria服务端的。
![下载-0-00-B-s-上传-0-00-B-s-AriaNg](https://github.com/hsuyelin/nas-tools/assets/140148567/ed9cd2de-7897-460e-880b-146cfae42a70)
你看一下会不会关http？还是POST的关系？

**Comment by hsuyelin** [comment]
> 这是我chrome上的aria2插件上的连接rpc的设置。chrome上的插件是可以连接我的aria服务端的。
> ![下载-0-00-B-s-上传-0-00-B-s-AriaNg](https://user-images.githubusercontent.com/140148567/258630945-ed9cd2de-7897-460e-880b-146cfae42a70.png)
> 你看一下会不会关http？还是POST的关系？

在外面，我回去部署一下aria2，测试完了再部署上来

**Comment by szicely** [comment]
好的，谢谢。post 方式是aria2 v1.15.2以上才有效的。

**Comment by hsuyelin** [comment]
> 好的，谢谢。post 方式是aria2 v1.15.2以上才有效的。

![02.png](https://pic4.58cdn.com.cn/nowater/webim/big/n_v21ce1e9674518448a9a78f7122d281460.png)
![04.png](https://pic9.58cdn.com.cn/nowater/webim/big/n_v2b20c40cb8f484135b7621a7e16eea4ae.png)
![01.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v2447ee1f5556e4cabac6309afffa44f89.png)
![03.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v281b77fee910949b18be4b68362c22c04.png)
已调试好，等待发布新版本

**Comment by Juway111** [comment]
没玩过这个下载器，这个下载器是有什么优势吗？

**Comment by szicely** [comment]
> 没玩过这个下载器，这个下载器是有什么优势吗？

我的aria2是部署在我的x86路由器上的，主要是配合chrome浏览器的aria2插件一起用，可以很方便的在网页上看到BT连接直接点击传导到aria2服务器上下载，在安卓手机上也有客户端，也可以在手机的浏览器上直接传导到服务端。这样就可以在任何地方随时下载喜欢的。

**Comment by iovejieba** [comment]
> 没玩过这个下载器，这个下载器是有什么优势吗？

相对bt站点的话方便一些我记得链上之后可以直接post推送磁力过去应该是！

**Comment by szicely** [comment]
刚才更新了试了一下，aria2好象磁力可以下载了，但不能直接下载种子文件下载。报错
![NAStool (1)](https://github.com/hsuyelin/nas-tools/assets/140148567/f9bc53fe-a719-4eb3-ba6b-bdc61e2bef01)
![NAStool (2)](https://github.com/hsuyelin/nas-tools/assets/140148567/0b81894f-52ae-4c6c-8c6f-891369ad32a8)

**Comment by hsuyelin** [comment]
> 刚才更新了试了一下，aria2好象磁力可以下载了，但不能直接下载种子文件下载。报错
> ![NAStool (1)](https://user-images.githubusercontent.com/140148567/258654613-f9bc53fe-a719-4eb3-ba6b-bdc61e2bef01.png)
> ![NAStool (2)](https://user-images.githubusercontent.com/140148567/258654617-0b81894f-52ae-4c6c-8c6f-891369ad32a8.png)

什么索引器。下载的什么电影，选的哪条资源，补充一下 @szicely

**Comment by szicely** [comment]
索引器是我内建的jackett,我直接点击那个种子连接是可以在浏览器上下载种子的，证明应该不是我内建的jackett的问题。而且我用QB可以下载同一种子连接。但如果是磁力连接的就可以直接下载，磁力是一个网址，而种子应该算是一种文件。磁力应该aria把网址连接贴上就可以下载，而种子要先下载种子再用种子再下载文件。aria2可以卡在下载种子那步了。aria2下载种子可能是用http协议吧，
我纯是小白，以上都是我的猜测。

**Comment by szicely** [comment]
你可以找一个纯种子的站点试一下，我试过好象有种子和磁力两种的站点，它优先就用了磁力就可以下载了。有一些是只有纯种子的站点就报错。

**Comment by hsuyelin** [comment]
> 你可以找一个纯种子的站点试一下，我试过好象有种子和磁力两种的站点，它优先就用了磁力就可以下载了。有一些是只有纯种子的站点就报错。

哪一个是纯种子站点，我直接测试就好了

**Comment by szicely** [comment]
https://www.torlock2.com/torrent/65888277/love-never-ends-2023-1080p-web-dl-hc-h264-aac-gpthd.html

**Comment by szicely** [comment]
你试下这个站点，我就是用这个站点aria2下载不下来。

**Comment by hsuyelin** [comment]
> https://www.torlock2.com/torrent/65888277/love-never-ends-2023-1080p-web-dl-hc-h264-aac-gpthd.html
> 
> 你试下这个站点，我就是用这个站点aria2下载不下来。我先在资源搜索那里找到地址然后点击用ARIA下载，就出现报错 ![33ff6db6-60ad-48da-aed0-b254ade9a8b0](https://user-images.githubusercontent.com/140148567/258687477-06c33f34-a2ec-4a21-a4a0-7e7862bee928.png)
> 
> ![2f03dee2-dd57-4c6d-9b30-42938b48830f](https://user-images.githubusercontent.com/140148567/258688259-9afa7b2e-f964-456d-bafe-d7ce7507ee31.png) ![863d64e7-137b-4023-b153-203a199c8a80](https://user-images.githubusercontent.com/140148567/258688495-9b259748-0eea-4aab-9e1b-41d872618144.png)

已修复，等到3.2.9.8更新

**Comment by szicely** [comment]
感谢大大，已更新，可以下载了，暂时没有其它问题了。谢谢。
