### ISSUE TITLE
希望增加一个我的媒体库和最新入库的筛选器

### ISSUE THREAD

**Issue by TonyLiooo** [hsuyelin/nas-tools#34]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.9.8 2ea2025
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望增加一个我的媒体库和最新入库的筛选器，可以自己选择展示或者不展示的电视及电视剧

## 这个功能有什么可以参考的资料吗？

> 无参考资料，不知道大佬好不好实现，目前情况是什么电影、电视剧都展示出来，怎这选择，让使用者自己选择是挺好的

**Comment by jackloves111** [comment]
难道真的有人用nastool点进去看吗？不都是打开jellyfin看的吗

**Comment by jackloves111** [comment]
感觉这样改动，不如直<frame>   标签jellyfin的地址拉到

**Comment by hsuyelin** [comment]
@TonyLiooo 这种需求和项目不是和契合，先不增加该需求哈

**Comment by jackloves111** [comment]
你的药58万魔力还差5万魔力，等我努努力 @hsuyelin

**Comment by TonyLiooo** [comment]
> 难道真的有人用nastool点进去看吗？不都是打开jellyfin看的吗

不是点进去看，只是在别的地方打开，有些电视剧就是不想让人一眼就看到你最近在看什么，有的不合适小朋友或旁人看到影视展示出来，看到了也不是很好吧

**Comment by jackloves111** [comment]
这种库建议分开来，docker可以建很多jellyfin容器，你放一起本身就很危险

**Comment by TonyLiooo** [comment]
> 这种库建议分开来，docker可以建很多jellyfin容器，你放一起本身就很危险

就是有一点血腥，不是限制级难道也单独创建个容器吗？现在影视都知道做儿童模式，在电视端可以自己分类，但是nastool现在是全部都展示到一个界面上，这样在搜索时候难免会看到一些不好的，毕竟登录nastool第一个展示的就是影视库

**Comment by jackloves111** [comment]
其实恢复到2.9版的显示模式我觉得也可以，因为这个显示库的海报墙，我个人觉得其实没有什么作用

**Comment by TonyLiooo** [comment]
> 其实恢复到2.9版的显示模式我觉得也可以，因为这个显示库的海报墙，我个人觉得其实没有什么作用

是的，在2.9时候不会都展示出来的，这个海报墙对我来说我都没用到过，虽然展示出来显得美观一点，但是其实大家都不会从这点开影视

**Comment by iovejieba** [comment]
额 emby或者jellyfin新建用户 给指定目录就好了啊....不可能给娃 nastools的用户去登陆nastools啊 ....

**Comment by TonyLiooo** [comment]
> 额 emby或者jellyfin新建用户 给指定目录就好了啊....不可能给娃 nastools的用户去登陆nastools啊 ....

是的，肯定不会给小朋友登录进去，但想找影视的时候你会登录进去，如果在公司其它人不就都看到了吗，在车上的话，手机屏幕小朋友也能看得到

**Comment by iovejieba** [comment]
> > 额 emby或者jellyfin新建用户 给指定目录就好了啊....不可能给娃 nastools的用户去登陆nastools啊 ....
> 
> 是的，肯定不会给小朋友登录进去，但想找影视的时候你会登录进去，如果在公司其它人不就都看到了吗，在车上的话，手机屏幕小朋友也能看得到

额  这个不算刚性需求...可以尽量避免小朋友，或者找个chrome插件 屏蔽所有js加载  或者找类似屏蔽所有图片显示的方法  也可以有一定作用....

**Comment by jackloves111** [comment]
自定义css里面，把媒体库的css   img标签全都改掉，理论上可以，没试过，你可以试下

**Comment by TonyLiooo** [comment]
> > > 额 emby或者jellyfin新建用户 给指定目录就好了啊....不可能给娃 nastools的用户去登陆nastools啊 ....
> > 
> > 
> > 是的，肯定不会给小朋友登录进去，但想找影视的时候你会登录进去，如果在公司其它人不就都看到了吗，在车上的话，手机屏幕小朋友也能看得到
> 
> 额 这个不算刚性需求...可以尽量避免小朋友，或者找个chrome插件 屏蔽所有js加载 或者找类似屏蔽所有图片显示的方法 也可以有一定作用....

是的，不是刚性需求，所以只是个提议，当然是需要的人多了才增加

**Comment by iovejieba** [comment]
刚去翻了下,Block ImageVideo  chrome插件 可以屏蔽所有图片 视频显示....  如果移动端chrome不方便装插件  可以考虑用kiwi的浏览器   可以装插件

**Comment by TonyLiooo** [comment]
> 刚去翻了下,Block ImageVideo chrome插件 可以屏蔽所有图片 视频显示.... 如果移动端chrome不方便装插件 可以考虑用kiwi的浏览器 可以装插件，简单快捷 省心省力

屏蔽了所有图片，是不是连搜索的也一并屏蔽了呢

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/9cc9c46c-c1ad-4273-991a-f182cd079b95)
帮你写好了，自定义css里面填写这个，就可以关闭图片显示
```
.page-body img {
    display: none;
}
```
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/61b26ff3-98a5-4f9c-9729-9228316c0299)

**Comment by iovejieba** [comment]
> > 刚去翻了下,Block ImageVideo chrome插件 可以屏蔽所有图片 视频显示.... 如果移动端chrome不方便装插件 可以考虑用kiwi的浏览器 可以装插件，简单快捷 省心省力
> 
> 屏蔽了所有图片，是不是连搜索的也一并屏蔽了呢

jackloves111 大佬的方案 应该更实用...

**Comment by jackloves111** [comment]
> > 刚去翻了下,Block ImageVideo chrome插件 可以屏蔽所有图片 视频显示.... 如果移动端chrome不方便装插件 可以考虑用kiwi的浏览器 可以装插件，简单快捷 省心省力
> 
> 屏蔽了所有图片，是不是连搜索的也一并屏蔽了呢

不会，我屏蔽的是page-body下的img，跟其他页面的css无关

**Comment by iovejieba** [comment]
> > > 刚去翻了下,Block ImageVideo chrome插件 可以屏蔽所有图片 视频显示.... 如果移动端chrome不方便装插件 可以考虑用kiwi的浏览器 可以装插件，简单快捷 省心省力
> > 
> > 
> > 屏蔽了所有图片，是不是连搜索的也一并屏蔽了呢
> 
> 用我的方案，就不会，我屏蔽的是page-body下的img，跟其他页面的css无关，这个方法，理论上还可以优化加载速度，哈哈哈

感谢大佬....为爱发电...

**Comment by hsuyelin** [comment]
再看看有没有人提，不是刚性需求，只是也比较忙，提的人多了，我可以改改 @TonyLiooo

**Comment by hsuyelin** [comment]
> 你的药58万魔力还差5万魔力，等我努努力 @hsuyelin

哈哈哈哈，谢谢哥，我有馒头的，我想要个彩虹岛其实

**Comment by TonyLiooo** [comment]
> > 你的药58万魔力还差5万魔力，等我努努力 @hsuyelin
> 
> 哈哈哈哈，谢谢哥，我有馒头的，我想要个彩虹岛其实

这个应该很少邀的吧，会影响邀请人的

**Comment by hsuyelin** [comment]
<img width="1330" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/21629ff8-b2fb-4196-934a-7ac4d975a551">

<img width="1318" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/7c455024-5569-4c75-bd3c-4addd9b6b051">

@TonyLiooo 开启开关只显示正在观看

**Comment by TonyLiooo** [comment]
> <img alt="image" width="1330" src="https://user-images.githubusercontent.com/17918063/260456936-21629ff8-b2fb-4196-934a-7ac4d975a551.png"> <img alt="image" width="1318" src="https://user-images.githubusercontent.com/17918063/260457100-7c455024-5569-4c75-bd3c-4addd9b6b051.png">
> @TonyLiooo 开启开关只显示正在观看

感谢大佬！
