### ISSUE TITLE
[错误报告]: v2将电视剧[兰闺喜事]识别成了电影 麻烦的婚礼 导致无法订阅必须手动识别

### ISSUE THREAD

**Issue by jiezaizone** [hsuyelin/nas-tools#341]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/28976666/71a419f9-052c-4373-a866-761347c1a4b9)
v2[兰闺喜事]电视剧识别成了电影 麻烦的婚礼 (2017)

**Comment by felix-klk** [comment]
自己用自定义识别词拉

**Comment by hsuyelin** [comment]
增强识别v2或者自定义识别词

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/d66e4809-d953-465a-907f-4c75183d04bb)
