### ISSUE TITLE
 [错误报告]:重启后网站被拒绝访问

### ISSUE THREAD

**Issue by YichenYH** [hsuyelin/nas-tools#348]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版

### 问题类型

主程序运行问题

### 问题描述

重启后nastool主页无法进入，显示拒绝访问。要么就是连接重置，无论如何切换网络都是这俩。停用后重启，重启机器，都无法恢复

**Comment by YichenYH** [comment]
期间添加了https的证书（证书没问题）

**Comment by YichenYH** [comment]
今日实测卸载所有配置文件重装NASTOOL，重装的NASTOOL仍被拒绝访问

**Comment by flytigerzhang** [comment]
我也遇到了同样的问题，现在完全进不了软件页面，求助。
