### ISSUE TITLE
内建的索引器是否没有公开的站点选择的？

### ISSUE THREAD

**Issue by szicely** [hsuyelin/nas-tools#35]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v3.2.9.8
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 内建的索引器没有公开站点选择的吗？我记得以前旧版本好象有的。我前几天装过自定义索引器，后来我把它卸载了。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![index](https://github.com/hsuyelin/nas-tools/assets/140148567/16b00b46-ea7e-444a-9f49-d91adadf00cf)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/0e52231d-3926-4db6-8181-340e7dc0ce03)
ji基础设置，最后一个实验室，这个打开才有

**Comment by hsuyelin** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/258995318-0e52231d-3926-4db6-8181-340e7dc0ce03.png) ji基础设置，最后一个实验室，这个打开才有

正确的，一针见血的

**Comment by szicely** [comment]
谢谢，已经打开了可以了，大大，象https://www.bt-tt.com 这样的站点能不能够加到公开站点上，或者是可否自定义公开站点，因
我用jackett很多都是国外的站点国内的站点很多也没有中文资源。

**Comment by hsuyelin** [comment]
> 谢谢，已经打开了可以了，大大，象https://www.bt-tt.com 这样的站点能不能够加到公开站点上，或者是可否自定义公开站点，因 我用jackett很多都是国外的站点国内的站点很多也没有中文资源。

可以但没必要，内置一些BT就可以了，多的为啥不直接用jackett，或者prowlarr

**Comment by szicely** [comment]
我有用jackett,但总感觉那些索引对国内的资源不够快，或中文支持不够友好。象我要搜索最新的国产电视剧，在jackett上可能就要等一段时间。jackett 好象不可以自定义站点的，我是个新手，PT感觉用起来很麻烦又要刷流，又要考试之类的。而且之前没玩过PT类的。不是很懂。只想找些方便的公开站点，因为不是要经常下载电影或电视剧之类的，只是有最新的感兴趣的会用一下。
![c74383c3-7813-432c-b417-84db8eafcbf6](https://github.com/hsuyelin/nas-tools/assets/140148567/d7727ff1-7bba-4399-bb9c-8526993b07d2)

**Comment by jackloves111** [comment]
jackett可以自定义站点的，百度可以搜索到教程方法，至于你说的那个网站支不支持，我不确定

**Comment by szicely** [comment]
刚搜索了一下百度和google好象都没找到jackett 自定义公开站点

**Comment by iovejieba** [comment]
jackett，prowlarr 都可以自定义公开站好像，具体可以度娘或者谷歌看看

**Comment by iovejieba** [comment]
或者像TorrentLeech这种的话  可以自己加一下 就几行...方法的话...不方便公开  反正看看就懂了....

**Comment by szicely** [comment]
在网上完全找不到jackett自建站点的信息。在jackett上好象也只有添加它已经定义好的站点的选项，是否我找不到关键点？或有朋友知道要搜什么关键字麻烦告诉我一下，谢谢。

**Comment by szicely** [comment]
好象jackett自定义站点是不行的，要通过开发者添加，我在他们网站发了请求，不知能否加上。
![2bfe8771-4086-49e7-8d61-1326196b5315](https://github.com/hsuyelin/nas-tools/assets/140148567/438be4f0-0578-4afe-a9a5-e4d1db2ddfe9)

**Comment by PterX** [comment]
> 谢谢，已经打开了可以了，大大，象https://www.bt-tt.com 这样的站点能不能够加到公开站点上，或者是可否自定义公开站点，因 我用jackett很多都是国外的站点国内的站点很多也没有中文资源。

https://github.com/PterX/nas-tools-plugins 如果需要你可以安装我实现的插件，拷贝文件到容器目录的config/plugins目录下，然后就可以在插件市场安装，内建索引器勾选就可以使用了

**Comment by szicely** [comment]
> > 谢谢，已经打开了可以了，大大，象https://www.bt-tt.com 这样的站点能不能够加到公开站点上，或者是可否自定义公开站点，因 我用jackett很多都是国外的站点国内的站点很多也没有中文资源。
> 
> https://github.com/PterX/nas-tools-plugins 如果需要你可以安装我实现的插件，拷贝文件到容器目录的config/plugins目录下，然后就可以在插件市场安装，内建索引器勾选就可以使用了。
> 
> 当然类似1337x这种单页式站点，完全可以用 作者的https://github.com/hsuyelin/nas-tools-sites 自己添加配置后build一个bin出来

太感谢啦，终于可以愉快地用起来了。你的点拨对于我这种菜鸟用户来说实在是太大的帮助了。谢谢。。。。
