### ISSUE TITLE
[错误报告]: 带年份不能正确识别，不带年份能正确识别

### ISSUE THREAD

**Issue by playboy24** [hsuyelin/nas-tools#355]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

带年份识别错误
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/0672b83b-5023-4b17-af3d-d5fbcfe9c8ac)
不带年份识别正确
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/3ac2c0b0-9938-4f10-b1ed-c5a60647318f)
tmdb信息
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/d22d1136-0393-4bf4-8dce-0359f976027f)
无论是否开启v2识别都这样

**Comment by cng10001** [comment]
![star](https://github.com/hsuyelin/nas-tools/assets/115156545/5292cb4e-5295-4265-ad14-7bb2c9923a29)
我好像没问题哎

**Comment by playboy24** [comment]
> ![star](https://user-images.githubusercontent.com/115156545/272643458-5292cb4e-5295-4265-ad14-7bb2c9923a29.jpg) 我好像没问题哎

我刚才试了下确实正确了，复现不了问题了。可能是我这里的问题吧，我把这个issue关了吧

**Comment by playboy24** [comment]
> ![star](https://user-images.githubusercontent.com/115156545/272643458-5292cb4e-5295-4265-ad14-7bb2c9923a29.jpg) 我好像没问题哎

我刚才试了下确实正确了，复现不了问题了。可能是我这里的问题吧，我把这个issue关了吧
