### ISSUE TITLE
[错误报告]: 识别测试的时候正确识别，转移硬链接却识别错误

### ISSUE THREAD

**Issue by playboy24** [hsuyelin/nas-tools#359]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

识别测试图
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/3937ed57-455f-4ea5-8a59-ce24c8856232)
转移日志图
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/3623c750-a1a5-4071-bcd5-5ee42d89f02b)
文件名
Star.Trek.First.Contact.1996.1080p.Blu-ray.REMUX.AVC.TrueHD.5.1-HDH.mkv

**Comment by playboy24** [comment]
现在发现清除tmdb数据后可以正确转移。但是如果先转移同文件夹里的星际旅行1，然后同文件夹里的其他星际旅行系列都会被转移识别成星际旅行1

**Comment by playboy24** [comment]
已经发现原因：如果在添加下载的时候被识别错误。那下载完成转移的时候会使用下载时识别错误的信息，并且如果是合集还会导致合集内所有影片都被识别成同一个影片（用的错误数据是添加下载的识别的数据）
贴上我下载x战警的识别错误的日志
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/b9c4f0b6-ea32-4491-b5e1-3566e1c46831)

**Comment by playboy24** [comment]
> 已经发现原因：如果在添加下载的时候被识别错误。那下载完成转移的时候会使用下载时识别错误的信息，并且如果是合集还会导致合集内所有影片都被识别成同一个影片（用的错误数据是添加下载的识别的数据） 贴上我下载x战警的识别错误的日志 ![image](https://user-images.githubusercontent.com/100653484/274575395-b9c4f0b6-ea32-4491-b5e1-3566e1c46831.png)

可以增加一个清理下载记录的功能

**Comment by Teddy-Zhu** [comment]
#377

**Comment by Teddy-Zhu** [comment]
This resolves #377

**Comment by playboy24** [comment]
> #377

感谢大佬，那我关闭这个issue了
