### ISSUE TITLE
请求增强豆瓣榜单订阅

### ISSUE THREAD

**Issue by naoki66** [hsuyelin/nas-tools#36]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.2.9.9 251ced0
>
> 环境: docker in synology

## 你想要新增或者改进什么功能？

>  能否增强豆瓣榜单订阅这个插件，限定上映时间，因为经常会出现订阅很古老的电影、电视剧。
      参考电影随机订阅这个插件，非常感谢！

## 这个功能有什么可以参考的资料吗？

![image](https://github.com/hsuyelin/nas-tools/assets/22931306/35b19239-c89f-42ab-b43f-641fba7dfd7e)

![image](https://github.com/hsuyelin/nas-tools/assets/22931306/c8ea4df6-18c6-40c4-b03d-7674dc9705f7)

**Comment by hsuyelin** [comment]
这个和你rss有关，自己找相关的rss就可以了。参考：https://docs.rsshub.app/social-media.html#dou-ban
