### ISSUE TITLE
[错误报告]: 内置索引器没有torrentleech了

### ISSUE THREAD

**Issue by ZQiannnn** [hsuyelin/nas-tools#362]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.9

### 问题类型

主程序运行问题

### 问题描述

旧NASTool是有的，之前还一直用，现在的版本在统计数据里面还能看到，索引器和资源都没有
<img width="1713" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/19886406/7d63dc2f-bddb-4534-a516-5e4b3824719f">
<img width="1045" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/19886406/7d75d7ee-7d0e-49fb-97fd-ea290da4a822">

**Comment by iovejieba** [comment]
作者同项目下有sites 可以翻老的sites自己加进去生成dat 覆盖.... 或者外部索引不就好了

**Comment by ZQiannnn** [comment]
> 作者同项目下有sites 可以翻老的sites自己加进去生成dat 覆盖.... 或者外部索引不就好了

已经没有sites.dat了

**Comment by iovejieba** [comment]
> > 作者同项目下有sites 可以翻老的sites自己加进去生成dat 覆盖.... 或者外部索引不就好了
> 
> 已经没有sites.dat了

换了目录换了文件名它不是没有了，web目录backed  user.sites.dat
