### ISSUE TITLE
关于NT搜索剧集不全的相关问题咨询

### ISSUE THREAD

**Issue by KeySoundsLa** [hsuyelin/nas-tools#37]
## 你使用的 NAStool 是什么版本，什么环境？
>v3.2.9.8 2ea2025
> NAStool 版本: vx.x.x
>v3.2.9.8 2ea2025
> 环境: docker or windows or Synology
>NAS
## 你遇到什么问题了？
关于NT搜索剧集不全的相关问题咨询
> 描述一下你遇到的问题
一、通过NT上方搜索如【死神少爷与黑女仆】仅显示1集，但到PT站核实却有4集，格式都一样。
二、经搜索百度找有同样问题的同志，查阅到的方式是：通过搜索栏右上角的高级搜索，就可以正常搜索出来。
三、通过设置无滤规则或更换夹克索引器，都是同样的结果- -！
四、不知道这个问题是不是BUG，是否会影响订阅效果。比如，当我订阅了某一部剧集，但设置的站点却搜索不到（实际有）。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
希望搜索与订阅能够正常搜索到相关剧集。
> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
一、上方搜索
![1](https://github.com/hsuyelin/nas-tools/assets/140850069/5c5f9ae1-561f-4da3-a918-1aa51c115cb4)
二、上方搜索 日志
![2](https://github.com/hsuyelin/nas-tools/assets/140850069/baf6e81a-525f-482c-bc0b-50091d7e905e)
三、高级搜索
![C4HG SDBK5UOR%3S_%@1FGH](https://github.com/hsuyelin/nas-tools/assets/140850069/86dfbbfd-3b2b-40f9-b6b4-af0649cbb37d)
四、高级搜索
![4](https://github.com/hsuyelin/nas-tools/assets/140850069/0c1bd0eb-655b-42ac-969c-529917e17d31)
五、高级搜索 日志
![5](https://github.com/hsuyelin/nas-tools/assets/140850069/0d7cf260-86d6-4097-a580-08a5c1fbf4c6)
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by iovejieba** [comment]
这个一般是过滤规则貌似...你把过滤改成不过滤试试 我记得好像是

**Comment by KeySoundsLa** [comment]
@iovejieba 我有测试过啦。。木有啊 所以才有疑问，PT贴吧的一些同志也是同样的问题- -

**Comment by FireGodson** [comment]
确实有这个问题，有些资源在多个站点有就只能搜出一个来，用高级搜索就全能搜索出来

**Comment by jackloves111** [comment]
这个问题好像一直存在，虽然我也不知道什么原因。

**Comment by kai456789** [comment]
這問題好像是一般搜索會用TMDB的字詞去搜 
用高級就會用你輸入的字去搜

**Comment by hsuyelin** [comment]
> 這問題好像是一般搜索會用TMDB的字詞去搜 用高級就會用你輸入的字去搜

是这样的，这个原理就是：
1. 先去TMDB用关键词查找到TMDBID，并获取中文名称和英文名称
2. 使用关键词去尝试从索引器搜索，如果有搜索结果直接返回搜索结果
3. 如果2没有拿到搜索结果，尝试使用英文名称去搜索

高级搜索会跳过TMDB查询，直接使用输入的关键词去检索，得到所有索引器包含关键词的结果，但有可能不准，因此不是问题 @KeySoundsLa
