### ISSUE TITLE
[错误报告]: tmdb搜索剧集是非第一季且标题的日期是当季时间时出现bug

### ISSUE THREAD

**Issue by Teddy-Zhu** [hsuyelin/nas-tools#370]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9 fc92254

### 问题类型

主程序运行问题

### 问题描述

标题:Supernatural.S03.2007.1080p.BluRay.x265.10bit.DD.5.1-ADE

识别结果 : 魔人侦探食脑奈罗
实际是 邪恶力量 第三季

出现这个的原因, 正常搜索Supernatural , 邪恶力量是排在第一位,但是因为2007是第三季的年份,首播是2005 所以对比是忽略了
这时候 魔人侦探食脑奈罗也在结果列表里,且时间是2007, 所以错误的匹配上了, 这里能否判断是tv且非第一季可以拿到当前季的时间去对比呢? 目前来看大部分的非第一季剧集种子标题都是非第一季的时间

**Comment by hsuyelin** [comment]
还真是，我把2007换成2005就可以识别成邪恶力量了，试了你的建议但是这种方式对原先逻辑有影响，建议自定义识别词：

被替换词：(?i)Supernatural.*[Ss]0?3.*2007
替换词：Supernatural.S03.2005

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/eb9d429c-a49c-4960-bc23-52e2668915de)


![image](https://github.com/hsuyelin/nas-tools/assets/17918063/83b04fb3-91d2-42ba-9f57-99f86c7d1bd3)

**Comment by hsuyelin** [comment]
有些特殊的只能善用自定义识别词解决了
