### ISSUE TITLE
[错误报告]: 豆瓣电视剧没有数据

### ISSUE THREAD

**Issue by nodesire7** [hsuyelin/nas-tools#373]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9 5c30f73

### 问题类型

主程序运行问题

### 问题描述

<img width="1555" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/63827263/095eca22-843a-4545-ab78-5011795fbfa3">
豆瓣电视剧没有数据

**Comment by hsuyelin** [comment]
![IMG_2912](https://github.com/hsuyelin/nas-tools/assets/17918063/1ce75e70-867f-4ed2-a060-3dc887c9da90)

网络问题

**Comment by nodesire7** [comment]
我更新前是好的，回家后看到确实是可以显示
但是显示是这样的
![image](https://github.com/hsuyelin/nas-tools/assets/63827263/2dd94c33-b34b-4ee6-b4d0-834c0d2eb194)

**Comment by nodesire7** [comment]
只有豆瓣电视剧这一个界面显示有问题，其他都是正常

**Comment by nodesire7** [comment]
知道原因了，右边的选项卡如果不选的话，就没有数据。
