### ISSUE TITLE
[错误报告]: 剧集名字含有2023年份信息会错误识别为电影

### ISSUE THREAD

**Issue by jiezaizone** [hsuyelin/nas-tools#378]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.9

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/28976666/78d49e5d-bc3f-4b8c-b9dc-b2f26a56e4c4)
![image](https://github.com/hsuyelin/nas-tools/assets/28976666/adac4df8-2d49-44a1-88d5-829b244651a6)
如截图所示，恶魔法则.Law.Devil.S01E04.2023.1080p.WEB-DL.H265.AAC-ADWeb.mp4 ，符合命名规范的剧集，名字中含有2023年份会影响识别，给错误识别成了其他，去掉年份就可以正确识别，v2识别开启关闭都是同样的识别结果。命名中有明显的剧集S01E04，结果错误识别为电影

**Comment by playboy24** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/100653484/c31e1cb6-b7bd-4444-af26-eb6489ef6536)
我这里正常，我之前也会出现这个问题，重启docker容器或者清除tmdb数据就1好了

**Comment by jiezaizone** [comment]
> ![image](https://user-images.githubusercontent.com/100653484/275584538-c31e1cb6-b7bd-4444-af26-eb6489ef6536.png) 我这里正常，我之前也会出现这个问题，重启docker容器或者清除tmdb数据就1好了

重启docker没用，清除tmdb数据后升级重试正常了
