### ISSUE TITLE
能否做个索引器多开功能？

### ISSUE THREAD

**Issue by solosing** [hsuyelin/nas-tools#38]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x

v3.2.9.8 2ea2025
环境: docker 

## 你想要新增或者改进什么功能？
不知道是否可行，能不能做个索引器多开功能，让内置索引器和jackett和p等索引器一起打开，搜索后结果聚合显示，因为好像有些站点，特别是bt站点jackett支持比较好，经常出现要切换索引器的情况。

**Comment by hsuyelin** [comment]
抽空看下，能否给我看看那个官方集成插件的交互是啥样的
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月09日 21:30 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 能否做个索引器多开功能？ (Issue #38) |

我看作者已经加入https://github.com/Mattoids 这个第三方插件，只是不过对于jackett是恢复成2.9版本的独立索引器了，而Mattoids是基于3.2.3然后把jackett搞成了插件，然后bt和pt都可以集中到内置索引器里面，这样不用反复切换索引器，只需要勾选站点就可以了，似乎这样更方便，希望能考虑下

**Comment by youyifentian** [comment]
> 抽空看下，能否给我看看那个官方集成插件的交互是啥样的 ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年08月09日 21:30 | | 收件人 | hsuyelin/nas-tools ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [hsuyelin/nas-tools] 能否做个索引器多开功能？ (Issue #38) | 我看作者已经加入https://github.com/Mattoids 这个第三方插件，只是不过对于jackett是恢复成2.9版本的独立索引器了，而Mattoids是基于3.2.3然后把jackett搞成了插件，然后bt和pt都可以集中到内置索引器里面，这样不用反复切换索引器，只需要勾选站点就可以了，似乎这样更方便，希望能考虑下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

复现过程：安装nastool官方的3.2.3版本镜像，然后去：https://gitee.com/Mattoid/nas-tools-plugin/安装第三方插件即可
具体方法：
1、一键脚本安装：bash <(curl -s https://gitee.com/Mattoid/nas-tools-plugin/raw/master/package/install.sh) docker
2、添加第三方源：https://gitee.com/Mattoid/nas-tools-plugin/raw/master/source.json
3、在插件中心添加jackett插件，然后填入jackett服务器参数即可，jackett服务器需要至少添加一个站点
最终效果：
1、插件中心显示第三方插件
![0](https://github.com/hsuyelin/nas-tools/assets/5012570/cd473349-c7dd-496d-87a5-ffa544143ed6)
2、在第三方插件中安装jackett
![1](https://github.com/hsuyelin/nas-tools/assets/5012570/21691468-040c-4801-9d39-8001c6e3b385)
3、添加jackett服务器（jackett服务器至少要有一个站点）
![2](https://github.com/hsuyelin/nas-tools/assets/5012570/b956f296-346a-4368-91e4-34a79e11dd21)
![3](https://github.com/hsuyelin/nas-tools/assets/5012570/ef24e1ed-3e77-4452-9090-ee3131b32851)
4、打开内置索引器，即可看到内置PT站点，也可以在公开站点里面选择jackett里面的站点
![4](https://github.com/hsuyelin/nas-tools/assets/5012570/cbde6275-3026-4f8f-8b0a-9ee8b75c41cf)

这样所有站点就都可以在内置索引器里面选择了，不用来回切换索引器了

**Comment by youyifentian** [comment]
## 顺道借楼在提一个需求改进，希望大佬有空闲的时候可以看下

## 功能需求：添加站点类型分组功能
## 需求原因：
现在如果搜索一个电影或者电视剧、动漫，无论哪种类型，每次都会对索引器中选中的站点进行全部检索，并且nt的搜索逻辑是先从tmdb获取影视信息，然后再到站点进行搜索并匹配结果，这样实际上在开始正式搜索之前，nt已经从tmdb获得了这个影视的分类信息，那如果说用户在维护站点的时候提前先对站点进行分组标记，比如动漫组，电影组，电视剧组或者电影、电视剧组或者全类型组等可以多选组合，这样nt就可以从已经获得的影视分类中知道它本身属于电影还是电视剧或者动漫了，这样nt就可以直接从标记了这些类型分组的站点中去搜索，而不是每次都检索全部站点，比如对于动漫类的，可能平时能够及时更新追番站点就那几个，如果用户有这些站点的话直接在站点维护中将其分组为动漫类型，这样搜索动漫的时候就只从这些站点搜索就可以了，同理也可以分电影组、电视剧组或者电影、电视剧组等
## 交互逻辑：
1、在站点维护中添加类似于目前“站点用途”这种选项，比如可以叫“站点类型”或者“媒体类型”等，然后分：电影、电视剧、动漫、其他等类型
2、用户维护站点时，默认在“站点类型”中是全部选中的，然后用户可以自定义选择类型组合，即选中“电影”、“电视剧”、“动漫”等就将该站点归类到该类型分组中
3、用户搜索某一影视时，nt从tmdb获取具体的影视信息之后，就可以知道其具体分类了，然后nt根据该分类在选中的索引站点中按上述类型分组进行筛选，最后在筛选后的站点中进行检索，这样当有很多站点时，可以很大的提升搜索效率，不至于每次都检索全部站点


## 可能这个功能对程序改动比较大，相对麻烦一些，不过还是希望大佬有时间的话可以考虑下，非常感谢！

**Comment by hsuyelin** [comment]
> > 抽空看下，能否给我看看那个官方集成插件的交互是啥样的 ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 发送日期 | 2023年08月09日 21:30 | | 收件人 | hsuyelin/nas-tools _**@**_.**_> | | 抄送人 | Subscribed _**@**_._**> | | 主题 | Re: [hsuyelin/nas-tools] 能否做个索引器多开功能？ (Issue #38) | 我看作者已经加入https://github.com/Mattoids 这个第三方插件，只是不过对于jackett是恢复成2.9版本的独立索引器了，而Mattoids是基于3.2.3然后把jackett搞成了插件，然后bt和pt都可以集中到内置索引器里面，这样不用反复切换索引器，只需要勾选站点就可以了，似乎这样更方便，希望能考虑下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 复现过程：安装nastool官方的3.2.3版本镜像，然后去：[https://gitee.com/Mattoid/nas-tools-plugin/安装第三方插件即可](https://gitee.com/Mattoid/nas-tools-plugin/%E5%AE%89%E8%A3%85%E7%AC%AC%E4%B8%89%E6%96%B9%E6%8F%92%E4%BB%B6%E5%8D%B3%E5%8F%AF) 具体方法： 1、一键脚本安装：bash <(curl -s https://gitee.com/Mattoid/nas-tools-plugin/raw/master/package/install.sh) docker 2、添加第三方源：https://gitee.com/Mattoid/nas-tools-plugin/raw/master/source.json 3、在插件中心添加jackett插件，然后填入jackett服务器参数即可，jackett服务器需要至少添加一个站点 最终效果： 1、插件中心显示第三方插件 ![0](https://user-images.githubusercontent.com/5012570/259449659-cd473349-c7dd-496d-87a5-ffa544143ed6.jpg) 2、在第三方插件中安装jackett ![1](https://user-images.githubusercontent.com/5012570/259449852-21691468-040c-4801-9d39-8001c6e3b385.jpg) 3、添加jackett服务器（jackett服务器至少要有一个站点） ![2](https://user-images.githubusercontent.com/5012570/259450008-b956f296-346a-4368-91e4-34a79e11dd21.jpg) ![3](https://user-images.githubusercontent.com/5012570/259450161-ef24e1ed-3e77-4452-9090-ee3131b32851.jpg) 4、打开内置索引器，即可看到内置PT站点，也可以在公开站点里面选择jackett里面的站点 ![4](https://user-images.githubusercontent.com/5012570/259450517-cbde6275-3026-4f8f-8b0a-9ee8b75c41cf.jpg)
> 
> 这样所有站点就都可以在内置索引器里面选择了，不用来回切换索引器了

@solosing @youyifentian 目前完成了jackett和内置索引的融合，但是还有问题会导致站点资源不显示正在想怎么解决，预计本周内可以解决

**Comment by hsuyelin** [comment]
@solosing 已解决，暂时不发版，我再增加两个功能：https://github.com/hsuyelin/nas-tools/commit/bb4c96e4aaf86cd34bf54d9c59e112d731055153

![1.png](https://pic1.58cdn.com.cn/nowater/webim/big/n_v2bf32e3d5a60c4bfb9c6adc79b62452b7.png)
![2.png](https://pic1.58cdn.com.cn/nowater/webim/big/n_v25ebe09a2dedf41aea1c0997d215d3b85.png)
![3.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v2e4125cfe36864d9987b87a6192337877.png)
![4.png](https://pic3.58cdn.com.cn/nowater/webim/big/n_v255a5584f6af4406b80695c6b41cb8c5c.png)

**Comment by solosing** [comment]
感谢大佬！

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/7cb67b8a-f85c-4c6e-8ece-b1f95754ce70)
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/a76a50b8-dbd6-4f2f-8be9-7cfb787595b7)
我测试了，添加后索引器并没有显示站点，并且设置里面打开更多站点选项，索引器的原先自带的几个站点也没有了

**Comment by jackloves111** [comment]
此项改动较大

**Comment by hsuyelin** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/259935523-7cb67b8a-f85c-4c6e-8ece-b1f95754ce70.png) ![image](https://user-images.githubusercontent.com/89971817/259935545-a76a50b8-dbd6-4f2f-8be9-7cfb787595b7.png) 我测试了，添加后索引器并没有显示站点，并且设置里面打开更多站点选项，索引器的原先自带的几个站点也没有了 甚至我添加的PT站点也没有了 ![image](https://user-images.githubusercontent.com/89971817/259936845-d3ae3ff6-59d2-4006-8900-d13bf90d6abf.png)

你这个代码拉的不全吧，我本地测试是可以的

**Comment by jackloves111** [comment]
应该不会不全吧，都是直接git的

**Comment by hsuyelin** [comment]
> 应该不会不全吧，都是直接git的，日志也是显示更新成功的 ![image](https://user-images.githubusercontent.com/89971817/259941132-27b3f6f6-3870-41f9-b845-06ce30dbdb67.png)

![01.png](https://pic4.58cdn.com.cn/nowater/webim/big/n_v2be807a08b8ad42c8aa9ccc77e173b27f.png)
![02.png](https://pic9.58cdn.com.cn/nowater/webim/big/n_v228bb9b00250e47be8a02043839ccc9c2.png)

**Comment by hsuyelin** [comment]
![插件01.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v2318239095b0f426d9267d9d0e9bcca19.png)

![插件02.png](https://pic2.58cdn.com.cn/nowater/webim/big/n_v28a162393fd8f44eb94167c07939571d3.png)

![插件03.png](https://pic6.58cdn.com.cn/nowater/webim/big/n_v21e83e055d0224bf287f26bbc3db9712a.png)

@youyifentian @solosing @jackloves111 

新版本大概是这样，麻烦帮忙测试下，我本地使用jackett。prowlarr。以及观众馒头都是正常的

**Comment by solosing** [comment]
![图片1](https://github.com/hsuyelin/nas-tools/assets/61271516/61016d65-3ed0-451a-81b3-61a4fed6d2ee)
![图片2](https://github.com/hsuyelin/nas-tools/assets/61271516/e385845d-018f-4fdb-b006-f670069b5234)
![图片3](https://github.com/hsuyelin/nas-tools/assets/61271516/10f3c44b-3a5b-4e74-9566-0b5c8bd4a7d8)
测试好像无法添加。

**Comment by jackloves111** [comment]
> ![图片1](https://user-images.githubusercontent.com/61271516/259988751-61016d65-3ed0-451a-81b3-61a4fed6d2ee.png) ![图片2](https://user-images.githubusercontent.com/61271516/259988768-e385845d-018f-4fdb-b006-f670069b5234.png) ![图片3](https://user-images.githubusercontent.com/61271516/259988779-10f3c44b-3a5b-4e74-9566-0b5c8bd4a7d8.png) 测试好像无法添加。

你看下你索引器里还有没有站点

**Comment by solosing** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/61271516/203b78f1-52ef-4962-becd-53da092e41d2)
没有的。

**Comment by jackloves111** [comment]
> ![image](https://user-images.githubusercontent.com/61271516/259989581-203b78f1-52ef-4962-becd-53da092e41d2.png) 没有的。
你至少还有，我怎么什么都没了

**Comment by solosing** [comment]
又成功了，我换了个服务器架设的jackeet就添加成功了，我怀疑是地址网段的问题，内网10.10.x.x不行
![image](https://github.com/hsuyelin/nas-tools/assets/61271516/27dd1ed1-c2cb-490f-9562-704241ffd4d4)
@hsuyelin

**Comment by solosing** [comment]
> 又成功了，我换了个服务器架设的jackeet就添加成功了，我怀疑是地址网段的问题，内网10.10.x.x不行
> ![image](https://github.com/hsuyelin/nas-tools/assets/61271516/27dd1ed1-c2cb-490f-9562-704241ffd4d4)
> @hsuyelin

我错了，我把原来10网段jackeet的密码清除，发现又成功了，是不是密码问题？

**Comment by youyifentian** [comment]
> > 又成功了，我换了个服务器架设的jackeet就添加成功了，我怀疑是地址网段的问题，内网10.10.x.x不行
> > ![image](https://user-images.githubusercontent.com/61271516/259997042-27dd1ed1-c2cb-490f-9562-704241ffd4d4.png)
> > @hsuyelin
> 
> 我错了，我把原来10网段jackeet的密码清除，发现又成功了，是不是密码问题？

jackett服务器地址结尾得有“/”，才可以，比如，http://127.0.0.1:9117/ 而不是http://127.0.0.1:9117
