### ISSUE TITLE
通知消息样式

### ISSUE THREAD

**Issue by uploadrclone** [hsuyelin/nas-tools#39]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.9.9 251ced0
>
> 环境: docker

## 你想要新增或者改进什么功能？

可以在通知消息中添加（或者设置成可勾选项） 站点信息 和 种子大小 以及 转移方式么
因为有时候其他站点会转载种子，出现重复下载的内容 想通过站点信息来识别
种子大小是因为nas-tools刮削动漫时候会漏掉一些op ed 歌曲

转移方式

## 这个功能有什么可以参考的资料吗？
无

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
无

**Comment by hsuyelin** [comment]
暂时无法做到，这个需要将所有的内容保存
