### ISSUE TITLE
目前使用nastools遇到的问题

### ISSUE THREAD

**Issue by wuyaos** [hsuyelin/nas-tools#4]
1.CloudflareSpeedTest优选的输出为result.csv，而不是result_hosts.txt, 导致无法解析到ip
2.日志输出的时间差8小时

**Comment by hsuyelin** [comment]
1. 请检查版本，目前确实输出为result_hosts.txt
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/2f9af746-3e09-4795-a98e-7c8df63744d3)
2. 日志输出差8小时，请检查部署的ntp服务
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/080f50d7-e868-4bde-8caf-f652f6bfa595)

**Comment by hsuyelin** [comment]
> 是result_hosts.txt, 导致无法解

貌似解决了，原作者犯了一个很粗心的问题，我也没仔细看，看这个修复：https://github.com/hsuyelin/nas-tools/commit/eb3e8f46436e6ce3b82535b3864c035cde29d2e2

新版本3.2.6应该会修复这个问题，你尝试一下
