### ISSUE TITLE
无论是jackett还是PT，我的索引器都是空白

### ISSUE THREAD

**Issue by jackloves111** [hsuyelin/nas-tools#40]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
>v3.2.10.1
> 环境: 
>docker

## 你遇到什么问题了？

> 无论是jackett还是PT，我的索引器都是空白

## 给出程序界面截图、后台运行日志或配置文件

![deef3841-6984-4a84-bd82-6aad2d5ae113](https://github.com/hsuyelin/nas-tools/assets/89971817/d5a92546-06b4-4084-9ac0-5d49038688db)
![cb724bc8-44a8-4aaf-84af-0f70626fc04f](https://github.com/hsuyelin/nas-tools/assets/89971817/6e1bb700-744d-420a-b50b-ff95f829103e)
![dfcacc27-e8d9-402b-9049-41620f3f1433](https://github.com/hsuyelin/nas-tools/assets/89971817/3dc0a24e-8474-4703-b91a-002956df0f3c)

**Comment by jackloves111** [comment]
![3fcade09-faef-4a97-bf1c-18b807791346](https://github.com/hsuyelin/nas-tools/assets/89971817/0dd71941-9820-4d03-845f-36c0859e1ba6)
这个开关开启过就无法关闭

**Comment by jackloves111** [comment]
![193fab2a-ed85-46ea-9561-ef967639e8e1](https://github.com/hsuyelin/nas-tools/assets/89971817/fb0a3190-53c4-46b3-a8a5-3a1a26da616c)
站点已经出来，但是需要把原本的配置全部删掉才可以，需要全部重新配置，这个改动不知道影响了配置文件什么地方。

**Comment by hsuyelin** [comment]
> ![193fab2a-ed85-46ea-9561-ef967639e8e1](https://user-images.githubusercontent.com/89971817/259990851-fb0a3190-53c4-46b3-a8a5-3a1a26da616c.png) 站点已经出来，但是需要把原本的配置全部删掉才可以，需要全部重新配置，这个改动不知道影响了配置文件什么地方。

莫慌，我来看看，我本地测试的可能是新配置，不是覆盖配置

**Comment by hsuyelin** [comment]
@jackloves111 我先下掉了，没有测试老版本覆盖的问题。我看看如何解决

**Comment by hsuyelin** [comment]
@jackloves111 本地测试就会有，用的docker的配置复制过来的，docker部署就不会有 😿

**Comment by KeySoundsLa** [comment]
我也是一样的问题。。。还没发觉更新了 想搜剧都搜索不到- -！！

**Comment by hsuyelin** [comment]
> 

回退下看看，我这边也是复现的，本地环境用nas上的配置复制过来的就可以，直接部署的就不可以，还在定位原因

**Comment by KeySoundsLa** [comment]
- -！不懂怎么操作回退 我先吃个饭等修复吧

**Comment by sagcan** [comment]
好吧，我的索引器也是测试不过

**Comment by lovek8s** [comment]
> > 
> 
> 回退下看看，我这边也是复现的，本地环境用nas上的配置复制过来的就可以，直接部署的就不可以，还在定位原因

内置索引是正常的，但是jackett和pr的不见了

**Comment by KeySoundsLa** [comment]
我内置建立的站点搜索不到。。jackett测试失败。。

**Comment by hsuyelin** [comment]
在修了在修了，着急的话先回退下版本

**Comment by chris6868** [comment]
我的完全一片空白
![1691759713893](https://github.com/hsuyelin/nas-tools/assets/22971922/64fae51b-2788-45ea-a422-df8f2fc174f3)

**Comment by 18878777877** [comment]
各位大佬好，小弟一直使用着，今天发现docker地址没有了下载不了，请问各位大佬可以给我个新的docker地址吗？跪谢

**Comment by hsuyelin** [comment]
> 各位大佬好，小弟一直使用着，今天发现docker地址没有了下载不了，请问各位大佬可以给我个新的docker地址吗？跪谢

临时关闭了，解完再打开

**Comment by hsuyelin** [comment]
已修复：https://github.com/hsuyelin/nas-tools/commit/ab9ab5e728c381cbeb2be72beb5497262ee0c9c6
