### ISSUE TITLE
windows版nastool无法添加第三方插件

### ISSUE THREAD

**Issue by zlllllllllllllllll** [hsuyelin/nas-tools#403]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.10

### 问题类型

插件问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/142093590/fcf0b0fc-f6db-46a7-8ded-e7dab1cf4c6a)
我拷贝相应的插件 `*.py` 文件到 `/config/pligins` 目录，但是插件市场却无法出现这个插件

**Comment by iovejieba** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> 3.3.10
> 
> ### 问题类型
> 插件问题
> 
> ### 问题描述
> ![image](https://user-images.githubusercontent.com/142093590/277665624-fcf0b0fc-f6db-46a7-8ded-e7dab1cf4c6a.png) 我拷贝相应的插件 `*.py` 文件到 `/config/pligins` 目录，但是插件市场却无法出现这个插件
> 
> ### 发生问题时系统日志和配置文件
> _No response_

直接丢到 app/plugins/modules 目录下即可

**Comment by zlllllllllllllllll** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/142093590/b95d99b4-c876-4910-bb1e-8298990463d1)
我手动创建了app/plugins/modules 目录，把文件丢进去，无论是插件市场还是在已安装的插件中均找不到该插件

**Comment by iovejieba** [comment]
> ![image](https://user-images.githubusercontent.com/142093590/278206275-b95d99b4-c876-4910-bb1e-8298990463d1.png) 我手动创建了app/plugins/modules 目录，把文件丢进去，无论是插件市场还是在已安装的插件中均找不到该插件

...我忘了 win下是py封装打包的  建议你不用打包完的 直接跑  要么就想办法把打包运行的程序根目录映射出来  你这个并不是程序本体目录

**Comment by zlllllllllllllllll** [comment]
了解了，感谢

**Comment by iovejieba** [comment]
> 了解了，感谢

没事 客气
