### ISSUE TITLE
[错误报告]: 站点管理不支持织梦，铂金家

### ISSUE THREAD

**Issue by avatasia** [hsuyelin/nas-tools#406]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.1

### 问题类型

主程序运行问题

### 问题描述

站点管理不支持织梦，铂金家。
站点测试织梦报cookie失败， 另一个正常。但是数据统计里这两个都没有。
其中织梦默认站点地址会重定向到百度，站点测试能否改进下，加个/index.php就正常啦。
以上站点站点资源都正常。

织梦尝试站点地址加attendance.php， 抓包看站点测试还是默认网址

### 发生问题时系统日志和配置文件

```bash
NA
```

**Comment by avatasia** [comment]
铂金家目前正常，织梦还是同样的问题。
使用burp suite，option-match and replace里 做如下操作， 代理需要设置一下。
![image](https://github.com/hsuyelin/nas-tools/assets/198357/42fe9d40-3ea6-43f4-a8e5-40844882d48c)

重新刷新数据统计，正常，但是这个需要每次都这样操作，如果nas tools原生支持就太好啦。

**Comment by avatasia** [comment]
找到办法啦,  登录到群晖, sudo -i,找到sites.py文件
/var/packages/NASTool/target/nas-tools/app/sites# 

cp sites.py sites.py.bak
vi sites.py
搜索 1ptbat  ->  /1ptba
回车, 修改成这样.
if ('1ptba' in site_url) or ('zmpt' in site_url):

保存.

**Comment by jinhua523** [comment]
真的解决了，谢谢大哥，大哥厉害呀

**Comment by avatasia** [comment]
zmpt已改回首页跳转的方式.
