### ISSUE TITLE
[功能改进]: 本人原创nt开源插件，方便大家，欢迎集成

### ISSUE THREAD

**Issue by hotlcc** [hsuyelin/nas-tools#408]
### 当前程序版本

1

### 功能改进

1

### 参考资料

插件仓库：https://gitee.com/hotlcc/nastool-plugin

**Comment by iovejieba** [comment]
感谢大佬，为爱发电！

**Comment by ThedoRap** [comment]
上次我用这个贼糟糕 把那些还没检验好的种子都干掉了

**Comment by elderren** [comment]
请问windows版如何使用，复制到config/plugins/modules之后插件市场里没有

**Comment by iovejieba** [comment]
> 请问windows版如何使用，复制到config/plugins/modules之后插件市场里没有

别用py封装版 跑个python环境 直接源码跑 丢到上述目录就行了
