### ISSUE TITLE
更新到3.2.10,实时日志不打印任何东西

### ISSUE THREAD

**Issue by lovek8s** [hsuyelin/nas-tools#41]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
更新到3.2.10,实时日志不打印任何东西

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

<img width="1105" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/43465732/3b668a4b-dffe-47d7-9c7d-10e5f9188a50">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by 18878777877** [comment]
各位大佬好，docker下载的地址更换了吗？小弟求地址
