### ISSUE TITLE
文件管理，手动转移文件的时候 cpu很高，ffmpeg进程cpu使用很高

### ISSUE THREAD

**Issue by lovek8s** [hsuyelin/nas-tools#42]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
文件管理，手动转移文件的时候 cpu很高，ffmpeg进程cpu使用很高

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
<img width="972" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/43465732/bf1430d5-26ef-4e11-8331-84ecd0b27511">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
设置 - 刮削设置中，取消thumb-ffmpeg，这个一般给高配置使用的
