### ISSUE TITLE
[错误报告]: 添加下载失败

### ISSUE THREAD

**Issue by Tony-Yes** [hsuyelin/nas-tools#427]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.11 848743b

### 问题类型

主程序运行问题

### 问题描述

站点无法下载 搜索出来的资源和站点资源里面都无法下载 发现手上只有众和杜比这两个站不能下载
搜索
![](https://tu.kp.al/2023/11/06/%25pn_2023-11-06_14-47-31.png)
站点资源
![](https://tu.kp.al/2023/11/06/%25pn_2023-11-06_14-48-24.png)
订阅下载时好时坏，确定ck和rss链接没问题
![](https://tu.kp.al/2023/11/06/%25pn_2023-11-06_14-49-55.png)
![](https://tu.kp.al/2023/11/06/%25pn_2023-11-06_14-50-11.png)

### 发生问题时系统日志和配置文件

```bash
14:42:23		
开始请求：https://audiences.me/torrents.php
14:42:54		
正在查询TMDB电视剧：101172 ...
14:42:54		
101172 查询结果：吞噬星空
14:42:54		
发送消息 TG：title=添加下载任务失败：吞噬星空 (2020) S04 E06, text=站点：Audiences 种子名称：Swallowed Star S04E06 2023 2160p WEB-DL H265 DDP2.0-DramaS@ADWeb 种子链接：None 错误信息：添加下载任务失败：下载链接为空
14:42:54		
处理事件：download.add - [<function Webhook.send at 0x7f11e16c6710>]
14:42:54		
处理事件：download.fail - [<function Webhook.send at 0x7f11e16c6710>]
```

**Comment by Diluka** [comment]
我直接贴磁链报: `添加下载失败：根据链接地址未匹配到站点`

磁链没问题，可以直接在下载器里面创建下载。而且点击搜索到的同站同资源也是可以创建下载的，就是直接去贴磁链不行

**Comment by 0xt41ch1** [comment]
我也有同样的问题（115网盘）

**Comment by xuzhuocool** [comment]
插眼  解决了么？

**Comment by Tony-Yes** [comment]
> 插眼 解决了么？

没有 就两三个站不能搜索之后进行下载 rss是正常的 不管它了

**Comment by xuzhuocool** [comment]
我也是，最近突然一个站点出问题了

**Comment by Tony-Yes** [comment]
> 我也是，最近突然一个站点出问题了

你是什么站 我观 杜比 还有ptt那个垃圾都不行 站点资源点进去也下不了

**Comment by xuzhuocool** [comment]
馒头  我点进去 复制链接，或用种子是 ok 的

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/091456af-774d-40b0-b3c9-601e0c5fe611)
我看你提问题的时候是这个版本，现在已经有新版本了，更新了吗？@xuzhuocool @Tony-Yes

**Comment by Tony-Yes** [comment]
> ![image](https://private-user-images.githubusercontent.com/89971817/298513139-091456af-774d-40b0-b3c9-601e0c5fe611.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTI2MzgsIm5iZiI6MTcwNTkxMjMzOCwicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTMxMzktMDkxNDU2YWYtNzc0ZC00MGIwLWIzYzktNjAxZTBjNWZlNjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MzIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDUwYWJjM2ExMGI4ODgzMmQ4MmMyNDg3OTU2ZTEzZGMxMTI4YjVlMjA4ZTZlN2Q3YjYzMzVkMmEyNDg2ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rSiRDXqL4GPVePHTLteMXA7R5EUybG8qo9EL1poNzPs) 我看你提问题的时候是这个版本，现在已经有新版本了，更新了吗？@xuzhuocool @Tony-Yes

一直在更新 是新版了 这个问题一直都在 我也懒得管了

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/44f7a298-0263-41f3-9470-4bc2ca2da543)
我测试是没有问题的，没有开自动更新[v3.3.13 30e0e24](https://github.com/hsuyelin/nas-tools/commits/master)这个版本

**Comment by Tony-Yes** [comment]
> ![image](https://private-user-images.githubusercontent.com/89971817/298515876-fa0f5bd8-0bef-4e2a-9a0e-a8f22f9a80d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMwNzgsIm5iZiI6MTcwNTkxMjc3OCwicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTU4NzYtZmEwZjViZDgtMGJlZi00ZTJhLTlhMGUtYThmMjJmOWE4MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjYyYTllNWNhMzM5ZDEwN2Q1NzQzNmExMzZhNzJhZDgxMTFhNzhiNmI2NjBmZWRjOTZmZjQzOGVkNGQ3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19OLgsbKukO61pUk32acC-ZJhXE-bQ2Ucn08_HKd6zc) 开启自动更新，也就是拉取的最新代码，一样没有问题

刚试的 
![](https://pic.kp.al/2024/01/22/%25pn_2024-01-22_16-40-59.gif)

**Comment by xuzhuocool** [comment]
作者不更新了啊， 换 MP 了， 这个凑合用，  对了我问题修复了，我把站点删除了 重新加了一下就好了， 我问题出现是因为 cookie 失效  然后我改了就不行了， 你也重新添加下试试呢

**Comment by jackloves111** [comment]
> > ![image](https://private-user-images.githubusercontent.com/89971817/298515876-fa0f5bd8-0bef-4e2a-9a0e-a8f22f9a80d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMwNzgsIm5iZiI6MTcwNTkxMjc3OCwicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTU4NzYtZmEwZjViZDgtMGJlZi00ZTJhLTlhMGUtYThmMjJmOWE4MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjYyYTllNWNhMzM5ZDEwN2Q1NzQzNmExMzZhNzJhZDgxMTFhNzhiNmI2NjBmZWRjOTZmZjQzOGVkNGQ3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19OLgsbKukO61pUk32acC-ZJhXE-bQ2Ucn08_HKd6zc) 开启自动更新，也就是拉取的最新代码，一样没有问题
> 
> 刚试的 https://pic.kp.al/2024/01/22/%25pn_2024-01-22_16-40-59.gif

要么就是你rss过期了？清楚什么问题，反正我测试都OK的，或者站点重新删掉添加以下试试

**Comment by Tony-Yes** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/89971817/298515876-fa0f5bd8-0bef-4e2a-9a0e-a8f22f9a80d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMwNzgsIm5iZiI6MTcwNTkxMjc3OCwicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTU4NzYtZmEwZjViZDgtMGJlZi00ZTJhLTlhMGUtYThmMjJmOWE4MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjYyYTllNWNhMzM5ZDEwN2Q1NzQzNmExMzZhNzJhZDgxMTFhNzhiNmI2NjBmZWRjOTZmZjQzOGVkNGQ3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19OLgsbKukO61pUk32acC-ZJhXE-bQ2Ucn08_HKd6zc) 开启自动更新，也就是拉取的最新代码，一样没有问题
> > 
> > 
> > 刚试的 https://pic.kp.al/2024/01/22/%25pn_2024-01-22_16-40-59.gif
> 
> 要么就是你rss过期了？清楚什么问题，反正我测试都OK的，或者站点重新删掉添加以下试试

RSS和CK都没问题 站点统计正常 R新资源没任何问题 我日常订阅都是正常下载的 只有在搜索出结果之后或者在站点资源里面点下载才会出这个情况 目前手上只有三个站有这个问题 找不出哪里的原因

**Comment by jackloves111** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/89971817/298515876-fa0f5bd8-0bef-4e2a-9a0e-a8f22f9a80d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMwNzgsIm5iZiI6MTcwNTkxMjc3OCwicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTU4NzYtZmEwZjViZDgtMGJlZi00ZTJhLTlhMGUtYThmMjJmOWE4MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjYyYTllNWNhMzM5ZDEwN2Q1NzQzNmExMzZhNzJhZDgxMTFhNzhiNmI2NjBmZWRjOTZmZjQzOGVkNGQ3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19OLgsbKukO61pUk32acC-ZJhXE-bQ2Ucn08_HKd6zc) 开启自动更新，也就是拉取的最新代码，一样没有问题
> > > 
> > > 
> > > 刚试的 https://pic.kp.al/2024/01/22/%25pn_2024-01-22_16-40-59.gif
> > 
> > 
> > 要么就是你rss过期了？清楚什么问题，反正我测试都OK的，或者站点重新删掉添加以下试试
> 
> RSS和CK都没问题 站点统计正常 R新资源没任何问题 我日常订阅都是正常下载的 只有在搜索出结果之后或者在站点资源里面点下载才会出这个情况 目前手上只有三个站有这个问题 找不出哪里的原因

你删除重新添加站点试过了没？

**Comment by Tony-Yes** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/89971817/298515876-fa0f5bd8-0bef-4e2a-9a0e-a8f22f9a80d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTMwNzgsIm5iZiI6MTcwNTkxMjc3OCwicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTU4NzYtZmEwZjViZDgtMGJlZi00ZTJhLTlhMGUtYThmMjJmOWE4MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA4MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjYyYTllNWNhMzM5ZDEwN2Q1NzQzNmExMzZhNzJhZDgxMTFhNzhiNmI2NjBmZWRjOTZmZjQzOGVkNGQ3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19OLgsbKukO61pUk32acC-ZJhXE-bQ2Ucn08_HKd6zc) 开启自动更新，也就是拉取的最新代码，一样没有问题
> > > > 
> > > > 
> > > > 刚试的 https://pic.kp.al/2024/01/22/%25pn_2024-01-22_16-40-59.gif
> > > 
> > > 
> > > 要么就是你rss过期了？清楚什么问题，反正我测试都OK的，或者站点重新删掉添加以下试试
> > 
> > 
> > RSS和CK都没问题 站点统计正常 R新资源没任何问题 我日常订阅都是正常下载的 只有在搜索出结果之后或者在站点资源里面点下载才会出这个情况 目前手上只有三个站有这个问题 找不出哪里的原因
> 
> 你删除重新添加站点试过了没？

试过 我曾经试过创建新的容器 只添加一个站点 一样的 不清楚是不是我账号有问题

**Comment by BBBKINGGG** [comment]
问题解决了吗？我显示添加下载成功，但是并没有下载。自己添加链接和种子可以用。

**Comment by BBBKINGGG** [comment]
> ![image](https://private-user-images.githubusercontent.com/89971817/298515876-fa0f5bd8-0bef-4e2a-9a0e-a8f22f9a80d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTA3MzcsIm5iZiI6MTcyOTA1MDQzNywicGF0aCI6Ii84OTk3MTgxNy8yOTg1MTU4NzYtZmEwZjViZDgtMGJlZi00ZTJhLTlhMGUtYThmMjJmOWE4MGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAzNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YWI1YTczMjBkYzZjZTE2NDY0ODJmM2QzYzVhZGYwOWNhZmQ0MzI1NGUxZTM2ODAyODdkZTAyMWQ4ZjQxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TqoIvpElu69DoopYfwYaoRylBoAzLw5pZTslvO5oVB0) 开启自动更新，也就是拉取的最新代码，一样没有问题

我显示添加下载成功，但是并没有下载任务，下载器中也没有，是为啥呀，版本用的3.4.1
