### ISSUE TITLE
[错误报告]: 【媒体库归档】插件安装后无法打开插件页面

### ISSUE THREAD

**Issue by jeblove** [hsuyelin/nas-tools#441]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.12 f74a3c9

### 问题类型

插件问题

### 问题描述

![image](https://github.com/hsuyelin/nas-tools/assets/17330034/ea196835-4a26-4b26-ac43-f2bb5099e298)
如图所示，需要安装该插件时创建目录
`/config/archive_file/media_library`

### 发生问题时系统日志和配置文件

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/config/archive_file/media_library'
```

**Comment by nostopp** [comment]
+1,插件页直接打不开了

**Comment by jackloves111** [comment]
@hotlcc 大佬修复下吧

**Comment by hotlcc** [comment]
> @hotlcc 大佬修复下吧

已提交合并请求

**Comment by hotlcc** [comment]
修改代码已提交合并请求，待发布版本。急需修复的[可到此下载](https://gitee.com/hotlcc/nastool-plugin/releases/tag/20231115)，将 `media_library_archive.py` 插件文件替换到nt的插件目录`app/plugins/modules/media_library_archive.py`，或者放到nt的配置目录`/config/plugins/` ，之后重启nt。
