### ISSUE TITLE
《我们诞生在中国》该纪录片被类型识别为“演唱会”

### ISSUE THREAD

**Issue by hxy310** [hsuyelin/nas-tools#442]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.12 f74a3c9

### 问题类型

主程序运行问题

### 问题描述

《我们诞生在中国》该纪录片被类型识别为“演唱会”并分类进演唱会的文件中，另外我想问一下，该怎么让影片不按照分类放入文件夹？

![image](https://github.com/hsuyelin/nas-tools/assets/42276845/897f46c3-7667-4e21-8ad3-98e2bd22d308)

### 发生问题时系统日志和配置文件

```bash
18:34:20		
我们诞生在中国 识别到 电影：TMDBID=355277, 名称=我们诞生在中国, 上映日期=2016-08-12
18:34:20		
正在查询TMDB电影：355277 ...
18:34:22		
355277 查询结果：我们诞生在中国
18:34:22		
正在查询TMDB电影：355277 ...
18:34:25		
355277 查询结果：Born in China
18:34:25		
正在转移文件：我们诞生在中国.mp4
=> /CloudDrive2/115/test/电影/演唱会/我们诞生在中国.2016/Born in China.2016.720p.H.264.AAC .mp4
```

**Comment by hsuyelin** [comment]
修改TMDB的分类即可，这个和程序没关系

**Comment by hxy310** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/42276845/20206733-8514-4042-983f-7bca6fdd6fed)
TMDB上的这个影片分类是纪录片啊。

**Comment by hxy310** [comment]
> 修改TMDB的分类即可，这个和程序没关系

TMDB上的这个影片分类是纪录片啊。
