### ISSUE TITLE
关于索引器的问题

### ISSUE THREAD

**Issue by KeySoundsLa** [hsuyelin/nas-tools#45]
## 你使用的 NAStool 是什么版本，什么环境？
 v3.2.10.2
> NAStool 版本: 
>93e2acc
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？
关于昨日更新修复的索引器问题
> 描述一下你遇到的问题
昨晚9点左右重启了一下容器，貌似退回了之前的版本，可以正常使用，jackett也在内置索引器旁边
晚上睡醒，更新后貌似还是一样没办法搜索到。。。
jackett按原来的部署的测试也失败- -！！！
目前无法成功完成索引器的搜索。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![IKR~TNISC2259}KSEC@3O~G](https://github.com/hsuyelin/nas-tools/assets/140850069/5651b6dd-6b93-4991-9b2e-1f33b1097c15)
![C952NP5CKIJGE`DHXB Y780](https://github.com/hsuyelin/nas-tools/assets/140850069/6a01f065-de7c-4e34-aa8e-4798191ff13a)
![(SU7U}L8HQL%DRQPN` 94B](https://github.com/hsuyelin/nas-tools/assets/140850069/4ebeb1b6-96e2-4f50-94bb-4d7d3e749ffe)
![95_LQU@7692ZB8(S(H_Y% S](https://github.com/hsuyelin/nas-tools/assets/140850069/5752a052-1f71-45ea-b502-9e17feaa46c6)
![41X0DO8@~%$BH8T2G74{9Z8](https://github.com/hsuyelin/nas-tools/assets/140850069/6f5081fe-490c-47e1-a5be-9be0155cf613)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by KeySoundsLa** [comment]
![C952NP5CKIJGE`DHXB Y780](https://github.com/hsuyelin/nas-tools/assets/140850069/62e7b462-79ec-4459-8abc-45440e43c055)

**Comment by hsuyelin** [comment]
点击开启内建站点，然后先点击确定，在测试

**Comment by KeySoundsLa** [comment]
- -！也有按这个流程测试过，均失败

**Comment by youyifentian** [comment]
> * -！也有按这个流程测试过，均失败

jackett服务器地址结尾得有“/”，才可以，比如，http://127.0.0.1:9117/ 而不是http://127.0.0.1:9117/

**Comment by youyifentian** [comment]
搜索结果得话，有时候需要第二次搜索才能搜到，尤其是一些bt站点，其他到没啥毛病，jackett地址后面斜杠的问题应该是没有对url做必要的判断，影响也不大

**Comment by KeySoundsLa** [comment]
- -！！我也有测试过增加尾巴的“/”也不行，，还没更新前我是输入127.0.0.1:9117直接测试就可以通，更新后无论增加http://还是/或者其他方式都失败！！！

**Comment by hsuyelin** [comment]
> 搜索结果得话，有时候需要第二次搜索才能搜到，尤其是一些bt站点，其他到没啥毛病，jackett地址后面斜杠的问题应该是没有对url做必要的判断，影响也不大

我来优化下，我测试的时候没想到

**Comment by hsuyelin** [comment]
> > * -！也有按这个流程测试过，均失败
> 
> jackett服务器地址结尾得有“/”，才可以，比如，http://127.0.0.1:9117/ 而不是http://127.0.0.1:9117

不是127.0.0.1，而是192.168.x.x 这种网络形式，或者172.x.x.x

**Comment by KeySoundsLa** [comment]
反馈下最新的情况，使用192.168.x.x:9117测试，显示测试失败。

**Comment by KeySoundsLa** [comment]
但是打开索引器，竟然出现了BT站- -！！实际是成功的

**Comment by KeySoundsLa** [comment]
就是到目前为止，内置建立的站点均搜索失败

**Comment by hsuyelin** [comment]
> 但是打开索引器，竟然出现了BT站- -！！实际是成功的

先点击确定，再重新打开测试，算了这个流程我优化下吧

**Comment by hsuyelin** [comment]
> 就是到目前为止，内置建立的站点均搜索失败

你试试动漫花园这些站，有些站不匹配是搜索不了的

**Comment by youyifentian** [comment]
> > 就是到目前为止，内置建立的站点均搜索失败
> 
> 你试试动漫花园这些站，有些站不匹配是搜索不了的

是不是系统读取jackett服务器超时啊，我笨的jackett可以正常连接读取站点，vps上面的就不行，莫名其妙

**Comment by KeySoundsLa** [comment]
![I}HW 2$242NU6 HYV{5IHB](https://github.com/hsuyelin/nas-tools/assets/140850069/b56d987d-b33e-45e8-bc24-205530b3330d)
![910`HJCI~H}~)1H21)0FTWR](https://github.com/hsuyelin/nas-tools/assets/140850069/72a08011-80ee-414f-9b3b-6b933f6d030d)
![$ 81_1PV0 Y%O@$IOTYJRVR](https://github.com/hsuyelin/nas-tools/assets/140850069/5932b2df-f8f8-459c-a7bc-1d67e25fb0a6)
![U$%E)RNW~X%MYDEEW NASPF](https://github.com/hsuyelin/nas-tools/assets/140850069/047928ae-5fb2-4f5f-a49b-c1c9dadfd940)
我测试下jackett关闭私人站，在进行搜索。可能是和NT内置部署的站点冲突，我排除一下

**Comment by youyifentian** [comment]
> ![I}HW 2$242NU6 HYV{5IHB](https://user-images.githubusercontent.com/140850069/260216575-b56d987d-b33e-45e8-bc24-205530b3330d.png) ![910`HJCIH})1H21)0FTWR](https://user-images.githubusercontent.com/140850069/260216581-72a08011-80ee-414f-9b3b-6b933f6d030d.png) ![$ 81_1PV0 Y%O@$IOTYJRVR](https://user-images.githubusercontent.com/140850069/260216585-5932b2df-f8f8-459c-a7bc-1d67e25fb0a6.png) ![U$%E)RNW~X%MYDEEW NASPF](https://user-images.githubusercontent.com/140850069/260216649-047928ae-5fb2-4f5f-a49b-c1c9dadfd940.png) 我测试下jackett关闭私人站，在进行搜索。可能是和NT内置部署的站点冲突，我排除一下

把“开启内建站点”关闭就可以了

**Comment by KeySoundsLa** [comment]
![PZYL19OL_0 `4@O099%R%D](https://github.com/hsuyelin/nas-tools/assets/140850069/c92ccf8e-9dc9-457f-8b26-1eb6094b33be)
我找到问题所在了。。。需要把站点内的仿真关闭才能搜索到。。。

**Comment by youyifentian** [comment]
> > > 就是到目前为止，内置建立的站点均搜索失败
> > 
> > 
> > 你试试动漫花园这些站，有些站不匹配是搜索不了的
> 
> 是不是系统读取jackett服务器超时啊，我本地jackett可以正常连接读取站点，vps上面的就不行，莫名其妙

我又试了几次，是因为给jackett设置了密码，关了密码就可以正常连上jackett了，本地和vps都是没有密码才能正常连

**Comment by sagcan** [comment]
> > > > 就是到目前为止，内置建立的站点均搜索失败
> > > 
> > > 
> > > 你试试动漫花园这些站，有些站不匹配是搜索不了的
> > 
> > 
> > 是不是系统读取jackett服务器超时啊，我本地jackett可以正常连接读取站点，vps上面的就不行，莫名其妙
> 
> 我又试了几次，是因为给jackett设置了密码，关了密码就可以正常连上jackett了，本地和vps都是没有密码才能正常连

[v3.2.10.2 93e2acc]也是一样，设置了密码的话jackett无法连接，去除了密码就可以

**Comment by hsuyelin** [comment]
> 了密码就可以

修复了，等发版惹
