### ISSUE TITLE
[错误报告]: 每次重启都报错 需要重新拉镜像才可以进入后台

### ISSUE THREAD

**Issue by felix-klk** [hsuyelin/nas-tools#460]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.12

### 问题类型

主程序运行问题

### 问题描述

每次重启都报错 需要重新拉镜像才可以进入后台
<img width="833" alt="Snipaste_2023-11-21_13-34-26" src="https://github.com/hsuyelin/nas-tools/assets/52670643/4499e43f-d87e-4f6a-bde1-5407b12e504b">

### 发生问题时系统日志和配置文件

```bash
每次重启都报错 需要重新拉镜像才可以进入后台
```

**Comment by hsuyelin** [comment]
这个其实问题不大，我已经修复了
