### ISSUE TITLE
Ying站改名为星空(star-space)后添加站点显示 cookie 失效，并且无法搜索资源，望适配

### ISSUE THREAD

**Issue by GangplankWong** [hsuyelin/nas-tools#467]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.12

### 问题类型

其他问题

### 问题描述

Ying站改名为星空(star-space)后添加站点显示 cookie 失效，并且无法搜索资源，望适配

**Comment by hsuyelin** [comment]
已适配
