### ISSUE TITLE
豆瓣图片 不显示

### ISSUE THREAD

**Issue by felix-klk** [hsuyelin/nas-tools#47]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>最新版
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？
豆瓣图片 不显示
> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://github.com/hsuyelin/nas-tools/assets/52670643/bf2e9d7f-4ccd-4086-a60d-9c2615c5f920)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by ati121** [comment]
一样出现了这个问题

**Comment by jackloves111** [comment]
应该是豆瓣又改了什么东西，不是程序本身的问题，我还用的之前的版本，也不行了

**Comment by hsuyelin** [comment]
修复了 ：https://github.com/hsuyelin/nas-tools/commit/77ac07aa8e2526e3ba1f2ae7ca9e4449bc4d241f

**Comment by jackloves111** [comment]
> 修复了 ：[77ac07a](https://github.com/hsuyelin/nas-tools/commit/77ac07aa8e2526e3ba1f2ae7ca9e4449bc4d241f)

好快，测试OK，好奇这是什么原因导致的？

**Comment by hsuyelin** [comment]
> > 修复了 ：[77ac07a](https://github.com/hsuyelin/nas-tools/commit/77ac07aa8e2526e3ba1f2ae7ca9e4449bc4d241f)
> 
> 好快，测试OK，好奇这是什么原因导致的？

豆瓣更新防盗链了
