### ISSUE TITLE
[错误报告]: 自定义识别-集数偏移不支持正数

### ISSUE THREAD

**Issue by Diluka** [hsuyelin/nas-tools#478]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.13

### 问题类型

主程序运行问题

### 问题描述

集数偏移填了10，处理结果和不填一样
![image](https://github.com/hsuyelin/nas-tools/assets/3766084/a386174d-4ab7-4b8a-bc8a-76bd55fc45be)

**Comment by Putarku** [comment]
这个是要填前面两个以后才有效果的
![image](https://github.com/hsuyelin/nas-tools/assets/66679443/7f9eace0-1929-46c3-acfd-52d8afcf5e54)

**Comment by Diluka** [comment]
好吧，特性，只是前面的识别都是正确的，难得写
