### ISSUE TITLE
豆瓣推荐的图片全部404了

### ISSUE THREAD

**Issue by chhc007** [hsuyelin/nas-tools#48]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.2
>
> 环境: docker
>

## 探索页，豆瓣的推荐全部无法加载图片

浏览器F12，https://qnmob3.doubanio.com/view/photo/m_ratio_poster/public/p2895401212.webp 这样的链接全部404了，不知道是豆瓣问题还是nastools问题。

**Comment by iovejieba** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.2.10.2
> > 环境: docker
> 
> ## 探索页，豆瓣的推荐全部无法加载图片
> 浏览器F12，https://qnmob3.doubanio.com/view/photo/m_ratio_poster/public/p2895401212.webp 这样的链接全部404了，不知道是豆瓣问题还是nastools问题。

已修复了 等下一版
