### ISSUE TITLE
站点获取流量失败

### ISSUE THREAD

**Issue by TonyLiooo** [hsuyelin/nas-tools#49]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.3 4a97555
>
> 环境: docker
>

## 你遇到什么问题了？

> 更新后启动nas-tools后台出现站点获取流量失败提示以及部分站点测试出现undefined 毫秒错误

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 新引入的问题

## 你期望的结果

> 应该是与chromedriver相关，希望可以修复这个bug

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://github.com/hsuyelin/nas-tools/assets/64239067/2e1834e0-563d-4efa-8001-17171b9958ce)
> docker日志
Exception: [Errno 26] Text file busy: '/usr/lib/chromium/chromedriver'
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sites/site_userinfo.py", line 162, in __refresh_site_data
    site_user_info = self.build(url=site_url,
  File "/nas-tools/app/sites/site_userinfo.py", line 70, in build
    if not chrome.visit(url=url, ua=ua, cookie=site_cookie, proxy=proxy):
  File "/nas-tools/app/helper/chrome_helper.py", line 155, in visit
    if not self.browser:
  File "/nas-tools/app/helper/chrome_helper.py", line 104, in browser
    self._chrome = self.__get_browser()
  File "/nas-tools/app/helper/chrome_helper.py", line 149, in __get_browser
    chrome = ChromeWithPrefs(options=options, driver_executable_path=self._executable_path)
  File "/nas-tools/app/helper/chrome_helper.py", line 267, in __init__
    super().__init__(*args, options=options, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 132, in auto
    return self.patch_exe()
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 297, in patch_exe
    with io.open(self.executable_path, "r+b") as fh:
OSError: [Errno 26] Text file busy: '/usr/lib/chromium/chromedriver'

2023-08-14 14:47:26,996 ERROR: 【Sites】站点  获取流量数据失败：[Errno 26] Text file busy: '/usr/lib/chromium/chromedriver'

**Comment by hsuyelin** [comment]
@TonyLiooo 重试就可以了，当前有别的进程占用了

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/a7d29987-cca0-46e0-b324-a7968baccd8c)

**Comment by TonyLiooo** [comment]
似乎开启浏览器仿真就会出现

**Comment by TonyLiooo** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/1dfe9103-3d72-40c7-91f4-09017a8b784a)
只有关闭了浏览器仿真才能测通

**Comment by TonyLiooo** [comment]
jackett插件测试是可以用的了，不过如果jackett中也添加了私有站点，索引器中会出现一样的两个站点，不知是否考虑去重？毕竟有的站点在nas-tools里有时候是访问失败的，但是jackett中使用了flaresolverr还是能正常进行索引

**Comment by TonyLiooo** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/b565ae1c-5e28-4549-a30a-6057b5bb34f6)
判断是否内置应该还是有问题，MT我也添加了内置，但是这里没判断内置true，大佬也有这个站点，可以试试看

**Comment by iovejieba** [comment]
> ![image](https://user-images.githubusercontent.com/64239067/260391618-b565ae1c-5e28-4549-a30a-6057b5bb34f6.png) 判断是否内置应该还是有问题，MT我也添加了内置，但是这里没判断内置true，大佬也有这个站点，可以试试看

开启浏览器仿真要调用浏览器内核  如果并没有内核调用 浏览器仿真 肯定失败....

**Comment by TonyLiooo** [comment]
> > ![image](https://user-images.githubusercontent.com/64239067/260391618-b565ae1c-5e28-4549-a30a-6057b5bb34f6.png) 判断是否内置应该还是有问题，MT我也添加了内置，但是这里没判断内置true，大佬也有这个站点，可以试试看
> 
> 开启浏览器仿真要调用浏览器内核 如果并没有内核调用 浏览器仿真 肯定失败....

之前的版本使用时候是没有这个问题的

**Comment by hsuyelin** [comment]
> ![image](https://user-images.githubusercontent.com/64239067/260391618-b565ae1c-5e28-4549-a30a-6057b5bb34f6.png) 判断是否内置应该还是有问题，MT我也添加了内置，但是这里没判断内置true，大佬也有这个站点，可以试试看

是这样的，浏览器内核的库不更新了，只能强行下载最新版本的内核去适配但是不稳定

**Comment by TonyLiooo** [comment]
> > jackett插件测试是可以用的了，不过如果jackett中也添加了私有站点，索引器中会出现一样的两个站点，不知是否考虑去重？毕竟有的站点在nas-tools里有时候是访问失败的，但是jackett中使用了flaresolverr还是能正常进行索引
> 
> 没有想到好的逻辑去重，没有字段可以标记是一样的

可以考虑交给用户去选择，或者直接判断站点链接？

**Comment by hsuyelin** [comment]
> 适配但是不稳定



> > > ![image](https://user-images.githubusercontent.com/64239067/260391618-b565ae1c-5e28-4549-a30a-6057b5bb34f6.png) 判断是否内置应该还是有问题，MT我也添加了内置，但是这里没判断内置true，大佬也有这个站点，可以试试看
> > 
> > 
> > 开启浏览器仿真要调用浏览器内核 如果并没有内核调用 浏览器仿真 肯定失败....
> 
> 之前的版本使用时候是没有这个问题的

实际上用仿真和不用没啥太大区别，只能等待依赖库版本更新

**Comment by hsuyelin** [comment]
> > > jackett插件测试是可以用的了，不过如果jackett中也添加了私有站点，索引器中会出现一样的两个站点，不知是否考虑去重？毕竟有的站点在nas-tools里有时候是访问失败的，但是jackett中使用了flaresolverr还是能正常进行索引
> > 
> > 
> > 没有想到好的逻辑去重，没有字段可以标记是一样的
> 
> 可以考虑交给用户去选择，或者直接判断站点链接？

站点链接不行，jacket和你直接在站点输入的找不到共同点，选择的话交互很麻烦，建议只保留一个，或者你可以帮我想想去重逻辑

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/261477cf-15b0-4916-b9d8-98e4349551c4)
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/c56ae1d0-ba36-4201-9515-d2717e74b2af)

我这个是可以的，我用的是EDGE浏览器，你用的Chrome浏览器且是115.X.X.X版本把

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/add69aa6-55bf-44bf-bbb6-05e637c81daa)

我打开的Chrome，这个版本也可以

**Comment by hsuyelin** [comment]
> > ![image](https://user-images.githubusercontent.com/64239067/260391618-b565ae1c-5e28-4549-a30a-6057b5bb34f6.png) 判断是否内置应该还是有问题，MT我也添加了内置，但是这里没判断内置true，大佬也有这个站点，可以试试看
> 
> 开启浏览器仿真要调用浏览器内核 如果并没有内核调用 浏览器仿真 肯定失败....

你这边测试可以么

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/4a45dbb3-ad39-41ea-a764-775c86d78c57)

这个是否内置的意思是，是不是自带的索引器，感觉迷惑了，我下个版本去掉，和浏览器仿真没半毛钱关系 @TonyLiooo

**Comment by TonyLiooo** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/6c21ea2d-0e54-4c30-a1ed-fd255d1c4ea2)
我的是这个版本，我重新试了下，还是不可以的，不知道会不会影响签到，等过了零点我再看看，如果关闭浏览器仿真没问题的话也还好

**Comment by hsuyelin** [comment]
> ![image](https://user-images.githubusercontent.com/64239067/260407435-6c21ea2d-0e54-4c30-a1ed-fd255d1c4ea2.png) 我的是这个版本，我重新试了下，还是不可以的，不知道会不会影响签到，等过了零点我再看看，如果关闭浏览器仿真没问题的话也还好

你换个EDGE浏览器看看，帮忙测试下，你用完卸载都可以

**Comment by TonyLiooo** [comment]
> > > > jackett插件测试是可以用的了，不过如果jackett中也添加了私有站点，索引器中会出现一样的两个站点，不知是否考虑去重？毕竟有的站点在nas-tools里有时候是访问失败的，但是jackett中使用了flaresolverr还是能正常进行索引
> > > 
> > > 
> > > 没有想到好的逻辑去重，没有字段可以标记是一样的
> > 
> > 
> > 可以考虑交给用户去选择，或者直接判断站点链接？
> 
> 站点链接不行，jacket和你直接在站点输入的找不到共同点，选择的话交互很麻烦，建议只保留一个，或者你可以帮我想想去重逻辑

我去看了下jackett的资料，也确实没有找到共同点，是否内置改为选项框，默认都选上，比较重复的一般都是少量的，感觉用户取消选择，这样也应该是可以的，不过就会引入交互了

**Comment by hsuyelin** [comment]
> 我去看了下jackett的资料，也确实没有找到共同点，是否内置改为选项框，默认都选上，比较重复的一般都是少量的，感觉用户取消选择，这样也应该是可以的，不过就会引入交互了

让用户勾选这个到是可以，我抽空试下，不过很少有人是内置的添加了，jackett或者prowlarr再添加一遍

**Comment by TonyLiooo** [comment]
> > 我去看了下jackett的资料，也确实没有找到共同点，是否内置改为选项框，默认都选上，比较重复的一般都是少量的，感觉用户取消选择，这样也应该是可以的，不过就会引入交互了
> 
> 让用户勾选这个到是可以，我抽空试下，不过很少有人是内置的添加了，jackett或者prowlarr再添加一遍

如果有签到需求的话，一般都会内置添加，但是确实有些站点，内置的兼容性较差一点，像是我添加的一些站点，内建都没识别到

**Comment by TonyLiooo** [comment]
> > ![image](https://user-images.githubusercontent.com/64239067/260407435-6c21ea2d-0e54-4c30-a1ed-fd255d1c4ea2.png) 我的是这个版本，我重新试了下，还是不可以的，不知道会不会影响签到，等过了零点我再看看，如果关闭浏览器仿真没问题的话也还好
> 
> 你换个EDGE浏览器看看，帮忙测试下，你用完卸载都可以

![image](https://github.com/hsuyelin/nas-tools/assets/64239067/8645973f-2485-4491-9c28-1e11ca1eb1a7)
我刚发现了点东西，其实一个个测全部站点都能测通，但是如果多选，只能测通一个，其余的都是[Errno 26] Text file busy: '/usr/lib/chromium/chromedriver'

**Comment by hsuyelin** [comment]
> 

我查了错误码IO错误，就是文件当前被占用了，估计你的站点比较多，你2个2个测看看行不行，如果2个可以，再测3个，我只有2个站没问题，这块估计要加一个延迟

**Comment by TonyLiooo** [comment]
> > 
> 
> 我查了错误码IO错误，就是文件当前被占用了，估计你的站点比较多，你2个2个测看看行不行，如果2个可以，再测3个，我只有2个站没问题，这块估计要加一个延迟 @TonyLiooo

我这边是只能1个，测2个也只有一个通的

**Comment by hsuyelin** [comment]
> > > 
> > 
> > 
> > 我查了错误码IO错误，就是文件当前被占用了，估计你的站点比较多，你2个2个测看看行不行，如果2个可以，再测3个，我只有2个站没问题，这块估计要加一个延迟 @TonyLiooo
> 
> 我这边是只能1个，测2个也只有一个通的
看看日志打印

**Comment by TonyLiooo** [comment]
> > > > 
> > > 
> > > 
> > > 我查了错误码IO错误，就是文件当前被占用了，估计你的站点比较多，你2个2个测看看行不行，如果2个可以，再测3个，我只有2个站没问题，这块估计要加一个延迟 @TonyLiooo
> > 
> > 
> > 我这边是只能1个，测2个也只有一个通的
> 
> 看看日志打印

> 2023-08-14 17:52:09,105 INFO: Challenge not detected!
这是测通的输出的，签到时候也会输出这个，但是能正常签到

> Exception: [Errno 26] Text file busy: '/usr/lib/chromium/chromedriver'
  Callstack:
  Traceback (most recent call last):
    File "/nas-tools/web/main.py", line 1038, in do
      return WebAction().action(cmd, data)
    File "/nas-tools/web/action.py", line 274, in action
      return func(data)
    File "/nas-tools/web/action.py", line 4016, in __test_site
      flag, msg, times = Sites().test_connection(data.get("id"))
    File "/nas-tools/app/sites/sites.py", line 273, in test_connection
      if not chrome.visit(url=site_url, ua=ua, cookie=site_cookie, proxy=site_info.get("proxy")):
    File "/nas-tools/app/helper/chrome_helper.py", line 155, in visit
      if not self.browser:
    File "/nas-tools/app/helper/chrome_helper.py", line 104, in browser
      self._chrome = self.__get_browser()
    File "/nas-tools/app/helper/chrome_helper.py", line 149, in __get_browser
      chrome = ChromeWithPrefs(options=options, driver_executable_path=self._executable_path)
    File "/nas-tools/app/helper/chrome_helper.py", line 267, in __init__
      super().__init__(*args, options=options, **kwargs)
    File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
      self.patcher.auto()
    File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 132, in auto
      return self.patch_exe()
    File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 297, in patch_exe
      with io.open(self.executable_path, "r+b") as fh:
  OSError: [Errno 26] Text file busy: '/usr/lib/chromium/chromedriver'

这是第二个站点输出的，报错的的在第二个

**Comment by TonyLiooo** [comment]
会不会是因为多个线程同时尝试初始化浏览器实例，导致对同一个资源进行操作，文件被认为是busy呢？如果是的话可以考虑每个线程中获取独立的ChromeHelper实例，或者尝试加lock解决？
