### ISSUE TITLE
[功能改进]: 本修改版nastool支持彩虹岛的多个域名吗?我现在使用ptchdbits.co域名tracker会出现问题

### ISSUE THREAD

**Issue by cng10001** [hsuyelin/nas-tools#498]
### 当前程序版本

3.3.8

### 功能改进

虽然现ptchdbits.co这个域名用自定义hosts还可以访问，但是如果自动订阅后种子的tracker也是ptchdbits.co，是连不通的，之前不这样，之前种子tracker是chdbits.xyz
可能跟网站变动有关系，作者能让本软件支持彩虹岛的最新域名吗 谢谢啦

**Comment by iovejieba** [comment]
> ### 当前程序版本
> 3.3.8
> 
> ### 功能改进
> 虽然现ptchdbits.co这个域名用自定义hosts还可以访问，但是如果自动订阅后种子的tracker也是ptchdbits.co，是连不通的，之前不这样，之前种子tracker是chdbits.xyz 可能跟网站变动有关系，作者能让本软件支持彩虹岛的最新域名吗 谢谢啦
> 
> ### 参考资料
> _No response_

可以说一下新域名 ...没岛的id

**Comment by cng10001** [comment]
> > ### 当前程序版本
> > 3.3.8
> > ### 功能改进
> > 虽然现ptchdbits.co这个域名用自定义hosts还可以访问，但是如果自动订阅后种子的tracker也是ptchdbits.co，是连不通的，之前不这样，之前种子tracker是chdbits.xyz 可能跟网站变动有关系，作者能让本软件支持彩虹岛的最新域名吗 谢谢啦
> > ### 参考资料
> > _No response_
> 
> 可以说一下新域名 ...没岛的id

![image](https://github.com/hsuyelin/nas-tools/assets/115156545/e5771fb3-db75-4b36-ba34-16c00167eb35)
如果部分地区访问老域名有问题，可以用图片这个方法，都可以自定义，我用的sz.chddiy.xyz，现在tracker链接和你能访问的域名是一样的也是sz.chddiy.xyz

**Comment by iovejieba** [comment]
> > > ### 当前程序版本
> > > 3.3.8
> > > ### 功能改进
> > > 虽然现ptchdbits.co这个域名用自定义hosts还可以访问，但是如果自动订阅后种子的tracker也是ptchdbits.co，是连不通的，之前不这样，之前种子tracker是chdbits.xyz 可能跟网站变动有关系，作者能让本软件支持彩虹岛的最新域名吗 谢谢啦
> > > ### 参考资料
> > > _No response_
> > 
> > 
> > 可以说一下新域名 ...没岛的id
> 
> ![image](https://private-user-images.githubusercontent.com/115156545/291463364-e5771fb3-db75-4b36-ba34-16c00167eb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTAyMTQsIm5iZiI6MTcwMjk4OTkxNCwicGF0aCI6Ii8xMTUxNTY1NDUvMjkxNDYzMzY0LWU1NzcxZmIzLWRiNzUtNGIzNi1iYTM0LTE2YzAwMTY3ZWIzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMjQ1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGU0ZGYyOWQ1OWVkMGY2YmJiMjM4NjBjOGU2MDg4OGVmMGQyZTU5OTJkM2VlN2EwNzE4NmE2YWU4MmQ1MmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8VuCDiMrZanx96O99-Qdt9L1hzCmgw1fLYi2JhyCFKM) 如果部分地区访问老域名有问题，可以用图片这个方法，都可以自定义，我用的sz.chddiy.xyz，现在tracker链接和你能访问的域名是一样的也是sz.chddiy.xyz

已pull 等hsuyelin大佬更新 sites即可

**Comment by cng10001** [comment]
> > > > ### 当前程序版本
> > > > 3.3.8
> > > > ### 功能改进
> > > > 虽然现ptchdbits.co这个域名用自定义hosts还可以访问，但是如果自动订阅后种子的tracker也是ptchdbits.co，是连不通的，之前不这样，之前种子tracker是chdbits.xyz 可能跟网站变动有关系，作者能让本软件支持彩虹岛的最新域名吗 谢谢啦
> > > > ### 参考资料
> > > > _No response_
> > > 
> > > 
> > > 可以说一下新域名 ...没岛的id
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/115156545/291463364-e5771fb3-db75-4b36-ba34-16c00167eb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTAyMTQsIm5iZiI6MTcwMjk4OTkxNCwicGF0aCI6Ii8xMTUxNTY1NDUvMjkxNDYzMzY0LWU1NzcxZmIzLWRiNzUtNGIzNi1iYTM0LTE2YzAwMTY3ZWIzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMjQ1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGU0ZGYyOWQ1OWVkMGY2YmJiMjM4NjBjOGU2MDg4OGVmMGQyZTU5OTJkM2VlN2EwNzE4NmE2YWU4MmQ1MmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8VuCDiMrZanx96O99-Qdt9L1hzCmgw1fLYi2JhyCFKM) 如果部分地区访问老域名有问题，可以用图片这个方法，都可以自定义，我用的sz.chddiy.xyz，现在tracker链接和你能访问的域名是一样的也是sz.chddiy.xyz
> 
> 已pull 等hsuyelin大佬更新 sites即可

![image](https://github.com/hsuyelin/nas-tools/assets/115156545/ddd56f3e-84e9-41f7-8d0e-153dac201cf9)

![image](https://github.com/hsuyelin/nas-tools/assets/115156545/096e04eb-e836-400e-a0ba-12c1c111b97d)
大佬大佬 你用moviepilot吗  我看到有这个插件 意思是不是解决网站域名问题的？如何配置 我也不懂

**Comment by iovejieba** [comment]
> moviepilot

没在用moviepilot当主力 只是拿moviepilot当临时签到来着....  自定义插件不适配这边的项目
