### ISSUE TITLE
win上面闪退或者程序自动崩溃

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#50]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: nastool_win_v3.2.10.3
>
> 环境: windows 
>

## 程序运行之后web登录页面有时候能打开，有时候打不开程序就崩了，即便是能打开web登录之后，点击登录之后，任务管理器也能看到程序闪退了，没有生成日志，但是捕捉到一个错误，不过，大部分情况下，没有报错就直接崩了，偶尔又报错，但不管有没有报错，程序始终是无法正常运行的
![QQ截图20230814182655](https://github.com/hsuyelin/nas-tools/assets/5012570/13325386-ac09-4d7e-bdb5-625aaf2ec00c)

**Comment by hsuyelin** [comment]
win暂时不支持了，随缘更新吧，要解决的问题太多了

**Comment by youyifentian** [comment]
> win暂时不支持了，随缘更新吧，要解决的问题太多了

但是之前几个版本在win上面现在还是可以正常打开的啊，，，，，额，有点莫名其妙啊
