### ISSUE TITLE
[错误报告]: 当synology chat用户数大于1时，主动通知消息会发送失败

### ISSUE THREAD

**Issue by bhwst** [hsuyelin/nas-tools#509]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.1

### 问题类型

主程序运行问题

### 问题描述

当synology chat用户数大于1时，nastools的主动通知消息会发送失败，但是交互消息有些能通
如：
<img width="816" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/8142503/4a695872-c73e-4f56-80b1-98c11a1fc839">
<img width="650" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/8142503/092719f7-5322-4e95-91ac-7c861e199e28">
经过测试发现当user_ids列表有多个用户id时会失败，应该是官方synology chat的bug，修改成遍历发送可以正常收到通知
![c3d6fb6701d4d0bdde5c5b47cb7eb210](https://github.com/hsuyelin/nas-tools/assets/8142503/3038d35d-ea44-421a-b4be-868f58ff6121)
修改文件：app/message/client/synologychat.py
修改部分：
<img width="886" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/8142503/c65bcb48-243f-4d22-b27d-19e0fcf0dfb1">

**Comment by bhwst** [comment]
117-None发现是file_url导致的，把这个关掉就正常了，猜测可能是图片偶尔下载失败导致

**Comment by taotaoge0208** [comment]
同样的问题，全网搜索都没有解决问题，难道需要等更新 ？

**Comment by bhwst** [comment]
> 同样的问题，全网搜索都没有解决问题，难道需要等更新 ？

chat软件本身在国内也没有发布，只有海外有，不知道啥原因，等它更新还不如先自己改了

**Comment by taotaoge0208** [comment]
> > 同样的问题，全网搜索都没有解决问题，难道需要等更新 ？
> 
> chat软件本身在国内也没有发布，只有海外有，不知道啥原因，等它更新还不如先自己改了

请问大佬，应该怎么改，我用的是群晖套件版，版本号3.3.1,请指教。

**Comment by bhwst** [comment]
> 修改文件：app/message/client/synologychat.py

117错误按我上面说的，修改文件：app/message/client/synologychat.py，把里面的file_url都注释掉，然后去套件中心重启服务即可

**Comment by dbwjxbakcn-vg** [comment]
> synologychat.py

我想问一下，这个《app/message/client/synologychat.py》文件的位置在哪里？

**Comment by bhwst** [comment]
> > synologychat.py
> 
> 我想问一下，这个《app/message/client/synologychat.py》文件的位置在哪里？

在你的程序安装目录，直接find搜一下就知道了，我是用的套件版，在/volume${N}/@appstore/NASTool/nas-tools/app/message/client/synologychat.py

**Comment by dbwjxbakcn-vg** [comment]
> > > synologychat.py
> > 
> > 
> > 我想问一下，这个《app/message/client/synologychat.py》文件的位置在哪里？
> 
> 在你的程序安装目录，直接find搜一下就知道了，我是用的套件版，在/volume${N}/@appstore/NASTool/nas-tools/app/message/client/synologychat.py

找到了，多谢。

**Comment by dbwjxbakcn-vg** [comment]
大佬，我按照你的代码修改了synologychat.py文件，仍未解决117-None问题；纯编程小白，修改是在定位到 if not userids后，完全copy了你的代码，是否有不妥之处？

**Comment by bhwst** [comment]
> 大佬，我按照你的代码修改了synologychat.py文件，仍未解决117-None问题；纯编程小白，修改是在定位到 if not userids后，完全copy了你的代码，是否有不妥之处？

`diff --git a/app/message/client/synologychat.py b/app/message/client/synologychat.py
index 56d8bfe..c31bab8 100644
--- a/app/message/client/synologychat.py
+++ b/app/message/client/synologychat.py
@@ -5,6 +5,7 @@ from threading import Lock
 from app.message.client._base import _IMessageClient
 from app.utils import ExceptionUtils, RequestUtils, StringUtils
 from config import Config
+import log
 
 lock = Lock()
 
@@ -72,19 +73,29 @@ class SynologyChat(_IMessageClient):
             if url and image:
                 caption = f"{caption}\n\n<{url}|查看详情>"
             payload_data = {'text': quote(caption)}
-            if image:
-                payload_data['file_url'] = quote(image)
+            #if image:
+            #    payload_data['file_url'] = quote(image)
             if user_id:
                 payload_data['user_ids'] = [int(user_id)]
+                ret, msg = self.__send_request(payload_data)
+                if not ret:
+                    log.error(f"【Message Err1】%s" % msg)
+                    return ret, msg
             else:
                 userids = self.__get_bot_users()
                 if not userids:
                     return False, "机器人没有对任何用户可见"
-                payload_data['user_ids'] = userids
-            return self.__send_request(payload_data)
+                for userid in userids:
+                    payload_data['user_ids'] = [int(userid)]
+                    ret, msg = self.__send_request(payload_data)
+                    if not ret:
+                        log.error(f"【Message Err1】%s" % msg)
+                        return ret, msg
+            return True, ""
         except Exception as msg_e:
             ExceptionUtils.exception_traceback(msg_e)
             return False, str(msg_e)
 
     def send_list_msg(self, medias: list, user_id="", title="", **kwargs):
@@ -123,10 +134,14 @@ class SynologyChat(_IMessageClient):
                 user_ids = self.__get_bot_users()
             payload_data = {
                 "text": quote(caption),
-                "file_url": quote(image),
-                "user_ids": user_ids
+                #"file_url": quote(image),
             }
-            return self.__send_request(payload_data)
+            for userid in user_ids:
+                payload_data["user_ids"] = [int(userid)]
+                ret, msg = self.__send_request(payload_data)
+                if not ret:
+                    return ret, msg
+            return True, ""
         except Exception as msg_e:
             ExceptionUtils.exception_traceback(msg_e)
             return False, str(msg_e)
`

**Comment by bhwst** [comment]
> 大佬，我按照你的代码修改了synologychat.py文件，仍未解决117-None问题；纯编程小白，修改是在定位到 if not userids后，完全copy了你的代码，是否有不妥之处？

<img width="720" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/8142503/34639477-bc31-43ed-b401-d0ce4d0f6b36">
<img width="820" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/8142503/b2b2ba6e-8f07-4526-9443-12fb81d4f1ae">

**Comment by dbwjxbakcn-vg** [comment]
> > 大佬，我按照你的代码修改了synologychat.py文件，仍未解决117-None问题；纯编程小白，修改是在定位到 if not userids后，完全copy了你的代码，是否有不妥之处？
> 
> <img alt="image" width="720" src="https://private-user-images.githubusercontent.com/8142503/292817486-34639477-bc31-43ed-b401-d0ce4d0f6b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzM3NjgsIm5iZiI6MTcwMzU3MzQ2OCwicGF0aCI6Ii84MTQyNTAzLzI5MjgxNzQ4Ni0zNDYzOTQ3Ny1iYzMxLTQzZWQtYjQwMS1kMGNlNGQwZjZiMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDY1MTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdkNTY3YTU2OTdlZTNmNTQzOTBiMjBmMmNjZjk5Nzc0ZGE0NmIwNGRlYjQyZTUwZWU1NTkwYmI2ZTk3NWE2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BgDv9M7_wFbrS2VjLR_kfDzN51Jhk62uujt0TCd2tTY"> <img alt="image" width="820" src="https://private-user-images.githubusercontent.com/8142503/292817524-b2b2ba6e-8f07-4526-9443-12fb81d4f1ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzM3NjgsIm5iZiI6MTcwMzU3MzQ2OCwicGF0aCI6Ii84MTQyNTAzLzI5MjgxNzUyNC1iMmIyYmE2ZS04ZjA3LTQ1MjYtOTQ0My0xMmZiODFkNGYxYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDY1MTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjUwZmYwOTJlYTE5YjRlYWE4ZjgzYzFjYjU1NDQwZDU0MGE4ZjAyM2I4YWNhMGUzODk4OGM3MTNlNzQ2M2NiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SOaPU7YyFDPRnb3jM5_A-BzV-NK3i2NKoBa9kmnd7Ow">

实测可用，大佬威武。

**Comment by taotaoge0208** [comment]
> > > 大佬，我按照你的代码修改了synologychat.py文件，仍未解决117-None问题；纯编程小白，修改是在定位到 if not userids后，完全copy了你的代码，是否有不妥之处？
> > 
> > 
> > <img alt="image" width="720" src="https://private-user-images.githubusercontent.com/8142503/292817486-34639477-bc31-43ed-b401-d0ce4d0f6b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzM3NjgsIm5iZiI6MTcwMzU3MzQ2OCwicGF0aCI6Ii84MTQyNTAzLzI5MjgxNzQ4Ni0zNDYzOTQ3Ny1iYzMxLTQzZWQtYjQwMS1kMGNlNGQwZjZiMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDY1MTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdkNTY3YTU2OTdlZTNmNTQzOTBiMjBmMmNjZjk5Nzc0ZGE0NmIwNGRlYjQyZTUwZWU1NTkwYmI2ZTk3NWE2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BgDv9M7_wFbrS2VjLR_kfDzN51Jhk62uujt0TCd2tTY"> <img alt="image" width="820" src="https://private-user-images.githubusercontent.com/8142503/292817524-b2b2ba6e-8f07-4526-9443-12fb81d4f1ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzM3NjgsIm5iZiI6MTcwMzU3MzQ2OCwicGF0aCI6Ii84MTQyNTAzLzI5MjgxNzUyNC1iMmIyYmE2ZS04ZjA3LTQ1MjYtOTQ0My0xMmZiODFkNGYxYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDY1MTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjUwZmYwOTJlYTE5YjRlYWE4ZjgzYzFjYjU1NDQwZDU0MGE4ZjAyM2I4YWNhMGUzODk4OGM3MTNlNzQ2M2NiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SOaPU7YyFDPRnb3jM5_A-BzV-NK3i2NKoBa9kmnd7Ow">
> 
> 实测可用，大佬威武。

求指教，synologychat.py这个文件按照上面的修改，无论修改多少，点保存更换文件后，重启NASTOOL套件就进不去页面了，但是一用回原版synologychat.py就可以正常进入NASTOOL页面使用。已经尝试了十多次了，都是这个情况 ，请大佬给出出主意，是我那里没有操作对吗？

**Comment by taotaoge0208** [comment]
> > 大佬，我按照你的代码修改了synologychat.py文件，仍未解决117-None问题；纯编程小白，修改是在定位到 if not userids后，完全copy了你的代码，是否有不妥之处？
> 
> <img alt="image" width="720" src="https://private-user-images.githubusercontent.com/8142503/292817486-34639477-bc31-43ed-b401-d0ce4d0f6b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTg4OTAsIm5iZiI6MTcwMzgxODU5MCwicGF0aCI6Ii84MTQyNTAzLzI5MjgxNzQ4Ni0zNDYzOTQ3Ny1iYzMxLTQzZWQtYjQwMS1kMGNlNGQwZjZiMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDI1NjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTZhOTRhOGU2NjFkMTZkOTZkOGFiODU0Njk2MGVmOTczM2JkMjcxNWIzYzAxYzkwNmIyNjJkNzY1ODZiYzA5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MZnYsb21T5kmumi7_y2BCorex0psBVPx1Rq7VWcD2ag"> <img alt="image" width="820" src="https://private-user-images.githubusercontent.com/8142503/292817524-b2b2ba6e-8f07-4526-9443-12fb81d4f1ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTg4OTAsIm5iZiI6MTcwMzgxODU5MCwicGF0aCI6Ii84MTQyNTAzLzI5MjgxNzUyNC1iMmIyYmE2ZS04ZjA3LTQ1MjYtOTQ0My0xMmZiODFkNGYxYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMDI1NjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ1M2EzMzY1MmZlODExYTNhY2I2ZTU3ZTJjMWQ4M2E0YTM5YjE2YjdjMGNjYjQxOTI5MGQ4MzZhNjkxZjRhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E2F17s6C6ew_YwK5lR0bffLVYa6bi1pS5OxGioCTnOA">

确实可用，谢谢大佬，估计这个问题的人不少，现在终于有了最终解决办法 ，再次感谢 。

**Comment by joneechua** [comment]
@hsuyelin 这个已经Merge了就关掉吧
