### ISSUE TITLE
进入nastool主页响应太慢

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#51]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: V3.2.10.2-V3.2.10.2
>
> 环境: docker

进入nastool主页响应太慢，重新启动nastool后进入会流畅些，但维持流畅的时间不久。有时候进去nastool要卡10秒左右，手机外网更慢了，自己已经尝试删了容器镜像拉了完整新镜像安装。安装新镜像时没用旧备份配置文件，都是全新配置。问题还是存在，请大佬找找问题所在！感谢

**Comment by 18878777877** [comment]
V3.2.10.2-V3.2.10.4

**Comment by hsuyelin** [comment]
@18878777877 没测出来这个，麻烦提供点日志

**Comment by hsuyelin** [comment]
https://github.com/hsuyelin/nas-tools/assets/17918063/c04867ed-0467-4413-9bb1-cfedd38e762c

我的非常快啊，看看你的是不是插件加载太多了，还有个就是看看你容器的占用，这种属于玄学问题了叭，这两个版本都是修复问题，不涉及这块的改动应该

**Comment by 18878777877** [comment]
好的，我多留意一下，谢谢大佬

**Comment by youyifentian** [comment]
借楼，win启动报错
![5](https://github.com/hsuyelin/nas-tools/assets/5012570/16b8a038-32fe-4fd9-9b91-aaf2dd4c3c40)

**Comment by MyGiki** [comment]
@hsuyelin  大神大佬请帮我看看我的响应问题，除非重启nastool才能临时解决响应慢的问题

https://github.com/hsuyelin/nas-tools/assets/107430324/f110d08f-2758-4d1d-ad93-5b8fc5a4ac5b
进nastool响应慢

https://github.com/hsuyelin/nas-tools/assets/107430324/64dc8ecd-63de-4a71-825c-b6132d370c6f
进订阅慢

https://github.com/hsuyelin/nas-tools/assets/107430324/7557d83b-4ffb-47f9-bb59-ca68ba39c3be
我的插件

视频都有打了日志了，日志没有baoc报错！

**Comment by jackloves111** [comment]
@MyGiki  兄弟，你只关注nastool响应慢，却忽视了你自身设备配置问题，经过我测试，当硬件总内存只有2G，没有SSD的低端设备，确实存在响应慢的问题，我认为这不能将问题算在nastool的身上。还请列出你使用的设备配置。

**Comment by MyGiki** [comment]
@jackloves111 
群辉 DS923+ 32G内存，docker安装在SSD固态盘，容器运行的其他软件正常，唯独nastool响应慢，我附属图片。
![QQ图片20230816090642](https://github.com/hsuyelin/nas-tools/assets/107430324/6c8e7819-8e6b-4756-990a-60e50ee47e75)

**Comment by jackloves111** [comment]
配置看起来没什么问题，会不会是浏览器问题，切换edge或者谷歌浏览器试下呢？苹果自带的浏览器确实不太行，或者你电脑端的是否有问题呢？

**Comment by MyGiki** [comment]
@jackloves111 大佬你好，我的电脑端用的是谷歌，用谷歌打开也存在响应慢的问题，甚至有时候干脆打不开，重启nastool容器可以临时解决，过得1-2天又再出现这种问题了。我每次进到nastool后都看日志，日志正常工作。求大佬有空检查检查一下，看能优化一下吗

**Comment by jackloves111** [comment]
你运行一个新的容器，不要配置任何设置，看看响应速度，同样不要配置，然后过得1-2天再看看。排查是否是你的某个设置导致的

**Comment by MyGiki** [comment]
@jackloves111 大佬，我感觉是登录账号密码造成响应慢甚至进不去的问题，我发觉进去要输账号密码的主页正常，输了账号密码点登录就卡着响应了

**Comment by jackloves111** [comment]
我都没看明白你的描述

**Comment by MyGiki** [comment]
@jackloves111 
我清空了游览器自动填充密码。秒进到nastool要输入账号密码的页面，输了账号密码登录才会卡着好久进去，是不是本地验证账号密码造成的？

**Comment by MyGiki** [comment]
![QQ图片20230816115557](https://github.com/hsuyelin/nas-tools/assets/107430324/2b5b41a8-e6f1-4085-9829-1538e5e168b6)
清空后秒进去到这里，输入账号密码就好久好久才响应

**Comment by jackloves111** [comment]
我这边测试发现，当其他的软件用192.168连接，会非常卡顿，用127.0.0.1就非常快，其他人测试不知道是不是一样   @hsuyelin

**Comment by jackloves111** [comment]
你用的是192.168链接的，还是127.0.0.1

**Comment by MyGiki** [comment]
@hsuyelin 大佬可以抽空优化一下吗？或者指导我怎么解决？

**Comment by hsuyelin** [comment]
> @hsuyelin 大佬可以抽空优化一下吗？或者指导我怎么解决？

我解了一个僵尸进程问题，你使用最新版本重建容器，在测试看看这个场景

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/6126bd49-b49e-41ac-b285-05dce5f5a130)

@MyGiki @jackloves111

**Comment by MyGiki** [comment]
@hsuyelin 收到大佬，那配置好的备份能用吗？还是要重新设置？

**Comment by hsuyelin** [comment]
> @hsuyelin 收到大佬，那配置好的备份能用吗？还是要重新设置？

备份可用，最好就是备份整个config文件夹

**Comment by MyGiki** [comment]
@hsuyelin 大佬，按指示清空缓存，重置nastool容器，删了nastool重新拉取3.2.10.5最新镜像，问题依然存在，一个晚上就出现响应过慢。这个新镜像我用的host网络测试，现在再清空缓存，重置nastool容器，安装镜像测试bridge网络看看

**Comment by jackloves111** [comment]
换台设备试一下

**Comment by hsuyelin** [comment]
> @hsuyelin 大佬，按指示清空缓存，重置nastool容器，删了nastool重新拉取3.2.10.5最新镜像，问题依然存在，一个晚上就出现响应过慢。这个新镜像我用的host网络测试，现在再清空缓存，重置nastool容器，安装镜像测试bridge网络看看

你这情况太诡异了，没有头绪，如果你使用旧版本3.2.9.9的话会卡顿么，还是最近两个版本卡顿的

**Comment by MyGiki** [comment]
不管它啦，用着先，就我自己一个人情况我也好无奈，谢谢大佬

**Comment by hsuyelin** [comment]
可以的话尽量想帮你解决的，你换个其他的浏览器，用隐身模式打开，如果卡顿，有没有可能此时目录监控启动了，恰好你在使用ffmpeg去获取图片，看一下容器中的占用，是内存占用高还是cpu占用高​，然后看下进程是什么，尽量想帮你排查的
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月18日 15:45 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 进入nastool主页响应太慢 (Issue #51) |

不管它啦，用着先，就我自己一个人情况我也好无奈，谢谢大佬

**Comment by kuroyukihime0** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/7975549/f6af47cb-c8ca-4aff-9c7f-798bb1fa2971)
遇到了类似问题，进入首页至少在3s左右，重启可以缓解；除官方外插件仅使用了自定义索引器

**Comment by Chen3553887** [comment]
我也有遇到，运行久了进入首页加载慢，加载完成后就没问题了。也是重启可以解决

**Comment by hsuyelin** [comment]
媒体库太多了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月20日 16:22 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 进入nastool主页响应太慢 (Issue #51) |

我也有遇到，运行久了进入首页加载慢，加载完成后就没问题了。也是重启可以解决

**Comment by kuroyukihime0** [comment]
打了几十个点，终于找到问题了，等会儿提个pr😂

**Comment by hsuyelin** [comment]
> 打了几十个点，终于找到问题了，等会儿提个pr😂

牛的，多多pr @MyGiki 3.2.10.7 不卡了，等更新

**Comment by MyGiki** [comment]
@hsuyelin 收到，谢谢各位大佬
