### ISSUE TITLE
[错误报告]: 织梦pt不显示种子标签

### ISSUE THREAD

**Issue by xyswordzoro** [hsuyelin/nas-tools#515]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.13

### 问题类型

其他问题

### 问题描述

织梦pt不显示种子标签.，如下图
![QQ截图20231227153754](https://github.com/hsuyelin/nas-tools/assets/86150433/4acc35f9-d9bb-4e5e-880c-6c7c453187b5)

**Comment by iovejieba** [comment]
看看标题的相关参数代码是否有变化吧 自己抄下改吧 没织梦....帮不上忙...额

**Comment by xyswordzoro** [comment]
> 看看标题的相关参数代码是否有变化吧 自己抄下改吧 没织梦....帮不上忙...额

大佬可以提供个邮箱 可以给您发个药

**Comment by iovejieba** [comment]
> > 看看标题的相关参数代码是否有变化吧 自己抄下改吧 没织梦....帮不上忙...额
> 
> 大佬可以提供个邮箱 可以给您发个药

我有点养不动了.....要么 你方便的话 远程？ 我看下代码？

**Comment by xyswordzoro** [comment]
> > > 看看标题的相关参数代码是否有变化吧 自己抄下改吧 没织梦....帮不上忙...额
> > 
> > 
> > 大佬可以提供个邮箱 可以给您发个药
> 
> 我有点养不动了.....要么 你方便的话 远程？ 我看下代码？

现在没法远程，可以给您开个vip账号，没有考核也，可以的话 可以发注册id和邮箱到我的邮箱onepicecedd@gmail.com

**Comment by Teddy-Zhu** [comment]
@iovejieba  @xyswordzoro  
配置 nas-tools-sites 中 织梦.json的
```
 "description": {
                "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
                "remove": "span,a,img,font,b",
                "contents": -1
            },
            "labels": {
                "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
            }
```
改为
```
 "description": {
                "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
                "remove": "span,a,img,font,b",
                "contents": -1
            },
            "labels": {
                "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
            }
```
应该就可以了，最近没啥空，你们可以改下测一下

**Comment by iovejieba** [comment]
> @iovejieba @xyswordzoro 配置 nas-tools-sites 中 织梦.json的
> 
> ```
>  "description": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
>                 "remove": "span,a,img,font,b",
>                 "contents": -1
>             },
>             "labels": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
>             }
> ```
> 
> 改为
> 
> ```
>  "description": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
>                 "remove": "span,a,img,font,b",
>                 "contents": -1
>             },
>             "labels": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
>             }
> ```
> 
> 应该就可以了，最近没啥空，你们可以改下测一下
nth-child标签要1么  我一直苦逼的抓selctor我看标签2啊 没错啊  ....太蛋疼了

**Comment by xyswordzoro** [comment]
> > @iovejieba @xyswordzoro 配置 nas-tools-sites 中 织梦.json的
> > ```
> >  "description": {
> >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
> >                 "remove": "span,a,img,font,b",
> >                 "contents": -1
> >             },
> >             "labels": {
> >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
> >             }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改为
> > ```
> >  "description": {
> >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
> >                 "remove": "span,a,img,font,b",
> >                 "contents": -1
> >             },
> >             "labels": {
> >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
> >             }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该就可以了，最近没啥空，你们可以改下测一下
> > nth-child标签要1么  我一直苦逼的抓selctor我看标签2啊 没错啊  ....太蛋疼了，ok修改完已正常！

弱弱的问下 还会更新到代码里吗，毕竟大多数人都不会搞

**Comment by iovejieba** [comment]
> > > @iovejieba @xyswordzoro 配置 nas-tools-sites 中 织梦.json的
> > > ```
> > >  "description": {
> > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
> > >                 "remove": "span,a,img,font,b",
> > >                 "contents": -1
> > >             },
> > >             "labels": {
> > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
> > >             }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 改为
> > > ```
> > >  "description": {
> > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
> > >                 "remove": "span,a,img,font,b",
> > >                 "contents": -1
> > >             },
> > >             "labels": {
> > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
> > >             }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 应该就可以了，最近没啥空，你们可以改下测一下
> > > nth-child标签要1么  我一直苦逼的抓selctor我看标签2啊 没错啊  ....太蛋疼了，ok修改完已正常！
> 
> 弱弱的问下 还会更新到代码里吗，毕竟大多数人都不会搞

我给你发邮件了成品bin，我一会去pull一下但什么时候更就得看大佬啥时候有功夫折腾了

**Comment by xyswordzoro** [comment]
> > > > @iovejieba @xyswordzoro 配置 nas-tools-sites 中 织梦.json的
> > > > ```
> > > >  "description": {
> > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
> > > >                 "remove": "span,a,img,font,b",
> > > >                 "contents": -1
> > > >             },
> > > >             "labels": {
> > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
> > > >             }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 改为
> > > > ```
> > > >  "description": {
> > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
> > > >                 "remove": "span,a,img,font,b",
> > > >                 "contents": -1
> > > >             },
> > > >             "labels": {
> > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
> > > >             }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 应该就可以了，最近没啥空，你们可以改下测一下
> > > > nth-child标签要1么  我一直苦逼的抓selctor我看标签2啊 没错啊  ....太蛋疼了，ok修改完已正常！
> > 
> > 
> > 弱弱的问下 还会更新到代码里吗，毕竟大多数人都不会搞
> 
> 我给你发邮件了成品bin，我一会去pull一下但什么时候更就得看大佬啥时候有功夫折腾了

好的 感谢感谢了 辛苦了

**Comment by iovejieba** [comment]
> > > > > @iovejieba @xyswordzoro 配置 nas-tools-sites 中 织梦.json的
> > > > > ```
> > > > >  "description": {
> > > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
> > > > >                 "remove": "span,a,img,font,b",
> > > > >                 "contents": -1
> > > > >             },
> > > > >             "labels": {
> > > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
> > > > >             }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 改为
> > > > > ```
> > > > >  "description": {
> > > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
> > > > >                 "remove": "span,a,img,font,b",
> > > > >                 "contents": -1
> > > > >             },
> > > > >             "labels": {
> > > > >                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
> > > > >             }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 应该就可以了，最近没啥空，你们可以改下测一下
> > > > > nth-child标签要1么  我一直苦逼的抓selctor我看标签2啊 没错啊  ....太蛋疼了，ok修改完已正常！
> > > 
> > > 
> > > 弱弱的问下 还会更新到代码里吗，毕竟大多数人都不会搞
> > 
> > 
> > 我给你发邮件了成品bin，我一会去pull一下但什么时候更就得看大佬啥时候有功夫折腾了
> 
> 好的 感谢感谢了 辛苦了

这不用谢我得谢@Teddy-Zhu  大佬   这css标签我都折腾吐了都没整明白

**Comment by xyswordzoro** [comment]
> @iovejieba @xyswordzoro 配置 nas-tools-sites 中 织梦.json的
> 
> ```
>  "description": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2)",
>                 "remove": "span,a,img,font,b",
>                 "contents": -1
>             },
>             "labels": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(2) > span[title=\"\"]"
>             }
> ```
> 
> 改为
> 
> ```
>  "description": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1)",
>                 "remove": "span,a,img,font,b",
>                 "contents": -1
>             },
>             "labels": {
>                 "selector": "td:nth-child(2) > table.torrentname > tr > td:nth-child(1) > span[title=\"\"]"
>             }
> ```
> 
> 应该就可以了，最近没啥空，你们可以改下测一下

也感谢大佬了，辛苦辛苦了
