### ISSUE TITLE
烦请大佬删除beta分支！！！

### ISSUE THREAD

**Issue by mantou568** [hsuyelin/nas-tools#524]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

beta

### 问题类型

其他问题

### 问题描述

烦请大佬删除beta分支！！！
隐秘项目的代码，恳请请不要开源发出去！！！看见贵项目有开发者将本项目docker扒取后 加入到nt的beta分支了
提交代码：https://github.com/hsuyelin/nas-tools/commit/41fbcf92a2ca454c70ca106303869550aa36f600
此提交为隐秘项目的主要代码，参与的开发者们并不想被公开。烦请删除该分支，这涉及到项目的生死存亡，不胜感激！！

@hsuyelin  @xuyanling  如果需要合作，可以交流沟通，共同进步。本项目为了隐秘和安全一直贯彻低调，仅百人的小圈子内使用，不公开使用，有限的用户量。并不会威胁或者影响到nt开源项目的发展。

### 发生问题时系统日志和配置文件

```bash
。。。
```

**Comment by mantou568** [comment]
@hsuyelin 而且贵项目本身已经走上了独立自主的道路上，没必要直接融合其他项目进来发展。大家都是基于nt独立发展，如果觉得某些模块想法很好，完全可以部分功能借鉴。而不是是把全库合并并公开。

**Comment by jackloves111** [comment]
说实话，你不说我都不知道还有beta版本

**Comment by mantou568** [comment]
> 说实话，你不说我都不知道还有beta版本，我看了一下，除了前端UI好像和本项目也没啥不一样的

你看commit日志就知道了。想要体验完整项目或者获取代码，邮件联系：xqxplm@gmail.com 

本项目一直低调运行，就是为了项目安全，不公开，少量使用。甚至还专门邀请了诸位大佬，一起合作都可以。都是基于nt继续开发，为了让项目继续走下去。看到不错的方案，可以局部的代码借鉴，互相进步，这都是可以的。如果真想要代码，可以给库权限，本项目虽然低调闭源，但是对开发者一直是开放态度。

但是哪晓得这大佬，直接扒docker文件，还公开到beta分支。这就过了。

某派派的行为这才多久，NT才停止维护多久，就干这事儿？

@hsuyelin 希望作者大大处理一下该分支。

**Comment by xylplm** [comment]
本来还以为只是提取了一个 内置索引更新插件，还不觉得啥，毕竟互相进步嘛。结果一看历史日志，这家伙直接扒库，啥行为啊这是，道德底线在哪里？

**Comment by hsuyelin** [comment]
> 本来还以为只是提取了一个 内置索引更新插件，还不觉得啥，毕竟互相进步嘛。结果一看历史日志，这家伙直接扒库，啥行为啊这是，道德底线在哪里？

已删除

**Comment by jackloves111** [comment]
https://github.com/hsuyelin/nas-tools-sites/issues/30

大佬，麻烦把这个人在站点项目的提交回退一下，导致程序运行不了了
