### ISSUE TITLE
不同任务的转移方式

### ISSUE THREAD

**Issue by uploadrclone** [hsuyelin/nas-tools#53]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 您好，能否在刷流任务里添加针对不同任务的转移方式 （因为有些站有hr 想用复制的转移方式保种一周 有的站没有hr站可以直接用转移的方式） 谢谢您

## 这个功能有什么可以参考的资料吗？
无
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by hsuyelin** [comment]
建议创建多个文件夹指定目录同步的方式，比如说PT下载的需要做种转移方式为硬链接，一般下载的转移方式为复制或者移动，然后QB选择自动管理即可

**Comment by iovejieba** [comment]
这个做个hr的目录同步任务就行  然后加个qb分类   写上最大做种时间 到时候手动清 就完事了

**Comment by uploadrclone** [comment]
> 这个做个hr的目录同步任务就行 然后加个qb分类 写上最大做种时间 到时候手动清 就完事了

这是个好办法

**Comment by uploadrclone** [comment]
> 建议创建多个文件夹指定目录同步的方式，比如说PT下载的需要做种转移方式为硬链接，一般下载的转移方式为复制或者移动，然后QB选择自动管理即可

测试了下，一个下载器好像只能选择一种转移方式，“PT下载的需要做种转移方式为硬链接，一般下载的转移方式为复制” 这个具体怎么实现大佬

**Comment by iovejieba** [comment]
> > 这个做个hr的目录同步任务就行 然后加个qb分类 写上最大做种时间 到时候手动清 就完事了
> 
> 这是个好办法

这样 特定qb标签 特定目录 不转移媒体目录  到做种时间就自动停止了  隔几天想起来清一下 就完事了  省心省力

**Comment by uploadrclone** [comment]
> > > 这个做个hr的目录同步任务就行 然后加个qb分类 写上最大做种时间 到时候手动清 就完事了
> > 
> > 
> > 这是个好办法
> 
> 这样 特定qb标签 特定目录 不转移媒体目录 到做种时间就自动停止了 隔几天想起来清一下 就完事了 省心省力

研究了下 标签做不到隔离 只能目录做到隔离 先试试目录
