### ISSUE TITLE
希望CookieCloud同步插件可以增加测试功能

### ISSUE THREAD

**Issue by TonyLiooo** [hsuyelin/nas-tools#54]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.4 ac93496
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望CookieCloud同步插件可以增加测试功能，以测试是否联通，想网站上的CookieCloud插件就有测试按键，虽然查看后台可以判断是否联通，但是不够直观，大佬有空时候希望可以升级下，感谢！！！

## 这个功能有什么可以参考的资料吗？

> Edge和Google浏览器上有对应的插件，可以参考下。
[CookieCloud](https://github.com/easychen/CookieCloud) [PyCookieCloud](https://github.com/lupohan44/PyCookieCloud)

**Comment by TonyLiooo** [comment]
关于jackett与内建合并后发现的一个问题在这也提一下。jackett插件添加后，站点资源也会显示jackett上的站点了，这点看起来也挺不错的，这点和我早期用的nastools一个版本很像，不过我有发现部分站点点开后会看不到资源，这个影响不大，可以慢慢完善。

**Comment by TonyLiooo** [comment]
发现cookiecloud后台报错信息
```
2023-08-16 00:00:00,000 INFO: 【Plugin】CookieCloud同步 - 同步服务开始 ...
Job "CookieCloud.__cookie_sync (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='0'], next run at: 2023-08-17 00:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/plugins/modules/cookiecloud.py", line 295, in __cookie_sync
    indexer_info = self._index_helper.get_indexer_info(domain_url)
AttributeError: 'IndexerHelper' object has no attribute 'get_indexer_info'
```

**Comment by hsuyelin** [comment]
> 发现cookiecloud后台报错信息
> 
> ```
> 2023-08-16 00:00:00,000 INFO: 【Plugin】CookieCloud同步 - 同步服务开始 ...
> Job "CookieCloud.__cookie_sync (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='0'], next run at: 2023-08-17 00:00:00 CST)" raised an exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
>     retval = job.func(*job.args, **job.kwargs)
>   File "/nas-tools/app/plugins/modules/cookiecloud.py", line 295, in __cookie_sync
>     indexer_info = self._index_helper.get_indexer_info(domain_url)
> AttributeError: 'IndexerHelper' object has no attribute 'get_indexer_info'
> ```

这个已解决

**Comment by TonyLiooo** [comment]
> > 发现cookiecloud后台报错信息
> > ```
> > 2023-08-16 00:00:00,000 INFO: 【Plugin】CookieCloud同步 - 同步服务开始 ...
> > Job "CookieCloud.__cookie_sync (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='0'], next run at: 2023-08-17 00:00:00 CST)" raised an exception
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
> >     retval = job.func(*job.args, **job.kwargs)
> >   File "/nas-tools/app/plugins/modules/cookiecloud.py", line 295, in __cookie_sync
> >     indexer_info = self._index_helper.get_indexer_info(domain_url)
> > AttributeError: 'IndexerHelper' object has no attribute 'get_indexer_info'
> > ```
> 
> 这个已解决

感谢大佬！我就是发现最近cookie失效，怀疑插件没生效，同步时候才发现这个bug，希望能增加下测试连通性的按键，这样在添加时候就知道有没有连通了，毕竟不是一直盯着日志去看的

**Comment by hsuyelin** [comment]
> > > 发现cookiecloud后台报错信息
> > > ```
> > > 2023-08-16 00:00:00,000 INFO: 【Plugin】CookieCloud同步 - 同步服务开始 ...
> > > Job "CookieCloud.__cookie_sync (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='0'], next run at: 2023-08-17 00:00:00 CST)" raised an exception
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
> > >     retval = job.func(*job.args, **job.kwargs)
> > >   File "/nas-tools/app/plugins/modules/cookiecloud.py", line 295, in __cookie_sync
> > >     indexer_info = self._index_helper.get_indexer_info(domain_url)
> > > AttributeError: 'IndexerHelper' object has no attribute 'get_indexer_info'
> > > ```
> > 
> > 
> > 这个已解决
> 
> 感谢大佬！我就是发现最近cookie失效，怀疑插件没生效，同步时候才发现这个bug，希望能增加下测试连通性的按键，这样在添加时候就知道有没有连通了，毕竟不是一直盯着日志去看的

抽空添加

**Comment by TonyLiooo** [comment]
> 已添加：[7e8220c](https://github.com/hsuyelin/nas-tools/commit/7e8220c2921a7146e207e9e43d3f11ab52bd598b)

感谢大佬！！！

**Comment by TonyLiooo** [comment]
> 已添加：[7e8220c](https://github.com/hsuyelin/nas-tools/commit/7e8220c2921a7146e207e9e43d3f11ab52bd598b)

大佬，添加的CookieCloud同步记录在新版本怎么取消了呢
