### ISSUE TITLE
下载管理--正在下载无法正常显示，下载器中已将标签设置成“NASTOOL”

### ISSUE THREAD

**Issue by supermanchou** [hsuyelin/nas-tools#548]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.1 c05cb16

### 问题类型

主程序运行问题

### 问题描述

下载管理--正在下载无法正常显示，下载器中已将标签设置成“NASTOOL”

**Comment by Kabulaka** [comment]
@supermanchou 这个问题在v3.3.14 已经解决了吗

**Comment by bilibilikanpei** [comment]
我3.4.1版本还有这个问题。
什么媒体库、下载器都设置好了，标签NASTOOL也给了，明明qb有下载任务，但是在nas-tools页面看不到。
虽然不影响什么，但很不爽。

**Comment by wushuo30** [comment]
> 我3.4.1版本还有这个问题。 什么媒体库、下载器都设置好了，标签NASTOOL也给了，明明qb有下载任务，但是在nas-tools页面看不到。 虽然不影响什么，但很不爽。

3.4.1版本默认也是，下载器，qb右上角的红五星默认选中
