### ISSUE TITLE
多标签隔离

### ISSUE THREAD

**Issue by uploadrclone** [hsuyelin/nas-tools#55]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 作者您好 现在nastool 标签隔离只支持有nastool标签和所有任务的隔离 能否支持下 自定义标签的隔离 谢谢您

## 这个功能有什么可以参考的资料吗？
无
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/b34420d8-faba-452c-9fde-d441c1248521)

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/4a4410c3-bf40-4c64-8f0e-f2b90f9cf620)


![image](https://github.com/hsuyelin/nas-tools/assets/17918063/ab3db79c-902b-46b6-b475-3b53a72e9c01)

**Comment by uploadrclone** [comment]
谢谢作者的截图，这个在搜索的站点资源可以添加，但刷流任务中好像只能选择下载器 没有选择下载设置

**Comment by uploadrclone** [comment]
> ![image](https://user-images.githubusercontent.com/17918063/260937609-b34420d8-faba-452c-9fde-d441c1248521.png)
> 
> ![image](https://user-images.githubusercontent.com/17918063/260937716-4a4410c3-bf40-4c64-8f0e-f2b90f9cf620.png)
> 
> ![image](https://user-images.githubusercontent.com/17918063/260937518-ab3db79c-902b-46b6-b475-3b53a72e9c01.png)

大佬 有办法在刷流任务中使用下载设置选项么

**Comment by uploadrclone** [comment]
@hsuyelin 仔细看了下nastool的wiki
https://wiki.nastool.org/zh/%E4%B8%8B%E8%BD%BD%E5%99%A8 
“所有下载器均需要通过下载设置来关联使用，刷流任务除外”
刷流任务好像不能用下载设置的选项
