### ISSUE TITLE
docker重启自动更新3.3.13后启动报错，无法打开登录页面

### ISSUE THREAD

**Issue by yourvid** [hsuyelin/nas-tools#554]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.13

### 问题类型

Docker或运行环境问题

### 问题描述

群晖DSM918+ 7.2.1 docker重启自动更新3.3.13后启动报错，无法打开登录页面
![image](https://github.com/hsuyelin/nas-tools/assets/33681727/a8b33b7b-3158-4f4e-a9c6-6e81a9b76035)

![image](https://github.com/hsuyelin/nas-tools/assets/33681727/ab5dc91b-8f8d-4ec1-be79-55f1427dc0c3)

![image](https://github.com/hsuyelin/nas-tools/assets/33681727/7894653b-3fc6-46f7-97b6-157cfeeb1d6b)

### 发生问题时系统日志和配置文件

```bash
如图所示
```

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/1f1fae73-3c01-4f49-a4a6-b67a3e79c4d5)

**Comment by yourvid** [comment]
谢谢作者，给出的说明可以解决。
