### ISSUE TITLE
内置索引器问题

### ISSUE THREAD

**Issue by lovek8s** [hsuyelin/nas-tools#56]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.10.4
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

问题1:  站点资源增加的站点和索引器开启后，索引器有的站点也一起在内置索引里面了，这里面没有去重
问题2: 内置索引器里面的站点有重复的，然而去除勾选后保存，不生效

## 你期望的结果

> 描述以下你期望的结果

增加站点资源与外置索引器重复站点的去重，解决去除勾选不生效问题

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
1. 手动去重，你内置站点都有了，为何还要去插件索引器增加
2. 为何不去重，因为找不到共同点，内置索引器和插件索引器不存在相似的地方

综上手动去重，否则可接受重复

**Comment by lovek8s** [comment]
> 2\. ，因为找不到共同点，内置索引器和插件索引器不存在相似的地方

好的，那第二个问题呢，关闭一些重复的，关闭不了

**Comment by hsuyelin** [comment]
> 

需要2个都关掉，还有个关闭方式是取消后，点击空白处

**Comment by DracoYus** [comment]
> 1. 手动去重，你内置站点都有了，为何还要去插件索引器增加
> 2. 为何不去重，因为找不到共同点，内置索引器和插件索引器不存在相似的地方
> 
> 综上手动去重，否则可接受重复

1.插件索引器支持FlareSolverr，可以查询内建索引器无法查询的站点。同时又想利用站点维护下载设置、RSS订阅和数据统计的功能。这种场景下该如何设置。
2.使用同一个账号，在内建索引器和插件索引器都勾选的情况下，是否会同时发起查询，是否会增加被ban的几率。为何无法设置成只使用其中一个进行查询，必须要两个同时开或同时关。

**Comment by TonyLiooo** [comment]
> > 
> 
> 需要2个都关掉，还有个关闭方式是取消后，点击空白处

点击空白处后点叉叉就能取消重复的，点击确定后就会恢复所取消的相同站点，这个问题感觉大佬可以修复一下。大家添加两个相同站点无非就像我之前提的，就是用nastool的签到、刷流、统计等功能，用第三方索引器的索引功能，从检索资源的角度来说像jackett对某些站点会比较友好，但是他只是索引器，没办法做到数据统计还有签到刷流等功能。可能去重目前不太好解决，但是手动取消相同站点这个大佬可以看看能不能优化下。

**Comment by hsuyelin** [comment]
> > 1. 手动去重，你内置站点都有了，为何还要去插件索引器增加
> > 2. 为何不去重，因为找不到共同点，内置索引器和插件索引器不存在相似的地方
> > 
> > 综上手动去重，否则可接受重复
> 
> 1.插件索引器支持FlareSolverr，可以查询内建索引器无法查询的站点。同时又想利用站点维护下载设置、RSS订阅和数据统计的功能。这种场景下该如何设置。 2.使用同一个账号，在内建索引器和插件索引器都勾选的情况下，是否会同时发起查询，是否会增加被ban的几率。为何无法设置成只使用其中一个进行查询，必须要两个同时开或同时关。

有点道理，我抽空看看把

**Comment by hsuyelin** [comment]
> > 1. 手动去重，你内置站点都有了，为何还要去插件索引器增加
> > 2. 为何不去重，因为找不到共同点，内置索引器和插件索引器不存在相似的地方
> > 
> > 综上手动去重，否则可接受重复
> 
> 1.插件索引器支持FlareSolverr，可以查询内建索引器无法查询的站点。同时又想利用站点维护下载设置、RSS订阅和数据统计的功能。这种场景下该如何设置。 2.使用同一个账号，在内建索引器和插件索引器都勾选的情况下，是否会同时发起查询，是否会增加被ban的几率。为何无法设置成只使用其中一个进行查询，必须要两个同时开或同时关。

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/92bc8451-b6b5-4963-bc6a-36a7180f591f)
