### ISSUE TITLE
[错误报告]: 微信使用代理的时候显示测试失败

### ISSUE THREAD

**Issue by Hi-Dka** [hsuyelin/nas-tools#561]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.14

### 问题类型

主程序运行问题

### 问题描述

我从官方版本换过来的，其他功能都正常，就是那个微信的那个会报错，不知道是什么原因，配置和我的原来配置一样，但是使用了代理服务器的时候就会报错，如果不使用代理服务器就没有问题。

### 发生问题时系统日志和配置文件

```bash
提示参数未配置或者配置失败
```

**Comment by Hi-Dka** [comment]
通过调试和对比程序发现发现没问题，是我开了代理导致连接不上

**Comment by SkyLakee** [comment]
> 通过调试和对比程序发现发现没问题，是我开了代理导致连接不上

是开了科学还是什么，我也是这样。
