### ISSUE TITLE
朱雀的站點資源 無法獲取

### ISSUE THREAD

**Issue by kai456789** [hsuyelin/nas-tools#57]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.4
>
> 环境: docker or windows or Synology
>linux docker arm64

## 你遇到什么问题了？
朱雀的站點資源 已失效 能修復一下嗎？

> 描述一下你遇到的问题
朱雀 搜索失败，出現错误码：401  jackett的索引也不支援 有人提出支援 但不在作者能力範圍內可處理

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://github.com/hsuyelin/nas-tools/assets/720118/ffffda71-7863-42e3-a440-26ac7704cda3)
![image](https://github.com/hsuyelin/nas-tools/assets/720118/5406f3ae-1ef4-4d3a-853c-15febce8ae94)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
朱雀我手上没这个站点，你先用3.2.10.5重试下，不管成不成功帮忙反馈下

**Comment by iovejieba** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.2.10.4
> > 环境: docker or windows or Synology
> > linux docker arm64
> 
> ## 你遇到什么问题了？
> 朱雀的站點資源 已失效 能修復一下嗎？
> 
> > 描述一下你遇到的问题
> > 朱雀 搜索失败，出現错误码：401  jackett的索引也不支援 有人提出支援 但不在作者能力範圍內可處理
> 
> ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 是
> 
> > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> 
> ## 你期望的结果
> > 描述以下你期望的结果
> 
> ## 给出程序界面截图、后台运行日志或配置文件
> ![image](https://user-images.githubusercontent.com/720118/261173469-ffffda71-7863-42e3-a440-26ac7704cda3.png) ![image](https://user-images.githubusercontent.com/720118/261173478-5406f3ae-1ef4-4d3a-853c-15febce8ae94.png)
> 
> > 如UI BUG请提供截图及配置文件截图
> > 其它问题提供后台日志，如为Docker请提供docker的日志

隔壁有json更新....不过我没id 加完没办法测试....就比较尴尬

**Comment by kai456789** [comment]
> 朱雀我手上没这个站点，你先用3.2.10.5重试下，不管成不成功帮忙反馈下

已用3.2.10.5重試 依舊不行

**Comment by kai456789** [comment]
> > ## 你使用的 NAStool 是什么版本，什么环境？
> > > NAStool 版本: v3.2.10.4
> > > 环境: docker or windows or Synology
> > > linux docker arm64
> > 
> > 
> > ## 你遇到什么问题了？
> > 朱雀的站點資源 已失效 能修復一下嗎？
> > > 描述一下你遇到的问题
> > > 朱雀 搜索失败，出現错误码：401  jackett的索引也不支援 有人提出支援 但不在作者能力範圍內可處理
> > 
> > 
> > ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > 是
> > > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> > 
> > 
> > ## 你期望的结果
> > > 描述以下你期望的结果
> > 
> > 
> > ## 给出程序界面截图、后台运行日志或配置文件
> > ![image](https://user-images.githubusercontent.com/720118/261173469-ffffda71-7863-42e3-a440-26ac7704cda3.png) ![image](https://user-images.githubusercontent.com/720118/261173478-5406f3ae-1ef4-4d3a-853c-15febce8ae94.png)
> > > 如UI BUG请提供截图及配置文件截图
> > > 其它问题提供后台日志，如为Docker请提供docker的日志
> 
> 隔壁有json更新....不过我没id 加完没办法测试....就比较尴尬

我先暫用pptp 的搜索

**Comment by iovejieba** [comment]
> > > ## 你使用的 NAStool 是什么版本，什么环境？
> > > > NAStool 版本: v3.2.10.4
> > > > 环境: docker or windows or Synology
> > > > linux docker arm64
> > > 
> > > 
> > > ## 你遇到什么问题了？
> > > 朱雀的站點資源 已失效 能修復一下嗎？
> > > > 描述一下你遇到的问题
> > > > 朱雀 搜索失败，出現错误码：401  jackett的索引也不支援 有人提出支援 但不在作者能力範圍內可處理
> > > 
> > > 
> > > ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > > 是
> > > > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> > > 
> > > 
> > > ## 你期望的结果
> > > > 描述以下你期望的结果
> > > 
> > > 
> > > ## 给出程序界面截图、后台运行日志或配置文件
> > > ![image](https://user-images.githubusercontent.com/720118/261173469-ffffda71-7863-42e3-a440-26ac7704cda3.png) ![image](https://user-images.githubusercontent.com/720118/261173478-5406f3ae-1ef4-4d3a-853c-15febce8ae94.png)
> > > > 如UI BUG请提供截图及配置文件截图
> > > > 其它问题提供后台日志，如为Docker请提供docker的日志
> > 
> > 
> > 隔壁有json更新....不过我没id 加完没办法测试....就比较尴尬
> 
> 我先暫用pptp 的搜索

[](https://www.123pan.com/s/bcsSVv-A7Bwv.html)

尝试加了下 肉丝和大概重新加了下朱雀  不确定是否ok  因为之前我看是有朱雀的

**Comment by iovejieba** [comment]
> > > > > ## 你使用的 NAStool 是什么版本，什么环境？
> > > > > > NAStool 版本: v3.2.10.4
> > > > > > 环境: docker or windows or Synology
> > > > > > linux docker arm64
> > > > > 
> > > > > 
> > > > > ## 你遇到什么问题了？
> > > > > 朱雀的站點資源 已失效 能修復一下嗎？
> > > > > > 描述一下你遇到的问题
> > > > > > 朱雀 搜索失败，出現错误码：401  jackett的索引也不支援 有人提出支援 但不在作者能力範圍內可處理
> > > > > 
> > > > > 
> > > > > ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> > > > > 是
> > > > > > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> > > > > 
> > > > > 
> > > > > ## 你期望的结果
> > > > > > 描述以下你期望的结果
> > > > > 
> > > > > 
> > > > > ## 给出程序界面截图、后台运行日志或配置文件
> > > > > ![image](https://user-images.githubusercontent.com/720118/261173469-ffffda71-7863-42e3-a440-26ac7704cda3.png) ![image](https://user-images.githubusercontent.com/720118/261173478-5406f3ae-1ef4-4d3a-853c-15febce8ae94.png)
> > > > > > 如UI BUG请提供截图及配置文件截图
> > > > > > 其它问题提供后台日志，如为Docker请提供docker的日志
> > > > 
> > > > 
> > > > 隔壁有json更新....不过我没id 加完没办法测试....就比较尴尬
> > > 
> > > 
> > > 我先暫用pptp 的搜索
> > 
> > 
> > [https://www.123pan.com/s/bcsSVv-A7Bwv.html](url)
> > 尝试加了下 肉丝和大概重新加了下朱雀 不确定是否ok 没站... 没办法测 大概筛json 理论可能应该没问题 谁有相关站 谁测下吧....
> 
> zhuque没有category和torrents么？ @iovejieba

隔壁那个大佬site 我看好像朱雀没有 其他的貌似有

**Comment by Chen3553887** [comment]
> 朱雀我手上没这个站点，你先用3.2.10.5重试下，不管成不成功帮忙反馈下

大佬是否需要一个药

**Comment by hsuyelin** [comment]
可以的，感谢
预注册id：hsuyelin
***@***.***
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月18日 12:16 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 朱雀的站點資源 無法獲取 (Issue #57) |

朱雀我手上没这个站点，你先用3.2.10.5重试下，不管成不成功帮忙反馈下

大佬是否需要一个药

**Comment by hsuyelin** [comment]
@kai456789 @Chen3553887 等我发布新版本，麻烦测试下
