### ISSUE TITLE
[功能改进] 建议用"-"替换字符":"而非“："

### ISSUE THREAD

**Issue by Saniadoajd** [hsuyelin/nas-tools#58]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.5
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
app/utils/string_utils.py的clear_file_name将带有副标题的媒体名称中的":"被替换为“："，上传OneDrive的时候会变成” ‘：“
![image](https://github.com/hsuyelin/nas-tools/assets/57792045/dfaa97b5-d33b-4693-baed-1a6e2cc6e022)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
建议用"-"替换字符":"而非“："
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by hsuyelin** [comment]
抽空加一个字符偏好，你的习惯是 - ，别人的习惯不一定是这个

**Comment by Saniadoajd** [comment]
> 抽空加一个字符偏好，你的习惯是 - ，别人的习惯不一定是这个

好的谢谢

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/78dd3114-81ec-47d0-badc-fa9270d95d7b)

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/09327068-e534-4a15-8f7f-4bae8558bce0)

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/62f8dbe5-e5cb-4b86-b6a2-e90f9e9be60d)

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/e399702c-6f36-4112-982c-c9b5ce366ba4)

**Comment by Saniadoajd** [comment]
> ![image](https://user-images.githubusercontent.com/17918063/261463746-78dd3114-81ec-47d0-badc-fa9270d95d7b.png)
> 
> ![image](https://user-images.githubusercontent.com/17918063/261463801-09327068-e534-4a15-8f7f-4bae8558bce0.png)
> 
> ![image](https://user-images.githubusercontent.com/17918063/261463841-62f8dbe5-e5cb-4b86-b6a2-e90f9e9be60d.png)
> 
> ![image](https://user-images.githubusercontent.com/17918063/261463668-e399702c-6f36-4112-982c-c9b5ce366ba4.png)

自定义识别词和重命名是两回事。重命名里的非法字符替换是转移文件的时候执行的，是在成功识别媒体文件后对官方命名里的字符做替换，比如识别文件为TMDB id 438148，将媒体文件重命名为官方命名Minions: The Rise of Gru，并将官方命名中的":"替换为“："，这跟识别词没有关系。

**Comment by hsuyelin** [comment]
https://github.com/hsuyelin/nas-tools/commit/c37f33c5c511361c8a8abef69d48724d36fc2546
