### ISSUE TITLE
[错误报告]: 观众站(audiences)做种数及下载数读取错误导致判断做种数量为0，无法完成订阅下载。

### ISSUE THREAD

**Issue by hanfly** [hsuyelin/nas-tools#581]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.14 d43cc5c

### 问题类型

其他问题

### 问题描述

![v3 3 14 d43cc5c](https://github.com/hsuyelin/nas-tools/assets/16554128/46ce1b93-3ae3-4de4-849b-38b1d09281e9)
如图所示，发布时间，大小，种子数，下载完成数均读取错位。导致订阅判断做种数量为0，无法下载订阅文件。
```
观众 返回数据：41
--
00:11:39 | Indexer | Running Man S2024E693 1080p WEB-DL AAC 2.0 H.264-MMR 做种数为0
00:11:39 | Indexer | Running Man S01E693 2010 1080p friDay WEB-DL H264 AAC-DramaS@ADWeb 做种数为0
00:11:39 | Indexer | Running Man S06 2015 720p KOR WEB-DL H264 AC3-MXZMZ 做种数为0
00:11:39 | Indexer | Running Man S2024E692 1080p WEB-DL AAC 2.0 H.264-MMR 做种数为0
00:11:39 | Indexer | Running Man S01E692 2010 1080p friDay WEB-DL H264 AAC-DramaS@ADWeb 做种数为0
00:11:39 | Indexer | Running Man S2024E691 1080p WEB-DL AAC 2.0 H.264-MMR 做种数为0
00:11:39 | Indexer | Running Man S01E691 2010 1080p friDay WEB-DL H264 AAC-DramaS@ADWeb 做种数为0

```

**Comment by jackloves111** [comment]
没有问题
