### ISSUE TITLE
hh更新ui了 大佬能适配下索引器吗

### ISSUE THREAD

**Issue by felix-klk** [hsuyelin/nas-tools#59]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.2.10.5
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://github.com/hsuyelin/nas-tools/assets/52670643/d9e74782-4595-46fc-b98e-a90597f56580)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jackloves111** [comment]
你不说我都没发现，这个肯定要适配，这个站点用的人还挺多的

**Comment by felix-klk** [comment]
最近周年庆 ！

> 你不是说我都发现了，这个肯定要改装，这个站点用的人还挺多的

它刚刚更新的ui

**Comment by jackloves111** [comment]
@hsuyelin  大佬有药没，没有我发一个，然后你抽空适配下，哈哈

**Comment by felix-klk** [comment]
> @hsuyelin 大佬有药没，没有我发一个，然后你抽空改装下，哈哈。有药，发现之前刷流错误，现在占有率太低发不了了。有能发的可以给他发一个@felix-klk

我等级不够啊 刚刚去抽奖啥也没抽到

**Comment by iovejieba** [comment]
我估计隔壁mantou568  应该会更 到时候看看隔壁吧...有json 就好搞了

**Comment by hsuyelin** [comment]
> > @hsuyelin 大佬有药没，没有我发一个，然后你抽空改装下，哈哈。有药，发现之前刷流错误，现在占有率太低发不了了。有能发的可以给他发一个@felix-klk
> 
> 我等级不够啊 刚刚去抽奖啥也没抽到

没号，不然第一时间就适配了 @jackloves111 @iovejieba 只能等喂饭了

**Comment by jackloves111** [comment]
今天晚上就可以发了，等我大佬

**Comment by lovek8s** [comment]
好羡慕你们可以给大佬喂药。

**Comment by jackloves111** [comment]
原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来

**Comment by ehguidu** [comment]
> 

原作者在哪更新了？

**Comment by hsuyelin** [comment]
> > 
> 
> 原作者在哪更新了？

https://github.com/jxxghp/MoviePilot , 是这个新项目哦 ~

**Comment by caneman** [comment]
> 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来

我解密出来了，需要发你吗？

**Comment by hsuyelin** [comment]
> > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> 
> 我解密出来了，需要发你吗？

我也搞定了

**Comment by hsuyelin** [comment]
> > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> 
> 我解密出来了，需要发你吗？

方法自己知道就好惹，不要公开哈，我也知道如何获取了

**Comment by jackloves111** [comment]
你们都有了，看来也不需要我了，就剩下测试了

**Comment by caneman** [comment]
> > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > 
> > 
> > 我解密出来了，需要发你吗？
> 
> 我也搞定了

你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？

**Comment by hsuyelin** [comment]
> > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > 
> > > 
> > > 我解密出来了，需要发你吗？
> > 
> > 
> > 我也搞定了
> 
> 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？

3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer

**Comment by jackloves111** [comment]
> > > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > > 
> > > > 
> > > > 我解密出来了，需要发你吗？
> > > 
> > > 
> > > 我也搞定了
> > 
> > 
> > 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？
> 
> 3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer

重组之后不知道改没改方法，原先的刷流他放最下面的单独列出来的

**Comment by caneman** [comment]
> > > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > > 
> > > > 
> > > > 我解密出来了，需要发你吗？
> > > 
> > > 
> > > 我也搞定了
> > 
> > 
> > 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？
> 
> 3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer

我一直用的是vt，没关注过刷流那块，我去看看

**Comment by jackloves111** [comment]
> > > > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > > > 
> > > > > 
> > > > > 我解密出来了，需要发你吗？
> > > > 
> > > > 
> > > > 我也搞定了
> > > 
> > > 
> > > 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？
> > 
> > 
> > 3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer
> 
> 我一直用的是vt，没关注过刷流那块，我去看看

要么发我看看吧，jackloves111@163.com，感谢

**Comment by hsuyelin** [comment]
> > > > > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > > > > 
> > > > > > 
> > > > > > 我解密出来了，需要发你吗？
> > > > > 
> > > > > 
> > > > > 我也搞定了
> > > > 
> > > > 
> > > > 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？
> > > 
> > > 
> > > 3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer
> > 
> > 
> > 我一直用的是vt，没关注过刷流那块，我去看看
> 
> 要么发我看看吧，[jackloves111@163.com](mailto:jackloves111@163.com)，感谢

拉下代码看看是不是可以了，顺便求个药

**Comment by jackloves111** [comment]
> > > > > > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > > > > > 
> > > > > > > 
> > > > > > > 我解密出来了，需要发你吗？
> > > > > > 
> > > > > > 
> > > > > > 我也搞定了
> > > > > 
> > > > > 
> > > > > 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？
> > > > 
> > > > 
> > > > 3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer
> > > 
> > > 
> > > 我一直用的是vt，没关注过刷流那块，我去看看
> > 
> > 
> > 要么发我看看吧，[jackloves111@163.com](mailto:jackloves111@163.com)，感谢
> 
> 拉下代码看看是不是可以了，顺便求个药

药今天会发的，还差一点升级

**Comment by hsuyelin** [comment]
> > > > > > > > > 原作者重构的更新了憨憨，但是他的站点文件加密了，我解包解不出来
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我解密出来了，需要发你吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 我也搞定了
> > > > > > 
> > > > > > 
> > > > > > 你这个是从哪个版本开始往后做的呀？我才发现这个项目，我是从3.2.3一直自己搞自用的，v3.2.3群晖版，不知道迁移到这个版本会不会出问题呀？
> > > > > 
> > > > > 
> > > > > 3.2.1 @caneman 刷流那个你能解析出来么。我直解析出indexer
> > > > 
> > > > 
> > > > 我一直用的是vt，没关注过刷流那块，我去看看
> > > 
> > > 
> > > 要么发我看看吧，[jackloves111@163.com](mailto:jackloves111@163.com)，感谢
> > 
> > 
> > 拉下代码看看是不是可以了，顺便求个药
> 
> 药今天会发的，还差一点升级

试了可以么

**Comment by jackloves111** [comment]
好像不行

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/34148ab0-4e39-4595-a615-f14b3782158c)
日志里面的链接进去是正确的搜索界面，但是获取不到种子，稍微再等等， 我要药马上就好了

**Comment by caneman** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/261622872-34148ab0-4e39-4595-a615-f14b3782158c.png) 日志里面的链接进去是正确的搜索界面，但是获取不到种子，稍微再等等， 我要药马上就好了

搜索我这里是可以跑通的，但是我的是从3.2.3构建的，不过站点统计我这边好像有点问题

![Snipaste_2023-08-18_22-08-55](https://github.com/hsuyelin/nas-tools/assets/13256051/57a967b7-956b-48b4-aa38-72cb2b967ca9)
![Snipaste_2023-08-18_22-09-08](https://github.com/hsuyelin/nas-tools/assets/13256051/d73219f9-3cc3-4871-adf2-e4eec9b0a5fc)

**Comment by jackloves111** [comment]
@caneman  你解出来的json方便发我吗？我测试下

**Comment by caneman** [comment]
> @caneman 你解出来的json方便发我吗？我测试下

之前发你了，没有收到吗？我再发一遍，解出来的站点资源可以直接用，搜索不行，结果会乱，要改下参数，我把改后的发你吧

**Comment by hyyangs** [comment]
我搜索刷流都可以了，可以数据那块还没找到哪里弄

**Comment by jackloves111** [comment]
> > 最新更新的可以了，我再多测试一下！我自己折腾的就不行，还得是你
> 
> @jackloves111 你更新了我最新上传的了么

是的，更新之后可以了  [316405c](https://github.com/hsuyelin/nas-tools/commit/316405c1e4dda533e25b248524b09f7bc8571a97)

**Comment by hsuyelin** [comment]
> > > 最新更新的可以了，我再多测试一下！我自己折腾的就不行，还得是你
> > 
> > 
> > @jackloves111 你更新了我最新上传的了么
> 
> 是的，更新之后可以了 [5b5ccb5](https://github.com/hsuyelin/nas-tools/commit/5b5ccb5e1d3d035fba1c821a7cdc3067139eb16d)

OK，那你再测测

**Comment by yellowstrong** [comment]
新版本beta憨憨更新之后搜索都没什么问题，但是站点信息里面好像数据不全，看不到等级信息以及上传下载数据

**Comment by yellowstrong** [comment]
> 新版本beta憨憨更新之后搜索都没什么问题，但是站点信息里面好像数据不全，看不到等级信息以及上传下载数据

<img width="1437" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/34505611/bb42d867-1efa-44f3-bc98-c612586316dc">

**Comment by caneman** [comment]
> > 新版本beta憨憨更新之后搜索都没什么问题，但是站点信息里面好像数据不全，看不到等级信息以及上传下载数据
> 
> <img alt="image" width="1437" src="https://user-images.githubusercontent.com/34505611/261655301-bb42d867-1efa-44f3-bc98-c612586316dc.png">

漏ID了，兄弟

**Comment by yellowstrong** [comment]
> > > 新版本beta憨憨更新之后搜索都没什么问题，但是站点信息里面好像数据不全，看不到等级信息以及上传下载数据
> > 
> > 
> > <img alt="image" width="1437" src="https://user-images.githubusercontent.com/34505611/261655301-bb42d867-1efa-44f3-bc98-c612586316dc.png">
> 
> 漏ID了，兄弟

感谢提醒 删了吧

**Comment by jackloves111** [comment]
我也是刚刚看到TG群里，有人发了修复方法，不知道这个里面的json是不是一样的```# 支持nt 3.2.3版本，适配憨憨新UI, docker名字记得改成自己的名字，默认是nas-tools
docker exec -it nas-tools sh -c 'cd /nas-tools/web/backend/ && mv user.sites.bin user.sites.bak && wget -O user.sites.bin  https://hhanclub.top/user.sites.bin' && docker restart nas-tools```

**Comment by yellowstrong** [comment]
> 我也是刚刚看到TG群里，有人发了修复方法，不知道这个里面的json是不是一样的`# 支持nt 3.2.3版本，适配憨憨新UI, docker名字记得改成自己的名字，默认是nas-tools docker exec -it nas-tools sh -c 'cd /nas-tools/web/backend/ && mv user.sites.bin user.sites.bak && wget -O user.sites.bin https://hhanclub.top/user.sites.bin' && docker restart nas-tools` 今天太晚了，明天周末，再研究研究

今天太晚了 也不影响使用 先休息吧 周末再说

**Comment by jackloves111** [comment]
![d859ca31-d100-469c-8dde-d2129eefca06](https://github.com/hsuyelin/nas-tools/assets/89971817/6b7d2b78-ed9d-4643-bf7b-0bcc9ddebed0)
@hsuyelin  1.55才能发，还差一点点，狗头

**Comment by hyyangs** [comment]
{"FREE": ["//span[@class='promotion-tag promotion-tag-free']"],"2XFREE": [],"HR": [],"PEER_COUNT": []}
这是rss free种过滤，hr还不清楚所以留空先

**Comment by jackloves111** [comment]
他这个方法，是增加一个/nas-tools/web/backend/user.sites.bin文件，就可以修复，我都没看明白这是为什么

**Comment by caneman** [comment]
> 他这个方法，是增加一个/nas-tools/web/backend/user.sites.bin文件，就可以修复，我都没看明白这是为什么

3.2.3版本所有的indexer信息都是加密的，就在这个文件里面，AES CBC，但是我暂时不知道key是什么。mp里面的也是加密的，跟这个是一样的，这个就相当于你们的sites.dat文件

**Comment by jackloves111** [comment]
> > 他这个方法，是增加一个/nas-tools/web/backend/user.sites.bin文件，就可以修复，我都没看明白这是为什么
> 
> 3.2.3版本所有的indexer信息都是加密的，就在这个文件里面，AES CBC，但是我暂时不知道key是什么。mp里面的也是加密的，跟这个是一样的，这个就相当于你们的sites.dat文件

解密方法不要直接说出来，改一下吧。

**Comment by jackloves111** [comment]
@hsuyelin 163的邮箱发不了hh，再给个别的邮箱吧！

**Comment by hsuyelin** [comment]
***@***.***
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月19日 09:29 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] hh更新ui了 大佬能适配下索引器吗 (Issue #59) |

@hsuyelin 163的邮箱发不了hh，再给个别的邮箱吧！

**Comment by hsuyelin** [comment]
> @hsuyelin 163的邮箱发不了hh，再给个别的邮箱吧！

852862698@qq.com

**Comment by jackloves111** [comment]
已发邮箱，注意查收！ @hsuyelin

**Comment by hsuyelin** [comment]
> 已发邮箱，注意查收！ @hsuyelin

哥帮忙看看是延迟还是邮箱不对，还没收到惹

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/2e850287-06c5-4b9d-8aee-a0a5985b77d9)
邮箱地址没错吧

**Comment by hsuyelin** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/261756107-2e850287-06c5-4b9d-8aee-a0a5985b77d9.png) 邮箱地址没错吧

没错呀，可能是延迟？

**Comment by jackloves111** [comment]
> > ![image](https://user-images.githubusercontent.com/89971817/261756107-2e850287-06c5-4b9d-8aee-a0a5985b77d9.png) 邮箱地址没错吧
> 
> 没错呀，可能是延迟？

我用我自己的邮箱转发给你了，你看下

**Comment by hsuyelin** [comment]
> > > ![image](https://user-images.githubusercontent.com/89971817/261756107-2e850287-06c5-4b9d-8aee-a0a5985b77d9.png) 邮箱地址没错吧
> > 
> > 
> > 没错呀，可能是延迟？
> 
> 我用我自己的邮箱转发给你了，你看下，可能现在注册的人太多了，邮箱服务器忙不过来了

收到了，我先把邮箱部分删掉哈

**Comment by hsuyelin** [comment]
> 已发邮箱，注意查收！ @hsuyelin

憨憨的发信服务器应该卡住了，验证邮件也不发送，等一等吧，谢谢哥，回头我看RSS怎么适配

**Comment by iovejieba** [comment]
大佬们忙的话，有json参数的话 我可以来尝试加....

**Comment by hsuyelin** [comment]
> 大佬们忙的话，有json参数的话 我可以来尝试加....

昨都更新了 -。-

**Comment by iovejieba** [comment]
> > 大佬们忙的话，有json参数的话 我可以来尝试加....
> 
> 昨都更新了 -。- beta版本

额 好的 大佬 辛苦！
