### ISSUE TITLE
[错误报告]: 全部电影 （未搜索到任何资源）

### ISSUE THREAD

**Issue by kweefc** [hsuyelin/nas-tools#591]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.14 d43cc5c

### 问题类型

其他问题

### 问题描述

![Screenshot 2024-03-11 222013](https://github.com/hsuyelin/nas-tools/assets/76863505/c84ef489-7fe8-49d8-89f2-cccade1eecd6)
不好意思我是新手
今天刚刚装就遇到这个问题，完全找不到下载资源。请帮帮我

**Comment by jackloves111** [comment]
> 同，之前也有issue提过 貌似没人正解

真晕倒，你把这个软件当爱奇艺吗？你不配置站点，为什么能搜出资源？

**Comment by kweefc** [comment]
> > 同，之前也有issue提过 貌似没人正解
> 
> 真晕倒，你把这个软件当爱奇艺吗？你不配置站点，为什么能搜出资源？

问题是它本身里面有站点了 然后不能加其他的站点才是大问题

**Comment by kweefc** [comment]
> > > > 同，之前也有issue提过 貌似没人正解
> > > 
> > > 
> > > 真晕倒，你把这个软件当爱奇艺吗？你不配置站点，为什么能搜出资源？
> > 
> > 
> > 问题是它本身里面有站点了 然后不能加其他的站点才是大问题
> 
> 我都加了20几个站了，不知道你在说啥

怎么加

**Comment by Travel2Here** [comment]
> > 同，之前也有issue提过 貌似没人正解
> 
> 真晕倒，你把这个软件当爱奇艺吗？你不配置站点，为什么能搜出资源？

张口就来啊，当然配过自己的PT站进去。还要怎样配吗？真心求解~同样的站URL和COOKIES，在MOVIE PILOT里就正常能搜~

<img width="810" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/99887507/d4d7a878-4573-410c-a622-cb8401d82df1">

**Comment by Travel2Here** [comment]
**docker里的日志貌似找到线索了。但为什么拒绝访问？这个127.0.0.1:6379是什么？**
————————————————————
stderr: 2024-03-15 22:21:30,305	INFO: 【Indexer】开始并行搜索 Remember Me，线程数：4 ...
stderr: 2024-03-15 22:21:30,307	INFO: 【Indexer】开始搜索Indexer：HH ...
stderr: 2024-03-15 22:21:30,313	INFO: 【Spider】开始请求：https://hhanclub.top/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&search_area=0&cat401=1&cat405=1
stderr: 2024-03-15 22:21:30,314	INFO: 【Indexer】开始搜索Indexer：ZMPT ...
stderr: 2024-03-15 22:21:30,318	INFO: 【Indexer】开始搜索Indexer：MT ...
stderr: 2024-03-15 22:21:30,328	INFO: 【Indexer】开始搜索Indexer：1PTBA ...
stderr: 2024-03-15 22:21:30,333	INFO: 【Spider】开始请求：https://zmpt.cc/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&cat401=1
stderr: 2024-03-15 22:21:30.334 | ERROR    | feapder.core.parser_control:deal_request:line:628 | 
stderr:                             -------------- TorrentSpider.parse error -------------
stderr:                             error          Error 111 connecting to 127.0.0.1:6379. Connection refused.
stderr:                             response       None
stderr:                             deal request   <Request https://hhanclub.top/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&search_area=0&cat401=1&cat405=1>
stderr:                             
stderr: 2024-03-15 22:21:30,338	INFO: 【Spider】开始请求：https://xp.m-team.io/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&cat401=1&cat419=1&cat420=1&cat421=1&cat439=1
stderr: 2024-03-15 22:21:30,339	INFO: 【Spider】开始请求：https://1ptba.com/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&cat401=1
stderr: 2024-03-15 22:21:30.344 | ERROR    | feapder.core.parser_control:deal_request:line:628 | 
stderr:                             -------------- TorrentSpider.parse error -------------
stderr:                             error          Error 111 connecting to 127.0.0.1:6379. Connection refused.
stderr:                             response       None
stderr:                             deal request   <Request https://1ptba.com/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&cat401=1>
stderr:                             
stderr: 2024-03-15 22:21:30.345 | ERROR    | feapder.core.parser_control:deal_request:line:628 | 
stderr:                             -------------- TorrentSpider.parse error -------------
stderr:                             error          Error 111 connecting to 127.0.0.1:6379. Connection refused.
stderr:                             response       None
stderr:                             deal request   <Request https://zmpt.cc/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&cat401=1>
stderr:                             
stderr: 2024-03-15 22:21:30.347 | ERROR    | feapder.core.parser_control:deal_request:line:628 | 
stderr:                             -------------- TorrentSpider.parse error -------------
stderr:                             error          Error 111 connecting to 127.0.0.1:6379. Connection refused.
stderr:                             response       None
stderr:                             deal request   <Request https://xp.m-team.io/torrents.php?search_mode=0&page=0&notnewword=1&search=Remember+Me&cat401=1&cat419=1&cat420=1&cat421=1&cat439=1>
stderr:                             
stderr: 2024-03-15 22:22:01,435	WARNING: 【Indexer】HH 未搜索到数据
stderr: 2024-03-15 22:22:01,510	WARNING: 【Indexer】ZMPT 未搜索到数据
stderr: 2024-03-15 22:22:01,549	WARNING: 【Indexer】MT 未搜索到数据
stderr: 2024-03-15 22:22:01,625	WARNING: 【Indexer】1PTBA 未搜索到数据
stderr: 2024-03-15 22:22:01,629	INFO: 【Indexer】所有站点搜索完成，有效资源数：0，总耗时 31 秒
stderr: 2024-03-15 22:22:01,797	INFO: 【Web】灿烂的她 未搜索到任何资源
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
stderr:     return self.wsgi_app(environ, start_response)
stderr:   File "/usr/local/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
stderr:     return self.app(environ, start_response)
stderr:   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2197, in wsgi_app
stderr:     return response(environ, start_response)
stderr:   File "/usr/local/lib/python3.10/site-packages/flask_sock/__init__.py", line 86, in __call__
stderr:     raise ConnectionError()
stderr: ConnectionError

**Comment by shuiyind** [comment]
看起来是运行环境File "/usr/local/lib/python3.10/site-packages/flask_sock/init.py", 有问题，我也不懂，你可以换个版本试一下（升级）

**Comment by Travel2Here** [comment]
> 看起来是运行环境File "/usr/local/lib/python3.10/site-packages/flask_sock/init.py", 有问题，我也不懂，你可以换个版本试一下（升级）

我也纳闷，不断升级过。一直保持最新。后来还怀疑环境完全新建了个容器全重新配置也一样~服了
可以看见日志里它爬的链接都是对的 就是最后出结果的时候不正常 包括那个中途的6379端口拒绝访问 没看明白是什么东西。
劳烦开发者给分析一下~

**Comment by Travel2Here** [comment]
> 
> 
> ![Screenshot 2024-03-19 182638](https://github.com/hsuyelin/nas-tools/assets/76863505/0c40a2a5-bcab-48ec-ab19-4215049a9f95)
> 
> 
> 
> 解决了 谢谢各位

怎么弄的分享下？😂
