### ISSUE TITLE
PT站点测试跳转失败

### ISSUE THREAD

**Issue by 1229574757** [hsuyelin/nas-tools#6]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.5 81b1c5d
>
> 环境: docker
>

## 你遇到什么问题了？

> 部分站点测试会出现跳转失败情况，主要是因为5秒盾（Cloudflare），以前官方版本就会出现，有时候可以通过本地先过Cloudflare，不是每次都能过，而且一段时间后会失效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有彻底的解决方案，不知道作者是否可以考虑解决这个问题或者像jackett一样支持使用flaresolverr

## 你期望的结果

> 站点更新cookie和测试站点时可以绕过Cloudflare，建议引入flaresolverr，这样可让nastool支持更多的站点

## 给出程序界面截图、后台运行日志或配置文件
日志：
2023-07-12 14:42:11,467 INFO: Challenge detected. Title found: Just a moment...
2023-07-12 14:43:11,529 ERROR: Error solving the challenge. Timeout 60 after 60.1 seconds.
截图：
![image](https://github.com/hsuyelin/nas-tools/assets/64239067/72bda2e2-8ee6-4694-bdef-ed38c65046c9)

**Comment by hsuyelin** [comment]
你说的我知道，但是鉴于原版的框架比较难改，作为一个优化项等有时间看看怎么吃下这个问题

**Comment by hsuyelin** [comment]
@1229574757 你说的我知道，但是鉴于原版的框架比较难改，作为一个优化项等有时间看看怎么吃下这个问题
