### ISSUE TITLE
[功能改进] 重命名规则的参数{videoCodec}中分离出10bit和HDR等标识

### ISSUE THREAD

**Issue by ArthurSmoke** [hsuyelin/nas-tools#61]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.10.5
>
> 环境: docker

## 你想要新增或者改进什么功能？
 规则：{title}.{year}.{edition}.{videoFormat}.{videoCodec}.{audioCodec}-{releaseGroup}
 测试文件：John.Wick.Chapter.4.2023.UHD.BluRay.2160p.x265.10bit.DoVi-CMRG.mkv
 `X265 10bit`会识别为一个整体，希望能添加{bitDepth}对应10bit，{colorSpace}对应HDR等信息
而{videoCodec}就只显示H264，H265等编码格式

**Comment by hsuyelin** [comment]
感觉差不多啊，说说看为何想区别开来
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月18日 16:27 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [hsuyelin/nas-tools] 重命名规则的参数{videoCodec}中分离出10bit和HDR等标识 (Issue #61) |

你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: v3.2.10.5

环境: docker

你想要新增或者改进什么功能？

规则：{title}.{year}.{edition}.{videoFormat}.{videoCodec}.{audioCodec}-{releaseGroup}
测试文件：John.Wick.Chapter.4.2023.UHD.BluRay.2160p.x265.10bit.DoVi.mUHD-FRDS.mkv
X265 10bit会识别为一个整体，希望能添加{bitDepth}对应10bit，{colorSpace}对应HDR等信息
而{videoCodec}就只显示H264，H265等编码格式

**Comment by hsuyelin** [comment]
评估了下，感觉没必要改动
