### ISSUE TITLE
好大签到报错Cookie失效问题解决

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#62]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>3.2.10.5
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 好大签到错误，提示Cookie已失效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 经过浏览源代码发现，好大的签到是有做独立的签到脚本，位于项目app/plugins/modules/_autosignin/hdarea.py文件，只需要修改文件中的第12行 **site_url = "hdarea.co"** 改为 **site_url = "hdarea.club"** 以及第45行中的 **url="https://www.hdarea.co/sign_in.php"** 改为 **url="https://hdarea.club/sign_in.php"** 即可正常运行，望H大能修改一下

**Comment by jackloves111** [comment]
Cookie已失效，就是Cookie已失效的意思

**Comment by hsuyelin** [comment]
https://github.com/hsuyelin/nas-tools/commit/e581d454c2c19541694ecf14cef9fe1fb103c5e3 @yellowstrong  done

**Comment by yellowstrong** [comment]
> 这个忘记改了

我也感觉是忘记了 没提过github的pull，所以看看就这一个修改直接提issue方便看看改了

**Comment by hsuyelin** [comment]
> > 这个忘记改了
> 
> 我也感觉是忘记了 没提过github的pull，所以看看就这一个修改直接提issue方便看看改了

喂饭的感觉太舒服了

**Comment by yellowstrong** [comment]
> > > 这个忘记改了
> > 
> > 
> > 我也感觉是忘记了 没提过github的pull，所以看看就这一个修改直接提issue方便看看改了
> 
> 喂饭的感觉太舒服了

看了下提交 还有第12行 **site_url = "hdarea.co"** 改为 **site_url = "hdarea.club"** 哈哈

**Comment by hsuyelin** [comment]
> > > > 这个忘记改了
> > > 
> > > 
> > > 我也感觉是忘记了 没提过github的pull，所以看看就这一个修改直接提issue方便看看改了
> > 
> > 
> > 喂饭的感觉太舒服了
> 
> 看了下提交 还有第12行 **site_url = "hdarea.co"** 改为 **site_url = "hdarea.club"** 哈哈

https://github.com/hsuyelin/nas-tools/commit/316405c1e4dda533e25b248524b09f7bc8571a97 @yellowstrong  下次可以提个pr，刷一下贡献

**Comment by yellowstrong** [comment]
> > > > > 这个忘记改了
> > > > 
> > > > 
> > > > 我也感觉是忘记了 没提过github的pull，所以看看就这一个修改直接提issue方便看看改了
> > > 
> > > 
> > > 喂饭的感觉太舒服了
> > 
> > 
> > 看了下提交 还有第12行 **site_url = "hdarea.co"** 改为 **site_url = "hdarea.club"** 哈哈
> 
> [316405c](https://github.com/hsuyelin/nas-tools/commit/316405c1e4dda533e25b248524b09f7bc8571a97) @yellowstrong 下次可以提个pr，刷一下贡献

👌 这就去学一下提pr 哈哈
