### ISSUE TITLE
[错误报告]: DOCKER版本一旦停止或者重启都无法重新启动。

### ISSUE THREAD

**Issue by liubin120** [hsuyelin/nas-tools#628]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.15

### 问题类型

Docker或运行环境问题

### 问题描述

111111111111111111111111111111

### 发生问题时系统日志和配置文件

```bash
1111111111111111111111111111111111111
```

**Comment by hs263** [comment]
看日志，sh输入几个命令就可以了。

**Comment by liubin120** [comment]
/
![QQ截图20240409110904](https://github.com/hsuyelin/nas-tools/assets/150803858/16dd74f3-37bc-44b2-9ffa-c0e050a864c5)

**Comment by liubin120** [comment]
大佬帮忙看一下，怎么解决

**Comment by liubin120** [comment]
[](url)

**Comment by liubin120** [comment]
[](url)

**Comment by liubin120** [comment]
[Uploading nastools.txt…]()
