### ISSUE TITLE
使用nastools刮削的时候使用fanart下载图片一直失败

### ISSUE THREAD

**Issue by serovovip** [hsuyelin/nas-tools#63]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.10.5
>
> 环境: docker or windows or Synology
>Synology
![截屏2023-08-18 22 06 26](https://github.com/hsuyelin/nas-tools/assets/49633761/edce2768-8319-4c54-9996-0e90ac80d1d8)

## 你遇到什么问题了？

> 刮削的时候使用fanart下载图片一直失败，我也尝试过使用代理，因为是http请求，我设置代理规则不生效。

**Comment by hsuyelin** [comment]
@serovovip 自行科学，这个无解

**Comment by iovejieba** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v3.10.5
> > 环境: docker or windows or Synology
> > Synology
> > ![截屏2023-08-18 22 06 26](https://user-images.githubusercontent.com/49633761/261634585-edce2768-8319-4c54-9996-0e90ac80d1d8.png)
> 
> ## 你遇到什么问题了？
> > 刮削的时候使用fanart下载图片一直失败，我也尝试过使用代理，因为是http请求，我设置代理规则不生效。

或者 dns check  看实时ip出口是否变化  不过 我印象中fanart 貌似没cdn 只有一个ip
