### ISSUE TITLE
[错误报告]:更新馒头站cookie时提示"未找到用户名输入框"

### ISSUE THREAD

**Issue by po1a2a** [hsuyelin/nas-tools#636]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.3.15 3fbde6a

### 问题类型

主程序运行问题

### 问题描述

更新馒头站cookie时提示"未找到用户名输入框"
<img width="729" alt="截屏2024-04-08 18 17 24" src="https://github.com/hsuyelin/nas-tools/assets/31470343/744b8484-0b19-40c9-b3db-9cb5c339ba14">
<img width="727" alt="截屏2024-04-08 18 17 48" src="https://github.com/hsuyelin/nas-tools/assets/31470343/40686b1d-f24b-4883-9a30-dc5ceb0c61c4">

### 发生问题时系统日志和配置文件

```bash
024-04-08 18:16:28,906 INFO: 【Sites】开始更新 M - team Cookie和User-Agent ...
2024-04-08 18:16:32,013 INFO: Challenge not detected!
2024-04-08 18:16:32,097 ERROR: 【Sites】获取 M - team 信息失败：未找到用户名输入框
```

**Comment by po1a2a** [comment]
问题应该是docker版本是26天前更新的版本，什么时候在dockerhub上更新一下？

**Comment by iovejieba** [comment]
mt现在用api key

**Comment by po1a2a** [comment]
> mt现在用api key

在哪里输入api key？从docker pull下来的版本是还没更新吗

**Comment by po1a2a** [comment]
> mt现在用api key

解决了，点右上角小人-更新，手动更新一下就可以了

**Comment by koyo922** [comment]
> mt现在用api key

请问如图所示的“存取令牌” 就是 API KEY吗？ 我不太确定在哪里能申请 api key

<img width="1763" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/6063429/f5f66419-a470-4523-82d5-063c0e5682cf">

**Comment by po1a2a** [comment]
> > mt现在用api key
> 
> 请问如图所示的“存取令牌” 就是 API KEY吗？ 我不太确定在哪里能申请 api key
> 
> <img alt="image" width="1763" src="https://private-user-images.githubusercontent.com/6063429/328016024-f5f66419-a470-4523-82d5-063c0e5682cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTEyMjUsIm5iZiI6MTcxNDkxMDkyNSwicGF0aCI6Ii82MDYzNDI5LzMyODAxNjAyNC1mNWY2NjQxOS1hNDcwLTQ1MjMtODJkNS0wNjNjMGU1NjgyY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDVUMTIwODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQwYmUyNjg1YTYxODZjZThiMjkxNjRmMzM0NWI1YmMyYmQwODBlNTVkNjc3MzliYWZkZDRhMTViZTkxMzJkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9EjYFscnQCDJ1VXm9KN2ltyNOyIrQI5JoR3YhpKBUqI">

就是存取令牌
