### ISSUE TITLE
反馈jackeet索引器与内置站点维护中下载器目录的问题

### ISSUE THREAD

**Issue by KeySoundsLa** [hsuyelin/nas-tools#64]
经测试
1.在索引器中使用内置建立的站点订阅剧集
剧集可根据站点下载器设置的目的地下载
2.索引器取消内置站点，使用jackeet部署的站点订阅下载
剧集无法根据内置站点下载器设置的目的地下载
而是默认使用预设的下载目录
导致某些需要HR的站点，无法根据个人设置留存。
不知道这个现象是不是一个问题 来反馈一下- -！！

![1](https://github.com/hsuyelin/nas-tools/assets/140850069/22566aec-d1fe-4058-a2af-f743662b171f)
![2](https://github.com/hsuyelin/nas-tools/assets/140850069/cb81325f-aef3-4386-a9bd-e8bcfca19040)

**Comment by hsuyelin** [comment]
> 经测试 1.在索引器中使用内置建立的站点订阅剧集 剧集可根据站点下载器设置的目的地下载 2.索引器取消内置站点，使用jackeet部署的站点订阅下载 剧集无法根据内置站点下载器设置的目的地下载 而是默认使用预设的下载目录 导致某些需要HR的站点，无法根据个人设置留存。 不知道这个现象是不是一个问题 来反馈一下- -！！
> 
> ![1](https://user-images.githubusercontent.com/140850069/261789767-22566aec-d1fe-4058-a2af-f743662b171f.png) ![2](https://user-images.githubusercontent.com/140850069/261789786-cb81325f-aef3-4386-a9bd-e8bcfca19040.png)

这不是正常的么，Jackett和内置本质上不同的东西

**Comment by hsuyelin** [comment]
我认为Jackett只是辅助，而且本质上并不是一个东西，你只是认为都是馒头就是一样的，其实不是的，我先关了，如果你觉得我说的不对，到时候再打开

**Comment by iovejieba** [comment]
> 经测试 1.在索引器中使用内置建立的站点订阅剧集 剧集可根据站点下载器设置的目的地下载 2.索引器取消内置站点，使用jackeet部署的站点订阅下载 剧集无法根据内置站点下载器设置的目的地下载 而是默认使用预设的下载目录 导致某些需要HR的站点，无法根据个人设置留存。 不知道这个现象是不是一个问题 来反馈一下- -！！
> 
> ![1](https://user-images.githubusercontent.com/140850069/261789767-22566aec-d1fe-4058-a2af-f743662b171f.png) ![2](https://user-images.githubusercontent.com/140850069/261789786-cb81325f-aef3-4386-a9bd-e8bcfca19040.png)

外部索引  你就只拿他当搜索 下载就行了 具体化的功能还是要依托内置 ...原因外置要大众兼容 而不是特定兼容
