### ISSUE TITLE
[错误报告]: 新版馒头数据统计不更新

### ISSUE THREAD

**Issue by xemaco** [hsuyelin/nas-tools#647]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.15

### 问题类型

其他问题

### 问题描述

新版馒头添加成功，设置了api，填写了真实cookie，能够正常搜索，测试站点连通性也没问题。但是站点数据统计那里，馒头的上传下载魔力等数据一直都不更新，一直是添加的那天的数据值，nastool里面显示的跟馒头网站上真实的数值已经不一致了，请求修复。

**Comment by joneechua** [comment]
看看日志是不是被限频了

**Comment by xemaco** [comment]
> 看看日志是不是被限频了

站点 M-Team 获取流量数据失败：'bool' object has no attribute 'get'
以上是日志消息，请问该怎么办。。谢谢

**Comment by joneechua** [comment]
拉一下最新代码试试

**Comment by xemaco** [comment]
> 拉一下最新代码试试

没有用，点了更新还是不行。日志里还有一个：“【Config】内置索引文件被改动，为保证稳定性，请检查是否安装第三方插件或者人为修改 1. 如果为docker容器/套件，请删除容器/套件重新添加 2. 如果为其他版本，请重新下载”
会跟这个有关系吗

**Comment by joneechua** [comment]
这个错误一般是自己改动导致的异常

**Comment by joneechua** [comment]
启动日志里面应该有报错

**Comment by xemaco** [comment]
> 这个错误一般是自己改动导致的异常

但是我没改动什么东西啊，让我也改我也不会改啊，目前是能够正常运行的，没发现有什么影响可以不管吗？除非馒头数据显示不正常跟这个有关。如果重装容器是不是继续使用目前的设置文件才能清除【Config】内置索引文件被改动 这个报错。

另外还在日志中发现一个warning
Running pip as the root user can result in broken permission and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
请问这个有什么影响，需要怎么配置容器才能避免，谢谢

**Comment by xemaco** [comment]
v3.4.0 f93cd9a

**Comment by xemaco** [comment]
补充一下，刚注意到数据统计页面馒头的更新时间为2024-03-22 12:35:40
也就是说很久之前就已经不更新了，这个时间节点应该就是馒头改版的时间吧。
但是为什么导致馒头的数据统计不更新，而且每次点击更新都会提示 站点 M-Team 获取流量数据失败：'bool' object has no attribute 'get'
在站点管理里面删除后重新添加还是一样

**Comment by xemaco** [comment]
如果删除容器重装，并且仍映射目前的config，会有用吗，设置不想初始化，，配置一遍太花时间了。。

**Comment by xemaco** [comment]
对了，其他pt站点的数据统计都是正常更新的

**Comment by joneechua** [comment]
把你的日志贴全一点，截个图看看，最好只刷新馒头站点统计看日志输出是什么

**Comment by xemaco** [comment]
![2024-04-14_110733](https://github.com/hsuyelin/nas-tools/assets/45475619/2c583ebc-2328-43df-b4e1-a3b95aea90c7)
最后的那条“ERROR: 【Sites】站点 M-Team 获取流量数据失败：'bool' object has no attribute 'get'”
就是我刷新统计数据获得的日志

**Comment by joneechua** [comment]
不太像是最新的版本，正常应该有这样的成功或者是失败
![image](https://github.com/hsuyelin/nas-tools/assets/156154680/3c54de22-92a3-41f1-ade9-1dde2bbd08cc)
把日志级别换成debug再看看有哪些信息
![image](https://github.com/hsuyelin/nas-tools/assets/156154680/b228f1a0-c577-48ad-a49e-d043fa6e897b)

**Comment by xemaco** [comment]
后台更新了好几遍，除非是拉取源码出了错，不然应该是最新的
![1713083223355](https://github.com/hsuyelin/nas-tools/assets/45475619/8eaa8ba9-2b17-461e-8836-6eb493bcb332)

**Comment by joneechua** [comment]
没看出来是哪里的问题，我加点日志，下次看看

**Comment by xemaco** [comment]
好的，谢谢大佬

**Comment by xemaco** [comment]
> > 好的，谢谢大佬
> 
> 更新最新代码看看日志

直接复制对关键信息脱敏了，忘记截图了。不过这是启动之后的全部日志

**Comment by joneechua** [comment]
知道问题了，近期修

**Comment by xemaco** [comment]
> 知道问题了，近期修

多谢大佬！！

**Comment by xemaco** [comment]
请问这几个信息如果没发现有影响正常使用可以不管吗，如果重装容器的话会解决这个问题吗。重装容器如果还是映射原本的config文件夹是不是也没用，必须要全部重新设置跟全新安装一样才可以？

2024/04/17 16:26:30 stderr 2. 如果为其他版本，请重新下载
2024/04/17 16:26:30 stderr 1. 如果为docker容器/套件，请删除容器/套件重新添加
2024/04/17 16:26:30 stderr 【Config】内置索引文件被改动，为保证稳定性，请检查是否安装第三方插件或者人为修改

**Comment by joneechua** [comment]
不影响，可以先不用管

**Comment by xemaco** [comment]
谢谢大佬，可以正常使用了
