### ISSUE TITLE
[错误报告]: QB下载电影自动转移文件失败

### ISSUE THREAD

**Issue by OZHLYO** [hsuyelin/nas-tools#649]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.0

### 问题类型

主程序运行问题

### 问题描述

![WX20240414-010936@2x](https://github.com/hsuyelin/nas-tools/assets/104991476/3c96f6fa-0041-420f-9bed-5c2b325d498e)
使用下载器设置内的“监控”，自动转移失败:目录或文件不存在。文件管理-手动转移 可以正常转移。

**Comment by georgegoodman** [comment]
看上去像是权限问题

**Comment by OZHLYO** [comment]
解决了，原因是下载器下面的下载目录未设置

**Comment by andychandowjones** [comment]
@OZHLYO 
你如何設定的？
我已設定了都不能轉移

![Image](https://github.com/user-attachments/assets/9efd3cbb-6280-4f42-bf15-5c3757aa2dc9)
![Image](https://github.com/user-attachments/assets/8d848e51-b74a-409e-b9c8-b4f0ac87a268)
