### ISSUE TITLE
[讨论区]功能需求+测试（禁水）

### ISSUE THREAD

**Issue by hsuyelin** [hsuyelin/nas-tools#65]
近期Task，想到再加

- [ ] 憨憨支持刷流 关联： https://github.com/hsuyelin/nas-tools/issues/69
- [x] 适配憨憨索引再次改版，关联：https://github.com/hsuyelin/nas-tools/issues/71
- [ ] 转移做种插件适配黑白名单，关联：https://github.com/hsuyelin/nas-tools/issues/74
- [ ] 增强名称识别，部分名称识别例如: `Spider-Man.Across.the.Spider-Verse.2023.2160p.WEB-DL.DDP5.1.Atmos.DV.H.265-yiiha`识别不了
- [ ] 根据IMDB增强匹配

**Comment by jackloves111** [comment]
![73e868b2-b4e0-4440-bdfb-4559aee11348](https://github.com/hsuyelin/nas-tools/assets/89971817/620bc176-15f0-4615-955f-112c2128c876)
依赖改了，拉取打开明显变慢，还是有科学的情况

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/4b536de4-b5cd-4b03-8410-e6d6d23776b6)
可能是拉取没有依赖的问题，还是没有等级显示，但是这个功能对我来说，毫无用处，其实没必要为此大改代码，我个人觉得应该回归本源，专注搜索，看片，订阅、刷流这些核心功能，其他的反而越精简越好，以免代码shi山，哈哈

**Comment by hsuyelin** [comment]
> 

可以，顺手改了下，反正不是重心在这上，其他的貌似有了？依赖等更新镜像把，科学问题，更新依赖是因为一个潜在的xpath报错，旧版本总是解析不了

**Comment by lovek8s** [comment]
大佬，看下是否看适配查看时魔呢？ptpp助手那样的耶

**Comment by hsuyelin** [comment]
> ptpp助手

不打算加，和 @jackloves111  说的一样，nt聚焦的功能不是这个，一些体验上的东西就是在不麻烦的情况下改下

**Comment by Fantuan-cell** [comment]
> > ptpp助手
> 
> 不打算加，和 @jackloves111 说的一样，nt聚焦的功能不是这个，一些体验上的东西就是在不麻烦的情况下改下

你好,能否插件市场有豆瓣榜单订阅插件,请问可以写一个bangumi新番订阅吗,比较喜欢看番,这个bangumi新番订阅就能自动订阅啦

**Comment by felix-klk** [comment]
想问问 你们都不会遇到主页进不去的问题吗 我经常性一分钟都打不开 主页 有时候又很快的 有点玄学 ![image](https://github.com/hsuyelin/nas-tools/assets/52670643/3216f6be-1948-4d8b-9c9d-7f11da67b9fe)这种卡进度条要卡几分钟才能进去 有时候换换浏览器又可以解决

**Comment by Fantuan-cell** [comment]
> 想问问 你们都不会遇到主页进不去的问题吗 我经常性一分钟都打不开 主页 有时候又很快的 有点玄学 ![image](https://user-images.githubusercontent.com/52670643/261828309-3216f6be-1948-4d8b-9c9d-7f11da67b9fe.png)这种卡进度条要卡几分钟才能进去 有时候换换浏览器又可以解决

能进去,很快,慢的话可能是你设备性能不行

**Comment by hsuyelin** [comment]
> 想问问 你们都不会遇到主页进不去的问题吗 我经常性一分钟都打不开 主页 有时候又很快的 有点玄学 ![image](https://user-images.githubusercontent.com/52670643/261828309-3216f6be-1948-4d8b-9c9d-7f11da67b9fe.png)这种卡进度条要卡几分钟才能进去 有时候换换浏览器又可以解决

@felix-klk 看是否开了自动更新，科学上网不行的话，关闭那个，还有就是设备性能问题

**Comment by felix-klk** [comment]
设备12代cpu 这肯定不会了 梯子油管可以跑30000 我试试关掉自动更新吧> 科学

**Comment by hsuyelin** [comment]
> 设备12代cpu 这肯定不会了 梯子油管可以跑30000 我试试关掉自动更新吧> 科学

docker完整安装哈，因为有下载依赖的问题存在

**Comment by felix-klk** [comment]
> > 设备12代cpu 这肯定不会了 梯子油管可以跑30000 我试试关掉自动更新吧> 科学
> 
> 
> 
> docker完整安装哈，因为有下载依赖的问题存在

都是完全重现安装的

**Comment by hsuyelin** [comment]
> > > 设备12代cpu 这肯定不会了 梯子油管可以跑30000 我试试关掉自动更新吧> 科学
> > 
> > 
> > docker完整安装哈，因为有下载依赖的问题存在
> 
> 都是完全重现安装的

关掉自动更新如何？

**Comment by hsuyelin** [comment]
> bangumi

豆瓣那个是榜单订阅，bangumi是每周订阅，数量多杂不确定性强，建议自己手动点击bangumi在订阅

**Comment by hsuyelin** [comment]
> 设备12代cpu 这肯定不会了 梯子油管可以跑30000 我试试关掉自动更新吧> 科学

想起来了，还有个原因，就是每次重启的话，如果你同步目录的文件太多也会进不去要读取完才能进去，你可以从日志看

2023-08-20 11:27:57,364	INFO: 加载插件：<class 'app.plugins.modules.jackett.Jackett'>
 * Serving Flask app 'web.main'
 * Debug mode: on
 
 到  * Debug mode: on 这种字样出现才算是加载完成，之后不重启的话应该很快

**Comment by Andyk10** [comment]
@hsuyelin 请大佬看一下https://github.com/hsuyelin/nas-tools/issues/69，感谢！

**Comment by felix-klk** [comment]
说个很玄学的我发现原本就是关的 反倒是打开了就不卡了> 更新

**Comment by felix-klk** [comment]
> > > > 设备12代cpu 这肯定不会了 梯子油管可以跑30000 我试试关掉自动更新吧> 科学
> 
> > > 
> 
> > > 
> 
> > > docker完整安装哈，因为有下载依赖的问题存在
> 
> > 
> 
> > 都是完全重现安装的
> 
> 
> 
> 关掉自动更新如何？

说个很玄学的我发现原本就是关的 反倒是打开了就不卡了
目录同步的话也是有一点但是我nastool长年不重启 我可能去留意是不是读取不到同步目录

**Comment by hsuyelin** [comment]
> 说个很玄学的我发现原本就是关的 反倒是打开了就不卡了
> 目录同步的话也是有一点但是我nastool长年不重启 我可能去留意是不是读取不到同步目录

我瞅一瞅，你原来的配置截图给我看看，看看是不是有异常逻辑卡住了

**Comment by jackloves111** [comment]
憨憨是不是又挂了，大家测试一下看看呢 @iovejieba @hsuyelin @felix-klk

**Comment by iovejieba** [comment]
> 憨憨是不是又挂了，大家测试一下看看呢 @iovejieba @hsuyelin @felix-klk

hh 我没id.....额

**Comment by iovejieba** [comment]
> > 
> 
> 更新啥实用性插件了？

他之前不是没匹配刷流规则么...hr啊  free啊    现在好像可以了

**Comment by caneman** [comment]
需求：自定义榜单

描述：目前的榜单功能有点孱弱，无法适应个性化需求

想法：
- 方案1：做成插件形式，每个榜单出一个单独的插件，安装哪个新增哪个榜单
   
   > 优点：用户友好，缺点：工作量比较大

- 方案2：基础设置里增加榜单设置或者出一个通用插件（感觉更好一些），可以自定义榜单名称、榜单API地址，满足特定格式则验证通过，然后在探索或榜单推荐界面渲染出来

   > 优点：工作量可控，缺点：小白不友好
   
感觉还是一个蛮普遍的痛点的，不同的人对影视资源总有不一样的品味，单一的榜单肯定无法契合所有人的口味。

感觉方案2好一些，写好自定义榜单页面，留好数据接口位置，工作量可控。本身圈子就小，纯小白也不太像是目标用户。

感觉有没有必要，一起讨论下？@hsuyelin @jackloves111

**Comment by iovejieba** [comment]
> 需求：自定义榜单
> 
> 描述：目前的榜单功能有点孱弱，无法适应个性化需求
> 
> 想法：
> 
> * 方案1：做成插件形式，每个榜单出一个单独的插件，安装哪个新增哪个榜单
>   > 优点：用户友好，缺点：工作量比较大
> * 方案2：基础设置里增加榜单设置或者出一个通用插件（感觉更好一些），可以自定义榜单名称、榜单API地址，满足特定格式则验证通过，然后在探索或榜单推荐界面渲染出来
>   > 优点：工作量可控，缺点：小白不友好
> 
> 感觉还是一个蛮普遍的痛点的，不同的人对影视资源总有不一样的品味，单一的榜单肯定无法契合所有人的口味。
> 
> 感觉方案2好一些，写好自定义榜单页面，留好数据接口位置，工作量可控。本身圈子就小，纯小白也不太像是目标用户。
> 
> 感觉有没有必要，一起讨论下？@hsuyelin @jackloves111

如果有三方大佬二开插件的话，估计是个好选择，不过在现有情况下改 目测工程量有点大...

**Comment by hsuyelin** [comment]
> > 更新啥实用性插件了？
> 
> 他之前不是没匹配刷流规则么...hr啊 free啊 现在好像可以了

抽空看看

**Comment by hsuyelin** [comment]
> 需求：自定义榜单
> 
> 描述：目前的榜单功能有点孱弱，无法适应个性化需求
> 
> 想法：
> 
> * 方案1：做成插件形式，每个榜单出一个单独的插件，安装哪个新增哪个榜单
>   > 优点：用户友好，缺点：工作量比较大
> * 方案2：基础设置里增加榜单设置或者出一个通用插件（感觉更好一些），可以自定义榜单名称、榜单API地址，满足特定格式则验证通过，然后在探索或榜单推荐界面渲染出来
>   > 优点：工作量可控，缺点：小白不友好
> 
> 感觉还是一个蛮普遍的痛点的，不同的人对影视资源总有不一样的品味，单一的榜单肯定无法契合所有人的口味。
> 
> 感觉方案2好一些，写好自定义榜单页面，留好数据接口位置，工作量可控。本身圈子就小，纯小白也不太像是目标用户。
> 
> 感觉有没有必要，一起讨论下？@hsuyelin @jackloves111 

挺好的想法就是觉得时间大于收益，抽空看看数据有没有办法填充，有办法填充的话，给特定人群自己填充数据了

**Comment by jackloves111** [comment]
> 需求：自定义榜单
> 
> 描述：目前的榜单功能有点孱弱，无法适应个性化需求
> 
> 想法：
> 
> * 方案1：做成插件形式，每个榜单出一个单独的插件，安装哪个新增哪个榜单
>   > 优点：用户友好，缺点：工作量比较大
> * 方案2：基础设置里增加榜单设置或者出一个通用插件（感觉更好一些），可以自定义榜单名称、榜单API地址，满足特定格式则验证通过，然后在探索或榜单推荐界面渲染出来
>   > 优点：工作量可控，缺点：小白不友好
> 
> 感觉还是一个蛮普遍的痛点的，不同的人对影视资源总有不一样的品味，单一的榜单肯定无法契合所有人的口味。
> 
> 感觉方案2好一些，写好自定义榜单页面，留好数据接口位置，工作量可控。本身圈子就小，纯小白也不太像是目标用户。
> 
> 感觉有没有必要，一起讨论下？@hsuyelin @jackloves111

额，我目前实际生产环境用的3.2.9.9版本的，原因也简单的，就是功能够用，稳定。我不反对增加新的功能，但是我个人是没有这块需求的，稳定、准确是我比较追求的，至于榜单嘛，众口难调，豆瓣本身已经非常适合国人使用了。功能越多，BUG越多。

**Comment by hsuyelin** [comment]
> > 需求：自定义榜单
> > 描述：目前的榜单功能有点孱弱，无法适应个性化需求
> > 想法：
> > 
> > * 方案1：做成插件形式，每个榜单出一个单独的插件，安装哪个新增哪个榜单
> >   > 优点：用户友好，缺点：工作量比较大
> > * 方案2：基础设置里增加榜单设置或者出一个通用插件（感觉更好一些），可以自定义榜单名称、榜单API地址，满足特定格式则验证通过，然后在探索或榜单推荐界面渲染出来
> >   > 优点：工作量可控，缺点：小白不友好
> > 
> > 感觉还是一个蛮普遍的痛点的，不同的人对影视资源总有不一样的品味，单一的榜单肯定无法契合所有人的口味。
> > 感觉方案2好一些，写好自定义榜单页面，留好数据接口位置，工作量可控。本身圈子就小，纯小白也不太像是目标用户。
> > 感觉有没有必要，一起讨论下？@hsuyelin @jackloves111
> 
> 额，我目前实际生产环境用的3.2.9.9版本的，原因也简单的，就是功能够用，稳定。我不反对增加新的功能，但是我个人是没有这块需求的，稳定、准确是我比较追求的，至于榜单嘛，众口难调，豆瓣本身已经非常适合国人使用了。功能越多，BUG越多。

那你岂不是每次都要手动同步fix么，感觉很麻烦的样子

**Comment by jackloves111** [comment]
> > > 需求：自定义榜单
> > > 描述：目前的榜单功能有点孱弱，无法适应个性化需求
> > > 想法：
> > > 
> > > * 方案1：做成插件形式，每个榜单出一个单独的插件，安装哪个新增哪个榜单
> > >   > 优点：用户友好，缺点：工作量比较大
> > > * 方案2：基础设置里增加榜单设置或者出一个通用插件（感觉更好一些），可以自定义榜单名称、榜单API地址，满足特定格式则验证通过，然后在探索或榜单推荐界面渲染出来
> > >   > 优点：工作量可控，缺点：小白不友好
> > > 
> > > 感觉还是一个蛮普遍的痛点的，不同的人对影视资源总有不一样的品味，单一的榜单肯定无法契合所有人的口味。
> > > 感觉方案2好一些，写好自定义榜单页面，留好数据接口位置，工作量可控。本身圈子就小，纯小白也不太像是目标用户。
> > > 感觉有没有必要，一起讨论下？@hsuyelin @jackloves111
> > 
> > 
> > 额，我目前实际生产环境用的3.2.9.9版本的，原因也简单的，就是功能够用，稳定。我不反对增加新的功能，但是我个人是没有这块需求的，稳定、准确是我比较追求的，至于榜单嘛，众口难调，豆瓣本身已经非常适合国人使用了。功能越多，BUG越多。
> 
> 那你岂不是每次都要手动同步fix么，感觉很麻烦的样子

还好，我现在就适配站点就可以了，其他的功能我不动就可以了

**Comment by uploadrclone** [comment]
https://github.com/hsuyelin/nas-tools/issues/39
大佬这个有计划做么

**Comment by jackloves111** [comment]
2.9版本也一样，看来是NT本身就有的缺陷

**Comment by hsuyelin** [comment]
> 2.9版本也一样，看来是NT本身就有的缺陷

主要是这个异人之下还带有一人之下的标签，这个没办法了，羡慕你们站点太多惹

**Comment by jackloves111** [comment]
> 主要是这个异人之下还带有一人之下的标签，这个没办法了，羡慕你们站点太多惹

等开药了才能发，药都有，没有权限

**Comment by jackloves111** [comment]
> 我的思路是每个站点都按照TMDB识别搜索，但是最总的结果是将所有站点的结果聚合在一起

这个想法你空了看看，有没有可能实现，刚才我看@MyGiki  发了，MP的好像解决了这个问题，但是我不清楚是怎么解决的，不知道有没有参考性。

**Comment by caneman** [comment]
> > 我的思路是每个站点都按照TMDB识别搜索，但是最总的结果是将所有站点的结果聚合在一起
> 
> 这个想法你空了看看，有没有可能实现，刚才我看@MyGiki 发了，MP的好像解决了这个问题，但是我不清楚是怎么解决的，不知道有没有参考性。

在索引器的search - params里有个search area 字段，那个控制的是搜索来源，以hh为例，0的话就是搜索title, 4的话就是IMDB链接，有没有可能利用这一块做到？ 先做一步TMDB ID ->IMDB 链接，这样搜索的结果应该是比较精准的。

不同的站支持的搜索方式可能不一样，没细看，但是同样架构的网站应该不会偏差很大，只是说一种思路，抛砖引玉吧。

**Comment by caneman** [comment]
> 

大部分的站点发种子是对种子格式有一定的要求的，基本都会有个IMDB链接的字段，方便下种人查看种子对应资源的详情，搜索imdb link 应该是NP类型网站统一都有的，刚翻了两三个大站都是有的。

TMDB ID -> IMDB Link 应该比较简单就可以实现的，IMDB Link 本身也有唯一性。只要做好转换这一块，效果和TMDB的精准查询没什么区别，MP应该也是采用了类似的思路，个人感觉（猜测）。

**Comment by uploadrclone** [comment]
> > 
> 
> 大部分的站点发种子是对种子格式有一定的要求的，基本都会有个IMDB链接的字段，方便下种人查看种子对应资源的详情，搜索imdb link 应该是NP类型网站统一都有的，刚翻了两三个大站都是有的。
> 
> TMDB ID -> IMDB Link 应该比较简单就可以实现的，IMDB Link 本身也有唯一性。只要做好转换这一块，效果和TMDB的精准查询没什么区别，MP应该也是采用了类似的思路，个人感觉（猜测）。

有没有可能用种子页面的douban或者imdb内容来搜索

**Comment by hsuyelin** [comment]
关闭，转移至讨论区

**Comment by wpf9889259** [comment]
[v3.2.10.7 a4c87c5]

**Comment by wpf9889259** [comment]
v3.2.10.7

**Comment by wpf9889259** [comment]
v3.2.10.7手动硬链接不行。自动硬链接没问题。
![WX20230824-094108](https://github.com/hsuyelin/nas-tools/assets/31613195/6854784c-2a9b-45cf-9513-a3febc0a0640)

**Comment by Magnoliar** [comment]
功能需求:自定义转移

描述：目前NT里面的文件转移能够覆盖大部分功能需求，但部分家庭录像/演唱会/小众收集的媒体文件在TMDB中没有收录，无法进一步转移入库，希望对于这部分影片可以增设一个自定义选项，选择后可以自定义相关内容完成入库，例如：
![image](https://github.com/hsuyelin/nas-tools/assets/18226972/679da826-9287-4dc8-ac4f-b7a04f03895d)

**Comment by shanshangshi** [comment]
3.3.4憨憨还是不能刷流啊。憨憨自从换了UI适配起来就难了啊。。。
