### ISSUE TITLE
 v3.2.10.5 49bd606 还有beta版本都出现了TMDB的图片加载不出来，已经挂了代理了，代理是能访问图片的地址

### ISSUE THREAD

**Issue by windn0** [hsuyelin/nas-tools#66]
![image](https://github.com/hsuyelin/nas-tools/assets/52818798/24788f59-e065-4cbd-aa65-0e2c334df32a)

![image](https://github.com/hsuyelin/nas-tools/assets/52818798/ddfffae6-87a9-4550-88c7-41a8c133e8fd)
麻烦大佬看看是我的问题，还是一个共性问题。谢谢

**Comment by windn0** [comment]
补充一点，点开卡片进去后，发现图片就能显示出来了。
![image](https://github.com/hsuyelin/nas-tools/assets/52818798/a6b91500-a0b9-4751-8d1a-936f78884f70)

**Comment by iovejieba** [comment]
> 补充一点，点开卡片进去后，发现图片就能显示出来了。 ![image](https://user-images.githubusercontent.com/52818798/261808829-a6b91500-a0b9-4751-8d1a-936f78884f70.png)

个案问题，尝试清浏览器缓存

**Comment by windn0** [comment]
> > 补充一点，点开卡片进去后，发现图片就能显示出来了。 ![image](https://user-images.githubusercontent.com/52818798/261808829-a6b91500-a0b9-4751-8d1a-936f78884f70.png)
> 
> 个案问题，尝试清浏览器缓存，不挂辅助线路 加载略慢 走线路 很丝滑

可是我已经设置了代理了啊，按理来说应该很快就能加载出来图片，而且现在是一张都加载不出来····但是点进去就能加载出来。他们都是tmbd提供图片吧

**Comment by iovejieba** [comment]
> > > 补充一点，点开卡片进去后，发现图片就能显示出来了。 ![image](https://user-images.githubusercontent.com/52818798/261808829-a6b91500-a0b9-4751-8d1a-936f78884f70.png)
> > 
> > 
> > 个案问题，尝试清浏览器缓存，不挂辅助线路 加载略慢 走线路 很丝滑
> 
> 可是我已经设置了代理了啊，按理来说应该很快就能加载出来图片，而且现在是一张都加载不出来····但是点进去就能加载出来。他们都是tmbd提供图片吧

嗯  图片均来自image.tmdb.org，尝试清浏览器缓存

**Comment by iovejieba** [comment]
> > > > 补充一点，点开卡片进去后，发现图片就能显示出来了。 ![image](https://user-images.githubusercontent.com/52818798/261808829-a6b91500-a0b9-4751-8d1a-936f78884f70.png)
> > > 
> > > 
> > > 个案问题，尝试清浏览器缓存，不挂辅助线路 加载略慢 走线路 很丝滑
> > 
> > 
> > 可是我已经设置了代理了啊，按理来说应该很快就能加载出来图片，而且现在是一张都加载不出来····但是点进去就能加载出来。他们都是tmbd提供图片吧
> 
> 嗯 图片均来自image.tmdb.org，尝试清浏览器缓存，而且...该说不说你这个线路访问image.tmdb.org比我裸连都高的多....额

**Comment by windn0** [comment]
好的，应该是我的代理问题，
![image](https://github.com/hsuyelin/nas-tools/assets/52818798/cdd28de8-c997-473c-9c80-2fd5da325bc6)
设置IMDB图片代理后，能抓到了。
清理浏览器缓存无效····而且我尝试了多个浏览器了
我明天试试换个节点看看，是不是路线的问题

**Comment by iovejieba** [comment]
> 好的，应该是我的代理问题， ![image](https://user-images.githubusercontent.com/52818798/261811543-cdd28de8-c997-473c-9c80-2fd5da325bc6.png) 设置IMDB图片代理后，能抓到了。 清理浏览器缓存无效····而且我尝试了多个浏览器了 我明天试试换个节点看看，是不是路线的问题

嗯 裸连改出口ip  平均300-450 ping 波动...不排除  你的线路问题

**Comment by JiaqinW** [comment]
同样问题，看了一下网络请求，服务器返回304，可能是缓存问题。

**Comment by ningzimu** [comment]
同样问题，看了一下网络请求，服务器返回值304，可能是缓存问题。
