### ISSUE TITLE
tjupt签到，日志显示：无法获取到答案选项

### ISSUE THREAD

**Issue by JusKyle** [hsuyelin/nas-tools#661]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.15

### 问题类型

主程序运行问题

### 问题描述

自动签到程序，tjupt站点无法自动签到
日志显示：
——————命中重试—————
【tjupt】签到失败，未获取到答案选项

经查 站点的数据已经发生改变，烦请更新xpath

**Comment by JusKyle** [comment]
![Snipaste_2024-04-19_13-47-20](https://github.com/hsuyelin/nas-tools/assets/36150985/2a6e43d3-f5b8-4680-b9aa-c9f789672428)

**Comment by NicholasYZ** [comment]
提句与技术无关的题外话，tjupt在规则里写明了禁止使用自动化脚本/程序进行非手动签到，我之前用nastool签过被站方检测出来警告了

**Comment by zzdywc** [comment]
教育网pt普遍要求都极低，没必要搞签到，而且这个站点明确说明了不允许自动签到

**Comment by JusKyle** [comment]
感谢各位提醒
