### ISSUE TITLE
大佬，nastool现在支持豆瓣和TMBD搜片，可以增加IMBD搜片识别吗？

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#67]
大佬，nastool现在支持豆瓣和TMBD搜片，可以增加IMBD搜片识别吗？经常有些资源TMBD没有，IMBD有
如果TMBD没有资源就不自动下载了。可以增加IMBD的资源库吗

**Comment by jackloves111** [comment]
TMDB都没有的资源，你应该考虑自己添加词条了

**Comment by hsuyelin** [comment]
> 大佬，nastool现在支持豆瓣和TMBD搜片，可以增加IMBD搜片识别吗？经常有些资源TMBD没有，IMBD有 如果TMBD没有资源就不自动下载了。可以增加IMBD的资源库吗

不考虑支持，参考 @jackloves111 的说法
