### ISSUE TITLE
[错误报告]: 目录同步选择硬链接后，只在目标目录构建了文件夹，硬链接文件未创建

### ISSUE THREAD

**Issue by ifornever** [hsuyelin/nas-tools#672]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.0

### 问题类型

主程序运行问题

### 问题描述

系统群晖，DSM7.2，我在目录同步设置了从下载目录同步到媒体库目录：

<img width="1216" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/157528990/7d16dee6-1f56-4db1-a314-4ab72e4e0cf5">

但是在目标目录只新建了识别后的多级文件夹，硬链接文件并未创建：

<img width="968" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/157528990/b1cd6f1a-6a09-48bb-b42d-ce5b2a9a4f58">

另一个同步目录选择同步方式为“移动”，目前工作正常（但是速度奇慢，并且移动的话无法做种了吧）
请问可能是哪里出了问题？我自定义了二级分类策略，新增了部分一级目录，更改了部分二级目录；另外我在 qbittorrent 下载器管理里面，也做了下载目录设置：

<img width="698" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/157528990/fecda57e-0fe1-41ae-b414-ce76bcee03d6">

媒体库设置如下：

<img width="1219" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/157528990/783e5127-e62f-45df-a5b4-5cf36e820fed">

### 发生问题时系统日志和配置文件

```bash
二级分类策略：
# 配置电影的分类策略， 配置为空或者不配置该项则不启用电影分类
movie:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  华语电影:
    # 分类依据，可以是：original_language 语种、production_countries(电影)/origin_country(电视剧) 国家或地区、genre_ids 内容类型等，只要TMDB API返回的字段中有就行
    # 配置多项条件时，需要同时满足；不需要的匹配项可以删掉或者配置为空
    # 匹配值对应用,号分隔，这里是匹配语种
    original_language: 'zh,cn,bo,za'
  欧美电影:
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  日韩电影:
    # 匹配 origin_country 国家，主要亚洲国家列表
    origin_country: 'JP,KP,KR,TH,IN,SG'
  动画电影:
    # 匹配 genre_ids 内容类型，16是动漫
    genre_ids: '16'
  # 未配置任何过滤条件时，则按先后顺序不符合上面分类的都会在这个分类下，建议配置在最末尾
  未分类:

# 配置电视剧的分类策略， 配置为空或者不配置该项则不启用电视剧分类
tv:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  # 如果有配置动漫独立目录，则实际上不会使用到tv下的动漫二级分类
  动漫:
    # 匹配 genre_ids 内容类型，16是动漫
    genre_ids: '16'
  儿童:
    # 匹配 genre_ids 内容类型，10762是儿童
    genre_ids: '10762'
  综艺:
    # 匹配 genre_ids 内容类型，10764 10767都是综艺
    genre_ids: '10764,10767'
  国产剧:
    # 匹配 origin_country 国家，CN是中国大陆，TW是中国台湾，HK是中国香港
    origin_country: 'CN,TW,HK'
  欧美剧:
    # 匹配 origin_country 国家，主要欧美国家列表
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  日韩剧:
    # 匹配 origin_country 国家，主要亚洲国家列表
    origin_country: 'JP,KP,KR,TH,IN,SG'
  # 未匹配以上分类，则命名为未分类
  未分类:

# 配置动漫的分类策略， 配置为空或者不配置该项则不启用动漫分类
anime:
  # 如果你的anime_path动漫目录已经直接设置到了动漫子目录，则这个分类可以取消
  动漫:
    # 匹配 genre_ids 内容类型，16是动漫
    genre_ids: '16'
documentary:
  纪录片:
     # 匹配 genre_ids 内容类型，99是纪录片
    genre_ids: '99'
music:
  音乐演出:
     # 匹配 genre_ids 内容类型，10402是音乐相关
    genre_ids: '10402'
```

**Comment by ifornever** [comment]
抱歉，查看日志貌似是因为跨盘创建硬链接导致，但是我这貌似是同一个存储空间 or 磁盘分区吧。。。

【4 个文件入库失败】
源路径：/volume1/downloads/tv/Catherine.The.Great.2019.S01.2160p.MAX.WEB-DL.x265.10bit.HDR.DDP5.1-EDITH[rartv]
原因：文件转移失败，错误码 -1

00131.m2ts 无法识别媒体信息！
05:19:24		
00131.m2ts 按原文件名转移到未识别目录：/volume1/video/unknown
05:19:24		
[Errno 18] Invalid cross-device link: '/volume1/downloads/movie/8.Mile.2002.2160p.BluRay.HEVC.DTS-X.7.1-ESiR/BDMV/STREAM/00131.m2ts' -> '/volume1/video/unknown/STREAM/00131.m2ts'
05:19:24		
/volume1/downloads/movie/8.Mile.2002.2160p.BluRay.HEVC.DTS-X.7.1-ESiR/BDMV/STREAM/00131.m2ts 硬链接到unknown失败，错误码 -1

**Comment by ifornever** [comment]
另外还有个问题，媒体库一级目录能自定义么，比如像我配置里面加的，我想要纪录片和音乐演出单独作为一级目录

**Comment by MoogleXX** [comment]
! [QQ screenshot 20240428173741] (https://github.com/hsuyelin/nas-tools/assets/160689415/ef7fffbd-8c3b-43b2-8c2a-6b07760c7104)
为什么你是/volume1/...... 这种路径? 你试试看把你的路径改成这种看看。    /volume1/XXX/downloads/movie/....    硬链接到/volume1/XXX/video/....

**Comment by ifornever** [comment]
> ! [QQ screenshot 20240428173741] (https://github.com/hsuyelin/nas-tools/assets/160689415/ef7fffbd-8c3b-43b2-8c2a-6b07760c7104) 为什么你是/volume1/...... 这种路径? 你试试看把你的路径改成这种看看。 /volume1/XXX/downloads/movie/.... 硬链接到/volume1/XXX/video/....

我解决方法是直接把下载目录放到了 video 里
