### ISSUE TITLE
[功能改进]: MT分页导致搜索不完全

### ISSUE THREAD

**Issue by Hirsi-He** [hsuyelin/nas-tools#675]
### 当前程序版本

3.4.0

### 功能改进

馒头分页size最大只能为100，这样就导致搜索的时候（例如：生化危机）返回了3页302条数据，但是我们只能获取到100条，导致获取不到完全数据

**Comment by Hirsi-He** [comment]
自己想了一个解决办法，在搜索keyword后边加上tmdb的year，这样精确点就可以只搜出来一页了。（才发现docker直接映射nas-tools文件夹可以直接运行源代码）

**Comment by joneechua** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/156154680/827a813e-52ec-431e-94b5-a3216a9a637a)
这是所有站点的默认配置，需要你有自己的需求可以改config.yaml下的这个值

**Comment by joneechua** [comment]
目前这个没有提供页面修改，需要自己去文件里修改，然后重启

**Comment by Hirsi-He** [comment]
> ![image](https://private-user-images.githubusercontent.com/156154680/326267791-827a813e-52ec-431e-94b5-a3216a9a637a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTc1NDUsIm5iZiI6MTcxNDMxNzI0NSwicGF0aCI6Ii8xNTYxNTQ2ODAvMzI2MjY3NzkxLTgyN2E4MTNlLTUyZWMtNDMxZS05NGI1LWEzMjE2YTlhNjM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNTE0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTgzYWQ4NmJiZDhkNTM4MmYwOGJjYTI4ZGJjOWM3OGNlMjM1ZjcyNGI5MGIyMDdkYTFiZTA5ZTVhNzBhMGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZX6ZdGiowJptb-YpU1CaUlvbEWbn_yNs631_l1Qrmc0) 这是所有站点的默认配置，需要你有自己的需求可以改config.yaml下的这个值

这个修改了超过200，mt会返回参数不正确，而total有309条

**Comment by joneechua** [comment]
说明mt的接口就限制了最大200
