### ISSUE TITLE
刚更新的3.2.10.6 索引资源乱套了

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#68]
刚更新的3.2.10.6 索引资源乱套了

例子：异人之下 是电视剧，搜索出来的是动画的”一人之下“

能否增强识别主标题和副标题呢
以憨憨站的发布剧集为例，标题都是没有集数的，所以订阅的时候不会命中，只有副标题才有集数，那能增强识别命中副标题吗
![1~}W%S B0( 3$CMF8E6PLV0](https://github.com/hsuyelin/nas-tools/assets/107430324/456fb3be-4e10-4a43-9169-25bbbcfbb1ec)
标题
I Am Nobody S01 2023 2160p WEB-DL H265 60fps ACC-HHWEB
副标题
异人之下 第01-04集 | 4K 60帧 | 类型:剧情/奇幻 | 主演:彭昱畅/侯明昊/王影璐/王学圻/毕雯珺

**Comment by MyGiki** [comment]
@hsuyelin 大佬，发现个BUG和新提的增强，有空看看，谢谢。更新了最好打包哈，我习惯备份你的产品。哈哈

**Comment by hsuyelin** [comment]
> @hsuyelin 大佬，发现个BUG和新提的增强，有空看看，谢谢。更新了最好打包哈，我习惯备份你的产品。哈哈

你这个抽空看看，我也有这个站我知道，憨憨主标题命名规范但是名字不包含集数多英文，副标题就是关键字但是命名不规范，匹配确实很难命中

**Comment by hsuyelin** [comment]
> @hsuyelin 大佬，发现个BUG和新提的增强，有空看看，谢谢。更新了最好打包哈，我习惯备份你的产品。哈哈

假如更新的话，一般小修改不打包，有科学的话，手动同步修改就好了

**Comment by MyGiki** [comment]
@hsuyelin 大佬，异人之下 是电视剧，搜索出来的是动画的”一人之下“ 麻烦改一下这个BUG ，动画和电视剧轮套了

**Comment by MyGiki** [comment]
@hsuyelin 大佬，异人之下 是电视剧，搜索出来的是动画的”一人之下“ 麻烦改一下这个BUG ，动画和电视剧nastool分不清了

**Comment by kuroyukihime0** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/7975549/766205e5-336f-4ae8-94b1-4bc8f51afb9e)
搜索没问题，应该是你使用方式有问题

**Comment by yellowstrong** [comment]
<img width="1501" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/34505611/136d676a-0bdf-4b6f-abe0-9f9eb0f9f7c6">
怀疑是你搜索的问题，同样版本测试没发现bug

**Comment by god1ong** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/10793095/596f862b-5202-4358-ae71-cf3d9f7459fa)
确实HH的出bug了，可能和新UI有关系。

**Comment by Contrass** [comment]
新的这一版 搜的独行月球 出来了很多错误的
![1692541594905](https://github.com/hsuyelin/nas-tools/assets/77086992/9ad107e5-824a-4911-b8df-a96a76dd64b1)
![image](https://github.com/hsuyelin/nas-tools/assets/77086992/3453358a-ef0a-47cd-95ad-65058fa9fe82)
![image](https://github.com/hsuyelin/nas-tools/assets/77086992/d2bf578f-57ad-444c-be8a-266e8c57adc2)

**Comment by hsuyelin** [comment]
> 新的这一版 搜的独行月球 搜出了很多不对的 大佬可以去看一下

<img width="1298" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/8cd04604-8423-4bd9-b8ac-721ed31539b2">

没有日志，没有图，我自己搜了正常的，不好看啊

**Comment by Andyk10** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/b1795253-a6f0-436e-a010-69402dfc3145)
今天的订阅确实有点乱

**Comment by Andyk10** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/138e8d7c-ec61-4a77-9d88-6592ba8360f2)
箭头所示都是错乱的订阅，最离谱的是《热烈》下了个PDF下来，- -！

**Comment by yellowstrong** [comment]
确实会有问题 大佬，搜索奥本海默的时候，出现很多不符合的东西，感觉现在的策略是不是只要主副标题存在关键词就匹配上了，没有匹配正确的tmdb
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/7c326c70-5f2c-417d-a1bb-fd7ad47c0080)
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/85374edb-2dcc-431e-86ff-a59bd0f35b3a)

**Comment by yellowstrong** [comment]
> 确实会有问题 大佬，搜索奥本海默的时候，出现很多不符合的东西，感觉现在的策略是不是只要主副标题存在关键词就匹配上了，没有匹配正确的tmdb
> ![image](https://github.com/hsuyelin/nas-tools/assets/34505611/7c326c70-5f2c-417d-a1bb-fd7ad47c0080)
> ![image](https://github.com/hsuyelin/nas-tools/assets/34505611/85374edb-2dcc-431e-86ff-a59bd0f35b3a)

孤注一掷也是同样的问题
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/e4649227-53ab-4399-8a37-559eab463536)

**Comment by Contrass** [comment]
独行月球出现很多错误的搜索
![独行月球1](https://github.com/hsuyelin/nas-tools/assets/77086992/ead25744-a63f-414d-b1a6-49ae7504ef81)
![独行月球2](https://github.com/hsuyelin/nas-tools/assets/77086992/918123eb-c7da-49f2-9226-57f2c3ef49e9)
![独行月球3](https://github.com/hsuyelin/nas-tools/assets/77086992/772c3267-dbfb-44dd-b640-7f5d5dd3aa9f)


其次是订阅问题
![订阅错误1](https://github.com/hsuyelin/nas-tools/assets/77086992/36c751ac-f42f-4bc5-865a-bcc12e10e5d3)
![订阅错误2](https://github.com/hsuyelin/nas-tools/assets/77086992/ac2d9a5f-120c-4c1a-a4ed-a627bda6fe3c)

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/a99c876d-cd19-413a-a906-41c8ee84150f)
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/9eed6df1-7981-4cea-9d61-69a1d87b4770)
应该是新版本导致的，具体是哪个版本我还没有测试。图1是3.2.10.6；图2是3.2.9.9

**Comment by yellowstrong** [comment]
> 版本：[v3.2.10.6 [e5867c6](https://github.com/hsuyelin/nas-tools/commit/e5867c691bbd9a82898580e2a6d635436520251f)] 独行月球出现很多错误的搜索 ![独行月球1](https://user-images.githubusercontent.com/77086992/261886650-ead25744-a63f-414d-b1a6-49ae7504ef81.png) ![独行月球2](https://user-images.githubusercontent.com/77086992/261886653-918123eb-c7da-49f2-9226-57f2c3ef49e9.png) ![独行月球3](https://user-images.githubusercontent.com/77086992/261886655-772c3267-dbfb-44dd-b640-7f5d5dd3aa9f.png)
> 
> 其次是订阅问题 ![订阅错误1](https://user-images.githubusercontent.com/77086992/261886673-36c751ac-f42f-4bc5-865a-bcc12e10e5d3.png) ![订阅错误2](https://user-images.githubusercontent.com/77086992/261886675-ac2d9a5f-120c-4c1a-a4ed-a627bda6fe3c.png)

虽然有问题 但是你这个独行月球tmdb维护的就有问题，你要搜电影的那个独行月球 而不是动漫的独行月球

**Comment by Contrass** [comment]
> > 版本：[v3.2.10.6 [e5867c6](https://github.com/hsuyelin/nas-tools/commit/e5867c691bbd9a82898580e2a6d635436520251f) ] 独行月球出现很多错误的搜索![独行月球1](https://user-images.githubusercontent.com/77086992/261886650-ead25744-a63f-414d-b1a6-49ae7504ef81.png) ![独行月球2](https://user-images.githubusercontent.com/77086992/261886653-918123eb-c7da-49f2-9226-57f2c3ef49e9.png) ![独行月球3](https://user-images.githubusercontent.com/77086992/261886655-772c3267-dbfb-44dd-b640-7f5d5dd3aa9f.png)
> > 其次是订阅问题![订阅错误1](https://user-images.githubusercontent.com/77086992/261886673-36c751ac-f42f-4bc5-865a-bcc12e10e5d3.png) ![订阅错误2](https://user-images.githubusercontent.com/77086992/261886675-ac2d9a5f-120c-4c1a-a4ed-a627bda6fe3c.png)
> 
> 虽然有问题但是你这个独行月球tmdb维护的问题，你要搜电影的那个独行月球动漫而不是独行月球

旁边那个电影的也是像这样的

**Comment by hsuyelin** [comment]
回滚了，适配憨憨。策略改成匹配标题或种子名称，没有去匹配TMDDB了，等新版本
