### ISSUE TITLE
馒头刷流下载了50%的种子

### ISSUE THREAD

**Issue by Hirsi-He** [hsuyelin/nas-tools#680]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.0

### 问题类型

其他问题

### 问题描述

馒头刷流下载了50%的种子
设置的是Free
![image](https://github.com/hsuyelin/nas-tools/assets/48676315/f0216675-d2b5-4380-ae49-13587b7c5f48)
![image](https://github.com/hsuyelin/nas-tools/assets/48676315/18e5e2e6-0252-48f6-820b-91e1e02195fc)
都是今天添加的
![image](https://github.com/hsuyelin/nas-tools/assets/48676315/b158f2ee-7949-47bf-9265-716ff0dfae70)

**Comment by joneechua** [comment]
有没有可能是免费到期了？

**Comment by Hirsi-He** [comment]
可能最近下了不少50%的，从50G下载量都快干到1T了，上传也抢不过，我说怎么分享率越来越低了呢
![image](https://github.com/hsuyelin/nas-tools/assets/48676315/299dfb2a-c341-4f36-9f42-aaff6fff1e26)

**Comment by joneechua** [comment]
在下载列表看一下是不是ns下的，我这边看着挺正常的
