### ISSUE TITLE
MT刷流任务检查种子属性接口403

### ISSUE THREAD

**Issue by Hirsi-He** [hsuyelin/nas-tools#681]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.0

### 问题类型

主程序运行问题

### 问题描述

如图
![image](https://github.com/hsuyelin/nas-tools/assets/48676315/073d5856-55b8-485f-ab76-1226b13763ea)
我按照代码postman一下接口是没问题的

**Comment by Hirsi-He** [comment]
找到原因了
site_url = "%s/api/torrent/detail" % StringUtils.get_base_url(torrent_url)
torrent_url是rss.m-team.io/xxx

**Comment by joneechua** [comment]
这个应该是官方rss种子地址错了，他这个地址就打不开

**Comment by joneechua** [comment]
站点bug，mt已修复该问题
