### ISSUE TITLE
馒头站点无法正常连接

### ISSUE THREAD

**Issue by Iongtao** [hsuyelin/nas-tools#689]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.40

### 问题类型

其他问题

### 问题描述

站点使用apikey配置，如下：
<img width="707" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/24762616/cc15415b-84f2-48d0-8831-a261fb182e2d">
却始终无法正常访问
<img width="630" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/24762616/bb27f726-6931-40ec-b43a-97e4c3c030b4">

**Comment by Iongtao** [comment]
我在想是否是馒头二级验证的原因导致的

**Comment by joneechua** [comment]
可能跟这个没关系，或者你们可以去掉二级验证看看，猜测大概率是代理的问题

**Comment by Iongtao** [comment]
> 可能跟这个没关系，或者你们可以去掉二级验证看看，猜测大概率是代理的问题

代理没有开， 二级验证感觉无法去掉
<img width="681" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/24762616/9d00951a-7d80-43a0-8b2a-8fdfaf0f594f">

**Comment by joneechua** [comment]
感觉应该不影响的，不过我是用的邮箱验证

**Comment by Iongtao** [comment]
> 感觉应该不影响的，不过我是用的邮箱验证

我不明白是不是馒头架构升级问题，个人信息里显示的是未启用二级验证
<img width="553" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/24762616/7dea2780-9d87-4c26-b07b-8baf2663d70d">
；但是安全设置中是
<img width="553" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/24762616/de50aaf1-59c3-4c46-9b2a-8434a5f917db">

假设我并没有设置二级验证的话， 我改如何解决这个issues？

**Comment by joneechua** [comment]
也是docker部署的吗

**Comment by Iongtao** [comment]
> 也是docker部署的吗

极空间docker

**Comment by joneechua** [comment]
目前看起来docker部署的问题比较大，有空我装一个试试，我是套件版的

**Comment by Iongtao** [comment]
> 目前看起来docker部署的问题比较大，有空我装一个试试，我是套件版的

好的。我发现刷流好像是可以的，问题不大，暂时用ptpp来看数据吧。
感谢解答

**Comment by Iongtao** [comment]
> 目前看起来docker部署的问题比较大，有空我装一个试试，我是套件版的

解决了， 我给馒头站点配置中设置了user-agent就可以了
