### ISSUE TITLE
憨憨刷流不成功

### ISSUE THREAD

**Issue by Andyk10** [hsuyelin/nas-tools#69]
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/2a7d21a7-185f-4d37-aaa4-34367cc47e23)
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/1da803d9-aad8-4cfc-abcc-d004a55b4b9a)
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/7a304415-eadd-4d90-8530-c8f489e59b0c)
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/4c5cd3bd-4f73-4374-a447-ecb04c0479fb)

使用 v3.2.10.6 e5867c6版本，憨憨刷流不成功

**Comment by hsuyelin** [comment]
@Andyk10  我在外面看看其他刷流是不是成功

**Comment by Andyk10** [comment]
好的，我先试试观众

**Comment by Andyk10** [comment]
@hsuyelin 
![image](https://github.com/hsuyelin/nas-tools/assets/125536059/b02a431c-df4f-4b34-987b-b597b27ae9b5)
观众能刷

**Comment by hsuyelin** [comment]
那看来还是憨憨没适配好
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月20日 20:21 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 憨憨刷流不成功 (Issue #69) |

@hsuyelin

观众能刷

**Comment by Andyk10** [comment]
@hsuyelin OK，反馈到了，劳烦大佬

**Comment by hsuyelin** [comment]
转成任务，关注讨论区任务列表

**Comment by jackloves111** [comment]
目前憨憨的刷流好像还没有适配吧！之前一个小更新说尝试憨憨刷流，我实际测试好像还是不行

**Comment by Andyk10** [comment]
3.3.10版，憨憨还是不能刷流
