### ISSUE TITLE
HH又又失效了，应该是HH站点又改了什么东西

### ISSUE THREAD

**Issue by jackloves111** [hsuyelin/nas-tools#71]
昨天还好好的，今天不行了。提个ISSUES，留档

**Comment by iovejieba** [comment]
> 昨天还好好的，今天不行了。提个ISSUES，留档

它最近好像改版...而且是没收尾  一直在陆续改

**Comment by hsuyelin** [comment]
> 

抽空看看，不要慌，我有憨憨只要花时间适配就可以了 @jackloves111 @iovejieba

**Comment by jackloves111** [comment]
> > 
> 
> 抽空看看，不要慌，我有憨憨只要花时间适配就可以了 @jackloves111 @iovejieba

要不是他们站点资源还行，我早就扔了（哭）

**Comment by hsuyelin** [comment]
快进到，在欢声笑语中，憨憨revert了近期所有的提交［🐶］
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月21日 16:43 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] HH又又失效了，应该是HH站点又改了什么东西 (Issue #71) |

昨天还好好的，今天不行了。提个ISSUES，留档

它最近好像改版...而且是没收尾 一直在陆续改

这就是项目不经beta直接上线的后果，老的UI应该不要关，启用新UI进行BETA测试，都好了再上线。我看论坛里也有好多反馈要恢复旧版的诉求

没毛病...生产项目要在最后更新....是常态....否则就是炸庙...

**Comment by jackloves111** [comment]
![IMG_3689](https://github.com/hsuyelin/nas-tools/assets/89971817/f002e08b-1f61-444b-9ad6-159b1e5aaed3)
放上官方通知，估计被问烦了

**Comment by Teddy-Zhu** [comment]
列表页的完成数加回来了 
<img width="1267" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/9956097/8feef475-633d-4155-9aa6-9c3a5550abea">

**Comment by hsuyelin** [comment]
@jackloves111 憨憨这两天太不稳定了，等稳一点在适配，现在有号了还算好适配的，只是不想适配完憨憨就更新

**Comment by hsuyelin** [comment]
已修复：https://github.com/hsuyelin/nas-tools/commit/810035c606cf9194c0d11dc9a7381546e4234e5c

<img width="1324" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/5069b4d5-e260-4f8e-b537-a249cec3499b">

**Comment by jackloves111** [comment]
> 已修复：[810035c](https://github.com/hsuyelin/nas-tools/commit/810035c606cf9194c0d11dc9a7381546e4234e5c)
> 
> <img alt="image" width="1324" src="https://user-images.githubusercontent.com/17918063/262034299-5069b4d5-e260-4f8e-b537-a249cec3499b.png">

牛逼，高效

**Comment by MyGiki** [comment]
@hsuyelin 
大佬，你试试搜索电视剧的资源，好像搜电视剧憨憨还是不显示。站点全不选，只选憨憨电视剧才能搜的出来，你可以试试搜“异人之下”
![image](https://github.com/hsuyelin/nas-tools/assets/107430324/bd346212-4ac7-4063-a200-59bde9a8c959)

![image](https://github.com/hsuyelin/nas-tools/assets/107430324/c28a7299-f66f-477d-9ed4-43936bcd2eef)

我堡也是这样，难道回滚优化搜索没到位导致电视剧搜索不准？
![image](https://github.com/hsuyelin/nas-tools/assets/107430324/40634bb9-14a1-46cb-a1d7-247381586792)

![image](https://github.com/hsuyelin/nas-tools/assets/107430324/f2f6790f-f5e7-48d2-bc48-5febfe620320)

**Comment by MyGiki** [comment]
补充，春天也是
![image](https://github.com/hsuyelin/nas-tools/assets/107430324/53b39c1b-b61d-4fa8-92cb-e13b2a616a3c)

![image](https://github.com/hsuyelin/nas-tools/assets/107430324/3acf716f-7058-428b-8942-2cde3cd17e26)

其他就不一一试了，都是单选站点才搜到资源

**Comment by jackloves111** [comment]
> 补充，春天也是 ![image](https://user-images.githubusercontent.com/107430324/262051661-53b39c1b-b61d-4fa8-92cb-e13b2a616a3c.png)
> 
> ![image](https://user-images.githubusercontent.com/107430324/262051507-3acf716f-7058-428b-8942-2cde3cd17e26.png)
> 
> 其他就不一一试了，都是单选站点才搜到资源

我测试也一样，问题在于刚刚更新修复憨憨的问题，我前一个版本，除了憨憨搜不到，其他都正常的。现在电影都正常，憨憨也能搜出来了，但是电视剧搜索结果不会全部出来
