### ISSUE TITLE
请问怎样保留官方版的设置换成这个版本？

### ISSUE THREAD

**Issue by HamBosco** [hsuyelin/nas-tools#72]
我尝试了两种：
1. 直接复制粘贴官方版的config文件夹替换这个的。
2. 直接在docker里把config指引到跟官方版同一个config目录。

两种方法都打不开webUI界面。但是用完全新的config就可以正常使用。

官方版有太多设置了，实在不想从头重新设置。有办法解决吗？谢谢。

**Comment by HamBosco** [comment]
> 我直接转移的，没有问题，配置都兼容的。

请问你是用什么方法转移的？具体哪个文件夹？谢谢！

**Comment by hsuyelin** [comment]
> > 我直接转移的，没有问题，配置都兼容的。
> 
> 请问你是用什么方法转移的？具体哪个文件夹？谢谢！

备份config文件夹。直接换就可以，不用改

**Comment by hsuyelin** [comment]
直接docker-compose简单的很，搜索下就可以了，nt的配置不要太简单，搜索docker-compose然后按照下面的配置，几分钟的事


https://github.com/hsuyelin/nas-tools/blob/master/docker/compose.yml

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月21日 16:56 |
| 收件人 | hsuyelin/nas-tools ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools] 请问怎样保留官方版的设置换成这个版本？ (Issue #72) |

我直接转移的，没有问题，配置都兼容的。

请问你是用什么方法转移的？具体哪个文件夹？谢谢！

**Comment by HamBosco** [comment]
> > > 我直接转移的，没有问题，配置都兼容的。
> > 
> > 
> > 请问你是用什么方法转移的？具体哪个文件夹？谢谢！
> 
> 备份config文件夹。直接换就可以，不用改

可是我备份替换之后，就webUI打不开了。试了好几次了……

**Comment by HamBosco** [comment]
> 直接docker-compose简单的很，搜索下就可以了，nt的配置不要太简单，搜索docker-compose然后按照下面的配置，几分钟的事 https://github.com/hsuyelin/nas-tools/blob/master/docker/compose.yml
> […](#)

这个类似我说的方法2吧，也是不行。我再研究研究。

**Comment by hsuyelin** [comment]
> > > > 我直接转移的，没有问题，配置都兼容的。
> > > 
> > > 
> > > 请问你是用什么方法转移的？具体哪个文件夹？谢谢！
> > 
> > 
> > 备份config文件夹。直接换就可以，不用改
> 
> 可是我备份替换之后，就webUI打不开了。试了好几次了……我再研究研究吧

你打不开到时截图啊，不然谁知道你错在哪

**Comment by HamBosco** [comment]
> > > > > 我直接转移的，没有问题，配置都兼容的。
> > > > 
> > > > 
> > > > 请问你是用什么方法转移的？具体哪个文件夹？谢谢！
> > > 
> > > 
> > > 备份config文件夹。直接换就可以，不用改
> > 
> > 
> > 可是我备份替换之后，就webUI打不开了。试了好几次了……我再研究研究吧
> 
> 你打不开到时截图啊，不然谁知道你错在哪

全部从头来了一遍，解决了。谢谢。

另外想问一下，有的站点添加后，索引器还是没有，正常吗？

**Comment by SouLXH** [comment]
一样，用原版web页面中备份的文件，在新版中web中恢复，直接无法启动。
在研究一下
