### ISSUE TITLE
3.2.10.7 自定义索引器问题

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#73]
自定义索引器 只能一个站点有效，添加多个站点只有第一个站点有效
![image](https://github.com/hsuyelin/nas-tools/assets/107430324/d7582063-1248-41a4-9890-e3ab10be56b1)

比如我图中添加了1站点，2站点，3站点。就只有1站点在内建索引器里显示，2-3站点内建索引器里没有。我把1站点删了，2站点就有了

**Comment by MyGiki** [comment]
重启容器，重启nastool都是试过了。确实再也加不上第二个站点

**Comment by jackloves111** [comment]
你还需要确认你添加的是否正确，你仅保留失效的那个看看，是数量问题还是站点数据问题

**Comment by cyx222800** [comment]
我也遇到了相同的问题，一起的小伙伴也有这个问题。   确定上个版本是可以用的，上午在更新.7版本之前.6版本所有自定义站点都可以显示，但是更新了.7版本后，不见了

**Comment by jackloves111** [comment]
> 我也遇到了相同的问题，一起的小伙伴也有这个问题。 确定上个版本是可以用的，上午在更新.7版本之前.6版本所有自定义站点都可以显示，但是更新了.7版本后，不见了

那我推测是修复，清除站点缓存导致的

**Comment by cyx222800** [comment]
> > 我也遇到了相同的问题，一起的小伙伴也有这个问题。 确定上个版本是可以用的，上午在更新.7版本之前.6版本所有自定义站点都可以显示，但是更新了.7版本后，不见了
> 
> 那我推测是修复，清除站点缓存导致的，还需要更多的测试才能知道

我之前设置了6个自定义，其中2个依然有效，另外四个失效了。今天新设置一个站点，设置之后不成功

**Comment by hsuyelin** [comment]
@cyx222800 @MyGiki https://github.com/hsuyelin/nas-tools/commit/5439cc9b0f1a4ce8c66d7eb500c0991c8830f3f4

修复了，被自己蠢到

**Comment by hsuyelin** [comment]
> > > 我也遇到了相同的问题，一起的小伙伴也有这个问题。 确定上个版本是可以用的，上午在更新.7版本之前.6版本所有自定义站点都可以显示，但是更新了.7版本后，不见了
> > 
> > 
> > 那我推测是修复，清除站点缓存导致的，还需要更多的测试才能知道
> 
> 我之前设置了6个自定义，其中2个依然有效，另外四个失效了。今天新设置一个站点，设置之后不成功

暂不发版本，拉取更新即可

**Comment by hsuyelin** [comment]
> 重启容器，重启nastool都是试过了。确实再也加不上第二个站点

暂不发版本，拉取更新即可

**Comment by felix-klk** [comment]
> > 重启容器，重启nastool都是试过了。确实再也加不上第二个站点
> 
> 暂不发版本，拉取更新即可

想问问大佬如何拉取更新尼  重新建容器也不行
