### ISSUE TITLE
更新后索引器内无站点，求大佬解决.

### ISSUE THREAD

**Issue by qqqjy250** [hsuyelin/nas-tools#749]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v3.4.1 958e4da

### 问题类型

主程序运行问题

### 问题描述

更新后索引器内无站点，求大佬解决.

**Comment by zhuangzhuangY** [comment]
出现同样问题，并且站点资源也是空的

**Comment by Joyace** [comment]
+1  同样遇到了

**Comment by hsuyelin** [comment]
正在打包了

**Comment by hsuyelin** [comment]
@Joyace @zhuangzhuangY @qqqjy250 10:00在更新一下试试，版本号没变，正在打包

**Comment by nhddhr** [comment]
> @Joyace @zhuangzhuangY @qqqjy25010:00在更新一下尝试，版本号没变，正在备份

作者大佬，最新版本，M-Team刷流，促销中，能否帮添加个免费，现在只有全部选项。谢谢，辛苦
