### ISSUE TITLE
下载文件转移命名与之前不符

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#76]
大佬，之前nas-tools对下载资源文件夹命名如果存在多部前缀相同使用：隔开，为什么昨天更新之后我今天洗版发现文件命名变成了-而不是之前的：，造成存在两个相同的电影资源，nastools无法覆盖洗版
<img width="523" alt="iShot_2023-08-21_22 04 58" src="https://github.com/hsuyelin/nas-tools/assets/34505611/862ee348-849a-4979-932a-8ffe6f6948cf">
希望能改回原来的方式

**Comment by yellowstrong** [comment]
这个涉及到之前的媒体库，电影资源比较多，对于经常洗版的不是很友好呀，是否能给个选项选择用-或者：的方式

**Comment by jackloves111** [comment]
为了适配之前一个提ISSues的要求，结果..... 这个确实

**Comment by yellowstrong** [comment]
> 为了适配之前一个提ISSues的要求，结果..... 这个确实

对啊 我觉得这样不太好吧，我感觉是应该根据tmdb的名称来，如果这样一改，几百部电影的工作量也太大了，如果洗到版然后去找出重复的 删除

**Comment by hsuyelin** [comment]
> > 为了适配之前一个提ISSues的要求，结果..... 这个确实
> 
> 对啊 我觉得这样不太好吧，我感觉是应该根据tmdb的名称来，如果这样一改，几百部电影的工作量也太大了，如果洗到版然后去找出重复的 删除

加个开关把，众口难调

**Comment by yellowstrong** [comment]
> > > 为了适配之前一个提ISSues的要求，结果..... 这个确实
> > 
> > 
> > 对啊 我觉得这样不太好吧，我感觉是应该根据tmdb的名称来，如果这样一改，几百部电影的工作量也太大了，如果洗到版然后去找出重复的 删除
> 
> 加个开关把，众口难调

可以的 老大，虽然我不能理解为什么会有把：改成-的需求，也不是说反对，加个开关能照顾一下洗版的时候老数据无法识别到进行覆盖的问题，就好很多，不然一个个去删真的头要大了

**Comment by hsuyelin** [comment]
<img width="1265" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/666628d1-2afb-44d9-b827-187b1779219b">
<img width="376" alt="image" src="https://github.com/hsuyelin/nas-tools/assets/17918063/3866e47c-71bf-4e41-a1f0-688855c3250b">

默认不替换
