### ISSUE TITLE
[功能改进]: 希望增加微信可信IP的插件

### ISSUE THREAD

**Issue by hanielrui** [hsuyelin/nas-tools#767]
### 当前程序版本

3.4.1

### 功能改进

希望增加微信可信IP的插件

### 参考资料

https://github.com/suraxiuxiu/MoviePilot-Plugins/

**Comment by louis000008** [comment]
这个有需要    看了下 需要加 playwright~=1.37.0  环境

**Comment by hanielrui** [comment]
Close

**Comment by hanielrui** [comment]
Close
