### ISSUE TITLE
两个bug

### ISSUE THREAD

**Issue by hxpcnz** [hsuyelin/nas-tools#78]
更新3.2.10.7版本后，数据统计没有数据，今日上传量与下载一直是0，一个新站点rousi内置索引器可以添加，但搜索后发现所有种子大小都是显示0

**Comment by hsuyelin** [comment]
1. 站点要刷新下，日志截图都没有，怎么看
2. rousi只是实验性适配，我没这个站点，全看朋友喂饭

**Comment by iovejieba** [comment]
统计 一般24小时  也就是隔天才有........至少我大概看貌似都是隔天才有统计数据 ...mt的话 3.2.10.7 统计是没问题的
