### ISSUE TITLE
正在下载 不显示资源

### ISSUE THREAD

**Issue by goodjimli** [hsuyelin/nas-tools#8]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.5

>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

 正常通过搜索添加资源，（QBitorrent）下载器已经在下载， 但是在 nas-tools 的下载管理 -》正在下载 看不到下载的内容。

![Snipaste_2023-07-18_20-40-03](https://github.com/hsuyelin/nas-tools/assets/19948103/289cba2e-ef4b-4471-a280-0f9aa657fcdd)
![Snipaste_2023-07-18_20-39-40](https://github.com/hsuyelin/nas-tools/assets/19948103/ccf506a7-e075-4e5a-a238-1f052e698e2c)

**Comment by hsuyelin** [comment]
> 下载器设置 ![Snipaste_2023-07-18_21-10-01](https://user-images.githubusercontent.com/19948103/254273368-cb74a183-b46b-4567-bc03-85553aaa978b.png)

你的下载目录设置是nastools共享的目录么。就是映射的媒体的下载目录，方便看下你映射的nastools文件夹和你下载目录的设置么

**Comment by goodjimli** [comment]
> > 下载器设置 ![Snipaste_2023-07-18_21-10-01](https://user-images.githubusercontent.com/19948103/254273368-cb74a183-b46b-4567-bc03-85553aaa978b.png)
> 
> 你的下载目录设置是nastools共享的目录么。就是映射的媒体的下载目录，方便看下你映射的nastools文件夹和你下载目录的设置么

下载器可以接受资源并且下载，保存的位置也是对的， 我认为文件夹映射应该是没问题。 我已经转回2.9.1， 所以拿不到3.2.5的映射文件夹信息了

**Comment by hsuyelin** [comment]
> 

我本地试试看，如果确实有问题，我来修复下

**Comment by hsuyelin** [comment]
> > > 下载器设置 ![Snipaste_2023-07-18_21-10-01](https://user-images.githubusercontent.com/19948103/254273368-cb74a183-b46b-4567-bc03-85553aaa978b.png)
> > 
> > 
> > 你的下载目录设置是nastools共享的目录么。就是映射的媒体的下载目录，方便看下你映射的nastools文件夹和你下载目录的设置么
> 
> 下载器可以接受资源并且下载，保存的位置也是对的， 我认为文件夹映射应该是没问题。 我已经转回2.9.1， 所以拿不到3.2.5的映射文件夹信息了

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/67f62631-7b6a-499c-adaf-49d4514d2876)

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/86255f6f-f904-472f-a424-b58ebda036bd)

我使用我的镜像是可以的，应该是你这边映射的问题，QB的下载路径和Nastools的下载路径是一个，第二个是需要设置QB为默认下载器，这个问题我先关了，我问了我朋友都是正常的，你自己查下吧

**Comment by linsmalldragon** [comment]
我也有这个问题,qb里正在下载的, nas-tools上正在下载页面不显示

**Comment by linsmalldragon** [comment]
显示了. 原来要点右上角的五角星. 这一般人根本不知道
