### ISSUE TITLE
同一个电视剧存在The Outcast和 I Am Nobody两个英文名称时，只出现一个名称的结果

### ISSUE THREAD

**Issue by jackloves111** [hsuyelin/nas-tools#81]
> @hsuyelin @jackloves111 The Outcast 是 一人之下 TMBD：67063 ![image](https://user-images.githubusercontent.com/107430324/262191291-4bc9d43d-cba4-4b57-8937-b1ab2c7d34c8.png)
> 
> I Am Nobody 是 异人之下 TMBD：225941 ![image](https://user-images.githubusercontent.com/107430324/262191248-3ec8e722-c184-4be1-ba38-19d47e7e25a4.png)
> 
> 明显程序把 一人之下的英文名 “The Outcast” 和 “异人之下”中文名 做比较了 反而 把 “异人之下”的英文名 I Am Nobody 忽略了 会不会搜索是动画和电视剧程序乱套了？看日志搜索变成了动画的 TMBD：67063 一人之下 ![image](https://user-images.githubusercontent.com/107430324/262191366-eda5ede6-67e3-4088-a917-768c9e2a0815.png)

@hsuyelin @MyGiki  这个BUG原因应该和你说的这个有点像，当同一个电视剧存在The Outcast和 I Am Nobody的英文名称时，只出现一个英文名的结果，当你选择单个站点时候，因为单个站点命名都是规范的，所以会出现结果，但多个站点时，只有同个英文名称的结果。所以总结来说，还是这部剧比较特殊。nt上有很多动漫搜不出来，可能也是这个原因，官方3.2.3版本就有这个问题。

干完这个，我觉得我可以去应聘测试岗了

所以要解决这个问题有2个方案，第一个就是程序能识别多个不同的英文名，第二个就是让站点改名字，这个不太现实

_Originally posted by @jackloves111 in https://github.com/hsuyelin/nas-tools/issues/77#issuecomment-1687265742_

**Comment by yellowstrong** [comment]
这种直接自定义识别词就好了吧，简单直接

**Comment by jackloves111** [comment]
> 这种直接自定义识别词就好了吧，简单直接

理论上是的，但是我试了好几种方案都不行，有没有作业可以抄一下

**Comment by yellowstrong** [comment]
> > 这种直接自定义识别词就好了吧，简单直接
> 
> 理论上是的，但是我试了好几种方案都不行，有没有作业可以抄一下
![iShot_2023-08-22_09 33 10](https://github.com/hsuyelin/nas-tools/assets/34505611/4b4aadeb-6efb-4811-98be-225363996b49)
![iShot_2023-08-22_09 33 29](https://github.com/hsuyelin/nas-tools/assets/34505611/2039bb4b-93ed-46ac-bec5-10e99268458d)
![iShot_2023-08-22_09 34 42](https://github.com/hsuyelin/nas-tools/assets/34505611/f012449c-d71a-487c-ba3e-aa46247063b5)
![iShot_2023-08-22_09 34 50](https://github.com/hsuyelin/nas-tools/assets/34505611/da0212e0-d535-4bf9-95f3-64082bbb8dbb)
![iShot_2023-08-22_09 36 02](https://github.com/hsuyelin/nas-tools/assets/34505611/9d0bb937-8e72-4872-8ede-09f2162fb415)
这样操作试试，我有的站点都能搜出来

**Comment by yellowstrong** [comment]
不过这个剧大概率是不会更新了，不用纠结了，听说是没过审优酷就播出来了，现在无限期停播，以后其他剧可以按这个方法试一下，我这样操作都没问题

**Comment by jackloves111** [comment]
> 不过这个剧大概率是不会更新了，不用纠结了，听说是没过审优酷就播出来了，现在无限期停播，以后其他剧可以按这个方法试一下，我这样操作都没问题

你这个方法确实多了，但是多出来的是动漫，不是正确的剧集，我再研究研究

**Comment by yellowstrong** [comment]
> > 不过这个剧大概率是不会更新了，不用纠结了，听说是没过审优酷就播出来了，现在无限期停播，以后其他剧可以按这个方法试一下，我这样操作都没问题
> 
> 你这个方法确实多了，但是多出来的是动漫，不是正确的剧集，我再研究研究

![iShot_2023-08-22_09 46 59](https://github.com/hsuyelin/nas-tools/assets/34505611/8666acb7-99cd-4687-8c7a-096d690f43b4)
这里别选错了，好多人这里选错了，tmdbid也要填写对应的tmdbid，tmdb的数据有的时候不是很准确，同样一步电视剧有多个分类，要选择正确的分类

**Comment by hsuyelin** [comment]
@MyGiki 看下

@jackloves111 那这个其实不是问题

**Comment by jackloves111** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/89971817/9dee8850-ba8f-4ec5-a0f2-f802fa55a32c)
@MyGiki 经测试，是识别词按这个设置就可以了
@hsuyelin 前一个commit[815b24b](https://github.com/hsuyelin/nas-tools/commit/815b24b1f2570d1e33c905cb8e965e3630be624c)可以恢复了

**Comment by yellowstrong** [comment]
> ![image](https://user-images.githubusercontent.com/89971817/262197476-9dee8850-ba8f-4ec5-a0f2-f802fa55a32c.png)
> 
> @MyGiki 经测试，是识别词按这个设置就可以了 @hsuyelin 前一个commit[815b24b](https://github.com/hsuyelin/nas-tools/commit/815b24b1f2570d1e33c905cb8e965e3630be624c)可以恢复了

有个小bug，如果这样设置，一人之下可能会搜索不到，但是我添加一人之下的自定义识别次将The Outcast再次分配给一人之下后，会报重复错误，这个好像也没什么好的解决办法，如果去掉重复验证不知道会不会有问题

**Comment by jackloves111** [comment]
> 

我觉得没什么好的办法，都是电视剧分类，都叫The Outcast，要区分具体是什么还真的有点难。最好的办法，还是让站点改统一的名字是正解
