### ISSUE TITLE
添加刷流任务的子任务

### ISSUE THREAD

**Issue by uploadrclone** [hsuyelin/nas-tools#82]
使用的 NAStool 是什么版本，什么环境？

Nastool 版本: v3.2.10
环境: docker

你想要新增或者改进什么功能？

这几天用两个刷流任务分别下载有hr(文件名包含audies）和没hr（文件名包含adweb）的种子发现识别会漏种，
看了下日志发现 没hr的规则会触发 忽略掉audies的种子 之后其他有hr的刷流任务也会报处理过的日志

能否在刷流任务里添加一个子任务 正则匹配指定字符匹配到的转移到指定下载目录（这样可以用下载器区分转移方式）然后可以单独设置子任务的做种时间 谢谢大佬了

**Comment by hsuyelin** [comment]
> 使用的 NAStool 是什么版本，什么环境？
> 
> Nastool 版本: v3.2.10 环境: docker
> 
> 你想要新增或者改进什么功能？
> 
> 这几天用两个刷流任务分别下载有hr(文件名包含audies）和没hr（文件名包含adweb）的种子发现识别会漏种， 看了下日志发现 没hr的规则会触发 忽略掉audies的种子 之后其他有hr的刷流任务也会报处理过的日志
> 
> 能否在刷流任务里添加一个子任务 正则匹配指定字符匹配到的转移到指定下载目录（这样可以用下载器区分转移方式）然后可以单独设置子任务的做种时间 谢谢大佬了


没懂，详细说一下

**Comment by uploadrclone** [comment]
做了一个图
![image](https://github.com/hsuyelin/nas-tools/assets/123237323/71d77243-bf25-4a8e-af13-e2c66c41ca24)

就是区分有Hr和没有hr的任务，这几天测试发现同一个站点两个刷流任务的话会互相冲突

**Comment by hsuyelin** [comment]
任务正则包含Audience，但排除掉ADWeb那个不能实现？

![image](https://github.com/hsuyelin/nas-tools/assets/17918063/329d875e-7489-4de3-bcbc-7cad9d032e6c)

**Comment by uploadrclone** [comment]
可以实现的但如果需要再建一个匹配adweb的刷流任务的话 就会因为这个任务只能匹配audies忽略adweb而出现漏种
