### ISSUE TITLE
Rousi不显示种子大小

### ISSUE THREAD

**Issue by shiningth** [hsuyelin/nas-tools#83]
nt搜索资源,出现rousi的结果,种子上没有文件大小
![8439dbf4dc6e50287d84294adeceb8c](https://github.com/hsuyelin/nas-tools/assets/38234408/5596a527-17fd-4b10-bcf5-3e841f673cea)

**Comment by jackloves111** [comment]
贴一个插件原作者的说明，你如果是自定义站点，检查你的JSON是否正确
# 索引规则

|序号|字段|描述|
|:--------:|:-------------|:-------------:|
|1|id|域名不包含 http:// 和 .com 的部分}|
|2|domain|完整的域名|
|3|name|站点名称|
|4|builtin|内建索引器`默认:true`|
|5|search|搜索规则|
|6|search.paths|站点种子页面|
|7|search.paths.path|页面地址`默认：torrents.php`|
|8|search.paths.method|请求方式`get/post`|
|9|params.search|搜索入参|
|10|torrents|种子页面搜索规则|
|11|torrents.list.selector|需要用选择器选中到一行|
|12|torrents.fields|搜索结果详情选择器|
|13|torrents.fields.description|副标题|
|14|torrents.fields.labels|标签|
|15|torrents.fields.grabs|完成人数|
|16|torrents.fields.leechers|下载人数|
|17|torrents.fields.seeders|上传人数|
|18|torrents.fields.size|种子大小|
|19|torrents.fields.date_added|发布时间|
|20|torrents.fields.date_elapsed|存活时间（发布了多久）|
|21|torrents.fields.download|下载地址|
|22|torrents.fields.details|详情页面地址|
|23|torrents.fields.title_optional|标题内容|
|24|torrents.fields.title_default|默认标题，若`title_optional`为空则显示该标题|

**Comment by hsuyelin** [comment]
拉下代码试试，不行就自己探索配置贴上来，我给你更新上去
