### ISSUE TITLE
请求大佬把 影PT 和 熊猫 加入内建索引器，能支持免费刷流。

### ISSUE THREAD

**Issue by MyGiki** [hsuyelin/nas-tools#84]
请求大佬把 影PT 和 熊猫 加入内建索引器，能支持免费刷流。

**Comment by jackloves111** [comment]
这两个站点都没有，没法测试啊

**Comment by MyGiki** [comment]
自定义添加的不好用，只能搜索不能刷流

**Comment by hsuyelin** [comment]
抽空把，而且加了也是盲加，没有这两个站点，抽空增强下自定义索引

**Comment by iovejieba** [comment]
> 抽空把，而且加了也是盲加，没有这两个站点，抽空增强下自定义索引

隔壁插件有自定义了，大佬闲的时候顺道移下就行 省事

**Comment by iovejieba** [comment]
> 请求大佬把 影PT 和 熊猫 加入内建索引器，能支持免费刷流。

忙加熊猫，另外忙改了下rousi，具体行不行  先试吧....
https://www.123pan.com/s/bcsSVv-YZBwv.html

**Comment by shiningth** [comment]
额..这个dat文件怎么弄???

**Comment by iovejieba** [comment]
> 额..这个dat文件怎么弄???

容器内  nt 根目录 config mv 备份重命名源文件  在wget过去新文件 即可！

**Comment by MyGiki** [comment]
> > 额..这个dat文件怎么弄???
> 
> 容器内 nt 根目录 config mv 备份重命名源文件 在wget过去新文件 即可！

哈哈，还是没看懂，怎么办，还能教会我妈

**Comment by hsuyelin** [comment]
> > > 额..这个dat文件怎么弄???
> > 
> > 
> > 容器内 nt 根目录 config mv 备份重命名源文件 在wget过去新文件 即可！
> 
> 哈哈，还是没看懂，怎么办，还能教会我妈

更新下试试

**Comment by iovejieba** [comment]
> > > 额..这个dat文件怎么弄???
> > 
> > 
> > 容器内 nt 根目录 config mv 备份重命名源文件 在wget过去新文件 即可！
> 
> 哈哈，还是没看懂，怎么办，还能教会我妈

大佬同步了应该，直接拉下更新看看吧

**Comment by iovejieba** [comment]
> 我有影，不过没资格发药，只有管理组能发，影的索引规则可以用阿童木的，跟阿童木的一样

影....域名大概是什么，不是清ying么 ，我没这个站有需要的话 可以大概说下站点 我盲加下看看

**Comment by iovejieba** [comment]
> 我有影，不过没资格发药，只有管理组能发，影的索引规则可以用阿童木的，跟阿童木的一样

https://www.123pan.com/s/bcsSVv-VZBwv.html

盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测试mt的话 多盯一会如果它疯狂下的话记得停止任务 并反馈...，亲 有影的话 麻烦测下 反馈是否ok
