### ISSUE TITLE
关于添加下载器的问题。

### ISSUE THREAD

**Issue by KoWming** [hsuyelin/nas-tools#85]
使用内网IP添加Transmission下载器和qBittorrent时偶尔会出现测试失败的情况，还有使用ddns解析的IPV6地址添加也会出现失败的情况，IPV4则可以。
![244cb96dcb487896a435816b029a76c7](https://github.com/hsuyelin/nas-tools/assets/96684377/f5b172d8-cb8d-4aca-b2a4-6654a1e5ff52)
![I8@A%TRF3_XN1BMW37ZSW7E](https://github.com/hsuyelin/nas-tools/assets/96684377/7985d8d7-ee24-46c3-ba6e-60774a1dceff)
![V BCAWDD{1`GU1F7WP`{ BJ](https://github.com/hsuyelin/nas-tools/assets/96684377/de4b2fdf-46f8-43b4-b31e-ae998ad17199)

**Comment by hsuyelin** [comment]
网络问题和本项目无关，自行保证下网络的稳定
