### ISSUE TITLE
nastool手动下载限制解除

### ISSUE THREAD

**Issue by youyifentian** [hsuyelin/nas-tools#86]
## 下载管理=》正在下载=》新增下载

这个之前是可以导入磁力以及bt种子来下载的，但是后来不知道为啥做了限制，只能传种子并且是支持的站点的种子，其他的种子都不行了，能不能把这个限制给解除了啊，感谢大佬

**Comment by lgsongsong** [comment]
难道忘了nt的原作者为什么关闭项目的吗？

**Comment by hsuyelin** [comment]
不打算解除，自行下载器添加
