### ISSUE TITLE
v3.2.10.7 订阅/搜索，错误匹配

### ISSUE THREAD

**Issue by caneman** [hsuyelin/nas-tools#87]
## 你使用的 NAStool 是什么版本，什么环境？

版本:  v3.2.10.7 afc7b57

环境: Docker

 ## 你遇到什么问题了？

 《沙漠大冒险》(2023) 搜索、订阅都不对
 
 - 3.2.10.6，奥本海默、八角笼中、沙漠大冒险，订阅搜索会乱，不匹配
 
 - 3.2.10.7, 奥本海默、八角笼中，表现正常（搜不到结果），但是 沙漠大冒险 还是会乱
 
 补充说明：
 - 《沙漠大冒险》 被错误的识别为了 《地雷区》
 - 《沙漠大冒险》 英文名 《SAND LAND》 ，TMDB: 1062372
 - 《地雷区》英文名 《Under sandet》，TMDB: 335578

</body>
</html>

> <html>
<body>

23:01:53 | Meta | 正在查询TMDB电影：1062372 ...
-- | -- | --
23:01:53 | Meta | 1062372 查询结果：沙漠大冒险
23:01:53 | Web | 从TMDB中匹配到电影：沙漠大冒险 (2023)
23:01:53 | Meta | 正在查询TMDB电影：1062372 ...
23:01:53 | Meta | 1062372 查询结果：Sand Land
23:01:53 | Web | 开始搜索 沙漠大冒险 ...
23:01:53 | System | 处理事件：search.start - [<function Webhook.send at 0x7f2a66b97f40>]
23:01:53 | Indexer | 开始并行搜索 Sand Land，线程数：6 ...
23:01:53 | Indexer | 开始搜索Indexer：馒头 ...
23:01:53 | Indexer | 开始搜索Indexer：HDDolby ...
23:01:53 | Indexer | 开始搜索Indexer：Audience ...
23:01:53 | Spider | 开始请求：https://kp.m-team.cc/torrents.php?search_mode=0&page=0&notnewword=1&search=Sand+Land&401=1&419=1&420=1&421=1&439=1
23:01:53 | Indexer | 开始搜索Indexer：彩虹岛 ...
23:01:53 | Indexer | 开始搜索Indexer：天空 ...
23:01:53 | Spider | 开始请求：https://www.hddolby.com/torrents.php?search_mode=0&page=0&notnewword=1&search=Sand+Land&401=1
23:01:53 | Spider | 开始请求：https://ptchdbits.co/torrents.php?search_mode=0&page=0&notnewword=1&search=Sand+Land&401=1
23:01:53 | Indexer | 开始搜索Indexer：憨憨 ...
23:01:53 | Spider | 开始请求：https://audiences.me/torrents.php?search_mode=0&page=0&notnewword=1&search=Sand+Land&401=1
23:01:53 | Spider | 开始请求：https://hdsky.me/torrents.php?search_mode=0&page=0&notnewword=1&search=Sand+Land&401=1&410=1
23:01:53 | Spider | 开始请求：https://hhanclub.top/torrents.php?search_mode=0&page=0&notnewword=1&search=Sand+Land&search_area=0&401=1&405=1
23:01:55 | Indexer | 馒头 返回数据：3
23:01:55 | Meta | 正在查询TMDB电影：335578 ...
23:01:55 | Meta | 335578 查询结果：地雷区
23:01:55 | Indexer | Land of Mine AKA Under sandet 2015 BluRay 720p MNHD-FRDS 识别为 电影/地雷区 (2015)/335578 与 电影/沙漠大冒险 (2023)/1062372 不匹配
23:01:55 | Indexer | Under sandet 2015 1080p BluRay x264 DTS-WiKi 地雷区 / 十个拆弹的少年(港) / 拆弹少年(台) / 血肉之区 / Land of Mine \| 类型: 剧情 / 历史 / 战争 识别为 沙漠大冒险 (2023) 匹配成功
23:01:55 | Meta | 正在查询TMDB电影：335578 ...
23:01:55 | Meta | 335578 查询结果：地雷区
23:01:55 | Indexer | Land of Mine AKA Under sandet 2015 BluRay 720p MNHD-FRDS 识别为 电影/地雷区 (2015)/335578 与 电影/沙漠大冒险 (2023)/1062372 不匹配
23:01:55 | Indexer | 馒头 3 条数据中，过滤 0，不匹配 2，错误 0，有效 1，耗时 2 秒
23:01:55 | Indexer | 憨憨 返回数据：1
23:01:55 | Indexer | The Wonderland of Ten Thousands S01 2018 1080p WEB-DL H264 AAC-HHWEB 是 电视剧，不匹配类型：电影
23:01:55 | Indexer | 憨憨 1 条数据中，过滤 1，不匹配 0，错误 0，有效 0，耗时 2 秒
23:01:55 | Indexer | HDDolby 返回数据：1
23:01:55 | Indexer | Under sandet 2015 1080p BluRay x264 DTS-WiKi 地雷区 / 十个拆弹的少年(港) / 拆弹少年(台) / 血肉之区 / Land of Mine \| 类型: 剧情 / 历史 / 战争 识别为 沙漠大冒险 (2023) 匹配成功
23:01:55 | Indexer | HDDolby 1 条数据中，过滤 0，不匹配 0，错误 0，有效 1，耗时 2 秒
23:01:55 | Indexer | Audience 未搜索到数据
23:01:56 | Indexer | 彩虹岛 返回数据：3
23:01:56 | Indexer | A Stranger in Town 1967 1080p Blu-ray AVC DTS-HD MA 2.0-GMA 大小：34.55G 促销：普通 不符合默认过滤规则 日常观影 要求
23:01:56 | Indexer | Under Sandet 2015 BluRay 1080p x265 10bit DTS 2Audios-CMCT 地雷区/十个拆弹的少年(港)/拆弹少年(台)/血肉之区/Land of Mine 识别为 沙漠大冒险 (2023) 匹配成功
23:01:56 | Indexer | Land of mine 2015 USA Blu-ray AVC DTS-HD MA 5.1-ltzww@CHDBits 大小：26.31G 促销：50% 不符合默认过滤规则 日常观影 要求
23:01:56 | Indexer | 彩虹岛 3 条数据中，过滤 2，不匹配 0，错误 0，有效 1，耗时 3 秒
23:01:58 | Indexer | 天空 返回数据：3
23:01:58 | Indexer | A Stranger in Town 1967 1080p Blu-ray AVC DTS-HD MA 2.0-GMA 大小：34.55G 促销：50% 不符合默认过滤规则 日常观影 要求
23:01:58 | Indexer | A Thousand Horses - Broken Heartland - 2022 - FLAC分轨 大小：262.38M 促销：普通 不符合默认过滤规则 日常观影 要求
23:01:58 | Indexer | ★禁转★Under Sandet AKA Land of Mine 2015 1080p NOR Blu-ray AVC DTS-HD MA 5.1-XOXO@HDSky 大小：22.12G 促销：50% 不符合默认过滤规则 日常观影 要求
23:01:58 | Indexer | 天空 3 条数据中，过滤 3，不匹配 0，错误 0，有效 0，耗时 5 秒
23:01:58 | Indexer | 所有站点搜索完成，有效资源数：3，总耗时 5 秒
23:01:58 | Web | 共搜索到 3 个有效资源

</body>
</html>

![Snipaste_2023-08-22_22-49-41](https://github.com/hsuyelin/nas-tools/assets/13256051/4f2f7d0c-47c6-481f-87ea-8ca33d1c8576)

**Comment by hsuyelin** [comment]
早就改过了没发版本，手动更新一下

**Comment by caneman** [comment]
> 你全部删掉重建试试吧 你的站点我都有 测试没有这个问题哎
> 
> ![image](https://user-images.githubusercontent.com/52670643/262410954-b65c4538-5a27-4fce-8e05-0ea8d59e387f.png)


你用的哪个版本？我3.2.10.8 这个问题还是有，不过之前的 馒/岛 不会出现了，杜比还是会出现

![image](https://github.com/hsuyelin/nas-tools/assets/13256051/7aafed44-8369-47a7-b0bd-1deb369fcffb)

**Comment by caneman** [comment]
> 早就改过了没发版本，手动更新一下

最新的3.2.10.8 没更新这个修复吗？
