### ISSUE TITLE
报错信息 找不到 /tmp/_MEIlbkKh5/proces/data/province_city.yaml  

### ISSUE THREAD

**Issue by mhxygu2018** [hsuyelin/nas-tools#88]
在尝试运行 sudo ./nastool_linux_arm64_v3.2.10.4 时，出现了一个 FileNotFoundError 错误。报错信息指出找不到 /tmp/_MEIlbkKh5/proces/data/province_city.yaml 文件或目录。
3.2.10.2版本可以正常使用，3.2.10.4和之后的版本都会出现这个错误无法运行

**Comment by hsuyelin** [comment]
更新最新版
