### ISSUE TITLE
添加目录同步之后，服务里没有手动同步目录的选项

### ISSUE THREAD

**Issue by serovovip** [hsuyelin/nas-tools#9]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.5
>
> 环境: docker

**Comment by serovovip** [comment]
我的意思就是服务里没有这个选项，原版添加完同步目录是有这个选项的

**Comment by serovovip** [comment]
![截屏2023-07-25 01 04 05](https://github.com/hsuyelin/nas-tools/assets/49633761/a0878025-dcc6-4869-b3d5-649a71412815)

**Comment by serovovip** [comment]
![截屏2023-07-25 01 04 50](https://github.com/hsuyelin/nas-tools/assets/49633761/8bab8b07-b662-4463-9742-e60413dbced1)

**Comment by serovovip** [comment]
![截屏2023-07-25 01 04 05](https://github.com/hsuyelin/nas-tools/assets/49633761/3321716a-883e-4940-8dde-0c130d7f83a6)

**Comment by serovovip** [comment]
![截屏2023-07-25 01 09 10](https://github.com/hsuyelin/nas-tools/assets/49633761/d529a717-7156-4750-a507-6b250e4de13c)

**Comment by hsuyelin** [comment]
![image](https://github.com/hsuyelin/nas-tools/assets/17918063/043acaa0-83dd-4387-9732-4d088bfe2595)

不是问题。是你使用的问题，没有填写目的目录，请按照如图所示填写目的目录即可
