### ISSUE TITLE
反馈馒头和hanhan刷流问题

### ISSUE THREAD

**Issue by chiao666** [hsuyelin/nas-tools#93]
版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧
![chi_20230823150953](https://github.com/hsuyelin/nas-tools/assets/46027934/ecad8854-0b7a-45ad-aeb1-13225b3b49d6)
![chi_20230823151019](https://github.com/hsuyelin/nas-tools/assets/46027934/7a36a715-0b41-462d-8c32-804709ffb225)

**Comment by iovejieba** [comment]
> 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)

我一会看看 馒头匹配free 有啥变化...我记得好像没啥变化

**Comment by iovejieba** [comment]
> 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)

https://www.123pan.com/s/bcsSVv-VZBwv.html

盲加了影，改了mt kp 结尾cc的  free通配参数  不确定是否ok 建议如果测的话  多盯一会如果它疯狂下的话记得停止任务 并反馈..

**Comment by chiao666** [comment]
> > 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)
> 
> https://www.123pan.com/s/bcsSVv-VZBwv.html
> 
> 盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测的话 多盯一会如果它疯狂下的话记得停止任务 并反馈..

老哥辛苦了！我是群晖上的docker，这个dat文件如何使用呢，是替换这个tmdb.dat吗
![chi_20230823204706](https://github.com/hsuyelin/nas-tools/assets/46027934/1672ae35-9b73-44b3-877b-f5ad20f66650)

**Comment by iovejieba** [comment]
> > > 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)
> > 
> > 
> > https://www.123pan.com/s/bcsSVv-VZBwv.html
> > 盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测的话 多盯一会如果它疯狂下的话记得停止任务 并反馈..
> 
> 老哥辛苦了！我是群晖上的docker，这个dat文件如何使用呢，是替换这个tmdb.dat吗 ![chi_20230823204706](https://user-images.githubusercontent.com/46027934/262672636-1672ae35-9b73-44b3-877b-f5ad20f66650.png)

容器的话  进入容器操作，nt根目录    config目录    同名文件    如果怕有问题可以 mv  重命名sites.dat  在 wget 拉一下就行了

**Comment by chiao666** [comment]
> > > > 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)
> > > 
> > > 
> > > https://www.123pan.com/s/bcsSVv-VZBwv.html
> > > 盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测的话 多盯一会如果它疯狂下的话记得停止任务 并反馈..
> > 
> > 
> > 老哥辛苦了！我是群晖上的docker，这个dat文件如何使用呢，是替换这个tmdb.dat吗 ![chi_20230823204706](https://user-images.githubusercontent.com/46027934/262672636-1672ae35-9b73-44b3-877b-f5ad20f66650.png)
> 
> 容器的话 进入容器操作，nt根目录 config目录 同名文件 如果怕有问题可以 mv 重命名sites.dat 在 wget 拉一下就行了

刚刚看到了老哥提的问题，我好像也没有找到sites.dat文件

**Comment by iovejieba** [comment]
> > > > > 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)
> > > > 
> > > > 
> > > > https://www.123pan.com/s/bcsSVv-VZBwv.html
> > > > 盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测的话 多盯一会如果它疯狂下的话记得停止任务 并反馈..
> > > 
> > > 
> > > 老哥辛苦了！我是群晖上的docker，这个dat文件如何使用呢，是替换这个tmdb.dat吗 ![chi_20230823204706](https://user-images.githubusercontent.com/46027934/262672636-1672ae35-9b73-44b3-877b-f5ad20f66650.png)
> > 
> > 
> > 容器的话 进入容器操作，nt根目录 config目录 同名文件 如果怕有问题可以 mv 重命名sites.dat 在 wget 拉一下就行了
> 
> 刚刚看到了老哥提的问题，我好像也没有找到sites.dat文件

docker....容器  终端   然后再找亲....  docker的  nt  终端 打开  就是nt的根目录了  然后进入config目录  下面有同名文件 可以考虑mv改名   然后wget拉文件进来也行 或者你用其他方式传也行 只要能传过来就行....

**Comment by iovejieba** [comment]
> > > > > 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)
> > > > 
> > > > 
> > > > https://www.123pan.com/s/bcsSVv-VZBwv.html
> > > > 盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测的话 多盯一会如果它疯狂下的话记得停止任务 并反馈..
> > > 
> > > 
> > > 老哥辛苦了！我是群晖上的docker，这个dat文件如何使用呢，是替换这个tmdb.dat吗 ![chi_20230823204706](https://user-images.githubusercontent.com/46027934/262672636-1672ae35-9b73-44b3-877b-f5ad20f66650.png)
> > 
> > 
> > 容器的话 进入容器操作，nt根目录 config目录 同名文件 如果怕有问题可以 mv 重命名sites.dat 在 wget 拉一下就行了
> 
> 刚刚看到了老哥提的问题，我好像也没有找到sites.dat文件

或者ssh root权限下  映射容器目录也行   列子  docker run -v /volume4/14T/sites:/nas-tools/config hsuyelin/nas-tools:latest   前段宿主机路径，后边容器内路径  后分段 容器id

**Comment by chiao666** [comment]
> > > > > > 版本是v3.2.10.7，馒头kp域名刷流选择了免费，但是还是会下载非免费的种子，看了一下是新种子应该不是过了免费期的那种，hanhan不能正常刷流，好像之前看到有issues反馈这个问题，应该是等到hanhan稳定了再说吧 ![chi_20230823150953](https://user-images.githubusercontent.com/46027934/262584696-ecad8854-0b7a-45ad-aeb1-13225b3b49d6.png) ![chi_20230823151019](https://user-images.githubusercontent.com/46027934/262584814-7a36a715-0b41-462d-8c32-804709ffb225.png)
> > > > > 
> > > > > 
> > > > > https://www.123pan.com/s/bcsSVv-VZBwv.html
> > > > > 盲加了影，改了mt kp 结尾cc的 free通配参数 不确定是否ok 建议如果测的话 多盯一会如果它疯狂下的话记得停止任务 并反馈..
> > > > 
> > > > 
> > > > 老哥辛苦了！我是群晖上的docker，这个dat文件如何使用呢，是替换这个tmdb.dat吗 ![chi_20230823204706](https://user-images.githubusercontent.com/46027934/262672636-1672ae35-9b73-44b3-877b-f5ad20f66650.png)
> > > 
> > > 
> > > 容器的话 进入容器操作，nt根目录 config目录 同名文件 如果怕有问题可以 mv 重命名sites.dat 在 wget 拉一下就行了
> > 
> > 
> > 刚刚看到了老哥提的问题，我好像也没有找到sites.dat文件
> 
> 或者ssh root权限下 映射容器目录也行 列子 docker run -v /volume4/14T/sites:/nas-tools/config hsuyelin/nas-tools:latest 前段宿主机路径，后边容器内路径 后分段 容器id........ 但好像映射目录之后修改....容器内文件好像没变化 ...所以建议还是 docker 操作容器终端 改名原文件 在wget 拉文件 覆盖目录比较理想

修改成功了，好像是可以了，不会下载50%免费的种子了，也成功添加了一个免费种子
