### ISSUE TITLE
下载器编辑弹窗优化建议

### ISSUE THREAD

**Issue by yellowstrong** [hsuyelin/nas-tools#94]
如图，目前的下载器编辑页面弹窗在手机端有bug，因为下载器选择数量过多导致在电脑以及手机端弹窗超出屏幕宽度无法操作，建议优化一下改成2+2+1的形式
![iShot_2023-08-23_16 24 23](https://github.com/hsuyelin/nas-tools/assets/34505611/124897d9-5d2b-4ce6-a328-b10124ee4fbe)
并且手机端无法滚动，参考新增站点页面添加滚动条处理
![IMG_9093](https://github.com/hsuyelin/nas-tools/assets/34505611/cde9b9e8-da95-4638-900f-d78678ff1ce2)
![IMG_9094](https://github.com/hsuyelin/nas-tools/assets/34505611/f2ac801a-9018-442f-b630-4429d2795aa9)

**Comment by iovejieba** [comment]
> 如图，目前的下载器编辑页面弹窗在手机端有bug，因为下载器选择数量过多导致在电脑以及手机端弹窗超出屏幕宽度无法操作，建议优化一下改成2+2+1的形式 ![iShot_2023-08-23_16 24 23](https://user-images.githubusercontent.com/34505611/262606166-124897d9-5d2b-4ce6-a328-b10124ee4fbe.png) 并且手机端无法滚动，参考新增站点页面添加滚动条处理 ![IMG_9093](https://user-images.githubusercontent.com/34505611/262607468-cde9b9e8-da95-4638-900f-d78678ff1ce2.PNG) ![IMG_9094](https://user-images.githubusercontent.com/34505611/262607486-f2ac801a-9018-442f-b630-4429d2795aa9.PNG)

新增站点滚动条 移动端 chrome 无问题，新增下载器 多少有点出框 不过...基础设置一定要在移动端么.....额

**Comment by yellowstrong** [comment]
也不是说在移动端去做基础配置，只是发现一个bug点跟作者提一下，如果偶尔应急的时候就没法保存了，然后网页端的话是个人感觉有点不太协调，2+2+1的形式也许会好一点？看作者感觉吧，不影响使用

**Comment by iovejieba** [comment]
> 也不是说在移动端去做基础配置，只是发现一个bug点跟作者提一下，如果偶尔应急的时候就没法保存了，然后网页端的话是个人感觉有点不太协调，2+2+1的形式也许会好一点？看作者感觉吧，不影响使用

嗯 移动端弹窗添加可以缩小 貌似就应该可以了

**Comment by yellowstrong** [comment]
还有一个bug，索引器里的统计信息，好像不显示了，不知道是从哪个版本开始的，刚刚发现
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/ab52b6c1-0698-4711-a3cc-10b28f1bd2ec)

**Comment by yellowstrong** [comment]
经测试，downloader.html文件第95行class中modal-content-minWidth更改为modal-content可解决手机端UIbug的问题，但是电脑端选择下载器可能需要特殊处理下排列问题
![iShot_2023-08-23_17 26 50](https://github.com/hsuyelin/nas-tools/assets/34505611/a07f6abd-321b-4ebf-967d-612638a461f2)
![IMG_9095](https://github.com/hsuyelin/nas-tools/assets/34505611/689f6a14-8142-48b9-9e23-7fb22dd79898)
![iShot_2023-08-23_17 25 50](https://github.com/hsuyelin/nas-tools/assets/34505611/b94a5d2d-779b-41b7-bb55-dec9d1543ef9)

**Comment by yellowstrong** [comment]
下载器类型选择，应该可以参考一下下面生成表单的逻辑，我尝试改了一下，好像不行，大佬有空可以看看
![image](https://github.com/hsuyelin/nas-tools/assets/34505611/d37e1783-3c5e-4468-bca4-2afbc1ad183b)

**Comment by yellowstrong** [comment]
样式问题已提交pull request

**Comment by hsuyelin** [comment]
感谢 @yellowstrong
