### ISSUE TITLE
3.10.8的 sites是不是有问题？

### ISSUE THREAD

**Issue by iovejieba** [hsuyelin/nas-tools#97]
我刚才解了下准备盲加影....结构变了？ 之前80+的分类站json没有了 结构变了么？ 还是？

**Comment by hsuyelin** [comment]
格式是隔壁那个大佬维护的格式，然后一行一个，你要会python我把脚本发你，每次手动太麻烦了

**Comment by jackloves111** [comment]
> 格式是隔壁那个大佬维护的格式，然后一行一个，你要会python我把脚本发你，每次手动太麻烦了

大佬，脚本发我一个，我还在手动。哭。jackloves111@163.com

**Comment by iovejieba** [comment]
> 格式是隔壁那个大佬维护的格式，然后一行一个，你要会python我把脚本发你，每次手动太麻烦了

额 那不对啊  我解了下  我发现格式乱了.....

**Comment by iovejieba** [comment]
mt有反馈说会下载非free种 我改了下free的通配参数  刚才看了下那兄弟的反馈好像是可以了  不过我还是让他多盯一会  毕竟都是忙改........

**Comment by iovejieba** [comment]
自动加的这个 貌似生成的结构不规范...至少我转回来之后结构大崩... 刚才又在10.7的sites基础上改的

**Comment by hsuyelin** [comment]
[链接自取](https://www.123pan.com/s/kiTKVv-MSz9A.html)，就是隔壁大佬的链接，我fork下来改了因为数据格式和我这个对不上，跑下 `python3.10 gen_all_sites.py` 将 `sites.dat` 提交即可，如果修改就是`sites`目录下修改即可 @iovejieba @jackloves111

**Comment by jackloves111** [comment]
> [链接自取](https://www.123pan.com/s/kiTKVv-MSz9A.html)，就是隔壁大佬的链接，我fork下来改了因为数据格式和我这个对不上，跑下 `python3.10 gen_all_sites.py` 将 `sites.dat` 提交即可，如果修改就是`sites`目录下修改即可 @iovejieba @jackloves111

那这个方便啊

**Comment by iovejieba** [comment]
> > [链接自取](https://www.123pan.com/s/kiTKVv-MSz9A.html)，就是隔壁大佬的链接，我fork下来改了因为数据格式和我这个对不上，跑下 `python3.10 gen_all_sites.py` 将 `sites.dat` 提交即可，如果修改就是`sites`目录下修改即可 @iovejieba @jackloves111
> 
> 那这个方便啊

这个生成的结构...挺诡异的

**Comment by hsuyelin** [comment]
https://github.com/hsuyelin/nas-tools-sites

@iovejieba @jackloves111 

这个
